(function(g){var window=this;var iZ=function(a){a.G=1E3;a.D=void 0;return a},jZ=function(a){g.qH.call(this,"upload");
this.C.query=a},kZ=function(a){if("youtubebanner"!==a&&"youtube-channel-banner"!==a)throw Error("configurationId must be YOUTUBE_BANNER or YOUTUBE_CHANNEL_BANNER");
jZ.call(this,a)},lZ=function(a,b,c){a.C.ytRecWidth=b;
a.C.ytRecHeight=c;return a},mZ=function(a,b){a.C.ytMaxFileSize=b;
return a},oZ=function(a,b){if(nZ()){var c=dsa()?"translate3d(0px,"+b+"px,0px)":"translate(0px,"+b+"px)";
g.Zn(a,esa(),c)}},pZ=function(a){g.U.call(this);
this.J={Dh:a.Dh,xj:(0,g.t)(function(){g.Zz.getInstance().hide(this.L());g.Aa(a.xj)&&a.xj()},this)};
this.D=this.lb=null},qZ=function(){g.U.call(this);
this.D=0;this.G=this.H=this.J=null},rZ=function(a){var b=a.L();
a=a.D?a.size()>=a.D:!1;g.cp(b,"yt-ui-elementlist-has-max-items",a)},fsa=function(a){a=a.T("yt-ui-elementlist-list");
if(!a)throw Error("Wrong DOM structure.");return a},sZ=function(){g.Jy.call(this,"ajax-form")},tZ=function(){g.Jy.call(this,"comboboxinput")},uZ=function(a){a=g.vz(a);
g.Dz(g.uz.getInstance(),a);g.K("yt-combobox-dropdown-button",a).focus()},vZ=function(a,b){return g.Ga(g.J(g.W(a,"radio"),b),function(a){return a.checked})},wZ=function(a,b,c){b=a.Ta(b);
c=c||500;var d=a.ka(b,"search-delay-timer-id");d&&g.Df((0,window.parseInt)(d,10));a=g.Bf((0,g.t)(a.wL,a,b),c);g.Dp(b,"search-delay-timer-id",a+"")},xZ=function(){g.Jy.call(this,"inlineedit");
this.C=null;this.F=[];this.D={}},zZ=function(a,b){yZ(a,b,!0,(0,g.t)(function(){var a=g.My(this,"form",b);
a&&(g.F("yt-dom-content-change",a),this.Hf(a))},a))},yZ=function(a,b,c,d){g.cp(b,g.W(a,"edit-mode"),c);
g.B(b,"yt-uix-flipwidget")?(g.NE(g.ME.getInstance(),b,c),g.zu(b,"transform",a.Cr.bind(a,b,c,d))):a.Cr(b,c,d)},AZ=function(a){a.C&&(g.Ig(a.F),a.F.length=0,g.F("yt-uix-inlineedit-form-dispose",a.Ta(a.C)),a.C=null)},gsa=function(a,b,c){a=g.My(a,"view-container",b);
g.F("yt-uix-inlineedit-view-dispose",b);g.Vm(a,c);g.F("yt-uix-inlineedit-view-init",b)},CZ=function(a,b,c,d){var e=g.My(a,"form-container",b);
AZ(a);g.Vm(e,c);a.Hf(g.My(a,"form",e));g.fz();d&&BZ(a,b,!0)},BZ=function(a,b,c){var d=g.Da(b);
if(!a.D[d]||c)a.D[d]=g.My(a,"form-container",b).innerHTML},DZ=function(){g.Jy.call(this,"orderedlist")},FZ=function(a){(0,g.z)(g.J(g.W(a,"auto-managed")),function(a){EZ(this,a,"down",!1);
EZ(this,a,"up",!1)},a)},hsa=function(a,b){var c=b,d=g.vn(b);
if(d){for(var e=d,f=0,k=0;d&&GZ(a,d)&&!(c=d,f=g.K("c4-max-editable-shelves-allowed-above",c).value,e=d=g.vn(d),0<f););if(0!=f){for(;d&&!GZ(a,d);)k++,d=g.vn(d);var l=function(){HZ(this,b,c).then(function(){g.nn(b,c);IZ(this,b);g.B(b,g.W(this,"bottom"))&&(g.O(b,g.W(this,"bottom")),EZ(this,b,"down",!0));JZ(this,b,c)}.bind(this))}.bind(a);
window.Promise.resolve();f==k?(KZ(a,e,c).then(function(){l();IZ(this,b)}.bind(a)),IZ(a,e)):l()}}},GZ=function(a,b){return b?g.B(b,g.W(a,"auto-managed")):!1},KZ=function(a,b,c){var d=c,e=0,f=0,k;
c=g.un(d);return new window.Promise(function(a){for(;c&&GZ(this,c);){d=c;e=g.K("c4-max-editable-shelves-allowed-above",c).value;if(0<e)break;k=c=g.un(d)}c||(c=null);if(b&&d){for(;c&&!GZ(this,c);)f++,c=g.un(c);HZ(this,b,d).then(function(){g.on(b,d);IZ(this,b);g.B(b,g.W(this,"top"))&&(g.O(b,g.W(this,"top")),EZ(this,b,"up",!0));JZ(this,b,k).then(a)}.bind(this))}}.bind(a))},HZ=function(a,b,c){var d=g.B(a.Ta(b),g.W(a,"animation")),e=(0,g.yu)();
return new window.Promise(function(a){g.B(b,g.W(this,"moving"))&&a();if(d&&e){var f=nZ(),l=(0,g.t)(function(){g.O(b,g.W(this,"moving"));g.O(c,g.W(this,"moving"));f?(g.Zn(b,"transform",""),g.Zn(c,"transform","")):(b.style.top="0",c.style.top="0");a()},this),m=g.ko(c),q=g.ko(b);
m=m.y>q.y?1:-1;g.N(b,g.W(this,"moving"));g.N(c,g.W(this,"moving"));f?(oZ(b,m*g.to(c).height),oZ(c,-m*g.to(b).height)):(b.style.top=m*g.to(c).height+"px",c.style.top=-m*g.to(b).height+"px");g.zu(b,"transform",l)}else a()}.bind(a))},isa=function(a,b){var c=g.rn(b),d=g.W(a,"item");
if((c=(0,g.Wi)(c,function(a){return g.B(a,d)}))&&c.length){var e=c[0];
g.N(e,g.W(a,"top"));EZ(a,e,"up",!1);1<c.length&&(e=c[1],g.O(e,g.W(a,"top")),EZ(a,e,"up",!0));e=c[c.length-1];g.N(e,g.W(a,"bottom"));EZ(a,e,"down",!1);1<c.length&&(c=c[c.length-2],g.O(c,g.W(a,"bottom")),EZ(a,c,"down",!0));FZ(a)}},IZ=function(a,b){if(b){var c=a.Ta(b);
isa(a,c)}},LZ=function(a,b){var c=a.Ta(b);
return!g.B(c,g.W(a,"disabled"))},EZ=function(a,b,c,d){if(a=g.K(g.W(a,c),b))a.disabled=!d},JZ=function(a,b,c){return new window.Promise(function(a){var d=b?this.Ta(b):null;
g.F("yt-uix-orderedlist-order-changed",d,b,c,a)}.bind(a))},MZ=function(){g.Jy.call(this,"styleable-checkbox")},NZ=function(){g.U.call(this)},OZ=function(){g.U.call(this)},jsa=function(a){g.Cy(a,"click","open-banner-image-editor",function(){g.Xz(g.$z.getInstance());
this.Hj.show()},a,window.document.body)},PZ=function(){g.U.call(this)},QZ=function(){g.U.call(this)},ksa=function(a){g.sc(a.T("yt-dialog-content"));
g.N(a.L(),"yt-dialog-show-loading");g.G("/channels_settings_ajax?action_get_casual_settings_editor=1",{onSuccess:a.KH,Ya:function(){g.O(this.L(),"yt-dialog-show-loading")},
context:a})},RZ=function(){g.U.call(this);
this.D=null;this.G=0},lsa=function(a){(a=a.Os)&&g.hi(a)},SZ=function(){g.U.call(this)},TZ=function(){g.U.call(this)},UZ=function(){g.U.call(this)},VZ=function(a){a.G&&a.G.dispose();
a.D&&a.D.dispose()},WZ=function(){g.U.call(this)},YZ=function(a,b){if(b){var c={input:b},d=g.E(a.L(),"ajax-servlet"),e=g.E(a.L(),"ajax-lookup-action");
c[e]=1;g.hz(a.T("content-picker-adder"));XZ(a);g.G(d,{method:"GET",za:c,onSuccess:a.LF,onError:a.KF,context:a})}},XZ=function(a){(a=a.T("c4-content-picker-warnings"))&&g.sc(a)},msa=function(a,b){return(0,g.Ck)(g.en("input","",a.D),function(a){return a.value==b})},ZZ=function(a,b){g.gz(a.T("content-picker-adder"),b)},$Z=function(a){var b=a.D.children.length;
a=a.L();g.cp(a,"has-content-items",0<b)},nsa=function(a){var b=[];
(0,g.z)(g.en("input","content-picker-input",a.D),function(a){b.push(a.value)});
return b},a_=function(a,b){var c=g.M(a.L(),"yt-dialog-content");
c=g.K("content-picker-save-button",c);a.getHandler().O(c,"click",function(){var a=this.T("content-picker-title-input").value;if(a){var c=g.M(this.T("content-picker-title-input"),"yt-uix-form-input-container");g.hz(c);g.nA.getInstance().hide();b(nsa(this),a)}else a=g.wq("CP_EMPTY_SECTION_TITLE_ERROR"),c=g.M(this.T("content-picker-title-input"),"yt-uix-form-input-container"),g.gz(c,a)})},b_=function(){g.U.call(this)},c_=function(a){g.cp(a.sf(),"c4-content-picker-dialog-loading",!0);
a={method:"POST",ha:g.El(g.jp(a.T("edit-section-form"))),onSuccess:a.CG,Ya:function(){g.cp(this.sf(),"c4-content-picker-dialog-loading",!1)},
context:a};g.G("/channels_picker_ajax?action_get_channel_picker_dialog=1",a)},d_=function(){g.U.call(this);
this.G=!1},e_=function(a){if(!a.G){a.G=!0;
var b=g.E(a.L(),"load-attachments-url");g.G(b,{context:a,onSuccess:a.kJ})}},f_=function(){g.U.call(this)},g_=function(a){var b=a.T("related-channels-enable-button");
a.getHandler().O(b,"click",g.u(a.D,!0));b=a.T("related-channels-disable-button");a.getHandler().O(b,"click",g.u(a.D,!1))},h_=function(){g.U.call(this)},i_=function(a){var b=g.M(a,"c4-shelf-container");
a=g.M(a,"c4-empty-shelf-container");return!!b||!!a},j_=function(a,b){var c=a.getHandler(),d=g.K("checkbox-on-off");
d&&c.Va(d,"change",a.Pp);(d=g.K("c4-shelf-layout-input",b))&&c.Va(d,"change",a.ph);if(d=g.K("c4-shelf-content-type-input",b))c.Va(d,"change",a.Tp),c.Va(d,"change",a.ph);(d=g.K("c4-shelf-playlist-entry-type-input",b))&&c.Va(d,"change",a.hq);(d=g.K("c4-shelf-single-show-entry-type-input",b))&&c.Va(d,"change",a.mq)},k_=function(a,b,c,d,e,f,k){var l=g.K(d,b),m="",q=[];
(0,g.z)(g.en("input",null,l),function(a){a.name==f&&(m=a.value);a.name==e&&q.push(a.value)});
l=g.K("yt-uix-overlay-target",l);var w=(0,g.t)(a.Iz,a,b,d,e,f);a.getHandler().O(l,"click",g.u(a.UB,b,c,d,m,q,w,k))},m_=function(a,b){var c=g.El(g.jp(b));
l_(b);g.G("/channels_picker_ajax?action_get_show_channels=1",{method:"POST",ha:c,onSuccess:(0,g.t)(a.uM,a,b),onError:(0,g.t)(a.SA,a,b)})},l_=function(a){(a=g.K("playlist-url-form-input-container",a))&&g.hz(a)},n_=function(a){var b=[],c=a.wb("c4-shelf-content-type-input");
(0,g.z)(c,function(a){b.push(a.value)},a);
(0,g.z)(c,function(a){(0,g.z)(g.en("option",null,a),function(a){var c=g.E(a,"duplicates-allowed");a.disabled=g.Ia(b,a.value)&&!a.selected&&!c})})},o_=function(){g.U.call(this);
this.H=this.G=this.J=null;this.D={}},p_=function(){g.U.call(this)},q_=function(a){(0,g.z)(a.wb(a.H),function(a){g.eB(a)})},r_=function(){g.U.call(this);
this.H=null;this.V=this.G=this.J=this.D=this.N=""},t_=function(a){return a.V!=g.Tc(s_(a,a.G))},u_=function(a,b){var c=a.T("c4-translation-editor-save-message-container"),d=g.E(c,b);
g.L(c,d)},s_=function(a,b){return a.H.getData().translations[b]},v_=function(a,b,c){var d=s_(a,b);
delete d.language;var e=a.N+"?action_update_translation=1",f=[],k=[];g.ab(d,function(a,b){f.push(b);k.push(a)});
b={language_id:b,field_keys:f,values:k};a.D&&(b.playlist_id=a.D);u_(a,"saving-message");g.G(e,{method:"POST",ha:b,onSuccess:(0,g.t)(a.zH,a,c),onError:a.yH,context:a})},w_=function(a,b){a.Y.disabled=!b;
u_(a,b?"unsaved-message":"saved-message")},osa=function(a){var b=g.D("TRANSLATIONEDITOR_JS",void 0),c=a.T("translation-editor");
g.Nf(g.D("ANGULAR_JS",void 0),function(){g.Nf(b,function(){a.H=g.r("yt.www.translationeditor.angular.bootstrap")(c);a.H.setOnChangeCallback((0,g.t)(a.IN,a))})})},psa=function(a){a=a.currentTarget;
g.B(a,"seen")||(g.N(a,"seen"),g.RE(a,"EVENT_SEEN"))},qsa=function(a){var b=a.currentTarget;
a.preventDefault();a={action:"channel_checklist_clicked_on_title",name:g.E(b,"name")};g.Dj(g.Tc(a))},rsa=function(a){a.stopPropagation();
if(a=g.M(a.currentTarget,"checklist-item"))g.tc(a),g.RE(a,"EVENT_DISMISSED"),g.M(a,"c4-checklist-module"),g.J("checklist-item").length||g.Q(g.K("c4-checklist-done-message"))},x_=function(){d_.init()},y_=function(){d_.dispose()},z_=function(){g.U.call(this);
this.D=null},ssa=function(a){g.F("playlist-dispose-header-components");
var b=g.x("pl-header");a=g.ln(g.Sn(a));g.qn(a,b);g.F("playlist-reinit-header-components")},A_=function(){g.U.call(this);
this.Cg=this.D=this.J=this.H=this.li=this.G=null},tsa=function(a,b,c,d){g.G("/playlist_edit_service_ajax/?action_remove_video=1",{method:"POST",
context:a,ha:{playlist_id:a.G,set_video_id:b,session_token:d},onSuccess:function(a,b){g.tc(c);this.oh(a,b)}})},usa=function(a,b,c,d){g.G("/like_service_ajax/?action_remove_like=1",{method:"POST",
ha:{video_id:b,session_token:d},context:a,onSuccess:function(a,b){g.tc(c);this.oh(a,b)}})},B_=function(a,b,c){b=g.M(b,"pl-video");
g.cp(b,"yt-editing-video",c);g.cp(a.L(),"yt-editing-list",c)},C_=function(){g.U.call(this);
this.fb=this.eb=null},D_=function(){g.U.call(this);
this.G="";this.D=null;this.H=!1},E_=function(a,b,c){a.getHandler().O(b,"blur",c)},F_=function(a,b){var c=a.T(b);
c&&(c=g.K("c4-module-editor-submit",c))&&c.click()},G_=function(a,b){g.cp(a.T("pl-header-content-container"),"flip",b)},H_=function(){g.U.call(this);
this.J="";this.N=this.D=this.wd=this.G=this.eb=null;this.Y=!0;this.H=null;this.V=""},vsa=function(a){var b={},c=g.x("open-to-contributions");
c&&c.checked!=a.Y&&(b.closed_to_contributions=!c.checked);g.Jp(a.H,{ha:b,onSuccess:a.Bn,onError:a.vH,Ya:function(){this.eb&&this.eb.setState("content")},
context:a})},wsa=function(a){(0,g.z)(a.wb("rule-keyword"),(0,g.t)(function(a){var b=g.gp(a);
(0,g.Ua)(b)||(a=g.M(a,"yt-ui-elementlist-item"),this.D.remove(a))},a))},I_=function(a,b){g.Bu(b,a.T("error-message"),a.T("messages"))},J_=function(a){a.getHandler().Va(a.T("save-button"),"click",a.qk);
a.getHandler().Va(a.T("settings-form"),"submit",a.qk);a.getHandler().Va(a.T("playlist-video-order-input"),"change",a.pm);if(a.T("playlist-privacy-input")){a.getHandler().Va(a.T("playlist-privacy-input"),"change",a.nm);var b=g.x("open-to-contributions");b&&a.getHandler().Va(b,"change",a.Gr)}a.D&&(a.D.dispose(),a.D=null);a.wd&&(a.wd.dispose(),a.wd=null);a.G&&(a.G.dispose(),a.G=null)},K_=function(a,b){var c=a.T("revoke-all-links-input");
g.kp(c,b);a.Ch(c)},L_=function(a){var b=g.El(g.jp(a.H));
delete b.invite_link;if(a=a.T("collaboration-settings-invite-link"))a=g.B(a,"has-invite-links"),b.has_invite_links=a;return g.Tc(b)},M_=function(){g.U.call(this)},N_=function(a,b){var c=[];
c.push(g.Jf("playlist-dispose-header-components",b));c.push(g.Jf("playlist-reinit-header-components",a));g.Ep("playlist-dispose-header-reresher",function(){g.Kf(c)})};
g.qH.prototype.Db=g.wl(31,function(a,b){var c=this.C.data||{};c[a]=b;this.C.data=c;return this});
g.rH.prototype.Db=g.wl(30,function(a,b){g.rH.M.Db.call(this,a,b);return this});
g.sH.prototype.Db=g.wl(29,function(a,b){g.sH.M.Db.call(this,a,b);return this});
g.tH.prototype.Db=g.wl(28,function(a,b){g.tH.M.Db.call(this,a,b);return this});
g.uH.prototype.Db=g.wl(27,function(a,b){g.uH.M.Db.call(this,a,b);return this});
g.wH.prototype.Db=g.wl(26,function(a,b){g.wH.M.Db.call(this,a,b);return this});
g.yH.prototype.Db=g.wl(25,function(a,b){g.yH.M.Db.call(this,a,b);return this});
g.qH.prototype.Hb=g.wl(24,function(a){this.C.mimeTypes=a;return this});
g.rH.prototype.Hb=g.wl(23,function(a){g.rH.M.Hb.call(this,a);return this});
g.sH.prototype.Hb=g.wl(22,function(a){g.sH.M.Hb.call(this,a);return this});
g.tH.prototype.Hb=g.wl(21,function(a){g.tH.M.Hb.call(this,a);return this});
g.uH.prototype.Hb=g.wl(20,function(a){g.uH.M.Hb.call(this,a);return this});
g.wH.prototype.Hb=g.wl(19,function(a){g.wH.M.Hb.call(this,a);return this});
g.yH.prototype.Hb=g.wl(18,function(a){g.yH.M.Hb.call(this,a);return this});
g.qH.prototype.Fb=g.wl(17,function(a){this.F=a||void 0;return this});
g.rH.prototype.Fb=g.wl(16,function(a){g.rH.M.Fb.call(this,a);return this});
g.sH.prototype.Fb=g.wl(15,function(a){g.sH.M.Fb.call(this,a);return this});
g.tH.prototype.Fb=g.wl(14,function(a){g.tH.M.Fb.call(this,a);return this});
g.uH.prototype.Fb=g.wl(13,function(a){g.uH.M.Fb.call(this,a);return this});
g.wH.prototype.Fb=g.wl(12,function(a){g.wH.M.Fb.call(this,a);return this});
g.yH.prototype.Fb=g.wl(11,function(a){g.yH.M.Fb.call(this,a);return this});
g.v(jZ,g.qH);jZ.prototype.Fb=function(a){jZ.M.Fb.call(this,a);return this};
jZ.prototype.Hb=function(a){jZ.M.Hb.call(this,a);return this};
jZ.prototype.Db=function(a,b){jZ.M.Db.call(this,a,b);return this};g.v(kZ,jZ);kZ.prototype.Fb=function(a){kZ.M.Fb.call(this,a);return this};
kZ.prototype.Hb=function(a){kZ.M.Hb.call(this,a);return this};
kZ.prototype.Db=function(a,b){kZ.M.Db.call(this,a,b);return this};var nZ=g.Gb(function(){return!g.C||g.Qt(9)}),dsa=g.Gb(function(){return g.yd||g.Jk||g.Lk&&g.Qt(10)||g.C&&g.Qt(10)}),esa=g.Gb(function(){return g.C&&9==g.xb?"-ms-transform":"transform"});g.v(pZ,g.U);pZ.prototype.Z=function(){pZ.M.Z.call(this);this.lb=g.x(g.E(this.L(),"dialog-id"));if(!this.lb)throw Error("Cannot find create playlist widget dialog.");this.getHandler().O(window.document,"click",this.G);this.ea("yt-uix-card-show",this.H);var a=g.K("create-playlist-widget-form",this.lb);this.D=new g.kz(this.J);this.D.La(a)};
pZ.prototype.Wa=function(){this.lb=null;this.D.dispose();this.D=null;pZ.M.Wa.call(this)};
pZ.prototype.G=function(a){g.yn(this.lb,g.iq(a))||g.Zz.getInstance().hide(this.L())};
pZ.prototype.H=function(a){a==this.L()&&this.D.T("title-input").focus()};g.v(qZ,g.U);g.h=qZ.prototype;g.h.Z=function(){qZ.M.Z.call(this);var a=g.E(this.L(),"yt-ui-elementlist-max-items");this.D=(0,window.parseInt)(a,10)||0;this.J=(a=this.T("yt-ui-elementlist-template"))?g.yy(a):null;(a=this.T("yt-ui-elementlist-add"))&&this.getHandler().O(a,"click",this.HD);g.Cy(this,"click","yt-ui-elementlist-remove",this.lE);rZ(this)};
g.h.HD=function(){if(!(this.D&&this.size()>=this.D)&&this.J){var a=g.aq(this.J.ub({}));a&&(this.C.appendChild(fsa(this),a),rZ(this),g.fz(),this.H&&this.H(a))}};
g.h.lE=function(a){if(a=this.C.fl(a.currentTarget,"yt-ui-elementlist-item"))this.C.uf(a),rZ(this),this.G&&this.G(a)};
g.h.size=function(){return this.wb("yt-ui-elementlist-item").length};
g.h.remove=function(a){this.C.uf(a);rZ(this);this.G&&this.G(a)};g.v(sZ,g.Jy);g.wa(sZ);g.rB(sZ);sZ.prototype.register=function(){g.X(this,"submit",this.C);g.X(this,"change",this.C,"submit-on-change");g.X(this,"click",this.C,"submit-button")};
sZ.prototype.unregister=function(){g.Y(this,"submit",this.C);g.Y(this,"change",this.C,"submit-on-change");g.Y(this,"click",this.C,"submit-button")};
sZ.prototype.C=function(a){var b=this.Ta(a);a=b.method||"POST";g.N(b,g.W(this,"submitting"));g.Jp(b,{method:a,context:this,Ya:function(){g.O(b,g.W(this,"submitting"))}})};g.v(tZ,g.Jy);g.wa(tZ);g.rB(tZ);g.h=tZ.prototype;g.h.register=function(){g.X(this,"click",this.nn,"update-and-hide");g.X(this,"keydown",this.qt,"radio");g.X(this,"keydown",this.Ht,"search-input");g.X(this,"paste",this.Ej,"search-input");g.X(this,"cut",this.Ej,"search-input");this.ea("yt-uix-menu-show",this.oG,this)};
g.h.unregister=function(){g.Y(this,"click",this.nn,"update-and-hide");g.Y(this,"keydown",this.qt,"radio");g.Y(this,"keydown",this.Ht,"search-input");g.Y(this,"paste",this.Ej,"search-input");g.Y(this,"cut",this.Ej,"search-input")};
g.h.oG=function(a){if(g.B(a,g.W(this,"menu"))){var b=g.xz(a);a=tZ.getInstance();b=g.My(a,"search-input",b);wZ(a,b,0);g.Bf((0,g.t)(b.focus,b),0)}};
g.h.Ht=function(a,b,c){27==c.keyCode?uZ(a):g.Bs(c.event)&&9!=c.keyCode&&(13==c.keyCode?c.preventDefault():wZ(this,a))};
g.h.qt=function(a,b,c){13==c.keyCode?(this.nn(a),c.preventDefault()):27==c.keyCode&&uZ(a)};
g.h.nn=function(a){g.Bf((0,g.t)(function(){var b=g.vz(a),c=g.K("yt-combobox-dropdown-button",b),d="",e=this.Ta(a),f=vZ(this,e);if(f){var k=this.ka(f,"dropdown-button-text");d=g.vz(e);d=g.K("yt-comboboxinput-input",g.M(d,"yt-comboboxinput")).value=f.value}else k=this.ka(c,"default-button-text");g.F("yt-uix-comboboxinput-notification-change",b,k,d);b=g.Ny.getInstance().getContent(c);g.L(b,k);uZ(a)},this),0)};
g.h.Ej=function(a){wZ(this,a)};
g.h.wL=function(a){var b=g.My(this,"search-input",a),c=vZ(this,a);if(c)var d=c.value;c=this.ka(a,"search-ajax-url")||"";g.G(c,{context:this,method:"get",za:{search_query:b.value,selected_item_value:d},onSuccess:function(b,c){g.K("yt-combobox-menu-content",a).innerHTML=c.html_content},
onError:function(b){(b=JSON.parse(b.response).error)&&this.Uf(a,b)},
Ya:function(){g.O(a,"loading")}})};
g.h.Uf=function(a,b){var c=g.Wp(g.K("error-small-template",a));g.Bu(b,c,g.K("yt-combobox-menu-notifications",a));g.Bf((0,g.t)(function(){(new g.gF(c,750)).play()},this),8E3)};g.v(xZ,g.Jy);g.wa(xZ);g.rB(xZ);g.h=xZ.prototype;g.h.register=function(){g.X(this,"focus",this.Hf,"form");g.X(this,"click",this.Hf,"form");g.X(this,"click",this.Mo,"edit")};
g.h.unregister=function(){g.Y(this,"focus",this.Hf,"form");g.Y(this,"click",this.Hf,"form");g.Y(this,"click",this.Mo,"edit");AZ(this)};
g.h.Mo=function(a,b,c){g.M(c.target,g.W(this,"ignore-edit"))||zZ(this,this.Ta(a))};
g.h.Cr=function(a,b,c){(a=g.gq(g.My(this,b?"form-container":"view-container",a)))&&a.focus();c&&c()};
g.h.Hf=function(a){if(this.C!=a){AZ(this);var b=this.Ta(a);BZ(this,b,!1);this.F.push(g.H(a,"submit",(0,g.t)(this.ix,this)));this.F.push(g.H(a,"reset",(0,g.t)(this.hx,this)));this.C=a;g.F("yt-uix-inlineedit-form-init",b)}};
g.h.hx=function(a){var b=this.Ta(a.currentTarget);yZ(this,b,!1,(0,g.t)(function(){AZ(this);var a=g.Da(b);g.My(this,"form-container",b).innerHTML=this.D[a];this.Hf(g.My(this,"form",b));g.fz()},this))};
g.h.ix=function(a){a.preventDefault();var b=a.currentTarget,c=this.Ta(b);g.Bf((0,g.t)(function(){g.cp(c,g.W(this,"mode-loading"),!0);g.Jp(b,{method:"POST",onSuccess:(0,g.t)(this.XM,this,c),onError:(0,g.t)(this.Ll,this,c),Oc:(0,g.t)(function(a){this.Ll(c,a,{})},this),
Ya:(0,g.t)(function(){g.cp(c,g.W(this,"mode-loading"),!1)},this),
nb:!0})},this),0)};
g.h.XM=function(a,b,c){c.form_html?c.view_html?(gsa(this,a,c.view_html),yZ(this,a,!1,(0,g.t)(function(){g.F("yt-dom-content-change",a);g.F("yt-uix-inlineedit-success",a,c);CZ(this,a,c.form_html,!0)},this))):CZ(this,a,c.form_html,!1):this.Ll(a,b,c)};
g.h.Ll=function(a,b,c){g.F("yt-uix-inlineedit-error",a,c.errors)};g.v(DZ,g.Jy);g.wa(DZ);g.rB(DZ);g.h=DZ.prototype;g.h.register=function(){g.X(this,"click",this.Qu,"up");g.X(this,"click",this.Pu,"down");(0,g.z)(g.J(g.W(this)),function(a){IZ(this,a)},this);
FZ(this)};
g.h.unregister=function(){g.Y(this,"click",this.Qu,"up");g.Y(this,"click",this.Pu,"down")};
g.h.Qu=function(a){if(LZ(this,a)){var b=g.W(this,"item"),c=g.M(a,b);if(c){var d=g.vn(c);d&&GZ(this,d)?hsa(this,c):d&&g.B(d,b)&&HZ(this,c,d).then(function(){g.nn(c,d);IZ(this,c);JZ(this,c,d)}.bind(this))}}};
g.h.Pu=function(a){if(LZ(this,a)){var b=g.W(this,"item"),c=g.M(a,b);if(c){var d=g.un(c);if(d&&GZ(this,d))KZ(this,c,d);else{var e=g.un(d);e&&g.B(e,b)||(e=null);d&&HZ(this,c,d).then(function(){g.on(c,d);IZ(this,c);JZ(this,c,e)}.bind(this))}}}};
g.h.enable=function(a,b){var c=this.Ta(a);g.cp(c,g.W(this,"disabled"),!b);FZ(this)};g.v(MZ,g.Jy);g.wa(MZ);g.rB(MZ);MZ.prototype.register=function(){g.X(this,"click",this.F,"toggle");g.X(this,"change",this.C,"checkbox")};
MZ.prototype.unregister=function(){g.Y(this,"click",this.F,"toggle");g.Y(this,"change",this.C,"checkbox")};
MZ.prototype.F=function(a){a=this.Ta(a);a=g.My(this,"checkbox",a);a.checked=!a.checked;g.mq(a,"change")};
MZ.prototype.C=function(a){var b=this.Ta(a);g.cp(b,g.W(this,"checked"),a.checked)};var xsa=["image/jpeg","image/png"];g.v(NZ,g.U);g.h=NZ.prototype;g.h.show=function(){this.D&&this.D.dispose();this.D=g.vI(this.H);this.D.Sb(!0)};
g.h.Z=function(){NZ.M.Z.call(this);var a=g.Cp(this.L(),"width")||0,b=g.Cp(this.L(),"height")||0,c=g.Cp(this.L(),"recommended-width")||0,d=g.Cp(this.L(),"recommended-height")||0,e=g.Cp(this.L(),"max-file-size")||0,f=g.E(this.L(),"title")||"",k=g.E(this.L(),"banner-gallery-title")||"",l="f",m=g.D("CHANNEL_ID",void 0),q="true"===g.E(this.L(),"use-channel-storage");g.E(this.L(),"show-banner-preview")&&(l="ytcb");this.H=g.OJ("yt-banner");q?g.CH(this.H,lZ(mZ((new kZ("youtube-channel-banner")).Db("X-YouTube-ChannelId",
m),e),c,d).Hb(xsa.join())):g.CH(this.H,lZ(mZ(new kZ("youtubebanner"),e),c,d));c=g.CH(this.H,new g.tH);d=new g.tH;d.C.type="ytbanner";k=g.DH(g.CH(c,d.Fb(k)),(0,g.t)(this.zA,this));f=iZ(k.setTitle(f));f.C.set("thumbs","orig");if((0,window.isNaN)(a)||(0,window.isNaN)(b))throw Error("MinSize - Not a number. ("+a+", "+b+")");f.C.set("minSize",a+"x"+b);f.C.set("cropMode",l)};
g.h.kw=function(a,b){this.G=null;g.F("banner-upload-succeeded",b.url,b.hq_url)};
g.h.jw=function(a,b){this.G=null;g.F("banner-upload-failed",b.errors)};
g.h.zA=function(a){switch(a.action){case "picked":var b="";a.viewToken&&(b=a.viewToken[2].type);var c=a.docs[0];a=c.thumbnails[0].url;var d=c.id;c=c.crop;g.F("banner-upload-started");var e={};e.channel_id=g.D("CHANNEL_ID");e.fife_url=a;e.photo_id=d;e.is_gallery_image="ytbanner"==b;c&&(e.crop_top=c.top,e.crop_right=c.right,e.crop_bottom=c.bottom,e.crop_left=c.left);b={method:"POST",ha:e,onSuccess:this.kw,onError:this.jw,context:this};this.G&&this.G.abort();this.G=g.G("/channels_profile_ajax?action_update_banner_image=1",
b)}};
g.h.X=function(){this.D&&(this.D.dispose(),this.D=null);this.G&&this.G.abort();NZ.M.X.call(this)};g.v(OZ,g.U);g.Dy(OZ,"c4-header-bg-container");
OZ.prototype.Z=function(){var a=this.T("c4-branding-upload-button");a&&(this.Hj=new NZ,g.eu(this,this.Hj),this.Hj.La(a),this.ea("banner-upload-started",(0,g.t)(this.N,this)),this.ea("banner-upload-succeeded",(0,g.t)(this.V,this)),this.ea("banner-upload-failed",(0,g.t)(this.J,this)),this.D=g.x("c4-banner-uploading-message"),this.H=g.x("c4-banner-upload-success-message"),this.G=g.x("c4-banner-upload-error-message"),jsa(this),g.D("CHANNEL_EDITOR_EDIT_BANNER")&&this.Hj.show())};
OZ.prototype.N=function(){g.O(this.H,"delay-fade-out");g.O(this.G,"delay-fade-out");g.N(this.D,"visible");var a=this.T("c4-banner-promo");a&&g.S(a)};
OZ.prototype.V=function(a,b){g.O(this.D,"visible");g.N(this.H,"delay-fade-out");g.N(this.L(),"has-custom-banner");var c={};c["background-image"]=1<(window.devicePixelRatio||1)?"url("+b+")":"url("+a+")";g.Zn(this.L(),c);(c=this.T("hd-banner-image"))&&g.Zn(c,{"background-image":"url("+b+")"})};
OZ.prototype.J=function(a){g.O(this.D,"visible");a&&0!=a.length&&(g.L(g.K("c4-header-bg-message-content",this.G),a[0]),g.N(this.G,"delay-fade-out"))};g.v(PZ,g.U);g.MN(PZ,"about-business-email-editor");PZ.prototype.Z=function(){PZ.M.Z.call(this);this.ea("yt-uix-inlineedit-success",this.G);this.ea("yt-uix-inlineedit-error",this.D)};
PZ.prototype.G=function(a){a==this.L()&&(a=(a=this.T("business-email-container"))&&g.Kn(a),g.cp(this.L(),"has-text",!!a))};
PZ.prototype.D=function(a,b){a==this.L()&&b&&0!=b.length&&g.gz(this.T("yt-uix-form-input-text-container"),b[0])};g.v(QZ,g.U);g.Dy(QZ,"c4-channel-settings-dialog-content");g.h=QZ.prototype;g.h.Z=function(){QZ.M.Z.call(this);this.ea("yt-uix-overlay-shown",this.vG);g.Cy(this,"click","channel-settings-dialog-save",this.bM);if(g.D("CHANNEL_EDITOR_EDIT_CHANNEL_SETTINGS")){var a=g.M(this.L(),"yt-uix-overlay");g.nA.getInstance().show(a)}};
g.h.X=function(){g.tc(this.L());QZ.M.X.call(this)};
g.h.vG=function(a){g.B(a,"channel-settings-overlay")&&ksa(this)};
g.h.KH=function(a,b){var c=g.$p(b.settings_html);this.T("yt-dialog-content").appendChild(c);g.bz();this.T("yt-dialog-fg").focus();(c=g.x("discussion_tab_enabled"))&&this.getHandler().O(c,"click",function(a){g.su(g.K("comment-moderation-dropdown"),a.currentTarget.checked)})};
g.h.BI=function(a,b){var c=this.T("channel-settings-error-template"),d=this.T("channel-settings-error");b.errors&&b.errors.length&&(g.sc(d),g.Bu(b.errors,c.cloneNode(!0),d),this.T("channel-settings-editor").scrollTop=0)};
g.h.bM=function(){g.Jp(g.x("account-channel-settings-form"),{onSuccess:function(){var a=new g.or(window.location);a.C.remove("edit_channel_settings");g.hi(a.toString())},
onError:this.BI,context:this})};g.v(RZ,g.U);g.MN(RZ,"country-container");RZ.prototype.Z=function(){RZ.M.Z.call(this);this.D=this.T("country-selector-select");this.G=this.D.selectedIndex;this.getHandler().O(this.D,"change",this.H)};
RZ.prototype.H=function(a){a=a.currentTarget;g.G("/channels_profile_ajax?action_update_country=1",{method:"POST",ha:{country:a.options[a.selectedIndex].value},context:this,onSuccess:this.N,onError:this.J})};
RZ.prototype.N=function(){this.G=this.D.selectedIndex;g.Q(this.T("channel-country-success-template"));g.S(this.T("channel-country-error-template"))};
RZ.prototype.J=function(a,b){this.D.selectedIndex=this.G;g.Zy.getInstance().wc(this.D);var c=this.T("channel-country-error-template");g.L(g.K("yt-alert-content",c),b.errors[0]);g.Q(c);g.S(this.T("channel-country-success-template"))};var O_=null;g.v(SZ,g.U);g.MN(SZ,"about-description-editor");SZ.prototype.Z=function(){SZ.M.Z.call(this);this.ea("yt-uix-inlineedit-success",this.G);this.ea("yt-uix-inlineedit-error",this.D)};
SZ.prototype.G=function(a){a==this.L()&&(a=(a=this.T("about-description"))&&g.Kn(a),g.cp(this.L(),"has-text",!!a))};
SZ.prototype.D=function(a,b){a==this.L()&&b&&0!=b.length&&g.gz(this.T("description-textarea-container"),b[0])};g.v(TZ,g.U);g.Dy(TZ,"c4-legal-info-editor");TZ.prototype.Z=function(){this.ea("yt-uix-inlineedit-success",function(a){a==this.L()&&(this.yh&&this.yh.dispose(),this.yh=new g.bO,this.yh.La(g.x("c4-legal-info")))});
this.ea("yt-uix-inlineedit-error",function(a,b){a==this.L()&&b&&g.gz(this.T("legal-info-textarea-container"),b[0])})};
TZ.prototype.X=function(){this.yh&&this.yh.dispose()};g.v(UZ,g.U);g.MN(UZ,"about-metadata-editor");g.h=UZ.prototype;g.h.Z=function(){UZ.M.Z.call(this);var a=g.x("c4-edit-links-banner-button");a&&this.getHandler().O(a,"click",function(){zZ(xZ.getInstance(),this.L())});
g.D("CHANNEL_EDITOR_EDIT_LINKS")&&zZ(xZ.getInstance(),this.L());this.ea("yt-uix-inlineedit-form-init",this.BF);this.ea("yt-uix-inlineedit-form-dispose",this.AF);this.ea("yt-uix-inlineedit-success",this.CN);this.ea("yt-uix-inlineedit-error",this.BN)};
g.h.BF=function(a){a==this.L()&&(VZ(this),this.G=new qZ,(a=this.C.L("about-metadata-form-network-links"))&&this.G.La(a),this.D=new qZ,a=this.C.L("about-metadata-form-custom-links"),this.D.La(a))};
g.h.AF=function(a){a==this.L()&&VZ(this)};
g.h.CN=function(a,b){if(a==this.L()&&"header_links_html"in b){var c=g.x("header-links"),d=g.ln(b.header_links_html);g.qn(d,c);c&&g.F("yt-dom-content-change",c)}};
g.h.BN=function(a,b){if(a==this.L()&&b&&0!=b.length){var c=this.T("c4-module-editor-form-error");g.sc(c);var d=g.x("custom-links-editor-error-template").cloneNode(!0);g.Bu(b[0],d,c)}};g.v(WZ,g.U);g.h=WZ.prototype;g.h.Z=function(){WZ.M.Z.call(this);this.G=this.T("content-picker-text-input");this.D=this.T("c4-content-list");var a=this.L();this.H=Number(g.E(a,"max-item-limit"));$Z(this);g.Cy(this,"click","content-picker-add",this.qq);g.Cy(this,"click","remove",this.KA);this.getHandler().O(this.G,"keydown",function(a){13==a.keyCode&&(a.preventDefault(),this.qq(a))});
this.T("yt-comboboxinput")&&this.ea("yt-uix-comboboxinput-notification-change",this.sN)};
g.h.show=function(){g.nA.getInstance().show(this.L())};
g.h.qq=function(a){a.preventDefault();YZ(this,this.G.value)};
g.h.sN=function(a,b,c){YZ(this,c)};
g.h.LF=function(a,b){var c=b.html;if(c&&(c=g.ln(g.Sn(c)),msa(this,g.Yp("input","content-picker-input",c).value)?ZZ(this,g.wq("CP_DUPLICATE_ITEM_ERROR")):this.D.children.length>=this.H?ZZ(this,g.wq("CP_MAX_ITEM_ERROR")):(this.D.appendChild(c),this.G.value="",$Z(this),XZ(this)),c=b.warnings))for(var d=g.yy(this.T("c4-content-picker-warning-template"),["warn"]),e=this.T("c4-content-picker-warnings"),f=0;f<c.length;f++)e.innerHTML+=d.ub({warn:c[f]})};
g.h.KF=function(a,b){b.errors&&0<b.errors.length&&ZZ(this,b.errors[0])};
g.h.KA=function(a){a.preventDefault();a=g.M(a.target,"content-picker-selector-item");g.tc(a);$Z(this);XZ(this)};g.v(b_,g.U);g.Dy(b_,"other-channels-sidebar-container");g.h=b_.prototype;g.h.Z=function(){this.ea("yt-ui-other-channels-editor-updated",this.Cq);this.ea("yt-uix-overlay-shown",this.DG);this.Cq();g.D("CHANNEL_EDITOR_EDIT_FEATURED_CHANNELS")&&c_(this)};
g.h.DA=function(a,b){var c={title:b,other_channel_ids:a};g.sc(this.D.T("c4-content-picker-errors"));g.G("/channels_other_channels_ajax?action_update_featured_channels_section=1",{method:"POST",ha:c,onSuccess:this.Ks,onError:this.Js,context:this})};
g.h.Ks=function(a,b){var c=g.x("other-channels-sidebar");c&&g.qn(g.ln(g.Sn(b.sidebar_html)),c);(c=g.x("other-channels-sidebar"))&&g.F("yt-dom-content-change",c);g.F("yt-ui-other-channels-editor-updated")};
g.h.Js=function(a,b){b.errors&&b.errors.length&&(0,g.z)(b.errors,function(a){var b=this.D;b.show();var c=b.T("c4-content-picker-errors");b=b.T("c4-content-picker-error-template").cloneNode(!0);g.Bu(a,b,c)},this)};
g.h.Cq=function(){this.H=this.T("yt-uix-overlay");this.G&&this.getHandler().Va(this.G,"click",this.Wp);(this.G=this.T("c4-delete-other-channels"))&&this.getHandler().O(this.G,"click",this.Wp)};
g.h.DG=function(a){g.B(a,"featured-content-picker-overlay")&&c_(this)};
g.h.CG=function(a,b){var c=b.header_text,d=g.$p(b.content_html),e=this.sf();g.L(g.K("yt-dialog-title",e),c);c=g.K("yt-dialog-content",e);g.sc(c);c.appendChild(d);d=g.K("c4-content-picker",c);this.D&&this.D.dispose();this.D=new WZ;this.D.La(d);a_(this.D,(0,g.t)(this.DA,this));this.D.show()};
g.h.sf=function(){var a=g.K("yt-dialog",this.H);a||(a=this.H.overlayContentNode);return a};
g.h.Wp=function(){g.G("/channels_other_channels_ajax?action_disable_featured_channels_section=1",{method:"POST",onSuccess:this.Ks,onError:this.Js,context:this})};g.v(d_,g.U);g.Dy(d_,"channels-feeds-posting");g.h=d_.prototype;g.h.Z=function(){d_.M.Z.call(this);var a=this.L();this.H=this.T("message-container");this.Yg=this.T("add-bulletin-form");this.getHandler().O(this.Yg,"submit",this.oz);(this.D=this.T("attachment-input-selector-select"))&&this.getHandler().O(this.D,"change",this.qz);g.B(a,"yt-uix-expander-collapsed")?this.ea("yt-uix-expander-toggle",this.qF):e_(this);var b=this.T("yt-uix-form-input-textarea");this.getHandler().O(b,"focus",function(){g.wA.getInstance().expand(a)})};
g.h.qF=function(a,b){"channels-feeds-posting"==a.getAttribute("id")&&b&&(this.T("yt-uix-form-input-textarea").focus(),e_(this))};
g.h.kJ=function(a,b){var c=this.T("attachment-inputs"),d=g.ln(g.Sn(b.attachment_inputs_html));g.qn(d,c);g.mq(this.D,"change")};
g.h.qz=function(a){a=a.currentTarget;var b=g.rn(this.T("attachment-inputs"));(0,g.z)(b,function(a){if(g.tu(a)){var b=g.K("yt-uix-form-input-text",a),c=g.K("yt-uix-form-input-select-element",a);b?g.kp(b,""):c&&(c.selectedIndex=0);g.S(a)}},this);
g.Q(b[a.selectedIndex]);g.bz()};
g.h.oz=function(a){a.preventDefault();g.sc(this.H);g.N(this.Yg,"loading");g.Jp(this.Yg,{onSuccess:this.nz,onError:this.mz,Ya:function(){g.O(this.Yg,"loading")},
context:this})};
g.h.nz=function(a,b){if("redirect_url"in b)g.ii(b.redirect_url);else if("feed_entry_html"in b){var c=g.$p(b.feed_entry_html),d=g.K("feed-item-container");d?g.nn(c,d):g.qn(c,g.xn(g.K("display-message",void 0)));g.F("yt-dom-content-change",g.K("feed-item-container"));this.D&&(this.D.selectedIndex=0,g.mq(this.D,"change"),g.Zy.getInstance().wc(this.D));g.kp(g.x("post-bulletin-message"),"")}};
g.h.mz=function(a,b){var c=g.E(this.Yg,"generic-error-message");b.errors&&b.errors.length&&(c=b.errors[0]);var d=g.x("bulletin-error-alert-template").cloneNode(!0);g.Bu(c,d,this.H)};g.v(f_,g.U);g.Dy(f_,"related-channels-sidebar-container");f_.prototype.Z=function(){g_(this)};
f_.prototype.G=function(a,b){var c=this.T("branded-page-related-channels-list");if(!(c&&0<g.rn(c).length)&&b.sidebar_html){c=g.x("related-channels-sidebar");var d=this.T("related-channels-enable-button");this.getHandler().Va(d,"click",g.u(this.D,!0));d=this.T("related-channels-disable-button");this.getHandler().Va(d,"click",g.u(this.D,!1));g.qn(g.ln(g.Sn(b.sidebar_html)),c);g_(this)}};
f_.prototype.D=function(a){g.cp(this.T("related-channels-editor"),"related-channels-module-disabled",!a);var b=this.T("related-channels-visibility-form"),c={};a&&(c.related_channels_visible=!0);g.Jp(b,{ha:c,onSuccess:this.G,context:this})};g.v(h_,g.U);var P_=null,Q_={yV:"c4-shelf-form-playlist-selected",UW:"c4-shelf-form-single-show-selected",DU:"c4-shelf-form-multi-channel-selected",EU:"c4-shelf-form-multi-playlist-selected"},ysa={BV:"c4-shelf-form-playlist-dropdown-selected",GV:"c4-shelf-form-playlist-url-selected"};g.h=h_.prototype;
g.h.Z=function(){h_.M.Z.call(this);this.Tf=g.x("c4-shelves-container");var a=this.T("c4-empty-shelf-container-template");if(a){var b=g.xy(a);g.aq(b);g.tc(a)}this.ea("yt-uix-inlineedit-success",this.dA);g.Cy(this,"click","c4-module-editor-delete",this.Lz);g.Cy(this,"submit","c4-module-editor-form",this.WA);g.Cy(this,"keydown","c4-shelf-preview-on-press",this.ph);g.Cy(this,"click","c4-shelf-playlist-url-button",this.EA);this.ea("yt-uix-comboboxinput-notification-change",this.DN);this.ea("yt-uix-orderedlist-order-changed",
this.PA);this.ea("yt-uix-inlineedit-error",this.lq);g.D("CHANNEL_EDITOR_ADD_SHELF")&&(a=this.T("c4-empty-shelf-container"))&&(a=g.K("yt-uix-inlineedit",a),zZ(xZ.getInstance(),a));this.ea("yt-uix-inlineedit-form-init",this.RA);this.ea("yt-uix-inlineedit-form-dispose",this.QA);this.D={};this.G={};n_(this);this.Tj()};
g.h.Wa=function(){this.H.length=0};
g.h.Tj=function(){this.H=this.wb("c4-shelf-container")};
g.h.RA=function(a){if(i_(a)){k_(this,a,this.D,"c4-shelf-form-multi-channel-inputs","shelf_channel_ids","channels_shelf_title","/channels_picker_ajax?action_get_channel_picker_dialog=1");k_(this,a,this.G,"c4-shelf-form-multi-playlist-inputs","shelf_full_list_ids","playlists_shelf_title","/channels_picker_ajax?action_get_playlist_picker_dialog=1");var b=g.K("c4-shelf-form-single-show-selected",a);b&&m_(this,b);b=this.getHandler();var c=g.K("checkbox-on-off");c&&b.O(c,"change",this.Pp);(c=g.K("c4-shelf-layout-input",
a))&&b.O(c,"change",this.ph);if(c=g.K("c4-shelf-content-type-input",a))b.O(c,"change",this.Tp),b.O(c,"change",this.ph);(c=g.K("c4-shelf-playlist-entry-type-input",a))&&b.O(c,"change",this.hq);(a=g.K("c4-shelf-single-show-entry-type-input",a))&&b.O(a,"change",this.mq)}};
g.h.QA=function(a){i_(a)&&(j_(this,a),a=g.Da(a),this.D[a]&&(this.D[a].dispose(),delete this.D[a]),this.G[a]&&(this.G[a].dispose(),delete this.G[a]))};
g.h.lq=function(a,b){if(i_(a)){var c=g.K("shelf-form-error-template",a),d=g.K("c4-module-editor-form-error",a);c&&d&&(g.sc(d),(0,g.z)(b,function(a){var b=c.cloneNode(!0);g.O(b,"shelf-form-error-template");g.Bu(a,b,d)}))}};
g.h.sf=function(a){var b=g.K("yt-dialog",a);b||(b=a.overlayContentNode);return b};
g.h.UB=function(a,b,c,d,e,f,k){var l=g.Da(a);if(!b[l]){var m=g.K("yt-uix-overlay",g.K(c,a));g.cp(this.sf(m),"c4-content-picker-dialog-loading",!0);g.G(k,{method:"POST",ha:{section_title:d,item_ids:e},onSuccess:g.u(this.CA,m,b,l,f),Ya:function(){g.cp(this.sf(m),"c4-content-picker-dialog-loading",!1)},
context:this})}};
g.h.CA=function(a,b,c,d,e,f){e=f.header_text;f=g.$p(f.content_html);a=this.sf(a);g.L(g.K("yt-dialog-title",a),e);a=g.K("yt-dialog-content",a);g.sc(a);a.appendChild(f);a=g.K("c4-content-picker",a);e=new WZ;e.La(a);d&&a_(e,d);b[c]=e};
g.h.DN=function(a){if(g.M(a,"c4-shelf-form")){var b=g.K("yt-comboboxinput-input",g.xn(a));if(b){var c=g.Mn(a,"form");"shelf_playlist_id"==b.name&&(b=g.K("c4-shelf-playlist-url-input",c))&&(b.value="");this.Hh(a)}}};
g.h.EA=function(a){a=a.currentTarget;var b=g.M(a,"c4-shelf-form-playlist-inputs");g.K("yt-comboboxinput-input",b).value="";this.Hh(a)};
g.h.Pp=function(a){a=a.currentTarget;var b=g.Mn(a,"form");g.dn("input",void 0,a).checked?(g.K("display-message").removeAttribute("hidden"),g.bp(b,g.lm(Q_))):(g.N(b,"c4-shelf-form-playlist-selected"),g.K("display-message").setAttribute("hidden",""))};
g.h.Tp=function(a){var b=a.currentTarget;a=g.Mn(b,"form");g.bp(a,g.lm(Q_));b=g.Ga(b.getElementsByTagName("option"),function(a){return a.selected});
g.E(b,"single-playlist-shelf")?g.N(a,"c4-shelf-form-playlist-selected"):g.E(b,"multi-playlist-shelf")?g.N(a,"c4-shelf-form-multi-playlist-selected"):g.E(b,"multi-channel-shelf")?g.N(a,"c4-shelf-form-multi-channel-selected"):g.E(b,"single-show-shelf")&&(g.N(a,"c4-shelf-form-single-show-selected"),a&&m_(this,a));n_(this)};
g.h.hq=function(a){var b=a.currentTarget;a=g.Mn(b,"form");g.bp(a,g.lm(ysa));b=g.Ga(b.getElementsByTagName("option"),function(a){return a.selected});
g.E(b,"playlist-dropdown-entry")?g.N(a,"c4-shelf-form-playlist-dropdown-selected"):g.E(b,"playlist-url-entry")&&g.N(a,"c4-shelf-form-playlist-url-selected")};
g.h.mq=function(a){this.Hh(a.currentTarget)};
g.h.uM=function(a,b,c){b=g.ln(g.Sn(c.entry_options_html));c=g.K("c4-shelf-single-show-entry-type-input",a);g.sc(c);c.appendChild(b);g.xF.getInstance().fe();g.F("yt-dom-content-change",a)};
g.h.SA=function(a,b,c){c.errors&&this.lq(a,c.errors)};
g.h.PA=function(a,b,c,d){a=g.K("c4-shelf-id",b).value;b=null;c&&(b=g.K("c4-shelf-id",c).value);DZ.getInstance().enable(this.Tf,!1);g.F("yt-dom-content-change",this.Tf);g.G("/channels_shelves_ajax?action_reorder_shelves=1",{method:"POST",ha:{shelf_id:a,shelf_id_successor:b},context:this,onSuccess:this.Tj,onError:this.kL,Ya:function(){d&&d();DZ.getInstance().enable(this.Tf,!0)}})};
g.h.kL=function(){var a=this.Tf;(0,g.z)(this.H,function(a){g.tc(a)});
g.mn(a,this.H);IZ(DZ.getInstance(),a)};
g.h.dA=function(a,b){if(i_(a)){g.xF.getInstance().fe();g.F("yt-dom-content-change",a);var c=g.M(a,"c4-empty-shelf-container");if(c){g.O(c,"c4-empty-shelf-container");g.ap(c,["c4-shelf-container","yt-uix-orderedlist-item"]);this.Tf.appendChild(c);if("creator_html"in b){var d=g.aq(g.$b(b.creator_html));this.L().appendChild(d);g.fz()}IZ(DZ.getInstance(),c)}n_(this);this.Tj()}};
g.h.WA=function(a){var b=g.K("c4-module-editor-submit",a.currentTarget);b&&(b.disabled=!0,g.Df(this.N),this.N=g.Bf(function(){b.disabled=!1},1500))};
g.h.Lz=function(a){var b=a.currentTarget;b.disabled=!0;if(a=g.M(b,"c4-shelf-container"))b={shelf_id:g.Mn(b,"form").shelf_id.value},g.G("/channels_shelves_ajax?action_delete_shelf=1",{method:"POST",ha:b,context:this,onSuccess:g.u(this.Kz,a),nb:!0})};
g.h.Kz=function(a,b,c){j_(this,a);g.tc(a);"creator_html"in c&&(a=g.aq(g.$b(c.creator_html)),this.L().appendChild(a),g.fz());n_(this);IZ(DZ.getInstance(),this.Tf);g.F("yt-dom-content-change",this.Tf);this.Tj()};
g.h.ph=function(a){a=a.currentTarget;g.Df(this.J);this.J=g.Bf((0,g.t)(this.Hh,this,a),500)};
g.h.Hh=function(a){a=g.Mn(a,"form");var b=g.El(g.jp(a));l_(a);g.G("/channels_shelves_ajax?action_preview_shelf=1",{method:"POST",ha:b,onSuccess:(0,g.t)(this.EN,this,a),onError:(0,g.t)(this.GA,this,a)})};
g.h.GA=function(a,b,c){g.S(g.K("c4-shelf-preview-container",a));(b=c.playlist_url_error)&&g.gz(g.K("playlist-url-form-input-container",a),b)};
g.h.EN=function(a,b,c){b=g.ln(g.Sn(c.preview_html));g.qn(b,g.K("c4-shelf-preview",a));g.Q(g.K("c4-shelf-preview-container",a));g.xF.getInstance().fe();g.F("yt-dom-content-change",a)};
g.h.Iz=function(a,b,c,d,e,f){var k=g.K(b,a);(0,g.z)(g.en("input",null,k),function(a){a.name!=c&&a.name!=d||k.removeChild(a)});
(0,g.z)(e,function(a){var b=g.jn("input");b.name=c;b.type="hidden";b.value=a;k.appendChild(b)});
a=g.jn("input");a.name=d;a.type="hidden";a.value=f;k.appendChild(a);this.Hh(k)};g.v(o_,g.U);g.h=o_.prototype;g.h.Z=function(){o_.M.Z.call(this);this.J=[];this.H=[];this.D={};g.Cy(this,"click","open-featured-content-picker",this.cm);g.Cy(this,"click","delete-featured-content",this.tN);this.ea("yt-ui-videopicker-save",this.vN)};
g.h.X=function(){g.ab(this.D,function(a){g.MK(a);a.dispose()});
this.D={};g.Ig(this.J);this.J.length=0;this.G&&(this.G.dispose(),g.Ig(this.H),this.H.length=0);o_.M.X.call(this)};
g.h.vN=function(a){g.km(this.D,a)&&g.G("/channels_spotlight_ajax?action_get_featured_content_confirm_dialog=1",{method:"POST",postBody:g.ip(g.K("c4-welcome-editor-form")),context:this,onSuccess:this.VI,onError:g.u(this.KL,a)})};
g.h.VI=function(a,b){g.ab(this.D,function(a){g.MK(a)});
var c=g.K("c4-featured-content-confirm-dialog-container");if(b.confirm_dialog_html&&(c.innerHTML=b.confirm_dialog_html,c=g.K("c4-featured-content-confirm-dialog"),this.G&&(this.G.dispose(),g.Ig(this.H)),c)){this.G=new g.aA(c);this.G.show();var d=g.P(c,"click",(0,g.t)(this.cm,this),"c4-featured-content-close-confirm-dialog");this.H.push(d);c=g.P(c,"click",(0,g.t)(this.rL,this),"c4-featured-content-save");this.H.push(c)}};
g.h.KL=function(a,b,c){c.errors&&a.ah(c.errors[0])};
g.h.cm=function(a){a=g.E(a.currentTarget,"ajax-action");g.ab(this.D,function(a){g.MK(a)});
if(this.D[a])this.D[a].show();else{var b="/video_picker_ajax?action_"+a+"=1",c=this.T("featured-content-video-picker");g.cp(c,"picker-dialog-loading",!0);g.G(b,{method:"GET",onSuccess:g.u(this.uN,c,a),Ya:function(){g.cp(c,"picker-dialog-loading",!1)},
context:this})}};
g.h.uN=function(a,b,c,d){var e=d.header_text,f=g.$p(d.content_html);d=g.K("yt-video-picker-dialog",a);c=g.K("yt-dialog",d).cloneNode(!0);g.L(g.K("yt-dialog-title",d),e);e=g.K("yt-dialog-content",d);e.appendChild(f);e=g.P(e,"click",(0,g.t)(this.cm,this),"open-content-picker");this.J.push(e);e=new g.KK;e.La(a);e.show();this.D[b]=e;d.appendChild(c)};
g.h.rL=function(){var a=g.K("c4-welcome-editor-form");this.G.dismiss("save");g.G("/channels_spotlight_ajax?action_preview_featured_content=1",{method:"POST",postBody:g.ip(a),context:this,onSuccess:this.wN})};
g.h.wN=function(a,b){var c=g.ln(g.Sn(b.preview_html)),d=this.T("c4-featured-content-preview");g.sc(d);d.appendChild(c);g.F("yt-dom-content-change",d);(c=g.K("c4-module-editor-submit",g.x("c4-spotlight-editor")))&&g.dp(c,"yt-uix-button-default","yt-uix-button-primary");d=g.M(d,"c4-featured-content-column");g.N(d,"preview-column")};
g.h.tN=function(){g.F("yt-www-channels-c4-component-featuredcontenteditor-delete")};g.v(p_,g.U);g.Dy(p_,"c4-spotlight-editor");g.h=p_.prototype;
g.h.Z=function(){p_.M.Z.call(this);this.ea("yt-ui-videopicker-save",this.HN);g.Cy(this,"click","open-upsell-video-picker",this.Pq);g.D("CHANNEL_EDITOR_EDIT_TRAILER")&&(this.H="upsell-tab",q_(this),this.Pq());g.Cy(this,"click","upsell-delete",this.Kw);var a=g.x("upsell-video-edit");a&&(this.D=new g.ON,this.D.La(a));this.ea("yt-www-channels-c4-component-featuredcontenteditor-delete",this.FN);g.Cy(this,"click","spotlight-editor-tab",this.YA);this.H="featured-content-tab";this.ea("yt-uix-inlineedit-form-init",
this.Xz);this.ea("yt-uix-inlineedit-form-dispose",this.Wz)};
g.h.X=function(){this.dd&&(this.dd.dispose(),this.dd=null);this.D&&(this.D.dispose(),this.D=null);this.G&&(this.G.dispose(),this.G=null);p_.M.X.call(this)};
g.h.Pq=function(){this.dd?this.dd.show():g.G("/video_picker_ajax?action_get_trailer_picker_dialog=1",{method:"GET",onSuccess:g.u(this.GN,this.T("upsell-video-picker")),context:this})};
g.h.GN=function(a,b,c){b=c.header_text;c=g.$p(c.content_html);var d=g.K("yt-video-picker-dialog",a);g.L(g.K("yt-dialog-title",d),b);g.K("yt-dialog-content",d).appendChild(c);this.dd=new g.KK;this.dd.La(a);this.dd.show()};
g.h.FN=function(){var a=this.T("c4-welcome-editor-form");a.action="/channels_spotlight_ajax?action_delete_featured_content=1";g.mq(a,"submit")};
g.h.Kw=function(){g.G("/channels_spotlight_ajax?action_delete_upsell=1",{method:"POST",context:this,onSuccess:this.Ms})};
g.h.HN=function(a){a==this.dd&&g.Jp(this.T("c4-upsell-editor-form"),{context:this,onSuccess:this.Ms,onError:function(a,c){var b=c.errors;b&&b.length&&(this.dd.show(),this.dd.ah(b[0]))}})};
g.h.Ms=function(a,b){var c=g.ln(g.Sn(b.upsell_editor_html)),d=this.T("c4-upsell-editor-container");g.qn(c,d);g.F("yt-dom-content-change",d);if(c=g.x("upsell-video-edit"))this.D?this.D.Wa():this.D=new g.ON,this.D.La(c);this.dd&&(this.dd.dispose(),this.dd=null)};
g.h.Xz=function(a){if("c4-welcome-editor"==a.id){if(a=g.K("c4-featured-content-editor"))this.G=new o_,this.G.La(a);q_(this)}};
g.h.Wz=function(a){"c4-welcome-editor"==a.id&&this.G&&(this.G.dispose(),this.G=null)};
g.h.YA=function(a){a=a.currentTarget;g.B(a,"featured-content-tab")?this.H="featured-content-tab":g.B(a,"upsell-tab")&&(this.H="upsell-tab");q_(this)};g.v(r_,g.U);g.MN(r_,"c4-translation-editor");g.h=r_.prototype;
g.h.Z=function(){r_.M.Z.call(this);osa(this);this.Y=this.T("save-button");this.getHandler().O(this.Y,"click",this.JN);var a=this.T("cancel-button");this.getHandler().O(a,"click",this.MD);this.N=g.E(this.L(),"ajax-endpoint");this.D=g.E(this.L(),"full-list-id");this.J=g.E(this.L(),"channel-url");this.ea("translation-editor-original-language-selected",this.HH);this.ea("translation-editor-translated-language-selected",this.IH);this.ea("translation-editor-translated-language-deleted",this.dF);g.hn().onbeforeunload=
(0,g.t)(this.xM,this)};
g.h.Wa=function(){r_.M.Wa.call(this);this.Y=null;g.hn().onbeforeunload=null};
g.h.xM=function(){if(t_(this))return g.wq("UNSAVED_CHANGES_WARNING")};
g.h.HH=function(a){w_(this,!0);var b=this.N+"?action_set_default_language=1";a={language_id:a};this.D&&(a.playlist_id=this.D);u_(this,"saving-message");g.G(b,{method:"POST",ha:a,onSuccess:this.uH,context:this})};
g.h.uH=function(){w_(this,t_(this))};
g.h.dF=function(a){w_(this,!0);var b=this.N+"?action_delete_translation_language=1";a={language_id:a};this.D&&(a.playlist_id=this.D);u_(this,"saving-message");g.G(b,{method:"POST",ha:a,onSuccess:this.cF,context:this})};
g.h.cF=function(){w_(this,!1)};
g.h.IH=function(a){this.G&&t_(this)&&v_(this,this.G,!1);this.G=a;this.V=g.Tc(s_(this,this.G))};
g.h.JN=function(){var a=this.H.getSelectedLanguage();!a&&t_(this)||v_(this,a,!0)};
g.h.MD=function(){this.dispatchEvent("c4-translation-editor-cancel");this.J&&g.hi(this.J)};
g.h.zH=function(a){w_(this,!1);this.V=g.Tc(s_(this,this.G));a&&(this.dispatchEvent("c4-translation-editor-save-by-user"),this.J&&g.hi(this.J))};
g.h.yH=function(a,b){var c=this.H.getSelectedLanguage(),d={},e=b.errors[0];g.lp(e)?d[c]=JSON.parse(e):d[c]={};this.H.setErrors(d);u_(this,"unsaved-message")};
g.h.IN=function(){w_(this,t_(this))};var R_=[];g.v(z_,g.U);g.Dy(z_,"playlist-add-video-form");z_.prototype.Z=function(){z_.M.Z.call(this);var a=this.T("playlist-add-video-button");this.getHandler().O(a,"click",this.H);var b=g.E(a,"picker-title")||"";b=g.CH(g.CH(g.CH(iZ(g.OJ("yt-addtoplaylist").setTitle(b)),g.xH()),g.vH()),"youtube");b.C.set("multiselectEnabled","true");a=g.Kn(a);b.C.set("selectButtonLabel",a);this.D=g.vI(g.DH(b,(0,g.t)(this.G,this)))};
z_.prototype.G=function(a){if("picked"==a.action){var b=(0,g.Zi)(a.docs,function(a){return a.id});
b&&b.length&&(this.T("playlist-add-video-form-video-id").value=b.join(","),a=(0,g.Zi)(a.docs,function(a){var b=a.accessToken;return b?a.id+":"+b:""}),this.T("playlist-add-video-form-video-access-token").value=a.join(","),g.Jp(this.L(),{onSuccess:function(){window.location.reload()},
onError:function(a,b){var c=g.x("add-video-failed");g.K("yt-alert-content",c).innerHTML=b.errors.join(" ");g.Q(c)}}))}};
z_.prototype.H=function(){this.D.Sb(!0)};
z_.prototype.X=function(){this.D=null;z_.M.X.call(this)};var S_;g.v(A_,g.U);g.Dy(A_,"pl-video-list");g.h=A_.prototype;
g.h.Z=function(){A_.M.Z.call(this);this.li=this.wb("pl-video");this.H=g.E(this.L(),"playlist-edit-xsrf-token");this.J=g.E(this.L(),"like-xsrf-token");this.G=g.E(this.L(),"playlist-id");g.Cy(this,"focusin","pl-video-edit-options",this.Uz);g.Cy(this,"focusout","pl-video-edit-options",this.Vz);g.Cy(this,"click","pl-video-edit-remove",this.JA);g.Cy(this,"click","pl-video-edit-remove-liked-video",this.IA);g.Cy(this,"click","pl-video-edit-move-top",this.tA);g.Cy(this,"click","pl-video-edit-move-bottom",
this.sA);g.Cy(this,"click","pl-video-set-thumbnail",this.OA);this.ea("yt-uix-dragdrop-notification-dragend",this.qO);this.ea("yt-uix-menu-before-show",(0,g.t)(this.sO,this));this.ea("yt-uix-menu-hide",(0,g.t)(this.rO,this));var a=g.K("playlist-cleared-of-deleted-videos-alert");a&&g.Cy(this,"click","close",this.gH,this,a)};
g.h.qO=function(a,b){if(a==this.L()&&b){var c=g.E(b,"set-video-id"),d=null,e=g.un(b);e&&(d=g.E(e,"set-video-id"));this.Bi(c,d)}};
g.h.Bi=function(a,b){a&&g.G("/playlist_edit_service_ajax/?action_move_video_before=1",{method:"POST",ha:{playlist_id:this.G,set_video_id:a,moved_set_video_id_successor:b,session_token:this.H},onSuccess:function(a,b){this.li=this.wb("pl-video",this.L());this.oh(a,b)},
onError:g.u(this.kH,a,b),context:this})};
g.h.kH=function(a,b,c,d){if(c=g.x("pl-load-more-destination"))g.sc(c),g.mn(c,this.li);"set-manual-sort-order-dialog"in d&&(this.Cg=[a,b],this.T("set-manual-sort-order-container").innerHTML=d["set-manual-sort-order-dialog"],a=this.T("set-manual-sort-order"),this.D&&this.D.dispose(),this.D=new g.aA(a),this.D.show(),g.bA(this.D,"cancel",(0,g.t)(this.lD,this)),g.bA(this.D,"save",(0,g.t)(this.Az,this),!0))};
g.h.lD=function(){this.Cg=null};
g.h.Az=function(){this.D.setState("working");var a=this.T("set-manual-sort-order-form");a&&g.Jp(a,{onSuccess:function(a,c){this.Cg?this.Bi.apply(this,this.Cg):this.oh(a,c)},
context:this})};
g.h.Uz=function(a){g.B(window.document.documentElement,"no-focus-outline")||g.N(a.currentTarget,"pl-video-edit-options-focus")};
g.h.Vz=function(a){g.O(a.currentTarget,"pl-video-edit-options-focus")};
g.h.JA=function(a){a=g.M(a.currentTarget,"pl-video");var b=g.E(a,"set-video-id"),c=this.H;b&&a&&c&&tsa(this,b,a,c)};
g.h.IA=function(a){a=g.M(a.currentTarget,"pl-video");var b=g.E(a,"video-id"),c=this.J;b&&a&&c&&usa(this,b,a,c)};
g.h.sO=function(a,b){var c=g.K("pl-video-edit-more",a);c&&(B_(this,c,!0),g.su(g.K("pl-video-edit-move-top",b),!!g.E(c,"can-move-to-top")),g.su(g.K("pl-video-edit-move-bottom",b),!!g.E(c,"can-move-to-bottom")),g.su(g.K("pl-video-edit-notes",b),!!g.E(c,"can-edit-notes")),g.su(g.K("pl-video-set-thumbnail",b),!!g.E(c,"can-set-playlist-thumbnail")))};
g.h.rO=function(a){(a=g.K("pl-video-edit-more",a))&&B_(this,a,!1)};
g.h.tA=function(){var a=g.Yp("tr","pl-video",this.L()),b=this.T("yt-editing-video");a=g.E(a,"set-video-id");var c=g.E(b,"set-video-id");g.pn(g.x("pl-video-table"),b,0);this.Bi(c,a)};
g.h.sA=function(){var a=this.T("yt-editing-video"),b=g.E(a,"set-video-id");if(this.wb("load-more-button").length)g.tc(a);else{var c=g.x("pl-video-table");g.pn(c,a,c.length)}this.Bi(b,null)};
g.h.OA=function(){var a=g.E(this.T("yt-editing-video"),"video-id");g.G("/playlist_edit_service_ajax/?action_set_playlist_thumbnail=1",{method:"POST",ha:{playlist_id:this.G,thumbnail_video_id:a,session_token:this.H},onSuccess:this.oh,context:this})};
g.h.oh=function(a,b){b&&b.header_html&&!this.Cg?g.F("playlist-update-header",b.header_html):(this.Cg=null,window.location.reload())};
g.h.gH=function(){g.G("/playlist_edit_service_ajax/?action_remove_cleared_of_deleted_videos=1",{method:"POST",ha:{playlist_id:this.G}})};
g.h.X=function(){this.G=this.J=this.H=this.li=null;this.D&&(this.D.dispose(),this.D=null);A_.M.X.call(this)};g.v(C_,g.U);g.Dy(C_,"pl-video-list");g.h=C_.prototype;g.h.Z=function(){C_.M.Z.call(this);var a=new g.aA(this.T("notes-editor-dialog"));g.bA(a,"save",(0,g.t)(this.sH,this));g.bA(a,"cancel",(0,g.t)(this.nD,this));this.eb=a;this.fb=this.T("notes-form");g.Cy(this,"click","pl-video-edit-notes",this.Rz)};
g.h.Rz=function(a){a=g.M(a.currentTarget,"pl-video");var b=g.E(a,"set-video-id"),c=this.T("notes-editor-input"),d=this.T("notes-editor-set-video-id"),e=g.E(a,"video-annotation")||"";c.value=e;d.value=b;b=this.T("yt-dialog-title");a=g.E(a,"title")||"";c=window.document.createElement("h3");g.L(c,a);g.N(c,"notes-editor-subtitle");g.on(c,b);this.eb.show()};
g.h.XA=function(){window.location.reload()};
g.h.sH=function(){this.eb.setState("working");g.Jp(this.fb,{onSuccess:this.XA,Ya:function(){this.eb.setState("content")},
context:this})};
g.h.nD=function(){g.tc(this.T("notes-editor-subtitle"))};g.v(D_,g.U);g.Dy(D_,"pl-header");g.h=D_.prototype;g.h.Z=function(){D_.M.Z.call(this);this.G=g.E(this.L(),"full-list-id");var a=this.getHandler(),b=this.T("remove-watched-button");b&&a.O(b,"click",this.mE);(b=this.T("pl-header-title-editor-input"))&&E_(this,b,function(){F_(this,"pl-header-title-editor-form")});
(b=this.T("pl-header-description-editor-textarea"))&&E_(this,b,function(){F_(this,"pl-header-description-editor-form")});
this.ea("yt-uix-inlineedit-error",this.cA);this.ea("yt-uix-inlineedit-success",function(){var a=this.T("pl-header-title-editor-input");a&&E_(this,a,function(){F_(this,"pl-header-title-editor-form")})});
this.ea("yt-uix-inlineedit-success",function(){var a=this.T("pl-header-description-editor-textarea");a&&E_(this,a,function(){F_(this,"pl-header-description-editor-form")})});
if(b=this.T("delete-button"))a.O(b,"click",this.tO),a.O(this.T("confirm-delete-button"),"click",this.QD),a.O(this.T("cancel-delete-button"),"click",this.LD);(b=this.T("translate-playlist-button"))&&a.O(b,"click",this.uI)};
g.h.cA=function(a,b){if(g.B(a,"pl-header-inlineedit")){if(b&&b[0]){var c=g.K("yt-uix-form-input-container",a);if(c){g.gz(c,b[0]);return}}window.location.reload()}};
g.h.tO=function(){this.D||(this.D=new g.aA(g.K("delete-confirmation-dialog",void 0)));this.D.show()};
g.h.LD=function(){this.D.dismiss("cancel")};
g.h.QD=function(){this.D.setState("working");g.G("/playlist_ajax?action_delete_playlist=1",{method:"POST",ha:{full_list_id:this.G},onSuccess:this.ZE,onError:this.Jr,context:this})};
g.h.ZE=function(a,b){b.errors&&this.Jr(a,b);g.F("yt-uix-playlistlike-unliked",{id:this.G});var c=g.E(this.L(),"all-playlists-url");g.hi(c)};
g.h.Jr=function(){this.D.setState("content");this.D.dismiss("cancel")};
g.h.mE=function(){g.Jp(g.x("playlist-remove-watched-form"),{onSuccess:function(){window.location.reload()}})};
g.h.uI=function(a){G_(this,!0);this.H||(a={full_list_id:g.E(a.target,"full-list-id")},g.G("/playlist_ajax?action_get_translation_editor=1",{za:a,onSuccess:this.MF,context:this}))};
g.h.MF=function(a,b){this.H=!0;this.T("pl-translation-editor-content").innerHTML=b.result.editor_html;var c=this.T("pl-translation-editor"),d=new r_;d.La(c);this.getHandler().O(d,"c4-translation-editor-cancel",this.cB);this.getHandler().O(d,"c4-translation-editor-save-by-user",this.dB)};
g.h.cB=function(){G_(this,!1)};
g.h.dB=function(){G_(this,!1)};g.v(H_,g.U);g.Dy(H_,"playlist-settings-editor");g.h=H_.prototype;
g.h.Z=function(){H_.M.Z.call(this);this.J=g.E(this.L(),"full-list-id")||"";this.N=this.T("yt-dialog-content");this.eb=new g.aA(this.T("playlist-settings-dialog"));var a=this.T("edit-button");this.getHandler().O(a,"click",this.Hr);g.Cy(this,"click","re-edit-button",this.kE);g.Cy(this,"click","confirm-auto-add-button",this.PD);g.Cy(this,"click","create-invite-link-button",this.Fo);g.Cy(this,"click","revoke-all-links",this.oE);g.Cy(this,"change","check-form-on-change",this.Ch);a=g.K("pl-header-title-icon");
this.getHandler().O(a,"click",this.show);this.ea("yt-uix-tabs-after-shown",this.UC)};
g.h.dispose=function(){H_.M.dispose.call(this);J_(this);this.eb&&(this.eb.dispose(),this.eb=null)};
g.h.UC=function(a,b){"collaboration-settings"==b.getAttribute("id")&&g.B(this.T("collaboration-settings-invite-link"),"has-invite-links")&&(g.gp(this.T("invite-link"))||this.Fo())};
g.h.Hr=function(){this.eb.show();this.eb.setState("loading");g.G("/playlist_ajax?action_get_settings_editor=1",{method:"GET",za:{full_list_id:this.J},onSuccess:this.gG,onError:this.fG,context:this})};
g.h.qk=function(a){a.preventDefault();g.S(this.T("error-message"));this.eb.setState("working");wsa(this);vsa(this)};
g.h.Bn=function(a,b){if(b.auto_add_confirmation_dialog_html){this.wd&&this.wd.dispose();this.T("auto-add-confirmation-dialog-container").innerHTML=b.auto_add_confirmation_dialog_html;var c=this.T("auto-add-confirmation-dialog");c&&(this.wd=new g.aA(c),this.eb.dismiss("close"),this.wd.show())}else window.location.reload()};
g.h.kE=function(){this.wd.dismiss("cancel");this.eb.show()};
g.h.PD=function(){var a=this.T("auto-add-confirmation-form");g.LN(a,"add_matching_videos")?(this.wd.setState("working"),g.Jp(a,{onSuccess:this.Bn,Ya:function(){this.wd&&this.wd.setState("content")},
context:this})):this.Bn(null,{})};
g.h.pm=function(){var a=g.K("add-to-top-container");if(a){var b="0"==g.gp(this.T("playlist-video-order-input"));g.su(a,b)}};
g.h.nm=function(){var a=g.gp(this.T("playlist-privacy-input")),b=this.T("collaboration-settings-tab-nav");a="0"!=a;g.cp(b,"disabled",!a);a?b.removeAttribute("aria-disabled"):b.setAttribute("aria-disabled","true")};
g.h.vH=function(a,b){b.errors&&b.errors[0]&&I_(this,b.errors[0])};
g.h.show=function(){this.Hr()};
g.h.gG=function(a,b){J_(this);this.N.innerHTML=b.editor_content;g.fz();this.getHandler().O(this.T("save-button"),"click",this.qk);this.getHandler().O(this.T("settings-form"),"submit",this.qk);this.getHandler().O(this.T("playlist-video-order-input"),"change",this.pm);this.pm(null);if(this.T("playlist-privacy-input")){this.getHandler().O(this.T("playlist-privacy-input"),"change",this.nm);this.nm(null);var c=g.x("open-to-contributions");c&&(this.getHandler().O(c,"change",this.Gr),this.Y=c.checked)}if(c=
this.T("auto-add-rule-list"))this.D=new qZ,this.D.La(c),c=(0,g.t)(this.Ch,this),this.D.H=c,c=(0,g.t)(this.Ch,this),this.D.G=c;this.H=this.T("settings-form");this.V=L_(this);this.T("save-button").disabled=!0;this.eb.setState("content")};
g.h.fG=function(a,b){b.errors&&b.errors[0]&&(I_(this,b.errors[0]),this.eb.setState("content"))};
g.h.Gr=function(a){a=a.currentTarget;g.cp(this.T("collaboration-settings-invite-link"),"disabled",!a.checked);g.su(this.T("collaboration-settings-contributor-list"),a.checked)};
g.h.oE=function(){g.dp(this.T("collaboration-settings-invite-link"),"has-invite-links","no-invite-links");K_(this,!0)};
g.h.Fo=function(){K_(this,!1);g.G("/playlist_ajax?action_create_collaboration_invite_link=1",{method:"POST",ha:{full_list_id:this.J},onSuccess:this.OE,onError:this.NE,context:this})};
g.h.NE=function(a,b){b.errors&&b.errors[0]&&I_(this,b.errors[0])};
g.h.OE=function(a,b){b.errors&&b.errors[0]?I_(this,b.errors[0]):(g.kp(this.T("invite-link"),b.result.invite_link),g.dp(this.T("collaboration-settings-invite-link"),"no-invite-links","has-invite-links"),this.Ch(null))};
g.h.Ch=function(){var a=L_(this);this.T("save-button").disabled=a==this.V};g.v(M_,g.U);g.Dy(M_,"pl-suggestions");M_.prototype.Z=function(){g.Cy(this,"click","remove-duplicate-button",this.G)};
M_.prototype.G=function(){g.Jp(this.T("remove-duplicate-form"),{onSuccess:this.D,context:this})};
M_.prototype.D=function(){window.location.reload()};var T_,U_={about:[function(){PZ.init();RZ.init();SZ.init();UZ.init()},
function(){PZ.dispose();RZ.dispose();SZ.dispose();UZ.dispose()}],
feed:[x_,y_],playlists:[function(){var a=g.x("playlists-tab-create-playlist-widget");a&&(O_=new pZ({Dh:lsa}),O_.La(a))},
function(){O_&&O_.dispose()}],
playlist:[function(){S_=g.Jf("playlist-update-header",ssa);z_.init();N_(z_.init,z_.dispose);H_.init();N_(H_.init,H_.dispose);N_(g.mO.init,g.mO.dispose);D_.init();N_(D_.init,D_.dispose);A_.init();C_.init();M_.init()},
function(){g.Kf(S_);g.F("playlist-dispose-header-reresher");z_.dispose();H_.dispose();D_.dispose();A_.dispose();C_.dispose();M_.dispose()}],
published_activity:[x_,y_]};
g.Zh(g.uq({name:"www/channels_edit",deps:["www/channels"],page:["channel","playlist"],init:function(){if(g.D("CHANNEL_EDITABLE")){sZ.init();g.FK.init();xZ.init();DZ.init();MZ.init();tZ.init();g.QE(window.document.body);var a=g.K("c4-checklist-module");a&&(R_.push(g.P(a,"mouseover",g.u(psa),"checklist-item")),R_.push(g.P(a,"click",g.u(qsa),"checklist-item")),R_.push(g.P(a,"click",g.u(rsa),"yt-close-img")));OZ.init();p_.init();if(a=g.x("browse-items-primary"))P_=new h_,P_.La(a);QZ.init();TZ.init();
b_.init();f_.init();r_.init();if(g.D("CHANNEL_EDITOR_EDIT_AVATAR")){a=g.K("settings-dialog-container");var b=g.K("change-profile-photo-dialog-container");a?g.nA.getInstance().show(a):b&&g.nA.getInstance().show(b)}a=g.D("CHANNEL_TAB",void 0);if(a in U_)U_[a][0]();T_=a}else T_=null},
dispose:function(){var a=T_;if(a){if(a in U_)U_[a][1]();sZ.dispose();g.FK.dispose();xZ.dispose();DZ.dispose();MZ.dispose();tZ.dispose();g.Ig(R_);OZ.dispose();p_.dispose();P_&&P_.dispose();QZ.dispose();TZ.dispose();b_.dispose();f_.dispose();r_.dispose()}}}));})(_yt_www);
