(function(g){var window=this;var yO=function(){this.V=40;this.F=1;this.J=3;this.la=this.H=0;this.ia=!1;this.N=this.R="";this.D=wO.Jn;this.W="";this.C=1;this.K=!1;this.G=[];this.Y=this.aa=!1;var a=wO.DECIMAL_PATTERN;a.replace(/ /g,"\u00a0");var b=[0];this.R=xO(this,a,b);for(var c=b[0],d=-1,e=0,f=0,k=0,l=-1,m=a.length,q=!0;b[0]<m&&q;b[0]++)switch(a.charAt(b[0])){case "#":0<f?k++:e++;0<=l&&0>d&&l++;break;case "0":if(0<k)throw Error('Unexpected "0" in pattern "'+a+'"');f++;0<=l&&0>d&&l++;break;case ",":0<l&&this.G.push(l);l=0;break;
case ".":if(0<=d)throw Error('Multiple decimal separators in pattern "'+a+'"');d=e+f+k;break;case "E":if(this.Y)throw Error('Multiple exponential symbols in pattern "'+a+'"');this.Y=!0;this.la=0;b[0]+1<m&&"+"==a.charAt(b[0]+1)&&(b[0]++,this.ia=!0);for(;b[0]+1<m&&"0"==a.charAt(b[0]+1);)b[0]++,this.la++;if(1>e+f||1>this.la)throw Error('Malformed exponential pattern "'+a+'"');q=!1;break;default:b[0]--,q=!1}0==f&&0<e&&0<=d&&(f=d,0==f&&f++,k=e-f,e=f-1,f=1);if(0>d&&0<k||0<=d&&(d<e||d>e+f)||0==l)throw Error('Malformed pattern "'+
a+'"');k=e+f+k;this.J=0<=d?k-d:0;0<=d&&(this.H=e+f-d,0>this.H&&(this.H=0));this.F=(0<=d?d:k)-e;this.Y&&(this.V=e+this.F,0==this.J&&0==this.F&&(this.F=1));this.G.push(Math.max(0,l));this.aa=0==d||d==k;c=b[0]-c;this.N=xO(this,a,b);b[0]<a.length&&";"==a.charAt(b[0])?(b[0]++,1!=this.C&&(this.K=!0),this.D=xO(this,a,b),b[0]+=c,this.W=xO(this,a,b)):(this.D+=this.R,this.W+=this.N)},zO=function(a,b,c,d){if(a.H>a.J)throw Error("Min value must be less than max value");
d||(d=[]);var e=Math.pow(10,a.J),f=Math.round(b*e);(0,window.isFinite)(f)?(b=Math.floor(f/e),e=Math.floor(f-b*e)):e=0;var k=b;b=e;var l=0<a.H||0<b||!1;e=a.H;l&&(e=a.H);var m="";for(f=k;1E20<f;)m="0"+m,f=Math.round(f/10);m=f+m;var q=wO.DECIMAL_SEP;f=wO.wk.charCodeAt(0);var w=m.length,y=0;if(0<k||0<c){for(k=w;k<c;k++)d.push(String.fromCharCode(f));if(2<=a.G.length)for(c=1;c<a.G.length;c++)y+=a.G[c];c=w-y;if(0<c){k=a.G;y=w=0;for(var I,R=wO.GROUP_SEP,V=m.length,T=0;T<V;T++)if(d.push(String.fromCharCode(f+
1*Number(m.charAt(T)))),1<V-T)if(I=k[y],T<c){var ra=c-T;(1===I||0<I&&1===ra%I)&&d.push(R)}else y<k.length&&(T===c?y+=1:I===T-c-w+1&&(d.push(R),w+=I,y+=1))}else{c=m;m=a.G;k=wO.GROUP_SEP;I=c.length;R=[];for(w=m.length-1;0<=w&&0<I;w--){y=m[w];for(V=0;V<y&&0<=I-V-1;V++)R.push(String.fromCharCode(f+1*Number(c.charAt(I-V-1))));I-=y;0<I&&R.push(k)}d.push.apply(d,R.reverse())}}else l||d.push(String.fromCharCode(f));(a.aa||l)&&d.push(q);l=String(b);b=l.split("e+");if(2==b.length){if(l=(0,window.parseFloat)(b[0])){q=
l;if((0,window.isFinite)(q)){for(c=0;1<=(q/=10);)c++;q=c}else q=0<q?q:0;q=0-q-1;-1>q?(q=Math.pow(10,1),l=Math.round(l/q)*q):(q=Math.pow(10,q),l=Math.round(l*q)/q)}l=String(l);l=l.replace(".","");l+=(0,g.Gk)("0",(0,window.parseInt)(b[1],10)-l.length+1)}a.J+1>l.length&&(l="1"+(0,g.Gk)("0",a.J-l.length)+l);for(a=l.length;"0"==l.charAt(a-1)&&a>e+1;)a--;for(k=1;k<a;k++)d.push(String.fromCharCode(f+1*Number(l.charAt(k))))},AO=function(a,b,c){c.push(wO.Hn);
0>b?(b=-b,c.push(wO.Jn)):a.ia&&c.push(wO.Gv);b=""+b;for(var d=wO.wk,e=b.length;e<a.la;e++)c.push(d);c.push(b)},BO=function(a){a=a.charCodeAt(0);
if(48<=a&&58>a)return a-48;var b=wO.wk.charCodeAt(0);return b<=a&&a<b+10?a-b:-1},xO=function(a,b,c){for(var d="",e=!1,f=b.length;c[0]<f;c[0]++){var k=b.charAt(c[0]);
if("'"==k)c[0]+1<f&&"'"==b.charAt(c[0]+1)?(c[0]++,d+="'"):e=!e;else if(e)d+=k;else switch(k){case "#":case "0":case ",":case ".":case ";":return d;case "\u00a4":c[0]+1<f&&"\u00a4"==b.charAt(c[0]+1)?(c[0]++,d+=wO.Gn):d+=Yka[wO.Gn][1];break;case "%":if(!a.K&&1!=a.C)throw Error("Too many percent/permill");if(a.K&&100!=a.C)throw Error("Inconsistent use of percent/permill characters");a.C=100;a.K=!1;d+=wO.Kn;break;case "\u2030":if(!a.K&&1!=a.C)throw Error("Too many percent/permill");if(a.K&&1E3!=a.C)throw Error("Inconsistent use of percent/permill characters");
a.C=1E3;a.K=!1;d+=wO.Ln;break;default:d+=k}}return d},CO=function(a){return 1==a%10&&11!=a%100?"one":2==a%10&&12!=a%100?"two":3==a%10&&13!=a%100?"few":"other"},DO=function(a,b){if(void 0===b){var c=a+"";
var d=c.indexOf(".");c=Math.min(-1==d?0:c.length-d-1,3)}else c=b;return 1==(a|0)&&0==c?"one":"other"},IO=function(a){this.G=a;
this.F=this.C=this.H=null;a=wO;var b=EO;if(FO!==a||GO!==b)FO=a,GO=b,HO=new yO;this.K=HO},JO=function(a,b,c,d,e){for(var f=0;f<b.length;f++)switch(b[f].type){case 4:e.push(b[f].value);
break;case 3:var k=b[f].value,l=a,m=e,q=c[k];g.qa(q)?(l.C.push(q),m.push(l.D(l.C))):m.push("Undefined parameter - "+k);break;case 2:k=b[f].value;l=a;m=c;q=d;var w=e,y=k.bi;g.qa(m[y])?(y=k[m[y]],g.qa(y)||(y=k.other),JO(l,y,m,q,w)):w.push("Undefined parameter - "+y);break;case 0:k=b[f].value;KO(a,k,c,LO,d,e);break;case 1:k=b[f].value,KO(a,k,c,MO,d,e)}},KO=function(a,b,c,d,e,f){var k=b.bi,l=b.Wn,m=+c[k];
(0,window.isNaN)(m)?f.push("Undefined or invalid parameter - "+k):(l=m-l,k=b[c[k]],g.qa(k)||(d=d(l),k=b[d],g.qa(k)||(k=b.other)),b=[],JO(a,k,c,e,b),c=b.join(""),e?f.push(c):(a=a.K.format(l),f.push(c.replace(/#/g,a))))},ala=function(a,b){var c=a.H,d=(0,g.t)(a.D,a);
b=b.replace(Zka,function(){c.push("'");return d(c)});
return b=b.replace($ka,function(a,b){c.push(b);return d(c)})},NO=function(a){var b=0,c=[],d=[],e=/[{}]/g;
e.lastIndex=0;for(var f;f=e.exec(a);){var k=f.index;"}"==f[0]?(c.pop(),0==c.length&&(f={type:1},f.value=a.substring(b,k),d.push(f),b=k+1)):(0==c.length&&(b=a.substring(b,k),""!=b&&d.push({type:0,value:b}),b=k+1),c.push("{"))}b=a.substring(b);""!=b&&d.push({type:0,value:b});return d},RO=function(a,b){for(var c=[],d=NO(b),e=0;e<d.length;e++){var f={};
if(0==d[e].type)f.type=4,f.value=d[e].value;else if(1==d[e].type){var k=d[e].value;switch(OO.test(k)?0:PO.test(k)?1:QO.test(k)?2:/^\s*\w+\s*/.test(k)?3:5){case 2:f.type=2;f.value=bla(a,d[e].value);break;case 0:f.type=0;f.value=cla(a,d[e].value);break;case 1:f.type=1;f.value=dla(a,d[e].value);break;case 3:f.type=3,f.value=d[e].value}}c.push(f)}return c},bla=function(a,b){var c="";
b=b.replace(QO,function(a,b){c=b;return""});
var d={};d.bi=c;for(var e=NO(b),f=0;f<e.length;){var k=e[f].value;f++;if(1==e[f].type)var l=RO(a,e[f].value);d[k.replace(/\s/g,"")]=l;f++}return d},cla=function(a,b){var c="",d=0;
b=b.replace(OO,function(a,b,e){c=b;e&&(d=(0,window.parseInt)(e,10));return""});
var e={};e.bi=c;e.Wn=d;for(var f=NO(b),k=0;k<f.length;){var l=f[k].value;k++;if(1==f[k].type)var m=RO(a,f[k].value);e[l.replace(/\s*(?:=)?(\w+)\s*/,"$1")]=m;k++}return e},dla=function(a,b){var c="";
b=b.replace(PO,function(a,b){c=b;return""});
var d={};d.bi=c;d.Wn=0;for(var e=NO(b),f=0;f<e.length;){var k=e[f].value;f++;if(1==e[f].type)var l=RO(a,e[f].value);d[k.replace(/\s*(?:=)?(\w+)\s*/,"$1")]=l;f++}return d},SO=function(a){this.hc=a;
this.D=g.x("no-adsense-promo");g.P(this.D,"click",(0,g.t)(this.iE,this),"no-adsense-signup-button");this.G=g.yy(g.x("no-adsense-agreement-overlay-template"));this.C=g.x("no-adsense-agreement");g.P(this.C,"click",(0,g.t)(this.GD,this),"no-adsense-sign-agreement-button");g.P(this.C,"click",(0,g.t)(this.tD,this),"no-adsense-agreement-checkbox");g.yy(g.x("no-adsense-bulk-monetization-overlay-template"));this.F=g.x("no-adsense-monetization");g.P(this.F,"click",(0,g.t)(this.dE,this),"monetize-overlay-monetize-button");
g.P(this.F,"click",(0,g.t)(this.eE,this),"monetize-overlay-cancel-button");this.H=g.yy(g.x("no-adsense-confirmation-overlay-template"));this.K=g.x("no-adsense-confirmation");g.P(this.K,"click",(0,g.t)(this.SD,this),"confirmation-overlay-dismiss-button");(a=g.x("no-adsense-signup-promo"))?ela(a):(a=g.x("no-adsense-signup-button"))&&fla(a);this.R=window.google.risk.midl(!1);this.Lo=g.D("DBLCLK_YPC_ACTIVITY_GROUP",void 0)},ela=function(a){var b=new g.OE(g.D("PROMO_NAME",void 0));
b.write("write_impression");g.H(g.K("close",a),"click",function(){b.write("write_dismiss")});
g.H(g.K("yt-uix-button",a),"click",function(){b.write("write_accept")})},fla=function(a){var b=new g.OE(g.D("PROMO_NAME",void 0));
b.write("write_impression");g.H(a,"click",function(){b.write("write_accept")})},TO=function(a,b,c,d){g.nA.getInstance().show(b);
b=g.M(b,"yt-dialog-fg");var e=g.rA();g.dp(b,"no-adsense","no-adsense-confirmation");e.innerHTML=a.H.ub({},null,!0);c&&d&&(b=g.x("no-adsense-confirmation-alert-container"),e=g.Wp("no-adsense-alert-template"),g.Au(d,c,e,b));g.AK(a.Lo,"ytppx",{ord:"1"})},gla=function(a){var b=a.monetized,c=a.eligible-b;
a=b-a.ad_settings_applied;if(0<c&&0<a){var d=new IO(g.wq("NA_FAILED_MONETIZE_AND_SETTINGS_OF_VIDEOS"));return{message:d.format({NUM_FAILED_MONETIZE:c,NUM_FAILED_SETTINGS:a}),Yh:"yt-alert-error"}}if(0<c)return d=new IO(g.wq("NA_FAILED_TO_MONETIZE_N_VIDEOS")),{message:d.format({NUM_VIDEOS:c}),Yh:"yt-alert-error"};if(0<a)return d=new IO(g.wq("NA_FAILED_SETTINGS_N_VIDEOS")),{message:d.format({NUM_VIDEOS:a}),Yh:"yt-alert-error"};d=new IO(g.wq("NA_MONETIZED_N_VIDEOS"));return{message:d.format({NUM_VIDEOS:b}),
Yh:"yt-alert-success"}},UO=function(a){var b=g.D("NO_ADSENSE_FEATURE","");
b&&(a.feature=b)},hla=function(a){if(!a||0==a.length)return null;
var b={ec:[],ex:!0,yq:!0,xq:!1};(0,g.z)(a,function(a){0!=a&&(b.yq=!1,0>a&&(b.xq=!0));b.ec.push(["",a])});
return b},VO=function(a){this.G=a;
this.H=null;this.C={};this.K={};this.F={};this.D=null},YO=function(a){WO();
XO=[];(0,g.z)(g.J("analytics-sparkline-card",a),function(a){a=new VO(a);XO.push(a);a.init()})},WO=function(){XO&&((0,g.z)(XO,function(a){a.dispose()}),XO=null)},ila=function(a){var b=a.currentTarget,c=ZO(b);
g.Jp(g.K("dashboard-widget-edit-form",c),{method:"POST",za:g.VB({feature:"vmdshb"}),onSuccess:function(a,b){var d=g.aq(b.widget_html);g.qn(d,c);g.bz()},
onError:function(){$O(b,!1)}});
$O(b,!0);g.bz()},$O=function(a,b){var c=g.M(a,"dashboard-widget-config");
c&&(g.cp(c,"yt-uix-form-input-select-disabled",b),g.cp(c,"config-save-busy",b),g.Zp(c,!b))},aP=function(a,b){var c=g.M(a,"dashboard-widget-config");
g.B(a,"yt-uix-button-dashboard-widget-remove")?(g.cp(a,"yt-spinner-img",b),g.Zp(a,!b)):c&&(g.cp(c,"yt-uix-form-input-select-disabled",b),g.cp(c,"config-remove-busy",b),g.Zp(c,!b))},jla=function(a){var b=a.currentTarget,c=g.M(b,"dashboard-widget");
a=g.em(g.E(c,"widget-id"));aP(b,!0);g.G("/dashboard_widget_ajax",{method:"POST",za:g.VB({action_delete_widget:1,feature:"vmdshb"}),ha:{widget_id:a},onSuccess:function(){g.N(c,"invisible");g.Bf(function(){"analytics"==g.E(c,"widget-type")&&WO();g.tc(c);g.F("yt-vm-dashboard-widgets-changed")},500)},
onError:function(){aP(b,!1)}})},kla=function(a){if(a=g.M(a.currentTarget,"dashboard-widget-edit-form"))a.reset(),g.bz()},ZO=function(a){return g.M(a,"dashboard-widget")},lla=function(a){a=ZO(a.target);
g.fp(g.K("agent-dashboard-widget-news",a),"collapsed","expanded")},mla=function(a){a=ZO(a.target);
g.fp(g.K("agent-dashboard-widget-news",a),"expanded","collapsed")},nla=function(a){g.E(a,"promo-event-sent")||(g.Dp(a,"promo-event-sent","true"),g.RE(a,"EVENT_SEEN"))},ola=function(a){if(!g.B(a.target,"todo-dismiss")){var b=g.M(a.currentTarget,"todo-item");
a=ZO(a.target);(0,g.z)(g.J("todo-item",a),function(a){a!=b&&g.O(a,"opened")});
b&&(g.ep(b,"opened"),g.RE(b,"EVENT_SEEN"))}},pla=function(a){if(a=g.M(a.currentTarget,"todo-item"))g.tc(a),g.RE(a,"EVENT_DISMISSED")},rla=function(a){var b=a.currentTarget,c=qla,d=bP,e=bP;
b.disabled=!0;a=g.M(b,"yt-creator-tip-in-place-action");var f={new_state:"EVENT_DONE"};b=g.M(b,"yt-creator-tip-item-container");var k=g.E(b,"name");f.suggestion=k;b=g.E(b,"location");f.location=b;c={method:"POST",ha:f,onSuccess:g.u(c,a),onError:g.u(d,a),Oc:g.u(e,a),timeout:5E3};a="/creator_suggestions_ajax?action_"+(g.E(a,"in-place-action-name")||"").toLowerCase()+"=1";g.G(a,c)},qla=function(a){g.fp(a,"error","success")},bP=function(a){g.fp(a,"success","error")},sla=function(a){a=ZO(a.currentTarget);
a=g.K("videos-widget-search-presets",a);"custom"!=a.value&&(a.value="custom",g.bz())},tla=function(a){var b=ZO(a.currentTarget);
a=a.currentTarget;b=g.K("videos-widget-search-query",b);"all"==a.value?b.value="":"public"==a.value?b.value="is:public":"unlisted"==a.value?b.value="is:unlisted":"private"==a.value&&(b.value="is:private")},cP=function(){this.F=!1;
this.G=g.K("add-widget-button");this.D=g.K("customize-dashboard-hint");this.H=g.K("customize-dashboard-hint-dismiss");this.K=g.J("dashboard-widget-column");this.C=g.K("dashboard-widgets");g.QE(this.C);var a=this.C;g.P(a,"click",kla,"dashboard-widget-dismiss");g.P(a,"click",ila,"dashboard-widget-save");g.P(a,"click",jla,"dashboard-widget-remove");YO(this.C);g.Jf("yt-uix-slider-slide-shown",nla);a=this.C;g.P(a,"click",ola,"todo-title");g.P(a,"click",pla,"todo-dismiss");g.P(a,"click",rla,"todo-in-place-action-enable-button");
a=this.C;g.P(a,"keyup",sla,"videos-widget-search-query");g.P(a,"click",tla,"videos-widget-search-presets");a=this.C;g.P(a,"click",lla,"yt-agent-news-view-more");g.P(a,"click",mla,"yt-agent-news-view-less");this.G&&this.D&&g.H(this.G,"click",(0,g.t)(this.to,this));this.R=g.P(null,"click",(0,g.t)(this.Yv,this),"add-widget-menu-item");this.H&&g.H(this.H,"click",(0,g.t)(this.to,this));g.nB(g.FK);g.nB(g.ME);g.Jf("yt-uix-dragdrop-notification-dragend",(0,g.t)(this.RN,this));g.Jf("yt-vm-dashboard-widgets-changed",
(0,g.t)(this.mn,this));this.mn()},ula=function(a,b,c){var d=g.E(b,"widget-limit");
a.F=c>=d;g.cp(b,"widget-limit",a.F)},dP=function(a,b){if(!a.F){var c=g.K("add-widget-clickcard");
c&&g.Zz.getInstance().hide(c);g.G("/dashboard_widget_ajax",{method:"POST",za:g.VB({action_add_widget:"1"}),ha:{ei:g.D("EVENT_ID"),widget_type:b},onSuccess:(0,g.t)(function(a,c){var d=g.aq(c.widget_html);g.N(d,"invisible");g.pn(this.K[0],d,0);g.Bf(function(){g.O(d,"invisible")},10);
"analytics"==b&&YO(this.C);this.mn();g.bz()},a)})}},vla=function(a){(new g.OE(a)).write("write_dismiss")},xla=function(a){var b=g.D("PROMO_NAME",void 0);
eP(b,g.K("notification-todos-widget"),function(){dP(a,"todos");return!0});
eP(b,g.K("notification-partner-survey"),function(){return!0});
eP(b,g.x("network-join-verify-promo"),null);if(b=g.x("no-adsense-signup-button")){var c=g.M(b,"notification");g.fp(b,"yt-uix-button-primary","yt-uix-button-default");new SO(g.u(wla,c))}},eP=function(a,b,c){if(b){var d=g.M(b,"dashboard-widget");
(new g.OE(a)).write("write_impression");c&&g.P(b,"click",function(){c()&&((new g.OE(a)).write("write_accept"),g.S(d))},"notification-accept");
g.P(d,"click",g.u(vla,a),"notification-dismiss")}},yla=function(a){a=g.M(a.currentTarget,"dashboard-widget");
g.S(a)},wla=function(a){g.S(a)},fP={iQ:{1E3:{other:"0K"},
1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},hQ:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},1E14:{other:"000 trillion"}}},
EO=fP;EO=fP;var Yka={AED:[2,"dh","\u062f.\u0625.","DH"],ALL:[0,"Lek","Lek"],AUD:[2,"$","AU$"],BDT:[2,"\u09f3","Tk"],BGN:[2,"lev","lev"],BRL:[2,"R$","R$"],CAD:[2,"$","C$"],CDF:[2,"FrCD","CDF"],CHF:[2,"CHF","CHF"],CLP:[0,"$","CL$"],CNY:[2,"\u00a5","RMB\u00a5"],COP:[32,"$","COL$"],CRC:[0,"\u20a1","CR\u20a1"],CZK:[50,"K\u010d","K\u010d"],DKK:[50,"kr.","kr."],DOP:[2,"RD$","RD$"],EGP:[2,"\u00a3","LE"],ETB:[2,"Birr","Birr"],EUR:[2,"\u20ac","\u20ac"],GBP:[2,"\u00a3","GB\u00a3"],HKD:[2,"$","HK$"],HRK:[2,"kn","kn"],HUF:[34,
"Ft","Ft"],IDR:[0,"Rp","Rp"],ILS:[34,"\u20aa","IL\u20aa"],INR:[2,"\u20b9","Rs"],IRR:[0,"Rial","IRR"],ISK:[0,"kr","kr"],JMD:[2,"$","JA$"],JPY:[0,"\u00a5","JP\u00a5"],KRW:[0,"\u20a9","KR\u20a9"],LKR:[2,"Rs","SLRs"],LTL:[2,"Lt","Lt"],MNT:[0,"\u20ae","MN\u20ae"],MVR:[2,"Rf","MVR"],MXN:[2,"$","Mex$"],MYR:[2,"RM","RM"],NOK:[50,"kr","NOkr"],PAB:[2,"B/.","B/."],PEN:[2,"S/.","S/."],PHP:[2,"\u20b1","PHP"],PKR:[0,"Rs","PKRs."],PLN:[50,"z\u0142","z\u0142"],RON:[2,"RON","RON"],RSD:[0,"din","RSD"],RUB:[50,"\u20bd",
"RUB"],SAR:[2,"Rial","Rial"],SEK:[50,"kr","kr"],SGD:[2,"$","S$"],THB:[2,"\u0e3f","THB"],TRY:[2,"\u20ba","TRY"],TWD:[2,"NT$","NT$"],TZS:[0,"TSh","TSh"],UAH:[2,"\u0433\u0440\u043d.","UAH"],USD:[2,"$","US$"],UYU:[2,"$","$U"],VND:[48,"\u20ab","VN\u20ab"],YER:[0,"Rial","Rial"],ZAR:[2,"R","ZAR"]};var gP={DECIMAL_SEP:".",GROUP_SEP:",",Kn:"%",wk:"0",Gv:"+",Jn:"-",Hn:"E",Ln:"\u2030",vk:"\u221e",Ev:"NaN",DECIMAL_PATTERN:"#,##0.###",yW:"#E0",iV:"#,##0%",xQ:"\u00a4#,##0.00",Gn:"USD"},wO=gP;wO=gP;yO.prototype.parse=function(a,b){var c=b||[0];a=a.replace(/ /g,"\u00a0");var d=a.indexOf(this.R,c[0])==c[0],e=a.indexOf(this.D,c[0])==c[0];d&&e&&(this.R.length>this.D.length?e=!1:this.R.length<this.D.length&&(d=!1));d?c[0]+=this.R.length:e&&(c[0]+=this.D.length);if(a.indexOf(wO.vk,c[0])==c[0]){c[0]+=wO.vk.length;var f=window.Infinity}else{f=a;for(var k=!1,l=!1,m=!1,q=-1,w=1,y=wO.DECIMAL_SEP,I=wO.GROUP_SEP,R=wO.Hn,V="";c[0]<f.length;c[0]++){var T=f.charAt(c[0]),ra=BO(T);if(0<=ra&&9>=ra)V+=ra,m=!0;
else if(T==y.charAt(0)){if(k||l)break;V+=".";k=!0}else if(T==I.charAt(0)&&("\u00a0"!=I.charAt(0)||c[0]+1<f.length&&0<=BO(f.charAt(c[0]+1)))){if(k||l)break}else if(T==R.charAt(0)){if(l)break;V+="E";l=!0;q=c[0]}else if("+"==T||"-"==T){if(m&&q!=c[0]-1)break;V+=T}else if(1==this.C&&T==wO.Kn.charAt(0)){if(1!=w)break;w=100;if(m){c[0]++;break}}else if(1==this.C&&T==wO.Ln.charAt(0)){if(1!=w)break;w=1E3;if(m){c[0]++;break}}else break}1!=this.C&&(w=this.C);f=(0,window.parseFloat)(V)/w}if(d){if(a.indexOf(this.N,
c[0])!=c[0])return window.NaN;c[0]+=this.N.length}else if(e){if(a.indexOf(this.W,c[0])!=c[0])return window.NaN;c[0]+=this.W.length}return e?-f:f};
yO.prototype.format=function(a){if((0,window.isNaN)(a))return wO.Ev;var b=[];var c=zla;a/=Math.pow(10,c.Sw);b.push(c.prefix);var d=0>a||0==a&&0>1/a;b.push(d?this.D:this.R);if((0,window.isFinite)(a))if(a=a*(d?-1:1)*this.C,this.Y){var e=a;if(0==e)zO(this,e,this.F,b),AO(this,0,b);else{a=Math.floor(Math.log(e)/Math.log(10)+2E-15);var f=Math.pow(10,a);(0,window.isFinite)(f)&&0!==f?e/=f:(f=Math.pow(10,Math.floor(a/2)),e=e/f/f,1==a%2&&(e=0<a?e/10:10*e));f=this.F;if(1<this.V&&this.V>this.F){for(;0!=a%this.V;)e*=
10,a--;f=1}else 1>this.F?(a++,e/=10):(a-=this.F-1,e*=Math.pow(10,this.F-1));zO(this,e,f,b);AO(this,a,b)}}else zO(this,a,this.F,b);else b.push(wO.vk);b.push(d?this.W:this.N);b.push(c.gM);return b.join("")};
var zla={prefix:"",gM:"",Sw:0};var MO=CO;MO=CO;var LO=DO;LO=DO;var FO=null,GO=null,HO=null,$ka=RegExp("'([{}#].*?)'","g"),Zka=RegExp("''","g");IO.prototype.format=function(a){if(this.G){this.H=[];var b=ala(this,this.G);this.F=RO(this,b);this.G=null}if(this.F&&0!=this.F.length)for(this.C=g.Ma(this.H),b=[],JO(this,this.F,a,!1,b),a=b.join(""),a.search("#");0<this.C.length;)a=a.replace(this.D(this.C),this.C.pop());else a="";return a};
var OO=/^\s*(\w+)\s*,\s*plural\s*,(?:\s*offset:(\d+))?/,PO=/^\s*(\w+)\s*,\s*selectordinal\s*,/,QO=/^\s*(\w+)\s*,\s*select\s*,/;IO.prototype.D=function(a){return"\ufddf_"+(a.length-1).toString(10)+"_"};g.h=SO.prototype;g.h.tD=function(){var a=g.x("agreement-checkbox-2"),b=g.x("agreement-checkbox-3");g.x("agreement-accept-button").disabled=g.x("agreement-checkbox-1").checked&&a.checked&&b.checked?!1:!0};
g.h.iE=function(a){a.preventDefault();a.stopPropagation();var b=a.currentTarget;b.disabled=!0;var c={action_load_agreement:1};UO(c);g.G("/account_no_adsense_ajax",{method:"POST",za:c,context:this,onSuccess:function(b,c){a.currentTarget.disabled=!1;this.Xm(a.currentTarget,c);a.currentTarget.disabled=!0},
onError:function(){g.Q(g.x("no-adsense-promo-error-msg"))},
Ya:function(){g.AK(this.Lo,"ytpp1",{ord:"1"});b.disabled=!1}})};
g.h.GD=function(a){a.preventDefault();a.stopPropagation();var b=a.currentTarget;if(!b.disabled){b.disabled=!0;g.K("monetization-agreement-close-button",g.M(b,"no-adsense-button-container")).disabled=!0;g.x("agreement-checkbox-1").disabled=!0;g.x("agreement-checkbox-2").disabled=!0;g.x("agreement-checkbox-3").disabled=!0;var c=g.x("agreement-checkbox-4");a=!1;null!=c&&(c.disabled=!0,a=c.checked);c={action_sign_up:1};UO(c);g.G("/account_no_adsense_ajax",{method:"POST",za:c,ha:{machine_id:this.R,opt_in_creator_email:a},
context:this,nb:!0,onSuccess:function(a,c){if(c.associate_adsense_html){var d=c.associate_adsense_html;g.nA.getInstance().show(b);var e=g.rA();g.Vm(e,d)}else window.location.reload()},
onError:function(){g.nA.getInstance().hide();g.Q(g.x("no-adsense-promo-error-msg"))}})}};
g.h.Xm=function(a,b){g.nA.getInstance().show(a);g.rA().innerHTML=this.G.ub({no_adsense_agreement:b.agreement,review_disclaimer:b.review_disclaimer,underage_message:b.underage_message},null,!0)};
g.h.eE=function(a){a.preventDefault();a.stopPropagation();TO(this,a.target);g.Dj(g.Tc({action:"ype_signup_monetize_skip"}))};
g.h.dE=function(a){a.preventDefault();a.stopPropagation();a=g.K("ad-formats-overlay");var b=g.K("monetize-overlay-monetize-button",a);g.K("monetize-overlay-cancel-button",a).disabled=!0;b.disabled=!0;a=g.El(g.jp(g.K("ad-options-overlay-form",a)));var c={action_monetize_all:1};UO(c);g.G("/account_no_adsense_ajax",{method:"POST",za:c,ha:a,context:this,onSuccess:function(a,c){var d=gla(c);TO(this,b,d.message,d.Yh)},
onError:function(){TO(this,b)}})};
g.h.SD=function(){g.x("confirmation-overlay-dismiss-button").disabled=!0;this.hc&&this.hc();g.nA.getInstance().hide();g.su(this.D,!1)};g.v(VO,g.sd);VO.prototype.X=function(){this.J&&this.J.cancel();this.D&&(this.D.clearChart(),this.D=null);g.nq(this.G,"click",(0,g.t)(this.R,this));VO.M.X.call(this)};
VO.prototype.init=function(){this.C=JSON.parse(g.E(this.G,"analytics-sparkline-card")||"")||{};this.K=JSON.parse(g.E(this.G,"analytics-sparkline-card-options")||"")||{};this.F=this.K.chart||{};if(this.H=g.K("chart",this.G))this.J=g.KJ.getInstance().C.then((0,g.t)(this.W,this));g.H(this.G,"click",(0,g.t)(this.R,this))};
VO.prototype.R=function(a){var b=this.K.link;b&&(a.stopPropagation(),g.hi(b))};
VO.prototype.W=function(){var a=hla(this.C.values);if(a&&!a.yq){var b=window.google.visualization.arrayToDataTable(a.ec,a.ex),c={width:this.F.width,height:this.F.height,chartArea:{width:this.F.width-this.F.label_width,left:this.F.label_width,height:this.F.height-10,top:5},backgroundColor:{fill:"transparent"},legend:"none",enableInteractivity:!1,lineWidth:1.5,series:[{color:"#0e7dcf"}],hAxis:{textPosition:"none"},vAxis:{minValue:0,gridlines:{count:3,color:"transparent"},baselineColor:"#f2f2f2",textStyle:{color:"#666"}}};
a.xq||(c.vAxis.viewWindow={min:0});this.D=new window.google.visualization.LineChart(this.H);this.D.draw(b,c)}};var XO=null;g.h=cP.prototype;g.h.Va=function(){g.Ig(this.R)};
g.h.to=function(){this.D&&(g.tc(this.D),g.G("/dashboard_widget_ajax",{method:"POST",za:g.VB({action_dismiss_customize_hint:"1"}),ha:{ei:g.D("EVENT_ID")}}))};
g.h.mn=function(){var a=0,b={};(0,g.z)(g.J("dashboard-widget"),function(c){c=g.E(c,"widget-type");a++;b[c]=b[c]+1||1},this);
(0,g.z)(g.J("add-widget-menu-item"),function(a){var c=g.E(a,"widget-type");"videos"==c||g.cp(a,"added",0<b[c])},this);
var c=g.K("add-widget-menu-content");c&&ula(this,c,a)};
g.h.Yv=function(a){a=a.currentTarget;g.B(a,"added")||dP(this,g.E(a,"widget-type"))};
g.h.RN=function(){var a=[];(0,g.z)(this.K,function(b){var c=[];(0,g.z)(g.rn(b),function(a){g.Ap(a,"widget-id")&&c.push(Number(g.E(a,"widget-id")))},this);
a.push(c)},this);
g.G("/dashboard_widget_ajax",{method:"POST",za:g.VB({action_update_order:"1"}),ha:{ei:g.D("EVENT_ID"),widget_order:g.Xe(a)}})};g.Zh(g.uq({name:"www/dashboard",deps:["www/common"],page:"dashboard",init:function(){g.VK();var a=new cP;g.P(g.x("notifications-widgets"),"click",yla,"notification-dismiss");xla(a)}}));})(_yt_www);
