(function(g){var window=this;var SQ=function(){g.U.call(this);this.Gc=null},$ma=function(a){for(var b=0,c=a.length;b<c;b++){var d=g.K("inline-playback-renderer-inline-player",a[b]),e=g.K("inline-playback-metadata-renderer",a[b]),f=g.E(d,"config");
g.Bp(d,"config");if(f){var k=JSON.parse(f);f=TQ.length;g.Dp(d,"player-id",f);d=new UQ(d,f,k);TQ[f]=d;d=new SQ;d.La(e);VQ[f]=d}}},$Q=function(a,b){if(WQ){var c=g.E(g.K("inline-playback-renderer-inline-player",b[0]),"player-id"),d;
c&&(d=TQ[(0,window.parseInt)(c,10)]);XQ&&(d==XQ&&(YQ=!1),YQ&&(d=XQ));d&&ZQ(d)}},ZQ=function(a,b){if(XQ!=a){if(XQ){var c=XQ;
c.F=!1;c.D&&c.C.pauseVideo()}XQ=a;WQ=!!a;YQ=!!b;WQ&&(c=XQ,c.F=!0,c.D&&c.C.playVideo())}},UQ=function(a,b,c){c.attrs.id="player-inline-api-"+b;
this.D=this.F=!1;this.C=g.nj(a,c);this.C.addEventListener("onReady",(0,g.t)(this.G,this));this.C.addEventListener("onStateChange",(0,g.t)(this.H,this))},aR=function(){g.Vh.call(this,"www/instant",["www/common"])};
g.v(SQ,g.U);SQ.prototype.Z=function(){SQ.M.Z.call(this);var a=g.K("like-button-renderer",this.L());a&&(new g.tK).La(a);(a=g.K("share-button-endpoint",this.L()))&&this.getHandler().O(a,"click",this.D)};
SQ.prototype.Wa=function(){SQ.M.Wa.call(this);this.Gc&&this.Gc.X()};
SQ.prototype.D=function(a){var b=g.D("EVENT_ID",void 0);a=g.E(a.currentTarget,"video-id");var c=g.K("share-button-renderer-panel-container",this.L());if(!this.Gc){var d=g.K("share-button-renderer-loading",this.L());g.Q(d);this.Gc=new g.dH(c,a,null,function(){g.S(d);g.Q(c)},null,!1,!1,null,null,null,null,null,null,null,null,null,"inline",b,null)}g.Q(c)};var TQ=[],VQ=[],WQ=!1,YQ=!0,XQ=null,bR=[];UQ.prototype.G=function(){this.D=!0;this.F&&(this.F=!0,this.D&&this.C.playVideo())};
UQ.prototype.H=function(a){1==a?ZQ(this,!0):2==a&&this.F&&ZQ(null)};g.v(aR,g.Vh);aR.prototype.enable=function(){aR.M.enable.call(this);this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this);g.Wh(this)};
aR.prototype.init=function(){aR.M.init.call(this);g.p("yt.abuse.player.botguardInitialized",g.r("yt.abuse.player.botguardInitialized")||g.cg,void 0);g.p("yt.abuse.player.invokeBotguard",g.r("yt.abuse.player.invokeBotguard")||g.dg,void 0);g.p("yt.abuse.dclkstatus.checkDclkStatus",g.r("yt.abuse.dclkstatus.checkDclkStatus")||g.Yf,void 0);g.p("yt.player.exports.navigate",g.r("yt.player.exports.navigate")||g.ji,void 0);g.p("yt.util.activity.init",g.r("yt.util.activity.init")||g.jh,void 0);g.p("yt.util.activity.getTimeSinceActive",
g.r("yt.util.activity.getTimeSinceActive")||g.lh,void 0);g.p("yt.util.activity.setTimestamp",g.r("yt.util.activity.setTimestamp")||g.hh,void 0);WQ=!0;var a=g.r("yt.www.page.visibilitymonitor.delegateByClass");bR.push(a(null,g.r("yt.www.page.visibilitymonitor.States.VISIBLE"),$ma,"inline-playback-renderer"));var b={complete:!0};bR.push(a(null,g.r("yt.www.page.visibilitymonitor.States.VISIBLE"),$Q,"inline-playback-renderer",b));bR.push(a(null,g.r("yt.www.page.visibilitymonitor.States.HIDDEN"),$Q,"inline-playback-renderer",
b));g.r("yt.www.page.visibilitymonitor.refresh")()};
aR.prototype.dispose=function(){aR.M.dispose.call(this);for(var a=0;a<TQ.length;a++)TQ[a].C.destroy();for(a=TQ.length=0;a<VQ.length;a++)VQ[a].dispose();VQ.length=0;for(var b=g.r("yt.www.page.visibilitymonitor.unlistenByKey"),c=0;c<bR.length;c++)b(bR[a]);bR.length=0;WQ=!1;XQ=null;YQ=!1};
g.Zh(new aR);})(_yt_www);
