(function(g){var window=this;var Yxa=function(){this.gb=g.rA();g.P(this.gb,"mouseover",(0,g.t)(this.C,this),"helpable-preview")},d$=function(a,b){this.C=a;
this.F=b},e$=function(a){this.C=[];
if(a)a:{if(a instanceof e$){var b=a.Jc();a=a.Eb();if(0>=this.Kb()){for(var c=this.C,d=0;d<b.length;d++)c.push(new d$(b[d],a[d]));break a}}else b=g.mm(a),a=g.lm(a);for(d=0;d<b.length;d++)Zxa(this,b[d],a[d])}},Zxa=function(a,b,c){var d=a.C;
d.push(new d$(b,c));b=d.length-1;a=a.C;for(c=a[b];0<b;)if(d=b-1>>1,a[d].C>c.C)a[b]=a[d],b=d;else break;a[b]=c},f$=function(a){g.U.call(this);
this.D=this.J=this.H=null;this.Ab=!1;this.N=a.IB;this.aa=a.NB;this.Y=a.nC;a=a.oC;this.D=a.cloneNode(!0);this.D.id="";this.J=g.K("yt-suggest-menu-item",a).cloneNode(!0)},h$=function(a){g$(a);
g.sc(a.D)},i$=function(a,b){var c=a.D.children[b];
c&&(g$(a),g.N(c,"yt-suggest-menu-item-selected"),a.G=b,g.Fo(c,a.D))},$xa=function(a,b,c){a=a.J.cloneNode(!0);
b.data?(a=new g.wy(g.An(a),g.mm(b.data)),a=g.ln(g.Sn(a.ub(b.data)))):g.L(a,b.text);g.Dp(a,"suggest-menu-item-index",c);return a},aya=function(a,b){a.H&&(a.V=a.H[b],a.aa(a),h$(a),a.hide())},g$=function(a){null!=a.G&&(g.O(a.D.children[a.G],"yt-suggest-menu-item-selected"),a.G=null)},dya=function(){var a=g.x("instream-ads");
a&&g.H(a,"click",bya);g.P(g.K("account-ad-defaults"),"click",cya,"ad-options-setting")},bya=function(a){a=a.currentTarget;
var b=g.x("long-instream-ads");b&&(a.checked?b.disabled=!1:(b.disabled=!0,b.checked=!1));if(b=g.x("trueview-inslate-ads"))a.checked?b.disabled=!1:(b.disabled=!0,b.checked=!1)},eya=function(){return(0,g.Ck)([g.x("instream-ads"),
g.x("trueview-instream-ads-checkbox")],function(a){return a&&a.checked})},cya=function(){var a=eya(),b=g.x("auto-gen-midroll-ads-checkbox");
b&&(b.disabled=!a,b.checked=b.checked&&a,g.Zy.getInstance().ae(b))},k$=function(a,b){var c=g.D("ADVANCED_SEARCH_DATA");
this.ma=a;this.Jb=b;this.formData=new j$(c);this.F=this.currentSearchValue="";var d=this;this.ma.$watch(function(){return d.formData},function(a,b){d.currentSearchValue=fya(d,a,b)},!0)},j$=function(a){this.visibility={"public":!1,
unlisted:!1,"private":!1,privacy_ru:!1,draft:!1};this.after=this.before=this.title=this.tag=this.video_id="";this.dataOrder=[];a&&g.lb(this,a)},gya=function(a,b){if(0==b.length)return"";
var c=b.join(" ");1<b.length&&(c="{"+c+"}");return a+":"+c},hya=function(a,b){return g.Qa(b)?"":a+":"+b},jya=function(a,b){var c=iya(b);
return 0==c.length?"":1==c.length?a+":"+c[0]:a+":("+c.join(" ")+")"},iya=function(a){var b=[];
g.ab(a.split('"'),function(a,d){a.trim()&&(d%2?b.push('"'+a+'"'):b=b.concat(a.trim().split(" ")))});
return b},kya=function(a){a.C&&(a.C.abort(),a.C=null)},fya=function(a,b,c){kya(a);
var d=[];g.ab(b,function(a,d){if("dataOrder"!=d){var e=l$[d](d,a),f=l$[d](d,c[d]),m=g.Fa(b.dataOrder,function(a){return a==d});
e!=f&&(-1==m?g.Qa(e)||b.dataOrder.push(d):g.Qa(e)&&b.dataOrder.splice(m,1))}});
(0,g.z)(b.dataOrder,function(a){d.push(l$[a](a,b[a]))});
return d.join(" ")},m$=function(a,b,c){var d=this;
this.Jb=b;this.metadata={};this.actions=[];c.C=this.actions;c.D=this.metadata;a.$watchCollection(function(){return d.actions},function(a,b){var c=a.filter(function(a){return-1==b.indexOf(a)});
(0,g.z)(c,function(a){this.Jb((0,g.t)(this.C,this,a),0,!1)},d)})},n$=function(a,b){this.ma=a;
this.selectedBatches=[];this.selectedIndex=-1;this.isAjaxComplete=!1;this.batchesDone=[];this.currentPage=-1;this.C=0;this.hasErrors=!1;a.$watch(function(){return b.C},(0,g.t)(this.D,this));
a.$watch(function(){return b.hasErrors},(0,g.t)(this.F,this))},o$=function(a){var b=a.currentPage,c=a.C;
a.ma.batchesDone=a.batchesDone.slice(b*c,b*c+c)},p$=function(a,b,c){this.matchPolicySettings={policy:a.defaultPolicy||"",
operation:"invalid",removeAll:!0};c.F=this.matchPolicySettings;b.$on("$destroy",function(){c.C=null})},q$=function(a,b,c,d){var e=g.Wp(g.x("alerts-template"));
d=d?g.x(d):g.x("vm-general-notifs");g.sc(d);var f=g.Au(a,b,e,d);window.scrollTo(0,0);c||g.Bf(function(){g.N(f,"vm-message-fade-out");g.Bf(g.u(g.tc,f),750)},8E3)},r$=function(a,b,c){q$("yt-alert-error",a,b,c)},lya=function(a){(0,g.z)(a,function(a){r$(a,void 0,void 0)})},mya=function(a){q$("yt-alert-info",a,!0,void 0)},nya=function(){r$(g.wq("ERROR_OCCURRED"))},s$=function(a,b,c,d){d=d||{};
d[a]="1";a={method:"POST",ha:b,za:g.VB(d)};c&&g.lb(a,c);g.G("/video_ajax",a)},t$=function(){var a=g.Ma(g.en("input","video-checkbox")),b=g.Ma(g.en("input","playlist-checkbox"));
return g.Ol(a,b)},oya=function(){return(0,g.Wi)(t$(),function(a){return a.checked})},u$=function(){return(0,g.Zi)(oya(),function(a){return a.value})},v$=function(){var a=u$().length,b=t$().length;
return 0<b&&a==b},pya=function(a){a=g.M(a,"vm-video-item");
return g.E(a,"video-id")},qya=function(a){var b=g.M(a,"vm-video-item")||g.M(a,"playlist-item");
b&&a&&g.cp(b,"selected",a.checked)},rya=function(){var a=g.J("vm-video-select-all");
if(a){var b=v$();(0,g.z)(a,function(a){a.checked=b})}g.F("yt-vm-select-all-checkbox-changed")},sya=function(){var a=(0,g.Zi)(g.J("vm-video-actions-bar"),function(a){return g.K("vm-addto-button",a)});
return(0,g.Wi)(a,function(a){return null!=a})},w$=function(a){return g.x("vm-video-"+a)},z$=function(){g.nB(g.eE);
if(!g.D("IS_READONLY",!1)){g.P(null,"click",tya,"vm-video-actions-delete-button-confirm");g.P(null,"change",uya,"vm-video-actions-delete-warning-checkbox");g.P(null,"click",x$,"vm-video-actions-delete-button-cancel");x$();vya();y$(!1);var a=g.x("vm-video-list-container");g.P(a,"click",wya,"video-checkbox");g.P(a,"click",wya,"playlist-checkbox");g.P(a,"click",xya,"vm-video-publish");g.P(a,"click",yya,"vm-video-delete");g.P(null,"click",zya,"vm-video-edit-menu-delete");Aya();Bya()}},Aya=function(){var a=
t$();
(0,g.z)(a,function(a){a.disabled=!1});
g.dz();A$()},vya=function(){g.P(null,"click",Cya,"vm-actions-bar-delete-videos");
g.P(null,"click",function(a){y$(a.target.checked)},"vm-video-select-all");
g.P(null,"click",Dya,"vm-download-mp4");B$={};g.P(null,"click",Eya,"vm-addto-button")},Eya=function(a){var b=g.M(a.target,"vm-addto-button");
a=g.E(b,"video-ids")||"";var c=String(g.yg(b)),d=B$[c];d?(c=d,c.D!=a&&(c.D=a,g.Nz(c))):(d=g.Zz.getInstance(),b=d.Ta(b),b=g.Uz(d,b),d=new g.Lz({feature:"vm",videoIds:a}),d.La(b),B$[c]=d)},yya=function(a){a=pya(a.target);
C$([a])},Cya=function(){C$(u$())},Fya=function(a){return"True"==w$(a).getAttribute("data-global-block")},Gya=function(a){return"True"==w$(a).getAttribute("data-takedown")},zya=function(a){a=g.E(a.currentTarget,"video-id");
C$([a])},C$=function(a){D$=a;
E$=(0,g.Ck)(a,Fya);var b=(0,g.Ck)(a,Gya),c=g.jc("vm-video-actions-delete-dialog");g.nA.getInstance().show(c);var d=F$();c="True"==c.getAttribute("data-has-live-restrictions-warning");g.di("/gen_204?"+g.Tc({a:"vm_delete_video_dialog",num_videos:a.length,has_global_block_videos:E$}));E$||b||c||!d.Rh?d.Sh&&(d.He.disabled=!d.Sh.checked,g.Q(d.Rh)):g.S(d.Rh);b=g.xq("VM_BULK_ACTIONS_WARN_DELETE_MESSAGE",a.length);25<a.length&&(b=g.wq("VM_BULK_ACTIONS_WARN_DELETE_MANY_MESSAGE"));d.vn.innerHTML=b;b=g.xq("VM_BULK_ACTIONS_WARN_DELETE_TITLE",
a.length);d.oB.innerHTML=b;d.Ii.innerHTML=g.xq("VM_DELETE_EXTRA_WARNING",a.length);g.L(g.K("yt-uix-button-content",d.He),g.xq("VM_DELETE_CONFIRM_BUTTON_MESSAGE",a.length))},tya=function(){var a=F$().Ii;
if(null!=D$)if(t$().length==D$.length&&1<D$.length&&!g.tu(a)){a=F$();g.S(a.vn);g.Q(a.Ii);var b=a.He,c=g.K("yt-uix-button-content",b);G$=c.innerHTML;H$=new g.Zo(1E3);I$=5;b.disabled=!1;b.setAttribute("disabled","true");g.L(c,g.xq("VM_DELETE_DELAY_MESSAGE",I$));g.Kd(H$,"tick",g.u(Hya,a.He,c),!1);H$.start()}else mya(g.wq("VM_PLEASE_WAIT_DELETING")),a=D$,b={onError:nya,onSuccess:g.u(Iya,a)},c={num_videos:a.length},E$&&(c.has_global_block_videos="true"),s$("action_delete_videos",{v:a.join(",")},b,c),g.nA.getInstance().hide(),
x$()},uya=function(){var a=F$();
a.He.disabled=!a.Sh.checked},x$=function(){D$=null;
E$=!1;var a=F$();g.S(a.Ii);g.Q(a.vn);a.Rh&&g.Q(a.Rh);a.Sh&&(a.Sh.checked=!1);H$&&H$.stop();a.He&&a.He.removeAttribute("disabled");G$&&(g.K("yt-uix-button-content",a.He).innerHTML=G$)},F$=function(){var a=g.rA(),b={};
b.oB=g.K("yt-dialog-title",a);b.vn=g.K("vm-video-actions-delete-warning",a);b.Ii=g.K("vm-video-actions-delete-extra-warning",a);b.Rh=g.K("vm-video-actions-delete-warning-area",a);b.Sh=g.K("vm-video-actions-delete-warning-checkbox",a);b.He=g.K("vm-video-actions-delete-button-confirm",a);return b},xya=function(a){a=g.E(a.currentTarget,"video-id");
mya(g.wq("VM_PLEASE_WAIT_PUBLISHING"));s$("action_publish",{video_id:a},{onError:nya,onSuccess:g.u(Jya,a)})},Jya=function(a,b,c){(b=c.errors)&&0<b.length?lya(b):(0,g.z)(c.messages,function(a){J$(a)});
c.success&&(Kya(a),Lya(a))},Hya=function(a,b){--I$;
if(0<I$){var c=g.xq("VM_DELETE_DELAY_MESSAGE",I$);g.L(b,c)}else c=u$(),g.L(b,g.xq("VM_DELETE_CONFIRM_BUTTON_MESSAGE",c.length)),a.removeAttribute("disabled"),H$.stop()},Iya=function(a,b,c){(b=c.errors)&&0<b.length?lya(b):((0,g.z)(a,function(a){g.tc(w$(a))}),Mya(a.length),J$(g.wq("VM_VIDEOS_DELETED"),!0))},Dya=function(a){1<u$().length?r$(g.wq("VM_VIDEOS_DOWNLOAD_ONE_AT_A_TIME"),!0):(a=a.target,g.Ap(a,"download-url")||(a=g.M(a,"vm-download-mp4")),a=g.E(a,"download-url"),g.hi(a))},wya=function(a){qya(a.target);
A$()},y$=function(a){var b=t$();
(0,g.z)(b,function(b){g.cz(b,a);qya(b)});
g.dz();A$();a||Nya()},A$=function(){Nya();
rya();var a=g.J("vm-video-action-button-selected"),b=g.J("vm-video-action-button-none-selected"),c=g.J("vm-video-list-action-menu"),d=g.J("vm-addto-button"),e=g.J("vm-retract-claims"),f=!!u$().length;Oya(b,f);Oya(a,!f);K$(c,!f);K$(d,!f);K$(e,!f)},Nya=function(){var a=u$().join();
(0,g.z)(sya(),function(b){g.Dp(b,"video-ids",a)})},K$=function(a,b){(0,g.z)(a,function(a){a.disabled=b})},Oya=function(a,b){(0,g.z)(a,function(a){g.su(a,!b)})},J$=function(a,b){q$("yt-alert-success",a,b,void 0);
y$(!1)},Mya=function(a){var b=g.x("creator-subheader-item-count");
if(b){var c=(0,window.parseInt)(g.Kn(b),10);g.L(b,String(c-a));g.N(b,"num-videos-flash");g.Bf(function(){g.O(b,"num-videos-flash")},10)}},L$=function(a){(0,g.z)(g.J("vm-video-actions-bar"),function(b){g.su(b,a)})},Kya=function(a){a=w$(a);
(0,g.z)(g.J("vm-draft-content",a),function(a){g.S(a)});
(a=g.K("vm-video-metrics",a))&&g.Q(a)},Lya=function(a){(0,g.z)(g.J("vm-video-privacy",w$(a)),function(a){g.su(a,g.B(a,"vm-public"))})},Bya=function(){(0,g.z)(g.J("vm-video-side-notification-text-item"),function(a){a=a.getElementsByTagName("a");
if(a[0]&&a[0].href){var b=a[0].href;if(b.match(/support.google.com.*answer/)&&(b=b.match(/[0-9]+/g))){var c=b[0];a[0].onclick=function(a){a.preventDefault();g.jC(c)}}}})},M$=function(a,b,c,d){this.C=c;
this.Jb=b;this.F=d;this.hideLoading=!0;this.videoItems=Pya(this.F);b((0,g.t)(function(){g.VK();z$();Qya(this.C);g.vF()},this),0,!1);
a.$on("videoList:updated",(0,g.t)(function(){this.videoItems=Pya(this.F);a.$root.$digest();g.VK();z$();Qya(this.C);g.vF()},this))},Rya=function(){return{require:"ngModel",
link:function(a,b,c,d){a.value="invalid";d.$setViewValue(a.value);a.$watch("value",function(){d.$setViewValue(a.value)});
a.$on("$destroy",function(){d.$setViewValue(null)})},
templateUrl:"block_outside_ownership_widget.html"}},Tya=function(){return{require:"?ngModel",
link:function(a,b,c,d){var e=new g.pF("yyyy-MM-dd"),f=new g.JM;f.Yj=!0;f.ab&&g.KM(f);f.Ug=!1;f.Sa&&g.KM(f);f.Wt=!0;g.UM(f);f.Lh=!1;g.QM(f);g.RM(f);g.LM(f);f.Zj=!0;g.QM(f);g.LM(f);f.Zm=!1;g.VM(f);g.UM(f);f=new g.ZM(e,new g.xM("yyyy-MM-dd"),f);"datePickerParent"in c&&(c=g.M(b[0],c.datePickerParent),f.Em=c);f.La(b[0]);a.$on("$destroy",g.u(g.ud,f));d&&g.Kd(f,"change",g.u(Sya,a,d,e))}}},Sya=function(a,b,c,d){c=d.date?c.format(d.date):"";
a.$apply((0,g.t)(b.$setViewValue,b,c))},Uya=function(){return{require:"ngModel",
link:function(a,b,c,d){a.filtering={};var e=a.filtering;e.option="invalid";e.domains="";a.$watch("filtering",function(){var a={option:e.option};if("blacklist"==e.option||"whitelist"==e.option)a.domains=e.domains;d.$setViewValue(a)},!0);
a.$on("$destroy",function(){d.$setViewValue(null)})},
templateUrl:"domain_filtering_widget.html"}},Wya=function(){return{require:"ngModel",
link:function(a,b,c,d){var e=c.separator||",";d.$formatters.push(function(a){a=(0,g.Zi)(a,g.Ua);return a.join(e+"\r\n")});
d.$parsers.push(function(a){var b=Vya(e,a);d.$setValidity("domain",b);return b?a.split(e):void 0})}}},Vya=function(a,b){var c=b.split(a);
if(1E3<=c.length)return!1;c=(0,g.Zi)(c,g.Ua);return(0,g.Dk)(c,function(a){-1!=a.indexOf("//")&&(a=g.Pc(a));return 50>=a.length&&"*"!=a.trim()})},N$=function(a,b,c,d){g.sd.call(this);
g.vd(this,b);this.F=c;this.H=d;this.G=a;this.C=this.D=null},Xya=function(a){a.G.$apply(g.u(g.Ll,a.C))},Yya=function(a){var b={};
g.ab(a.D,function(a,d){null!=a&&(b[d]=g.sa(a)?a:window.angular.toJson(a))});
return b},O$=function(a,b){this.D=a;
this.F=b;this.C=null;this.hasErrors=!1},Zya=function(a){a.F.post("/my_videos_ajax",{},{params:g.VB({action_bulk_actions_history:1})}).then(function(b){return a.Aj(b.data)})["catch"](function(){return a.Nr()})},$ya=function(a){a.D.$apply((0,g.t)(function(){this.C=null;
this.hasErrors=!1},a))},P$=function(a){g.wd.call(this,a)},aza=function(a){this.payload=a;
g.wd.call(this,"S")},bza=function(a){this.payload=a;
g.wd.call(this,"T")},cza=function(a){this.payload=a;
g.wd.call(this,"U")},dza=function(a){this.payload=a;
g.wd.call(this,"V")},Q$=function(){this.F=null;
this.D=(0,g.A)();this.G=!1;this.C=new g.Se;this.H=new g.TK;this.K=new g.mh(void 0)},eza=function(a,b){g.Te(a.C.F,b);
a.C.remove(b);R$(a)},R$=function(a){if(!a.G){g.Ie(a.F);
a.F=null;var b=fza(a);null!==b&&(b=Math.max(b,a.D),gza(a,b))}},fza=function(a){var b=null;
a.C.forEach(function(a){b=null===b?a.C:Math.min(b,a.C)});
return b},gza=function(a,b){var c=b-(0,g.A)();
a.F=g.He(function(){this.F=null;hza(this)},c,a)},hza=function(a){a.C.isEmpty();
var b=(0,g.A)();a.G=!0;a.D=b+1E3;var c=iza(a),d=a.H.getValue(),e=(0,g.t)(function(){this.G=!1;g.UK(this.H);this.D=Math.max(this.D,b+d);R$(this)},a),f={};
f.timeout=d;f.onSuccess=(0,g.t)(a.J,a);f.onError=e;f.Oc=e;g.ch(a.K,"upload/feedback",c,f)},jza=function(a){var b=new e$;
a.C.forEach(function(a){Zxa(b,-a.C,a);20<b.Kb()&&b.remove()});
return b.Eb()},iza=function(a){var b={context:g.bh(a.K.C),
continuations:[],ids:[]};a=jza(a);(0,g.z)(a,function(a){var c=a.Co;c?b.continuations.push(c):(c={},c.videoId=a.F,b.ids.push(c))});
return b},kza=function(a){var b=[];
(0,g.z)(a.contents||[],function(a){a.uploadFeedbackItem&&b.push(a.uploadFeedbackItem)});
(0,g.z)(a.continuationContents||[],function(a){a.uploadFeedbackItemContinuation&&b.push(a.uploadFeedbackItemContinuation)});
return b},lza=function(a){var b=null;
a.continuations&&(a=(0,g.Wi)(a.continuations,function(a){return"uploadFeedbackRefreshContinuation"in a}),a.length&&(b=a[0].uploadFeedbackRefreshContinuation));
return b},mza=function(a,b){this.F=a;
this.ZN=b;this.Co=null;this.C=(0,g.A)()},nza=function(a,b){a.C=b},qza=function(a,b){this.aa=pya(a);
this.V=this.la=this.J=this.R=this.K=this.D=this.N=this.F=null;this.Y=!1;this.G=this.H=null;this.W=b;this.C=new g.zs;oza(this,a);pza(this)},oza=function(a,b){a.F=b;
a.N=g.K("vm-upload-progress-indicator",b);a.D=g.K("vm-processing-progress-message",b);a.K=g.K("vm-processing-time-remaining-message",b);var c=a.D;c&&g.wo(c,!1);(c=a.K)&&g.wo(c,!1);a.R=g.K("vm-transfer-progress-message",b);a.J=g.K("vm-transfer-time-remaining-message",b);a.la=g.K("vm-video-status-message",b);a.V=g.K("vm-video-status-detailed-message",b);a.H=g.K("vm-processing-progress-overlay",b);(c=a.H)&&g.wo(c,!1);a.G=g.bn("IMG",g.K("vm-thumbnail-container",b)).item(0)},pza=function(a){var b=a.C,
c=0,d;
for(d in b.C)Object.prototype.hasOwnProperty.call(b.C,d)&&c++;null!=a.F&&null!=a.N&&(a.C.O(a.W,"S",(0,g.t)(a.HO,a)),a.C.O(a.W,"T",(0,g.t)(a.VG,a)),a.C.O(a.W,"U",(0,g.t)(a.FI,a)));a.C.O(a.W,"V",(0,g.t)(a.ZH,a))},rza=function(a){var b=a.F;
a.C.removeAll();a.F=null;a.N=null;a.R=null;a.J=null;a.D=null;a.la=null;a.V=null;a.H=null;a.G=null;g.tc(b)},S$=function(a,b){g.sc(a);
if(b){var c=g.sK(b);a.appendChild(c)}},sza=function(a){a=(0,g.Wi)(a,function(a){return 0<a.width&&0<a.height&&!!a.url});
if(!a.length)return null;var b=(0,g.Wi)(a,function(a){return 212<=a.width&&119<=a.height});
return(b.length?b[0]:a[a.length-1]).url},tza=function(a){var b=a.R;
b&&g.wo(b,!1);(a=a.J)&&g.wo(a,!1)},T$=function(a,b){var c=a.D;
c&&g.wo(c,b);(c=a.K)&&g.wo(c,b);(c=a.H)&&g.wo(c,b)},uza=function(){this.C=new Q$;
g.vd(this,this.C)},Qya=function(a){(0,g.z)(g.J("vm-video-item"),(0,g.t)(function(a){if(g.K("vm-upload-progress-indicator",a)){var b=new g.Zd;
a=(new qza(a,b)).aa;if(!g.Te(this.C.C.F,a)){var d=this.C;g.Te(d.C.F,a);d.C.set(a,new mza(a,b));R$(d)}}},a))},U$=function(a){g.sd.call(this);
g.vd(this,a);this.F=null},vza=function(a,b){this.D=a;
this.F=b;this.C=g.D("VIDEO_LIST_DISPLAY_OBJECT")||[]},wza=function(a){return(0,g.Zi)(a.C,function(a){return a.id})},Pya=function(a){return(0,g.Zi)(a.C,(0,g.t)(function(a){return{id:a.id,
html:this.F.trustAsHtml(a.html)}},a))},xza=function(a,b){b&&b.length&&((0,g.z)(b,(0,g.t)(function(a){var b=g.Ga(this.C,function(b){return a.id==b.id});
b&&(b.html=a.html)},a)),a.D.$broadcast("videoList:updated"))},yza=function(){this.R=new g.uN(3E3,(0,g.t)(this.ly,this),(0,g.t)(this.FA,this));
this.K=0;this.F=!1;this.C=null;var a=g.x("creator-page-content");var b=g.cN(a,[V$.name],"BulkActionsService");var c=g.cN(a,[V$.name],"BulkActionsHistoryService");a=g.cN(a,[V$.name],"VideoListService");this.H=b;this.W=c;this.ia=a},Dza=function(a){a.Ab=g.D("VM_BULK_ACTIONS_ENABLED")||!1;
if(a.Ab){g.lb(g.mF,g.wF());a.la=g.x("vm-general-notifs");a.J=g.x("vm-bulk-actions-selection");a.D=g.x("confirm-bulk-update-checkbox");a.na=g.x("vm-bulk-actions-selection-message");a.G=g.x("vm-bulk-actions-editing");a.N=g.x("vm-bulk-actions-editing-button-cancel");a.V=g.x("vm-bulk-actions-editing-button-submit");a.Y=g.x("vm-bulk-actions-progress-bar");a.Yb=g.x("vm-bulk-actions-progress-bar-message");var b=g.x("bulk-action-search-query");b&&(a.searchQuery=b.value);g.tu(a.Y)&&zza(a);(0,g.z)(g.J("vm-bulk-actions-history"),
function(a){g.H(a,"click",(0,g.t)(this.Ns,this))},a);
(0,g.z)(g.J("vm-actions-menu-advanced"),function(a){g.H(a,"click",(0,g.t)(this.Ut,this))},a);
a.aa=g.x("vm-bulk-actions-selection-link");g.H(a.aa,"click",(0,g.t)(a.zL,a,!0));g.H(a.N,"click",(0,g.t)(a.Fg,a));g.H(a.V,"click",(0,g.t)(a.un,a));g.H(a.D,"click",(0,g.t)(a.Fz,a));g.Jf("yt-vm-select-all-checkbox-changed",(0,g.t)(a.FH,a));g.P(a.la,"click",(0,g.t)(a.Ns,a,1),"vm-bulk-actions-view-report-link");Aza(a);Bza(a);Cza(a)}},Aza=function(a){g.P(null,"click",(0,g.t)(a.rG,a),"monetization-input");
g.P(null,"change",(0,g.t)(a.HI,a),"usage-policy-select");g.P(null,"click",(0,g.t)(a.mu,a),"ad-friendly-checkbox")},Bza=function(a){g.P(null,"click",(0,g.t)(a.fk,a,"public"),"vm-playlist-set-videos-privacy-public");
g.P(null,"click",(0,g.t)(a.fk,a,"unlisted"),"vm-playlist-set-videos-privacy-unlisted");g.P(null,"click",(0,g.t)(a.fk,a,"private"),"vm-playlist-set-videos-privacy-private");g.P(null,"click",(0,g.t)(a.fk,a,"privacy_ru"),"vm-playlist-set-videos-privacy-privacy_ru");(0,g.z)(g.J("vm-actions-bar-freq-action"),function(a){var b=(0,g.t)(this.Tv,this,a.attributes["bulk-action"].value);g.H(a,"click",b)},a)},Cza=function(a){g.P(null,"click",(0,g.t)(a.pu,a,"all_rights_reserved"),"vm-playlist-set-videos-license-standard");
g.P(null,"click",(0,g.t)(a.pu,a,"creative_commons"),"vm-playlist-set-videos-license-cc")},W$=function(a){if(v$()&&Eza()){if(a.F){var b=""!=a.searchQuery?g.wq("VM_BULK_ACTIONS_ALL_SEARCHED_VIDEOS_SELECED"):g.wq("VM_BULK_ACTIONS_ALL_VIDEOS_SELECED");
g.S(a.aa)}else b=u$(),b=g.xq("VM_BULK_ACTIONS_SELECTED_VIDEOS",b.length),g.Q(a.aa);g.L(a.na,b);g.su(a.J,!0)}else g.su(a.J,!1)},X$=function(a,b){var c=g.xq("VM_BULK_ACTIONS_PROGRESS",b);
g.L(a.Yb,c)},Fza=function(a){return g.x("vm-bulk-actions-editing-field-"+a)},Gza=function(a,b,c){var d=Fza(a);
if(d){var e=[];(0,g.z)(g.J("yt-uix-form-input-checkbox",d),function(a){a=a.name;g.Te(b.F,a)&&(e.push(a),b.remove(a))});
e.length||(e=[c]);b.set(a,e)}},Hza=function(a){switch(a.K){case 0:a=a.R;
g.wN(a);a.F=3E3;break;case 4:a=a.R;g.wN(a);a.F=6E3;g.vN(a);break;case 8:a=a.R,g.wN(a),a.F=15E3,g.vN(a)}},zza=function(a){L$(!1);
g.S(a.G);g.Q(a.Y);a.R.start()},Eza=function(){var a=g.x("vm-pagination");
return null!=a&&null!=g.K("yt-uix-pager",a)},Iza=function(a,b){var c=g.x("ad-friendly-guidelines-content");
c&&(g.su(c,b),a.mu())},Jza=function(a,b,c,d,e,f){a.Fg();
var k=[];b&&k.push("overlay_ads");c&&k.push("trueview_instream_ads");d&&k.push("instream_ads");e&&k.push("product_listing_ads");f&&k.push("display_ads");a.Mt(function(a){a.set("monetization","ads");a.set("ad_formats",k);a.set("ad_friendly_guidelines","")})},Y$=function(a){this.D=g.K("ad-formats-overlay");
this.K=a;this.G=g.K("bulk-monetize-overlay-cancel-button",this.D);this.F=g.K("bulk-monetize-overlay-monetize-button",this.D);this.C=g.K("acknowledged-ad-friendly-guidelines",this.D)},Z$=function(a){this.F=null;
this.C=g.K("vm-multi-channel-top-channels",a);var b=g.K("vm-multi-channel-search-box",a),c=new f$({nC:g.K("vm-multi-channel-search-results",a),oC:g.K("vm-multi-channel-search-menu-template",a),IB:(0,g.t)(this.D,this),NB:(0,g.t)(this.H,this)});c.La(b);g.H(g.K("vm-multi-channel-search-btn",a),"click",(0,g.t)(this.D,this,c))},$$=function(){var a=g.x("vm-video-list-container");
g.P(a,"click",(0,g.t)(this.D,this),"vm-video-suggestion-button");g.P(a,"click",(0,g.t)(this.G,this),"vm-video-suggestion-close-button");a=g.J("vm-video-item",a);this.C={};(0,g.z)(a,function(a){if(1==g.rn(g.K("vm-owner-bar",a)).length){var b=g.E(a,"video-id");this.C[b]=a}},this);
0!=Object.keys(this.C).length&&(a={method:"POST",ha:{video_ids:Object.keys(this.C).join(",")},za:{action_video_manager_suggestions:1},onSuccess:(0,g.t)(this.F,this),timeout:1E3},g.G("/creator_suggestions_ajax",a))},Kza=function(){var a=g.x("channel-picker-container"),b=g.K("vm-multi-channel-search-box",a);
a&&b&&(new Z$(a),(0,g.z)(window.document.querySelectorAll("[data-button-menu-id=channel-picker-menu]"),function(a){g.H(a,"click",function(){g.Bf(function(){var a=window.document.querySelectorAll("[id=channel-picker-menu] input");a.length&&a[a.length-1].focus()},0)})}))};
Yxa.prototype.C=function(a){a=g.E(a.target,"preview-id");for(var b=g.J("ad-format-preview",this.gb),c=0;c<b.length;c++)b[c].id===a?g.Q(b[c]):g.S(b[c])};
d$.prototype.getValue=function(){return this.F};
d$.prototype.clone=function(){return new d$(this.C,this.F)};g.h=e$.prototype;g.h.remove=function(){var a=this.C,b=a.length,c=a[0];if(!(0>=b)){if(1==b)g.Ll(a);else{a[0]=a.pop();a=0;b=this.C;for(var d=b.length,e=b[a];a<d>>1;){var f=2*a+1,k=2*a+2;f=k<d&&b[k].C<b[f].C?k:f;if(b[f].C>e.C)break;b[a]=b[f];a=f}b[a]=e}return c.getValue()}};
g.h.Eb=function(){for(var a=this.C,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getValue());return b};
g.h.Jc=function(){for(var a=this.C,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].C);return b};
g.h.Pd=function(a){return(0,g.Ck)(this.C,function(b){return b.getValue()==a})};
g.h.clone=function(){return new e$(this)};
g.h.Kb=function(){return this.C.length};
g.h.isEmpty=function(){return g.Ja(this.C)};
g.h.clear=function(){g.Ll(this.C)};g.v(f$,g.U);g.h=f$.prototype;
g.h.Z=function(){f$.M.Z.call(this);(this.Y||g.M(this.L(),"yt-uix-form-input-container")).appendChild(this.D);g.Cy(this,"mousedown","yt-suggest-menu-item",this.iA,this,this.D);g.Cy(this,"click","yt-suggest-menu-item",this.NM,this,this.D);g.Cy(this,"mouseover","yt-suggest-menu-item",this.jA,this,this.D);var a=this.L(),b=this.getHandler();b.O(a,"focus",(0,g.t)(this.fA,this));b.O(a,"blur",(0,g.t)(this.eA,this));b.O(a,"keydown",(0,g.t)(this.gA,this));b.O(a,"keyup",(0,g.t)(this.hA,this));h$(this);this.hide()};
g.h.isEnabled=function(){return this.Ab};
g.h.show=function(){g.Q(this.D)};
g.h.hide=function(){g.S(this.D)};
g.h.fA=function(){this.Ab=!0};
g.h.eA=function(){this.Ab=!1;this.hide();h$(this)};
g.h.gA=function(a){if(0!==this.D.children.length)switch(a.keyCode){case 38:a.preventDefault();null==this.G?i$(this,this.D.children.length-1):(a=this.G-1,0<=a&&a<this.D.children.length?i$(this,a):g$(this));break;case 9:case 40:a.preventDefault(),null==this.G?i$(this,0):(a=this.G+1,0<=a&&a<this.D.children.length?i$(this,a):g$(this))}};
g.h.hA=function(a){switch(a.keyCode){case 38:case 9:case 40:break;case 13:a.preventDefault();null!=this.G&&aya(this,this.G);break;case 27:a.preventDefault();h$(this);this.hide();break;default:this.N(this)}};
g.h.iA=function(a){a.preventDefault();a=g.E(a.currentTarget,"suggest-menu-item-index");aya(this,(0,window.parseInt)(a,10))};
g.h.NM=function(a){a.preventDefault()};
g.h.jA=function(){g$(this)};
g.h.Vv=function(a,b,c){a.appendChild($xa(this,b,c));return a};g.p("yt.www.creator.angular.controllers.advancedSearch",k$,void 0);k$.$inject=["$scope","$timeout"];var l$={before:hya,after:hya,hasWords:function(a,b){return b},
video_id:function(a,b){var c=iya(b);c=(0,g.Zi)(c,function(a){return!/[^a-zA-Z0-9]/.test(a)||2<=a.length&&'"'===a[0]&&'"'===a[a.length-1]?a:'"'+a+'"'});
return gya(a,c)},
tag:jya,title:jya,visibility:function(a,b){var c=[];g.ab(b,function(a,b){a&&c.push(b)});
c.sort();return gya("is",c)}};
k$.prototype.jJ=function(){if(g.x("advanced-search-button").classList.contains("yt-uix-button-active"))this.F=this.currentSearchValue;else{this.Jb((0,g.t)(function(){g.x("advanced-search-id-label").focus()},this));
kya(this);var a=g.x("vm-myvideos-search-box").value;if(a!=this.F){var b=this;this.C=g.tg("/my_videos_ajax",{za:{action_process_search_query:1},ha:{query:a},onSuccess:function(a,d){b.ma.$apply(function(){b.formData=new j$(d)})}})}}};
k$.prototype.populateAdvancedSearch=k$.prototype.jJ;k$.prototype.ww=function(){this.formData=new j$};
k$.prototype.clearAll=k$.prototype.ww;g.p("yt.www.creator.angular.controllers.BulkActions",m$,void 0);m$.$inject=["$scope","$timeout","BulkActionsService"];m$.prototype.zk=function(a){g.Ml(this.actions,a)};
m$.prototype.addAction=m$.prototype.zk;m$.prototype.aL=function(a){g.La(this.actions,a)};
m$.prototype.removeAction=m$.prototype.aL;m$.prototype.Jy=function(a){return a+".html"};
m$.prototype.getTemplate=m$.prototype.Jy;m$.prototype.isActive=function(a){return g.Ia(this.actions,a)};
m$.prototype.isActive=m$.prototype.isActive;m$.prototype.C=function(a){var b=g.x("vm-bulk-actions-editing-field-"+a);b.tabIndex=0;b.focus();var c=g.Zy.getInstance();(0,g.z)(g.J("yt-uix-form-input-select-element",b),function(a){c.wc(a)});
(0,g.z)(g.J("yt-uix-form-input-text",b),function(a){g.H(a,"keypress",function(a){13!=a.keyCode&&3!=a.keyCode||a.preventDefault()})});
"ad_formats"==a&&dya()};g.p("yt.www.creator.angular.controllers.bulkActionsHistory",n$,void 0);n$.$inject=["$scope","BulkActionsHistoryService"];n$.prototype.D=function(a){a?(this.isAjaxComplete=!0,(0,g.z)(a.done,function(a){a.timestamp_text=g.uF(a.timestamp,"longdate")},this),this.batchesDone=a.done,this.C=a.batches_per_page,this.selectedBatches=[!0],this.currentPage=this.selectedIndex=0,o$(this)):(this.isAjaxComplete=!1,this.batchesDone=null,this.C=0)};
n$.prototype.F=function(a){this.hasErrors=a};
n$.prototype.Tz=function(a){a.stopPropagation()};
n$.prototype.handleExpanderBodyClick=n$.prototype.Tz;n$.prototype.iM=function(a){a==this.selectedIndex?(this.selectedBatches[this.selectedIndex]=!1,this.selectedIndex=-1):(0<=this.selectedIndex&&(this.selectedBatches[this.selectedIndex]=!this.selectedBatches[this.selectedIndex]),this.selectedBatches[a]=!this.selectedBatches[a],this.selectedIndex=a)};
n$.prototype.toggleBatchSelected=n$.prototype.iM;n$.prototype.WB=function(){0<this.currentPage&&(--this.currentPage,o$(this))};
n$.prototype.loadPrevPage=n$.prototype.WB;n$.prototype.VB=function(){this.wq()&&(this.currentPage+=1,o$(this))};
n$.prototype.loadNextPage=n$.prototype.VB;n$.prototype.wq=function(){return 0<=this.currentPage&&!!this.batchesDone&&!!this.C&&this.currentPage+1<Math.ceil(this.batchesDone.length/this.C)};
n$.prototype.hasMorePages=n$.prototype.wq;g.p("yt.www.creator.angular.controllers.matchPolicy",p$,void 0);p$.$inject=["$attrs","$scope","MatchPolicyService"];p$.prototype.FL=function(){return"set"==this.matchPolicySettings.operation};
p$.prototype.setPolicyDisplayed=p$.prototype.FL;p$.prototype.fL=function(){return"remove"==this.matchPolicySettings.operation};
p$.prototype.removePolicyDisplayed=p$.prototype.fL;var I$,G$,H$,D$,E$,B$;g.p("yt.www.creator.angular.controllers.videoList",M$,void 0);M$.$inject=["$scope","$timeout","FeedbackService","VideoListService"];var Lza=g.dN(function(){var a=window.angular.module("yt.www.creator.angular.directives.blockOutsideOwnership",[]);a.directive("blockOutsideOwnership",Rya);return a});var Mza=g.dN(function(){var a=window.angular.module("yt.www.creator.angular.directives.datePicker",[]);a.directive("datePicker",Tya);return a});var Nza=g.dN(function(){var a=window.angular.module("yt.www.creator.angular.directives.domainFiltering",[]);a.directive("domainFiltering",Uya);return a});var Oza=g.dN(function(){var a=window.angular.module("yt.www.creator.angular.directives.domainList",[]);a.directive("domainList",Wya);return a});g.v(N$,g.sd);N$.$inject=["$rootScope","DisposeService","ContentRatingService","MatchPolicyService"];N$.prototype.zk=function(a){this.G.$apply(g.u(g.Ml,this.C,a))};O$.$inject=["$rootScope","$http"];O$.prototype.Aj=function(a){this.C=a};
O$.prototype.Nr=function(){this.hasErrors=!0};g.v(P$,g.wd);g.v(aza,P$);g.v(bza,P$);g.v(cza,P$);g.v(dza,P$);g.v(Q$,g.sd);Q$.prototype.X=function(){Q$.M.X.call(this);g.Ie(this.F);this.F=null};
Q$.prototype.J=function(a){this.H.reset();this.G=!1;a=kza(a);(0,g.z)(a,this.R,this);R$(this)};
Q$.prototype.R=function(a){var b=a.id&&a.id.videoId,c=this.C.get(b);if(c){var d=c.ZN;(0,g.z)(a.contents||[],function(a){a.transferProgressBar&&d.dispatchEvent(new aza(a.transferProgressBar));a.processingProgressBar&&d.dispatchEvent(new bza(a.processingProgressBar));a.uploadStatus&&d.dispatchEvent(new cza(a.uploadStatus));a.thumbnailStatus&&d.dispatchEvent(new dza(a.thumbnailStatus))});
(a=lza(a))&&a.continuation&&g.qa(a.continueInMs)?(c.Co=a.continuation,nza(c,(0,g.A)()+a.continueInMs)):eza(this,b)}};g.h=qza.prototype;g.h.HO=function(a){S$(this.R,a.payload.progressMessage);S$(this.J,a.payload.remainingTimeMessage);.999<a.payload.fractionCompleted&&(tza(this),T$(this,!0))};
g.h.VG=function(a){S$(this.D,a.payload.progressMessage);S$(this.K,a.payload.remainingTimeMessage);.01<a.payload.fractionCompleted&&.999>a.payload.fractionCompleted&&!this.Y&&(tza(this),T$(this,!0))};
g.h.FI=function(a){this.Y=!0;"DELETED"==a.payload.uploadStatus?rza(this):(T$(this,!1),S$(this.la,a.payload.message),S$(this.V,a.payload.detailedMessage),a={},a.onSuccess=(0,g.t)(this.KI,this),s$("action_refresh_video_row",{video_id:this.aa},a))};
g.h.KI=function(a,b){if(b)if(b.row_deleted)rza(this);else if(b.row_html){var c=g.ln(g.Sn((0,g.Ua)(b.row_html)));g.wn(c)&&(this.C.removeAll(),g.qn(c,this.F),oza(this,c),this.G.setAttribute("src",this.G.getAttribute("src")+"&t="+(0,g.A)()),pza(this),g.vF(void 0,this.F))}};
g.h.ZH=function(a){a.payload.thumbnailDetails&&a.payload.thumbnailDetails.thumbnails&&(a=sza(a.payload.thumbnailDetails.thumbnails))&&this.G.setAttribute("src",a)};g.v(uza,g.sd);var Pza=g.dN(function(){var a=window.angular.module("yt.www.creator.services.feedbackService",[]);a.service("FeedbackService",uza);return a});g.v(U$,g.sd);U$.$inject=["DisposeService"];vza.$inject=["$rootScope","$sce"];var Qza=g.dN(function(){var a=window.angular.module("yt.www.creator.services.videoListService",[]);a.service("VideoListService",vza);return a});var V$=g.dN(function(){var a=window.angular.module("yt.www.creator.angular.apps.myVideos",[g.DN.name,g.CN.name,g.EN.name,Lza.name,Mza.name,Nza.name,Oza.name,g.FN.name,g.GN.name,g.HN.name,g.IN.name,g.JN.name,Pza.name,Qza.name]);a.controller("advancedSearchCtrl",k$);a.controller("bulkActionCtrl",m$);a.controller("bulkActionsHistory",n$);a.controller("matchPolicyCtrl",p$);a.controller("videoListCtrl",M$);a.service("BulkActionsService",N$);a.service("BulkActionsHistoryService",O$);a.service("ContentRatingService",
g.rN);a.service("MatchPolicyService",U$);return a});g.h=yza.prototype;g.h.Ns=function(){var a=g.x("vm-bulk-actions-history-dialog");a&&(this.C||(this.C=new g.aA(a,!1,!0)),g.bA(this.C,"all",(0,g.t)(this.zw,this),!1),this.C.show(),Zya(this.W))};
g.h.zw=function(){this.C.dispose();this.C=null;this.W&&$ya(this.W)};
g.h.Tv=function(a){L$(!1);this.H.zk(a);g.Q(this.G)};
g.h.FH=function(){v$()||(this.F=!1);0==u$().length&&this.Fg();W$(this)};
g.h.Fg=function(){this.F=!1;this.K=0;Hza(this);g.su(this.J,v$()&&Eza());g.S(this.G);L$(!0);X$(this,0);W$(this);Xya(this.H);this.D&&(this.D.checked=!1);g.K("vm-bulk-actions-overlay-button-confirm",g.K("yt-uix-overlay-fg-content")).disabled=!0};
g.h.zL=function(){this.F=!0;W$(this);g.tu(this.G)||this.Ut()};
g.h.Ut=function(){window.scrollTo(0,0);g.sc(this.la);L$(!1);g.Q(this.G);Xya(this.H);g.Bf((0,g.t)(function(){var a=g.K("vm-bulk-action-editing-menu-container");a&&g.Cz(g.uz.getInstance(),a)},this),1)};
g.h.un=function(a){var b=(0,g.t)(this.nJ,this);!a||a instanceof g.Ag||(b=a);a=(0,g.t)(this.Mt,this,b);var c=u$().length;b=g.jc("vm-bulk-actions-warn-dialog");var d=g.xq("VM_BULK_ACTIONS_WARN_UPDATE_TITLE",c);g.Vm(g.K("yt-dialog-title",b),g.bc(d));c=g.xq("VM_BULK_ACTIONS_WARN_UPDATE_MESSAGE",c);this.F&&(c=""!=this.searchQuery?g.wq("VM_BULK_ACTIONS_WARN_UPDATE_MANY_MESSAGE"):g.wq("VM_BULK_ACTIONS_WARN_UPDATE_ALL_MESSAGE"));g.Vm(g.K("vm-confirmation-overlay-message-all",b),g.bc(c));g.nA.getInstance().show(b);
g.Jg(g.K("vm-bulk-actions-overlay-button-confirm",g.K("yt-uix-overlay-fg-content")),"click",a)};
g.h.Fz=function(){var a=g.K("vm-bulk-actions-overlay-button-confirm",g.K("yt-uix-overlay-fg-content"));this.D&&(a.disabled=!this.D.checked)};
g.h.Mt=function(a){var b=g.x("vm-bulk-actions-form");this.N.disabled=!0;this.V.disabled=!0;g.nA.getInstance().hide();g.sc(this.la);(0,g.z)(g.J("yt-alert",b),function(a){a.classList.contains("fixed-yt-alert")||g.S(a)});
g.S(this.J);var c=g.x("vm-bulk-actions-video-ids");if(this.F)c.value="";else{var d=u$();c.value=d.join(",")}c=g.jp(b);a&&a(c);g.G(b.action,{method:"POST",za:g.VB({action_enqueue:"1"}),ha:g.El(c),onSuccess:(0,g.t)(this.Lt,this,!0),onError:(0,g.t)(this.Lt,this,!1)})};
g.h.Lt=function(a,b){this.N.disabled=!1;this.V.disabled=!1;if(a)X$(this,0),zza(this);else{var c=JSON.parse(b.responseText);r$(c.errors,!0);c=c.field_errors;for(var d in c){var e=Fza(d);e&&(e=g.K("bulk-action-field-alert",e),g.L(g.K("yt-alert-content",e),c[d]),g.Q(e))}}};
g.h.nJ=function(a){Gza("ad_breaks",a,"auto_gen_off");Gza("ad_formats",a," ");var b=this.H;var c=(c=g.tN(b.F))?g.eb(c)?"":window.angular.toJson(c):null;var d=b.H;if(d.F){var e={operation:d.F.operation,remove_all:d.F.removeAll};if("set"==d.F.operation){var f="invalid";d.F.policy&&(f=d.F.policy);e.match_policy=f}d=e}else d=null;d=d?window.angular.toJson(d):null;e=b.F;e=g.sN(e)?window.angular.toJson(g.sN(e)):null;c={country_ratings:c,match_policy:d,youtube_ratings:e};g.lb(c,Yya(b));g.Re(a,c)};
g.h.ly=function(){var a=g.VB({action_check_running:1,visible_video_ids:wza(this.ia),format:"json"});return g.Uc("/bulk_actions_ajax",a)};
g.h.FA=function(a){this.K+=1;Hza(this);var b=JSON.parse(a.responseText);b.finished?(this.Fg(),g.S(this.Y),xza(this.ia,b.json_video_list),a=b.success_count,(b=b.failure_count)?(a=g.xq("VM_BULK_ACTIONS_SUCCESS",a)+" "+g.xq("VM_BULK_ACTIONS_FAILURE",b)+" "+g.wq("VM_BULK_ACTIONS_VIEW_REPORT"),q$("yt-alert-warn",a,!0,void 0),g.K("vm-bulk-actions-view-report-link").focus()):a&&(a=g.xq("VM_BULK_ACTIONS_SUCCESS",a),J$(a,!0))):X$(this,b.processed_count)};
g.h.fk=function(a){this.Fg();this.un(function(b){b.set("privacy",a)})};
g.h.pu=function(a){this.Fg();this.un(function(b){b.set("license",a)})};
g.h.rG=function(){var a=window.document.querySelector(".monetization-input[value='ads']");a&&Iza(this,a.checked)};
g.h.HI=function(){var a=g.K("usage-policy-select");a=(a=a[a.selectedIndex])&&"true"==g.E(a,"is-monetized-policy");Iza(this,a);var b=g.x("disable-m10n-usage-policy-by-ypps-warning");b&&g.su(b,a)};
g.h.mu=function(){var a=g.x("ad-friendly-guidelines-input"),b=g.x("ad-friendly-checkbox");g.tu(g.x("ad-friendly-guidelines-content"))&&b?a.value=b.checked?"confirmed":"not_confirmed":a.value=""};Y$.prototype.rf=function(){return(0,g.t)(this.J,this)};
Y$.prototype.J=function(){var a=g.K("ad-options-overlay-content",void 0);g.nA.getInstance().show(a);new Yxa;g.H(this.F,"click",(0,g.t)(this.R,this));this.C&&(g.H(this.C,"click",(0,g.t)(this.H,this)),this.C.checked=!1);a=!!this.C;this.G.disabled=!1;this.F.disabled=a};
Y$.prototype.R=function(a){a.preventDefault();a.stopPropagation();this.G.disabled=!0;this.F.disabled=!0;a=g.El(g.jp(g.K("ad-options-overlay-form",this.D)));Jza(this.K,"overlay"in a,"true_view"in a,"standard_instream"in a,"product_listing_ads"in a,"display_ads"in a)};
Y$.prototype.H=function(){var a=!this.C.checked;this.G.disabled=!1;this.F.disabled=a};Z$.prototype.D=function(a){this.F&&this.F.abort();if(g.Qa(a.L().value))g.Q(this.C),h$(a);else{var b={action_search_channels:1};b.query=a.L().value;this.F=g.tg("/my_videos_ajax",{za:g.VB(b),onSuccess:g.u(this.G,a),context:this})}};
Z$.prototype.G=function(a,b,c){c.channels?(g.S(this.C),b=c.channels,h$(a),a.H=b,b=(0,g.Xi)(b,a.Vv,window.document.createDocumentFragment(),a),a.D.appendChild(b),a.show()):(g.Q(this.C),h$(a))};
Z$.prototype.H=function(a){g.hi(a.V.data.video_manager_url)};$$.prototype.F=function(a,b){b&&g.ab(b.suggestions,function(a,b){var c=g.K("vm-owner-bar",this.C[b]);c&&(0,g.z)(a,function(a){a=g.aq(a);c.appendChild(a)})},this)};
$$.prototype.D=function(a){(a=g.Mn(a.currentTarget,"SPAN","vm-video-suggestion"))&&g.RE(a,"EVENT_CLICKED")};
$$.prototype.G=function(a){if(a=g.Mn(a.currentTarget,"SPAN","vm-video-suggestion"))g.S(a),g.RE(a,"EVENT_DISMISSED")};var Rza=null;g.Zh(g.uq({name:"www/my_videos",deps:["www/videomanager"],page:"my_videos",init:function(){g.VK();z$();Rza=g.cN(g.x("creator-page-content"),[V$.name],"FeedbackService");new $$;var a=new yza;g.K("vm-playlist-monetize-videos")&&g.P(null,"click",(new Y$(a)).rf(),"vm-playlist-monetize-videos");Kza();Dza(a)},
dispose:function(){Rza.dispose()}}));})(_yt_www);
