(function(g){var window=this;var dR=function(){},eR=function(a,b){!a.parentElement||3<=a.currentPage||(g.S(a.C[a.currentPage-1],a.F),void 0===b?g.L(a.R,g.wq("FUNCTIONALITY_NOT_AVAILABLE")):g.L(a.R,b.join(", ")),g.Q(a.D,a.la),a.D.focus())},fR=function(a,b,c){a.H.disabled=!0;
a.G.disabled=!0;var d={};d[b]=1;g.G("/account_partner_network_ajax",{format:"JSON",method:"POST",za:d,ha:{req_id:a.requestId},onSuccess:(0,g.t)(function(a){a=JSON.parse(a.responseText);"SUCCESS"==a.code?(c(),this.V&&g.S(this.V)):"ERROR"==a.code?eR(this,a.errors):eR(this)},a),
onError:(0,g.t)(function(){eR(this)},a)})},dna=function(){var a=g.x("confirm-join-network-promo");
if(a){var b=new g.OE(g.D("PROMO_NAME",void 0));g.H(g.K("close",a),"click",function(){b.write("write_dismiss")})}},gR=null;
g.h=dR.prototype;g.h.Vt=function(){if(this.parentElement&&!(3<=this.currentPage)){g.S(this.C[this.currentPage-1]);var a="step-"+this.currentPage;this.currentPage+=1;var b="step-"+this.currentPage;g.Q(this.C[this.currentPage-1]);this.C[this.currentPage-1].focus();g.fp(this.F,a,b)}};
g.h.PL=function(){if(this.parentElement&&!(1>=this.currentPage)){g.S(this.C[this.currentPage-1]);var a="step-"+this.currentPage;--this.currentPage;var b="step-"+this.currentPage;g.Q(this.C[this.currentPage-1]);this.C[this.currentPage-1].focus();g.fp(this.F,a,b)}};
g.h.QL=function(){!this.parentElement||3<=this.currentPage||(g.S(this.C[this.currentPage-1],this.F),g.Q(this.J,this.Y),this.J.focus())};
g.h.jM=function(){this.K.disabled=!this.W.checked};
g.h.OB=function(){g.D("isMcnAffiliateMonetizationAllowed")||(this.K.disabled=!0);this.N.disabled=!0;fR(this,"action_join",(0,g.t)(this.Vt,this))};
g.h.ZK=function(){this.H.disabled=!0;this.G.disabled=!0;fR(this,"action_reject",(0,g.t)(this.QL,this))};g.p("yt.www.account.JoinNetwork.onOverlayShown",function(a){var b=g.rA(),c=gR;c.parentElement=b;c.V=g.M(a,"dashboard-widget");c.requestId=g.E(g.jc("join-network-action"),"req-id");c.currentPage=1;c.H=g.K("step1-continue",c.parentElement);c.N=g.K("step2-back",c.parentElement);c.G=g.K("step2-reject",c.parentElement);c.K=g.K("step2-continue",c.parentElement);c.W=g.K("step2-agreement",c.parentElement);c.F=g.K("join-network-title-indicator",c.parentElement);c.la=g.K("title-step-error",c.parentElement);
c.Y=g.K("title-step-reject",c.parentElement);c.C=[];for(a=1;3>=a;a++)c.C.push(g.K("content-step"+a,c.parentElement));c.D=g.jc("content-step-error");c.R=g.K("yt-alert-message",c.D);c.J=g.K("content-step-reject",c.parentElement);g.H(c.H,"click",(0,g.t)(c.Vt,c));g.H(c.K,"click",(0,g.t)(c.OB,c));g.H(c.G,"click",(0,g.t)(c.ZK,c));g.H(c.N,"click",(0,g.t)(c.PL,c));g.H(c.W,"change",(0,g.t)(c.jM,c))},void 0);
g.p("yt.www.account.JoinNetwork.onOverlayHidden",function(){gR.parentElement=void 0},void 0);
g.Zh(g.uq({name:"www/promo_join_network",deps:["www/common"],page:["dashboard"],init:function(){gR=new dR;dna()}}));})(_yt_www);
