(function(g){var window=this;var mna=function(a,b,c){try{if(a.C&&a.C.C){var d=a.C.start(b.toString(),3);var e=c();a.C.end(d)}else e=c()}catch(k){c=!0;try{g.id(d);var f=g.od(k);c=a.G.call(a,b,f,void 0,void 0)}catch(l){a.F(217,l)}if(!c)throw k;}return e},nna=function(a,b){var c=g.jl;
return function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];return mna(c,a,function(){return b.apply(void 0,e)})}},FR=function(a,b){var c=g.x(b);
if(c){var d=g.W(a,"toggled");(0,g.z)(g.J(d,c),function(a){g.O(a,d);a.removeAttribute("aria-pressed")})}},GR=function(a,b){if(a.F&&!g.B(a.F,"focused")&&!a.ab&&(a.F.value=b,a.Ph(),g.tu(a.H)&&a.la)){var c=a.la;
if(c.na&&c.Pb){var d=g.CG(),e=Math.round(1E3*d.getCurrentTime());e=[e,e+3E3];e=g.WG(c,e,!0);g.aH(c,e,1!=d.getPlayerState())}}},HR=function(a){if(!arguments.length)return[];
for(var b=[],c=arguments[0].length,d=1;d<arguments.length;d++)arguments[d].length<c&&(c=arguments[d].length);for(d=0;d<c;d++){for(var e=[],f=0;f<arguments.length;f++)e.push(arguments[f][d]);b.push(e)}return b},ona=function(a){for(var b=RegExp("(\\w[\\w ]+)/([^\\s]+)\\s*(?:\\((.*?)\\))?","g"),c=[],d;d=b.exec(a);)c.push([d[1],
d[2],d[3]||void 0]);return c},pna=function(a){var b=/rv: *([\d\.]*)/.exec(a);
if(b&&b[1])return b[1];b="";var c=/MSIE +([\d\.]+)/.exec(a);if(c&&c[1])if(a=/Trident\/(\d.\d)/.exec(a),"7.0"==c[1])if(a&&a[1])switch(a[1]){case "4.0":b="8.0";break;case "5.0":b="9.0";break;case "6.0":b="10.0";break;case "7.0":b="11.0"}else b="7.0";else b=c[1];return b},qna=function(){function a(a){a=g.Ga(a,d);
return c[a]||""}
var b=g.Za;if(g.mb())return pna(b);b=ona(b);var c={};(0,g.z)(b,function(a){c[a[0]]=a[1]});
var d=g.u(g.cb,c);return g.$a("Opera")?a(["Version","Opera"]):g.$a("Edge")?a(["Edge"]):g.nb()?a(["Chrome","CriOS"]):(b=b[2])&&b[1]||""},IR=function(a){var b=a.length;
if(0==b)return 0;for(var c=305419896,d=0;d<b;d++)c^=(c<<5)+(c>>2)+a.charCodeAt(d)&4294967295;return 0<c?c:4294967296+c},rna=function(){var a=JR(g.Bk),b=g.Kc();
this.G=a;this.C=b;this.F=this.J=g.Bk;this.H=-1;this.R=!1;this.W="";this.K=this.D=0},KR=function(a){a=void 0===a?g.n:a;
var b=a.context||a.AMP_CONTEXT_DATA;if(!b)try{b=a.parent.context||a.parent.AMP_CONTEXT_DATA}catch(c){}try{if(b&&b.pageViewId&&b.canonicalUrl)return b}catch(c){}return null},LR=function(){var a=KR();
return a?g.wc(a.master)?a.master:null:null},MR=function(a,b){for(var c in a)g.Bca.call(a,c)&&b.call(void 0,a[c],c,a)},NR=function(a){return!(!a||!a.call)&&"function"===typeof a},OR=function(a,b){if(a.filter)return a.filter(b,void 0);
for(var c=[],d=0;d<a.length;d++)b.call(void 0,a[d],d,a)&&c.push(a[d]);return c},sna=function(a,b){var c=b.slice(-1),d="?"===c||"#"===c?"":"&",e=[b];
MR(a,function(a,b){if(a||0===a||!1===a)"boolean"===typeof a&&(a=a?1:0),e.push(d),e.push(b),e.push("="),e.push((0,window.encodeURIComponent)(String(a))),d="&"});
return e.join("")},PR=function(a){a=a.google_unique_id;
return"number"===typeof a?a:0},tna=function(){var a,b=window.ActiveXObject;
if(window.navigator.plugins&&window.navigator.mimeTypes.length){if((a=window.navigator.plugins["Shockwave Flash"])&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else{if(window.navigator.userAgent&&0<=window.navigator.userAgent.indexOf("Windows CE")){var c=3;for(a=1;a;)try{a=new b("ShockwaveFlash.ShockwaveFlash."+(c+1)),c++}catch(d){a=null}return c.toString()}if(g.mb()){a=null;try{a=new b("ShockwaveFlash.ShockwaveFlash.7")}catch(d){c=0;try{a=new b("ShockwaveFlash.ShockwaveFlash.6"),
c=6,a.AllowScriptAccess="always"}catch(e){if(6===c)return c.toString()}try{a=new b("ShockwaveFlash.ShockwaveFlash")}catch(e){}}if(a)return c=a.GetVariable("$version").split(" ")[1],c.replace(/,/g,".")}}return"0"},JR=function(a){a=a.top;
return g.wc(a)?a:null},vna=function(a){return(0,g.Ck)(una,function(b){return b.test(a)})},QR=function(a){if(a=/[-\w]+\.[-\w]+$/.exec(a))switch(g.Ya(a[0].toLowerCase())){case 1967261364:return 0;
case 3147493546:return 1;case 1567346461:return 2;case 2183041838:return 3;case 763236279:return 4;case 1342279801:return 5;case 526831769:return 6;case 352806002:return 7;case 2755048925:return 8;case 3306848407:return 9;case 2207000920:return 10;case 484037040:return 11;case 3506871055:return 12;case 672143848:return 13;case 2528751226:return 14;case 2744854768:return 15;case 3703278665:return 16;case 2014749173:return 17;case 133063824:return 18;case 2749334602:return 19;case 3131239845:return 20;
case 2074086763:return 21;case 795772493:return 22;case 290857819:return 23;case 3035947606:return 24;case 2983138003:return 25;case 2197138676:return 26;case 4216016165:return 27;case 239803524:return 28;case 975993579:return 29;case 1794940339:return 30;case 1314429186:return 31;case 1643618937:return 32;case 497159982:return 33}return-1},RR=function(a){if(!a.length)return 0;
for(var b=[],c=0;33>=c;c++)b[c]=0;for(c=a.length-1;0<=c;c--){var d=QR(a[c]);0<=d&&(b[33-d]=1)}return(0,window.parseInt)(b.join(""),2)},SR=function(a){a=(this.F=a||g.n)||g.n;
this.D=a.top==a?1:g.wc(a.top)?2:3;3!=this.D&&(this.lastModifiedTime=Date.parse(g.n.top.document.lastModified)/1E3);this.C=g.Wc(this.F)},UR=function(a){for(var b=[],c=Math.min(a.C.length,27),d=1;d<c;d++)a.C[d]&&a.C[d].url&&(b[d-1]=a.C[d].url);
return TR(a,b.reverse())},VR=function(a){var b=a.F.document&&a.F.document.scripts?a.F.document.scripts:[];
if(!b)return 0;for(var c=[],d=b.length-1;0<=d&&26>c.length;)b[d].src&&c.unshift(b[d].src),d--;return TR(a,c)},TR=function(a,b){for(var c,d=0,e=(c=a.C[Math.max(a.C.length-1,0)].url||null)&&g.Pc(c),f=Math.min(b.length,26),k=0;k<f;k++)c=null!=b[k]&&g.Pc(b[k])||"",d*=4,c&&(e&&c==e?d+=3:vna(b[k])?d+=2:c&&0<=QR(c)&&(d+=1));
return d},WR=function(a){a=a.C;
for(var b=[],c=a.length-1;0<c;c--){var d=a[c];d&&null!=d.url&&b.push(g.Pc(d.url))}return RR(b)},XR=function(a){a=a.F.document&&a.F.document.scripts?a.F.document.scripts:[];
if(!a)return 0;for(var b=[],c=a.length-1;0<=c;c--){var d=a[c];d&&null!=d.src&&b.push(g.Pc(d.src))}return RR(b)},YR=function(a){this.F={};
this.C={};a=a||[];for(var b=0,c=a.length;b<c;++b)this.C[a[b]]=""},$R=function(a){var b=ZR();
return b.C.hasOwnProperty(a)?b.C[a]:""},aS=function(a){var b=[];
g.xc(a.F,function(a,d){b.push(d)});
g.xc(a.C,function(a){""!=a&&b.push(a)});
return b},xna=function(){var a=wna(),b=new YR;
g.xc(a.F,function(a,d){b.F[d]=a});
g.xc(a.C,function(a,d){b.C[d]=a});
return b},bS=function(a,b){return nna(a,b)},cS=function(a,b){for(var c=0,d=a,e=0;a&&a!=a.parent;)if(a=a.parent,e++,g.wc(a))d=a,c=e;
else if(b)break;return{Mg:d,level:c}},eS=function(){dS||(dS=cS(g.n,!0).Mg);
return dS},fS=function(a){YR.call(this,a);
this.dfltBktExt=this.F;this.lrsExt=this.C},yna=function(){this.S={}},hS=function(){if(gS)return gS;
var a=LR()||g.Kc(),b=a.google_persistent_state_async;return null!=b&&"object"==typeof b&&null!=b.S&&"object"==typeof b.S?gS=b:a.google_persistent_state_async=gS=new yna},iS=function(a,b,c){b=g.ll[b]||"google_ps_"+b;
a=a.S;var d=a[b];return void 0===d?a[b]=c:d},jS=function(a){try{return!!a&&g.sb(!0)}catch(b){return!1}},zna=function(){if(jS(kS))return!0;
var a=hS();if(a=iS(a,3,null)){if(a&&a.dfltBktExt&&a.lrsExt){var b=new fS;b.F=a.dfltBktExt;b.dfltBktExt=b.F;b.C=a.lrsExt;b.lrsExt=b.C;a=b}else a=null;a||(a=new fS,b={context:"ps::gpes::cf",url:g.Kc().location.href},g.bd(g.kd,"jserror",b,void 0,void 0))}return jS(a)?(kS=a,!0):!1},wna=function(){if(zna())return kS;
var a=hS(),b=new fS(g.yc(Ana));return kS=a.S[g.ll[3]||"google_ps_3"]=b},ZR=function(){lS||(lS=xna());
return lS},Bna=function(a){a=void 0===a?ZR():a;
return OR(aS(a),function(a){return!!mS[a]})},Cna=function(a){a=void 0===a?ZR():a;
return OR(aS(a),function(a){return!mS[a]})},Dna=function(a,b){MR(a,function(a,d){b[d]=a})},nS=function(a){var b=a.location.href;
if(a==a.top)return{url:b,Tl:!0};var c=!1,d=a.document;d&&d.referrer&&(b=d.referrer,a.parent==a.top&&(c=!0));(a=a.location.ancestorOrigins)&&(a=a[a.length-1])&&-1==b.indexOf(a)&&(c=!1,b=a);return{url:b,Tl:c}},Ena=function(){var a=g.Kc();
if(a==a.top)return 0;for(;a&&a!=a.top&&g.wc(a);a=a.parent){if(a.sf_)return 2;if(a.$sf)return 3;if(a.inGptIF)return 4;if(a.inDapIF)return 5}return 1},Gna=function(){if("1"!=g.nm(g.D("PLAYER_CONFIG",{}),"args","privembed")){var a=function(){oS=!0;
"google_ad_status"in window?g.uf("DCLKSTAT",1):g.uf("DCLKSTAT",2)};
g.Nf("//static.doubleclick.net/instream/ad_status.js",a);Fna.push(g.Tf(function(){if(!(oS||"google_ad_status"in window)){var b=g.Mf("//static.doubleclick.net/instream/ad_status.js");window.spf.script.ignore(b,a);g.uf("DCLKSTAT",3)}},5E3))}},Hna=function(a){g.$f("botguard_periodic_refresh")?pS=g.ah():g.$f("botguard_always_refresh")&&(qS=a)},Ina=function(a){if(a){if(g.bg.F)return!1;
if(g.$f("botguard_periodic_refresh"))return 72E5<g.ah()-pS;if(g.$f("botguard_always_refresh"))return qS!=a}else return!1;return!rS},Jna=function(){var a=g.D("BG_P",void 0);
return Ina(a)&&(g.D("BG_I")||g.D("BG_IU"))?(rS=!0,g.bg.initialize(g.D("BG_I",null),g.D("BG_IU",null),a,Hna),!0):!1},sS=function(a,b){var c=a.split("#",2);
a=c[0];var d=1<c.length?"#"+c[1]:"";c=g.Hp(d);for(var e in b)c[e]=b[e];if(!g.eb(c)){e="!"=="#".charAt(1)?"#".substr(0,2):"#";d=g.Hp("#");for(var f in c)d[f]=c[f];d=e+g.Tc(d)}return a+d},Kna=function(a,b){var c=void 0===c?0:c;
g.uf(g.Ph(c),a);g.uf(g.Qh(c),b);0==c&&(c=function(){(0,window.setTimeout)(function(){g.tq(a)},0)},"requestAnimationFrame"in window?window.requestAnimationFrame(c):c())},Lna=function(){var a=new SR(g.Bk),b=a.C[0].depth,c={};
c=(c.dssz=g.Jc.scripts?g.Jc.scripts.length:0,c.icsg=VR(a),c.mdo=WR(a),c.mso=XR(a),c);g.Bk.location&&g.Bk.location.ancestorOrigins&&(c.iag=UR(a));0<b&&(c.nhd=b);return c},Mna=function(a){var b;
g.dq(["fullscreenEnabled","webkitFullscreenEnabled","mozFullScreenEnabled","msFullscreenEnabled"],window.document)?g.Ku()==a&&(b=window.document):b=a;b&&(a=g.dq(["exitFullscreen","webkitExitFullscreen","mozCancelFullScreen","msExitFullscreen"],b))&&a.call(b)},Nna=function(a){return(0,g.Zi)(a,function(a){return{key:a.id,
name:a.name}})},tS=function(){var a=g.vw("yt-remote-cast-receiver");
return a?a.friendlyName:null},Ona=function(){var a=g.ey().Ac.$_gos();
var b=g.my();b&&g.py()&&(g.mw(a,b)||a.push(b));return Nna(a)},Pna=function(){var a=Ona(),b=g.my();
b||(b=g.jy());return g.Ga(a,function(a){return b&&g.gw(b,a.key)?!0:!1})},uS=function(){var a=Pna();
!a&&g.wx()&&tS()&&(a={key:"cast-selector-receiver",name:tS()});return a},vS=function(){var a=g.x("watch-queue-mole");
return!!a&&g.tu(a)},wS=function(){var a=g.x("watch-queue-mole");
return a&&g.tn(a)?0:1},Qna=function(a){if(!a||g.Qa(a.responseText))g.yJ();
else try{eval(a.responseText)}catch(b){throw g.yJ(),b;}},Rna=function(){var a={};
return a.dff="times new roman",a.dfs="16",a.ppjl="u",a.rsz="||n|",a},xS=function(a){var b=g.Hq();
g.Hl(b,g.Gq());g.$f("desktop_pyv_on_watch_missing_params")&&(g.Hl(b,Rna()),g.Hl(b,Lna()));a=g.Uc(a,b);g.$f("desktop_pyv_on_watch_override_lact")&&(a=g.Po(a,"lact",g.lh()));g.rJ=g.G(a,{format:"RAW",onSuccess:Qna,onError:function(){g.yJ()},
withCredentials:!0});(0,g.kj)("parq")},Sna=function(a){var b=a.F;
null==b.google_ad_output&&(b.google_ad_output="html");b.google_ad_client=String(b.google_ad_client);null!=b.google_ad_slot&&(b.google_ad_slot=String(b.google_ad_slot));var c;(c=b.google_ad_client)?(c=c.toLowerCase())&&"ca-"!=c.substring(0,3)&&(c="ca-"+c):c="";b.google_ad_client=c;if(null==b.google_flash_version){try{var d=tna()}catch(e){d="0"}b.google_flash_version=d}b.google_webgl_support=!!g.Bk.WebGLRenderingContext;b.google_ad_section=b.google_ad_section||b.google_ad_region||"";b.google_country=
b.google_country||b.google_gl||"";d=(new Date).getTime();g.ya(b.google_color_bg)&&(b.google_color_bg=yS(a,b.google_color_bg,d));g.ya(b.google_color_text)&&(b.google_color_text=yS(a,b.google_color_text,d));g.ya(b.google_color_link)&&(b.google_color_link=yS(a,b.google_color_link,d));g.ya(b.google_color_url)&&(b.google_color_url=yS(a,b.google_color_url,d));g.ya(b.google_color_border)&&(b.google_color_border=yS(a,b.google_color_border,d));g.ya(b.google_color_line)&&(b.google_color_line=yS(a,b.google_color_line,
d))},CS=function(){var a=window;
MR(zS,function(b,c){a[c]=null});
MR(AS,function(b,c){a[c]=null});
MR(BS,function(b,c){a[c]=null});
a.google_container_id=null;a.google_enable_async=null;a.google_eids=null;a.google_page_location=null;a.google_referrer_url=null;a.google_ad_region=null;a.google_gl=null;a.google_loader_used=null;a.google_loader_features_used=null},yS=function(a,b,c){a.D|=2;
return b[c%b.length]},DS=function(a,b){var c;
c||(c="https");g.n.location&&"https:"==g.n.location.protocol&&"http"==c&&(c="https");return[c,"://",a,b].join("")},FS=function(a){var b=a.google_page_location||a.google_page_url;
"EMPTY"==b&&(b=a.google_page_url);if(!b)return!1;a=b.toString();0==a.indexOf("http://")?a=a.substring(7,a.length):0==a.indexOf("https://")&&(a=a.substring(8,a.length));b=a.indexOf("/");-1==b&&(b=a.length);a=a.substring(0,b);if(Tna.test(a))return!1;a=a.split(".");b=!1;3<=a.length&&(b=a[a.length-3]in ES);2<=a.length&&(b=b||a[a.length-2]in ES);return b},GS=function(a){this.C=this.F=null;
g.Aa(a)?this.C=a:this.F=a},HS=function(a){a=a.document;
var b={};a&&(b="CSS1Compat"==a.compatMode?a.documentElement:a.body);return b||{}},JS=function(a){a=a.google_reactive_ad_format;
return g.km(IS,a)?""+a:null},KS=function(a){return a.top!=a?512:0},LS=function(a,b){var c=HS(a).clientWidth;
return c?c>(void 0===b?420:b)?32768:320>c?65536:0:16384},MS=function(a){var b=HS(a).clientWidth;
a=a.innerWidth;return(b=b&&a?b/a:0)?1.05<b?262144:.95>b?524288:0:131072},NS=function(){var a="IMG AMP-IMG IFRAME AMP-IFRAME HR EMBED OBJECT VIDEO AMP-VIDEO INPUT BUTTON SVG".split(" ");
this.C={};this.F={};if(a)for(var b=0;b<a.length;++b)this.add(a[b])},Una=function(){try{return OS.javaEnabled()}catch(a){return!1}},PS=function(a){var b=1,c;
if(void 0!=a&&""!=a)for(b=0,c=a.length-1;0<=c;c--){var d=a.charCodeAt(c);b=(b<<6&268435455)+d+(d<<14);d=b&266338304;b=0!=d?b^d>>21:b}return b},QS=function(a,b){if(!a||"none"==a)return 1;
a=String(a);"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return PS(a.toLowerCase())},Vna=function(a){var b=0;
MR(RS,function(c,d){SS(a,d)&&(b=c)});
return b},TS=function(a){return a?(a=a.hash)&&a.indexOf?a:"":""},SS=function(a,b){if(!a)return!1;
var c=a.hash;if(!c||!c.indexOf)return!1;if(-1!=c.indexOf(b))return!0;var d=Wna(b);return"go"!=d&&-1!=c.indexOf(d)?!0:!1},Wna=function(a){var b="";
MR(a.split("_"),function(a){b+=a.substr(0,2)});
return b},Xna=function(a){US.e=-1;
US.i=6;US.n=7;US.t=8;if(!VS){var b=[];g.xc(US,function(a,c){b[a+1]=c});
var c=b.join(""),d=a&&a[c];VS=d&&function(b,c){return d.call(a,b,c)}}return VS},Yna=function(){this.wasPlaTagProcessed=!1;
this.wasReactiveAdConfigReceived={};this.adCount={};this.wasReactiveAdVisible={};this.stateForType={};this.reactiveTypeEnabledInAsfe={};this.isReactiveTagFirstOnPage=this.wasReactiveAdConfigHandlerRegistered=this.wasReactiveTagRequestSent=!1;this.reactiveTypeDisabledByPublisher={};this.debugCard=null;this.messageValidationEnabled=this.debugCardRequested=!1;this.adRegion=this.floatingAdsFillMessage=this.grappleTagStatusService=null},WS=function(a){a.google_reactive_ads_global_state||(a.google_reactive_ads_global_state=
new Yna);
return a.google_reactive_ads_global_state},Zna=function(a,b){var c=JS(b);
if(c){if("32"==c)return 1;if("30"==c)return 0}a:{for(c=g.Kc();c&&g.wc(c);){if(c.name&&-1!=c.name.indexOf("google_ifsl_cifr")){c=!0;break a}if(c.parent==c)break;c=c.parent}c=!1}if(c)return 3;if(!g.wc(a))return 0;c=WS(a);return c.stateForType[32]?2:c.stateForType[30]?4:0},aoa=function(){this.C=$na},boa=function(a,b,c){switch(c){case 1:case 2:var d=0;
try{d|=KS(a);var e=Math.min(a.screen.width||0,a.screen.height||0);d|=e?320>e?8192:0:2048;var f=a.navigator.userAgent;var k=/Firefox/.test(f)||/Android 2/.test(f)||/iPhone OS [34]_/.test(f)||/Windows Phone (?:OS )?[67]/.test(f);d|=k?1048576:0}catch(y){d|=32}b=0;try{b|=a.innerHeight>=a.innerWidth?0:8,b|=LS(a,XS),b|=MS(a)}catch(y){b|=32}var l;if(l=2==c)a:{l=a.document;e=a.innerWidth;k=Math.round(a.innerWidth/320*50+15);var m=[];for(f=0;3>f;f++)for(var q=0;3>q;q++)m.push({x:q/2*e,y:f/2*k});for(e=0;e<
m.length;e++)if((k=l.elementFromPoint(m[e].x,m[e].y))&&"fixed"==g.eo(k)){l=!0;break a}l=!1}l?b|=16777216:2==c&&(Math.max(0,(HS(a).offsetHeight||0)-HS(a).clientHeight)||0)<=a.innerHeight+Math.round(a.innerWidth/320*50+15)&&(b|=1024);return d|b;case 8:c=0;try{c|=KS(a),c|=/Android 2/.test(a.navigator.userAgent)?1048576:0,c|=FS(b)?16:0}catch(y){c|=32}b=0;try{d="828064255"===$R(74)?XS:420,b|=LS(a,d),b|=MS(a),b|=a.innerHeight>=a.innerWidth?0:8}catch(y){b|=32}return c|b;case 9:c=0;try{c|=KS(a),c|=MS(a),
c|=LS(a),c|=a.innerHeight>=a.innerWidth?0:8,c|=FS(b)?16:0,c|=/Android 2/.test(a.navigator.userAgent)?1048576:0}catch(y){c|=32}return c;case 32:c=0;try{c|=KS(a)}catch(y){c|=32}return c;case 16:return b.google_ad_resizable&&!b.google_reactive_ad_format&&a.navigator&&/iPhone|iPod|iPad|Android|BlackBerry/.test(a.navigator.userAgent)&&a.top==a?0:8388608;case 30:c=0;try{c|=KS(a);c|=a.getComputedStyle?0:2097152;!(g.$a("iPad")||g.$a("Android")&&!g.$a("Mobile")||g.$a("Silk"))&&(g.$a("iPod")||g.$a("iPhone")||
g.$a("Android")||g.$a("IEMobile"))||(c|=1048576);q=Math.floor(a.document.body.getBoundingClientRect().width);YS||(YS=new aoa);var w=(0,window.parseFloat)(YS.C[79]);q<=((0,window.isNaN)(w)?0:w)||(c|=32768);a:{m=a.document.getElementsByClassName("adsbygoogle");for(a=0;a<m.length;a++)if("autorelaxed"==g.ys(m[a],"adFormat")){l=!0;break a}l=!1}l&&(c|=33554432)}catch(y){c|=32}return c;case 26:c=0;try{c|=KS(a),c|=a.getComputedStyle?0:2097152,c|=a.document.querySelectorAll&&a.document.querySelector?0:4194304,
c|=LS(a)}catch(y){c|=32}return c;case 27:c=0;try{c|=KS(a),c|=a.getComputedStyle?0:2097152,c|=LS(a,1E4)}catch(y){c|=32}return c;default:return 32}},coa=function(a,b){if(!a.adCount)return!1;
var c=a.adCount[b];return c&&27!=b&&26!=b?1<=c:!1},foa=function(a){if(!a.hash)return null;
var b=null;MR(doa,function(c){!b&&SS(a,c)&&(b=eoa[c])});
return b},ioa=function(a,b){if(!b)return null;
var c=WS(b);if(!c.wasReactiveAdConfigHandlerRegistered)return null;var d=0;MR(IS,function(c){var e=goa[c];e&&0===hoa(a,b,c)&&(d|=e)});
c.wasPlaTagProcessed&&(d|=256);c.isReactiveTagFirstOnPage&&(d|=1024);return d?""+d:null},hoa=function(a,b,c){if(!b)return 256;
var d=0,e=WS(b),f=coa(e,c);if(a.google_reactive_ad_format==c||26!=c&&27!=c&&f)d|=64;var k=!1;MR(e.reactiveTypeDisabledByPublisher,function(a,b){String(c)===b&&(k=!0)});
k&&foa(b.location)!==c&&(d|=128);return d|boa(b,a,c)},ZS=function(a){this.G=[];
this.F=a||window;this.C=0;this.D=null;this.H=0},$S=function(a){var b=bS(189,(0,g.t)(a.mM,a));
a.F.setTimeout(b,0)},aT=function(a){try{return a.sz()}catch(b){return!1}},bT=function(a,b){this.lc=a;
this.Mg=b},dT=function(a,b,c,d,e){var f={};
f.context=a;f.msg=b.substring(0,512);c&&(f.file=c);0<d&&(f.line=d.toString());f.sw=1;cT(f,e);return!0},cT=function(a,b,c){try{if(Math.random()<(b||.01)){var d="https://pagead2.googlesyndication.com/pagead/gen_204?id=jserror"+joa(a);
d=d.substring(0,2E3);var e=g.n.fetch(d,{mode:"no-cors"});c&&e.then(c,c)}}catch(f){}},joa=function(a){var b="";
Object.getOwnPropertyNames(a).forEach(function(c){var d=a[c];if(0===d||d)b+="&"+c+"="+(0,window.encodeURIComponent)(String(d))});
return b},koa=function(a){var b=!0;
try{var c=a()}catch(k){try{var d=g.nd(k);a="";k.fileName&&(a=k.fileName);var e=-1;k.lineNumber&&(e=k.lineNumber);b=dT("cache_key.js",d,a,e)}catch(l){d=l;try{var f=g.nd(d);a="";d.fileName&&(a=d.fileName);e=-1;d.lineNumber&&(e=d.lineNumber);dT("pAR",f,a,e,void 0)}catch(m){cT({context:"mRE",msg:m.toString()+"\n"+(m.stack||""),sw:1},void 0,void 0)}}if(!b)throw k;}finally{}return c?String(c):""},loa=function(a){a=a.url;
return g.Pc(g.sa(a)?a:"")||""},noa=function(a,b){(0,g.z)(moa,function(c){var d=a[c];
if(d||0===d||!1===d)g.ta(d)&&(d=Number(d)),b(c,d)})},ooa=function(a){return koa(function(){var b={};
noa(a,function(a,c){return b[a]=c});
b.domain=loa(a);var c=g.Tc(b);return String(IR(c))})},eT=function(a,b,c){a-=b;
return a>=(void 0===c?1E5:c)?"M":0<=a?a:"-M"},fT=function(a){var b=g.Kc();
if(b.google_pub_config)return b.google_pub_config[a];b.google_pub_config={};var c=null;try{(c=b.localStorage.getItem("google_pub_config"))&&(b.google_pub_config[a]=JSON.parse(c))}catch(d){}return b.google_pub_config[a]},poa=function(a){(a=fT(a))&&(a.sraRequestSent=!0)},gT=function(a,b){if($R(69))var c=!!a.google_reactive_ads_config&&(b||"20040051"==$R(69));
else $R(48)?(c=g.Gc(a)?1==PR(a):!PR(a))&&!(c=b)&&(c=$R(48),c=!!c&&"453848292"==c||"20040051"==$R(69)):c=!1;return c},soa=function(a){if(!hT)a:{var b=[g.n.top];
var c=[];for(var d=0,e;e=b[d++];){c.push(e);try{if(e.frames)for(var f=e.frames.length,k=0;k<f&&1024>b.length;++k)b.push(e.frames[k])}catch(m){}}for(b=0;b<c.length;b++)try{var l=c[b].frames.google_esf;if(l){hT=l;break a}}catch(m){}hT=null}c=hT;try{return g.Gc(a)&&"1"!=a.google_tag_for_child_directed_treatment&&c&&(qoa||roa)&&"20"===a.google_iframing?gT(a,!1):!1}catch(m){}return!1},Aoa=function(a){for(var b=a.getElementsByTagName("script"),c=b.length,d=0;d<c;++d){var e=b[d];
if(e.hasAttribute("src")){e=e.getAttribute("src");if(toa.test(e))return 5;if(iT.test(e))return 6}}b=a.getElementsByTagName("link");c=b.length;for(d=0;d<c;++d)if(e=b[d],e.hasAttribute("href")&&(e=e.getAttribute("href"),uoa.test(e)||iT.test(e)))return 6;a=a.getElementsByTagName("meta");d=a.length;for(e=0;e<d;++e){var f=a[e];if("generator"==f.getAttribute("name")&&f.hasAttribute("content")){f=f.getAttribute("content");if(voa.test(f))return 1;if(woa.test(f))return 2;if(xoa.test(f))return 3;if(yoa.test(f))return 4}}for(a=
0;a<c;++a)if(d=b[a],"stylesheet"==d.getAttribute("rel")&&d.hasAttribute("href")&&(d=d.getAttribute("href"),zoa.test(d)))return 2;return 0},Doa=function(a){var b=a.F,c=a.F,d=g.Kc().document,e={},f=g.Kc();
var k=cS(g.Kc(),!1).Mg;var l=nS(k);a:{var m=g.Kc();var q=c.google_ad_width||m.google_ad_width;var w=c.google_ad_height||m.google_ad_height;if(m&&m.top==m)m=!1;else{var y=d.documentElement;if(q&&w){var I=1,R=1;m.innerHeight?(I=m.innerWidth,R=m.innerHeight):y&&y.clientHeight?(I=y.clientWidth,R=y.clientHeight):d.body&&(I=d.body.clientWidth,R=d.body.clientHeight);if(R>2*w||I>2*q){m=!1;break a}}m=!0}}l=l.Tl;q=g.Kc();q=q.top==q?0:g.wc(q.top)?1:2;w=4;m||1!=q?m||2!=q?m&&1==q?w=7:m&&2==q&&(w=8):w=6:w=5;l&&
(w|=16);q=""+w;w=Ena();l=!!c.google_page_url;e.google_iframing=q;0!=w&&(e.google_iframing_environment=w);if(!l&&"ad.yieldmanager.com"==d.domain){for(l=d.URL.substring(d.URL.lastIndexOf("http"));-1<l.indexOf("%");)try{l=(0,window.decodeURIComponent)(l)}catch(T){break}c.google_page_url=l;l=!!l}q=KR(f);l?(e.google_page_url=c.google_page_url,e.google_page_location=(m?d.referrer:d.URL)||"EMPTY"):"21061977"==$R(119)&&q&&q.canonicalUrl?(e.google_page_url=q.canonicalUrl,e.google_page_location=(m?d.referrer:
d.URL)||"EMPTY"):(m&&g.wc(f.top)&&d.referrer&&f.top.document.referrer===d.referrer?e.google_page_url=f.top.document.URL:e.google_page_url=m?d.referrer:d.URL,e.google_page_location=null);a:{if(d.URL==e.google_page_url)try{var V=Date.parse(d.lastModified)/1E3;break a}catch(T){}V=null}e.google_last_modified_time=V;d=k==k.top?k.document.referrer:(d=KR())&&d.referrer||"";e.google_referrer_url=d;Dna(e,c);c=FS(b)?"pagead2.googlesyndication.com":"googleads.g.doubleclick.net";e=Boa(a);d=b.google_ad_channel;
f="/pagead/ads?";"ca-pub-6219811747049371"===b.google_ad_client&&Coa.test(d)&&(f="/pagead/lopri?");d=DS(c,f);f=a.F;if(f=!("33895333"===$R(19)&&"html"===f.google_ad_output))f=a.F,f=(!f.google_ad_output||"html"===f.google_ad_output)&&3===g.yp(a.C.document);f&&(a.R=!0,a.W=d,d=DS(c,"/pagead/blank.gif#?"));a=sna(e,d+"");return b.google_ad_url=a},Eoa=function(a){try{if(a.parentNode)return a.parentNode}catch(e){return null}if(9===a.nodeType)a:{try{var b=g.hn(a);
if(b){var c=b.frameElement;if(c&&g.wc(b.parent)){var d=c;break a}}}catch(e){}d=null}else d=null;return d},Foa=function(a,b){var c=ZR(),d=Cna(c),e=a.F.google_eids;
if(g.ya(e)){a.D|=64;for(var f=0;f<e.length;f++)g.sa(e[f])&&d.push(e[f])}b.eid=d.join();c=Bna(c);d=a.F.google_loeid;g.sa(d)&&(a.D|=4096,g.Na(c,d.split(",")));b.loeid=c.join()},Goa=function(a,b){var c=JR(a.C);
if(c&&c.document){var d=c.document;c=void 0===c?g.n:c;d=d.scrollingElement||("CSS1Compat"==d.compatMode?d.documentElement:d.body);d=new g.fc(c.pageXOffset||d.scrollLeft,c.pageYOffset||d.scrollTop)}else d=new g.fc(-12245933,-12245933);b.scr_x=d.x;b.scr_y=d.y},Hoa=function(a,b){var c=a.F,d=a.J,e=a.C,f=eS();
b.ref=c.google_referrer_url;b.loc=c.google_page_location;var k;(k=KR(a.C))&&g.Ba(k.data)&&g.sa(k.data.type)?(k=k.data.type.toLowerCase(),k="doubleclick"==k||"adsense"==k?null:k):k=null;k&&(b.apn=k.substr(0,10));k=nS(f);b.url||b.loc||!k.url||(b.url=k.url,k.Tl||(b.usrc=1));k.url!=(b.loc||b.url)&&(b.top=k.url);c.google_async_rrc&&(b.rr=c.google_async_rrc);b.rx=0;if(jT&&aT(jT))k=jT;else{k=eS();var l=k.google_jobrunner;k=l&&("object"===typeof l||"function"===typeof l)&&aT(l)&&NR(l.nq)&&NR(l.nqa)&&NR(l.al)&&
NR(l.rl)?jT=l:k.google_jobrunner=jT=new ZS(k)}(k=NR(k.tc)?k.tc():null)&&(b.jtc=k);0<=a.H&&(b.eae=a.H);(k=ioa(c,a.G))&&(b.fc=k);k=c.google_ad_format;if(!(k?0<k.indexOf("_0ads"):"html"!==c.google_ad_output&&0<c.google_num_radlinks)){k=d.document;l="";if(k.documentMode){var m=(new g.Nn(k)).createElement("IFRAME");m.frameBorder="0";m.style.height=0;m.style.width=0;m.style.position="absolute";if(k.body){k.body.appendChild(m);try{var q=m.contentWindow.document;q.open();q.write("<!DOCTYPE html>");q.close();
l+=q.documentMode}catch(Pi){}k.body.removeChild(m)}}b.docm=l}b.brdim=g.Qo(e).join();k="618018086"===$R(67);q=0;!g.qa(g.n.postMessage)&&(q|=1);k&&((k=KR(d))&&k.observeIntersection&&(q|=256),g.Aa(Xna(d&&d.document))&&(q|=1024));d=q;0<d&&(b.osd=d);b.vis=g.yp(e.document);(d=fT(c.google_ad_client))&&d.sraConfigs?(d=d.sraConfigs,d=d["2"]&&d["2"].sraEnabled?"t":"f"):d="u";b.ppjl=d;if("html"===(c.google_ad_output||"html")&&!JS(c)){a:{d=Number(c.google_ad_width);q=Number(c.google_ad_height);if(!(0<d&&0<q)){b:{try{var w=
String(c.google_ad_format);if(w&&w.match){var y=w.match(/(\d+)x(\d+)/i);if(y){var I=(0,window.parseInt)(y[1],10),R=(0,window.parseInt)(y[2],10);if(0<I&&0<R){var V={width:I,height:R};break b}}}}catch(Pi){}V=null}if(!V){V=null;break a}d=0<d?d:V.width;q=0<q?q:V.height}V={width:d,height:q}}if(V){w=0;a:{try{var T=c.google_async_iframe_id,ra=g.Kc().document;if(T)var Wa=ra.getElementById(T);else{var kb=ra.getElementsByTagName("script"),Ud=kb[kb.length-1];Wa=Ud&&Ud.parentNode||null}if(T=Wa){Wa=[];ra=0;for(var Ue=
(0,g.A)();100>=++ra&&50>(0,g.A)()-Ue&&(T=Eoa(T));)1===T.nodeType&&Wa.push(T);b:{for(Ue=0;Ue<Wa.length;Ue++){c:{var Yb=Wa[Ue];try{if(Yb.parentNode&&0<Yb.offsetWidth&&0<Yb.offsetHeight&&Yb.style&&"none"!==Yb.style.display&&"hidden"!==Yb.style.visibility&&(!Yb.style.opacity||0!==Number(Yb.style.opacity))){var Fm=Yb.getBoundingClientRect();var Qi=0<Fm.right&&0<Fm.bottom;break c}}catch(Pi){}Qi=!1}if(!Qi){var Gm=!1;break b}}Gm=!0}if(Gm){b:{var wh=(0,g.A)();Gm=/^html|body$/i;Qi=/^fixed/i;for(Yb=0;Yb<Wa.length&&
50>(0,g.A)()-wh;Yb++){var xh=Wa[Yb];if(!Gm.test(xh.tagName)&&Qi.test(xh.style.position||g.eo(xh))){var ie=xh;break b}}ie=null}break a}}}catch(Pi){}ie=null}ie&&ie.offsetWidth*ie.offsetHeight<=4*V.width*V.height&&(w=1);b.pfx=w}}wh=e.location;e=c.google_ad_slot;if(wh){ie=Vna(wh);a:{xh=TS(wh);try{var Ek=xh.match(/\bpfofmt=([\w]+)/);var Fk=Ek&&Ek[1]||null;break a}catch(Pi){}Fk=null}a:{Ek=TS(wh);try{var iu=Ek.match(/\bpfoslot=([\d]+)/);var bq=iu&&iu[1]||null;break a}catch(Pi){}bq=null}0>=ie||!(ie!=RS.google_server_side_slot_resize||
Fk&&bq&&bq==e)||(b.pfo=ie,b.adtest="on",Fk&&(b.pfofmt=Fk))}if("26835106"===$R(41)&&a.G){try{var ju=a.G.document.getElementsByTagName("head")[0];var Hm=ju?Aoa(ju):0}catch(Pi){Hm=0}0!==Hm&&(b.cms=Hm)}f=Zna(f,c);0!=f&&(b.ifsl=f);"r20100101"!==c.google_lrv&&(b.alvm=c.google_lrv||"none")},Noa=function(a,b){var c=a.F;
b.dt=g.ml;g.Gc(c)&&c.google_bpp&&(b.bpp=c.google_bpp);var d,e=g.Kc();a:{var f=g.Kc();try{var k=f.performance;if(k&&k.timing&&k.now){var l=k.timing.navigationStart+Math.round(k.now())-k.timing.domLoading;break a}}catch(O4){}l=null}var m=l;(d=m?eT(m,e.Date.now()-g.ml,1E6):null)&&(b.bdt=d);var q=c.google_iframe_start_time;if(g.ua(q)){c.google_iframe_start_time=null;var w=eT(q,g.ml)}else w=null;var y=w;null!=y&&(b.fdt=y);b.idt=eT(g.ml,g.ml);var I=a.F;b.shv="r20100101";b.cbv="/r20100101".replace("/","");
/^\w{1,3}$/.test(I.google_loader_used)&&(b.saldr=I.google_loader_used);var R=KR(a.C);if(R){b.is_amp=1;var V=R||KR();b.amp_v=V&&V.mode?+V.mode.version||null:null;var T=R||KR();if(T&&T.container){for(var ra=T.container.split(","),Wa=[],kb=0;kb<ra.length;kb++)Wa.push(Ioa[ra[kb]]||"x");var Ud=Wa.join()}else Ud=null;var Ue=Ud;Ue&&(b.act=Ue)}g.Kc()==window.top&&(b.abxe=1);var Yb=hS(),Fm=iS(Yb,8,{}),Qi=c.google_ad_section;Fm[Qi]&&(b.prev_fmts=Fm[Qi]);var Gm=iS(Yb,9,{});Gm[Qi]&&(b.prev_slotnames=Gm[Qi].toLowerCase());
var wh=iS(Yb,8,{}),xh=iS(Yb,9,{}),ie=c.google_ad_section,Ek=c.google_ad_format,Fk=c.google_ad_slot;Ek?wh[ie]=wh[ie]?wh[ie]+(","+Ek):Ek:Fk&&(xh[ie]=xh[ie]?xh[ie]+(","+Fk):Fk);var iu=iS(Yb,15,0);0<iu&&(b.nras=String(iu));var bq=g.Kc(),ju=KR(bq);if(ju){var Hm=ju||KR();if(Hm){var Pi=Hm.pageViewId,P4=Hm.clientId;g.sa(P4)&&(Pi+=P4.replace(/\D/g,"").substr(0,6));var Q4=Pi}else Q4=null;var R4=+Q4}else{var S4=cS(bq,!1).Mg,dM=S4.google_global_correlator;dM||(S4.google_global_correlator=dM=1+Math.floor(Math.random()*
Math.pow(2,43)));R4=dM}b.correlator=iS(Yb,7,R4);ZR().F[Joa.ENABLED]&&(b.rume=1);if(c.google_ad_channel){for(var T4=iS(Yb,10,{}),U4="",W4=c.google_ad_channel.split(kT),eM=0;eM<W4.length;eM++){var fM=W4[eM];T4[fM]?U4+=fM+"+":T4[fM]=!0}b.pv_ch=U4}if(c.google_ad_host_channel){for(var sB=iS(Yb,11,[]),X4=c.google_ad_host_channel.split("|"),tB=-1,gM=[],Ri=0;Ri<X4.length;Ri++){var Y4=X4[Ri].split(kT);sB[Ri]||(sB[Ri]={});for(var ku="",hM=0;hM<Y4.length;hM++){var uB=Y4[hM];""!==uB&&(sB[Ri][uB]?ku+="+"+uB:sB[Ri][uB]=
!0)}ku=ku.slice(1);gM[Ri]=ku;""!==ku&&(tB=Ri)}var iM="";if(-1<tB){for(var jM=0;jM<tB;jM++)iM+=gM[jM]+"|";iM+=gM[tB]}b.pv_h_ch=iM}b.frm=c.google_iframing;b.ife=c.google_iframing_environment;var Z4=c.google_ad_client;try{var $4=eS(),vB=$4.google_prev_clients;vB||(vB=$4.google_prev_clients={});if(Z4 in vB)var kM=1;else vB[Z4]=!0,kM=2}catch(O4){kM=0}b.pv=kM;var lM=a.C.document,a5=a.F,b5="";try{b5=lM.cookie}catch(O4){}var c5=lM.domain,lu=b5,wB=a.C.screen,ira=lM.referrer,jra=g.Go();if(KR())var d5=g.Kc().gaGlobal||
{};else{var mM=Math.round((new Date).getTime()/1E3),nM=a5.google_analytics_domain_name,xB="undefined"==typeof nM?QS("auto",c5):QS(nM,c5),kra=-1<lu.indexOf("__utma="+xB+"."),lra=-1<lu.indexOf("__utmb="+xB),oM;if(!(oM=(LR()||g.Kc()).gaGlobal)){var mra={};oM=(LR()||g.Kc()).gaGlobal=mra}var Id=oM,e5=!1;if(kra){var pM=lu.split("__utma="+xB+".")[1].split(";")[0].split(".");lra?Id.sid=pM[3]+"":Id.sid||(Id.sid=mM+"");Id.vid=pM[0]+"."+pM[1];Id.from_cookie=!0}else{Id.sid||(Id.sid=mM+"");if(!Id.vid){e5=!0;var nra=
Math.round(2147483647*Math.random()),f5=jra,g5,Im=[OS.appName,OS.version,OS.language?OS.language:OS.browserLanguage,OS.platform,OS.userAgent,Una()?1:0].join("");if(wB)Im+=wB.width+"x"+wB.height+wB.colorDepth;else if(g.n.java&&g.n.java.gw){var h5=g.n.java.gw.yX.FZ().HZ();Im+=h5.screen.width+"x"+h5.screen.height}Im=Im+lu+(ira||"");for(g5=Im.length;0<f5;)Im+=f5--^g5++;Id.vid=(nra^PS(Im)&2147483647)+"."+mM}Id.from_cookie=!1}if(!Id.cid){b:{var cq=nM,i5=999;cq&&(cq=0==cq.indexOf(".")?cq.substr(1):cq,i5=
(""+cq).split(".").length);for(var j5,k5=999,yB=lu.split(";"),mu=0;mu<yB.length;mu++){var zB=Koa.exec(yB[mu])||Loa.exec(yB[mu])||Moa.exec(yB[mu]);if(zB){var qM=zB[1]||0;if(qM==i5){var l5=zB[2];break b}qM<k5&&(k5=qM,j5=zB[2])}}l5=j5}var nu=l5;e5&&nu&&-1!=nu.search(/^\d+\.\d+$/)?Id.vid=nu:nu!=Id.vid&&(Id.cid=nu)}Id.dh=xB;Id.hid||(Id.hid=Math.round(2147483647*Math.random()));d5=Id}var ou=d5;b.ga_vid=ou.vid;b.ga_sid=ou.sid;b.ga_hid=ou.hid;b.ga_fc=ou.from_cookie;b.ga_cid=ou.cid;b.ga_wpids=a5.google_analytics_uacct;
var pu=a.C,qu=new SR(pu);pu.location&&pu.location.ancestorOrigins&&(b.iag=UR(qu));b.icsg=VR(qu);var m5=qu.C[0].depth;0<m5&&(b.nhd=m5);b.dssz=pu.document.scripts?pu.document.scripts.length:0;b.mdo=WR(qu);b.mso=XR(qu);var rM=c.google_ad_layout;rM&&0<=lT[rM]&&(b.rplot=lT[rM])},Ooa=function(a,b){var c=a.F;
MR(AS,function(a,e){b[a]=c[e]});
MR(zS,function(a,e){b[a]=c[e]});
MR(BS,function(a,e){b[a]=c[e]});
JS(c)&&(b.fa=JS(c));gT(c,!0)&&(soa(c)?(poa(c.google_ad_client),b.srr=1):b.srr=0)},Poa=function(a,b){var c;
if(c=((c=(c=KR())&&c.initialIntersection)&&g.Ba(c.rootBounds)?new g.ic(c.rootBounds.width,c.rootBounds.height):null)||g.Io(a.C.top))b.biw=c.width,b.bih=c.height;c=a.C;c.top!=c&&(c=g.Io(a.C))&&(b.isw=c.width,b.ish=c.height)},Qoa=function(a,b){var c=a.C;
if(null!==c&&c!=c.top){var d=[c.document.URL];c.name&&d.push(c.name);c=g.Io(c,!1);d.push(c.width.toString());d.push(c.height.toString());d=IR(d.join(""))}else d=0;0!==d&&(b.ifk=d.toString())},Boa=function(a){var b={};
Ooa(a,b);Noa(a,b);g.Ho(b);Poa(a,b);Qoa(a,b);Goa(a,b);Foa(a,b);a.K&&(b.oid=a.K);Hoa(a,b);b.fu=a.D;b.bc=g.pp();b.url&&g.Oa(String(b.url),"https:")&&g.nb()&&0<=g.Xa(qna(),57)&&(b.osw_key=ooa(b));if("21061320"==$R(104)){var c={};g.xc(b,function(a,b){c[b]=a&&"string"===typeof a&&2E3<a.length?a.substring(0,2E3):a});
return c}return b},mT=function(a){g.Zd.call(this);
this.C=a||window;this.F=g.Kd(this.C,"resize",this.G,!1,this);this.D=g.nc(this.C)},nT=function(){this.G=this.C=!1;
this.F=new g.iH(this);this.H=!1},wT=function(){if(g.D("WATCH_LEGAL_TEXT_ENABLE_AUTOSCROLL")){var a=window.document.getElementById("watch_companion_legal_text");
a&&(oT=new nT,oT.start(a))}var b=g.D("ADS_DATA",void 0);b&&(pT(),Roa(b),qT=b,rT=g.CG(),null!=rT&&(rT.addEventListener("onApiChange",Soa),rT.addEventListener("onReady",Toa)),b.pyv_ad_tag&&Uoa(b),b.use_gut&&(g.Of("//www.googletagservices.com/tag/js/gpt.js"),g.Nf("//www.googletagservices.com/tag/js/gpt.js",function(){Voa(b.gut_vars.tag)})),b.show_afv&&(g.Of("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),sT(),g.Nf("//pagead2.googlesyndication.com/pagead/show_companion_ad.js",Woa),g.$f("remove_yt_uds")||
g.Nf("//www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22ads%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22(function()%7B%7D)%22%2C%22packages%22%3A%5B%22content%22%5D%7D%5D%7D")),tT(),uT&&(uT=!1,vT(b)),g.F("watchAdsInit"))},tT=function(){xT&&null!=rT&&null!=rT.getOptions&&null!=rT.getOptions()&&g.Ia(rT.getOptions(),"ad")&&rT.getOption("ad","PAGE_JAVASCRIPT_INITIALIZED",{})},pT=function(){var a=window.Goog_Osd_UnloadAdBlock,b=g.x("google_companion_ad_div");
g.Aa(a)&&null!=b&&a(g.tn(b))},Roa=function(a){yT.length=0;
if("afv_vars"in a)for(var b in a.afv_vars)window[b]=a.afv_vars[b],yT.push(b)},Voa=function(a){"googletag"in window&&window.googletag&&(window.googletag.cmd=window.googletag.cmd||[],window.googletag.cmd.push(function(){if(zT=window.googletag.defineSlot(a,[[300,
250],[300,60]],"google_companion_ad_div")){zT.set("ad_type","flash");zT.addService(window.googletag.companionAds());window.googletag.enableServices();var b=zT.getSizes();b&&2<=b.length&&(AT=b[0],BT=b[1])}}))},CT=function(a,b){a||(a="");
b||(b=!1);var c=g.x("watch-channel-brand-div");c&&g.cp(c,"collapsible",b);if(c=g.x("google_companion_ad_div"))c.innerHTML=a},DT=function(a){var b=Math.round(1E4*Math.random());
return['<iframe src="',a,'" name="ifr_300x250ad',b,'" id="ifr_300x250ad',b,'" width="300" height="250" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join("")},ET=function(a){return!!a.match("/ad_companion.*render=video_wall_companion")},FT=function(a,b){var c=250;
"video"==a&&(c=60);var d=(0,window.decodeURIComponent)(b);CT(['<iframe name="fw_ad" id="fw_ad" ','width="300" height="'+c+'" ','marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join(""));var e=g.x("fw_ad");if(e){e=e.contentWindow?e.contentWindow:e.contentDocument&&e.contentDocument.document?e.contentDocument.document:e.contentDocument;var f=window.navigator.userAgent.toLowerCase();c=-1!=f.indexOf("msie");f=-1!=f.indexOf("opera");e.document.open();e.document.write(d);
c||f?g.Bf(function(){e.document.close()},7500):e.document.close()}},Woa=function(){g.F("showCompanionAdLoaded")},sT=function(){window.google_ad_output="html";
window.google_ad_height="250";window.google_ad_format="300x250_as";window.google_container_id="google_companion_ad_div"},IT=function(){var a=window.document.getElementById("google_companion_ad_div");
if(a&&(a=a.firstElementChild)){"DIV"==a.nodeName&&(a=a.firstElementChild);try{var b=(0,window.encodeURIComponent)(GT)+","+(0,window.encodeURIComponent)(HT);a.contentWindow.postMessage(b,"*");a.width=370;a.height=null!=GT?210:185}catch(c){}}},JT=function(){var a=window.document.getElementById("movie_player");
a&&a.pauseVideo()},Uoa=function(a){xS(a.pyv_ad_tag.tag);
a.log_pyv&&KT.push(g.Tf(function(){"google_render_ad"in window?g.Dj("pyvls"):g.Dj("pyvlf")},5E3))},vT=function(a){if(!LT){if(!a){if(!qT){uT=!0;
return}a=qT}if(g.$f("remove_yt_uds")){LT=!0;window.google_ad_client=a.afv_vars.google_ad_client;window.google_page_url=a.afv_vars.google_page_url;window.google_page_location=window.location.href;var b=a.afc_vars,c;for(c in b){var d=b[c];if("no_initial_ads"==c&&d){CS();return}if("format"!=c||g.Qa(g.cm(d)))if("loeid"!=c||g.Qa(g.cm(d))){var e="google_"+c;(zS[e]||AS[e]||BS[e])&&(window[e]=d)}else window.google_loeid=g.cm(d);else if(d=g.cm(d),e=d.match(/(\d+)x(\d+)/))window.google_ad_width=e[1],window.google_ad_height=
e[2],window.google_ad_format=d}b=new rna;Sna(b);window.google_loader_used="yt";(b=Doa(b))&&Xoa(b);CS()}else(b=g.r("google.ads.Ad"))?(LT=!0,new b(a.afv_vars.google_ad_client,"google_companion_ad_div",a.afc_vars)):MT=g.Bf(function(){vT(a)},200)}},Xoa=function(a){var b=g.x("google_companion_ad_div");
null!=b&&(a=g.qc("IFRAME",{width:window.google_ad_width,height:window.google_ad_height,frameBorder:0,marginWidth:0,marginHeight:0,vpsace:0,hspace:0,allowTransparency:"true",scrolling:"no",src:a,style:{visibility:"visible"}}),b.appendChild(a))},Soa=function(){tT()},Toa=function(){xT=!0;
tT()},Yoa=function(a){var b=null;
"transition"in a.style?b="transition-duration":"webkitTransition"in a.style?b="-webkit-transition-duration":"MozTransition"in a.style?b="-moz-transition-duration":"OTransition"in a.style?b="-o-transition-duration":"msTransition"in a.style&&(b="-ms-transition-duration");a=b?(window.document.defaultView?window.document.defaultView.getComputedStyle(a,null):window.document.parentWindow.getComputedStyle(a,null)).getPropertyValue(b):"0";return 1E3*(0,window.parseFloat)(a)},Zoa=function(){var a=g.x("facebook_token_refresh_iframe"),
b=g.D("FACEBOOK_TOKEN_REFRESH_URL");
a&&g.vw("facebook_token_refresh")!=b&&(g.uw("facebook_token_refresh",b,3600),a.src=b)},NT=function(){g.U.call(this);
this.D=null},OT=function(){g.U.call(this);
this.H=null;this.G=0;this.N={report:(0,g.t)(this.iL,this),share:(0,g.t)(this.GL,this)}},PT=function(a){a.G&&(g.Ef(a.G),a.G=0);
a.Gc&&(a.Gc.dispose(),a.Gc=null)},$oa=function(a){a.Gc=new g.dH(a.D,a.J,a.Y,null,null,!1,!1,g.D("SHARE_REFERER",void 0),g.D("SHARE_CAPTION",void 0),null,null,null,null,null,g.D("PLAYLIST_INDEX",void 0),null,"metadata",g.D("EVENT_ID",void 0),null,!0);
g.vd(a,a.Gc);g.Ef(a.G);a.G=g.Cf(function(){var a=g.CG().getCurrentTime(),c=Math.floor(a/3600),d=Math.floor(a%3600%60);a=(0<c?c+":":"")+g.bm(Math.floor(a%3600/60),0<c?2:1)+":"+g.bm(d,2);GR(this.Gc,a)},1E3)},cpa=function(){if(QT=g.K("mealbar-promo-renderer")){var a=g.K("yt-uix-button-primary",QT);
if(a){var b=g.K("yt-uix-button-blue-text",QT);if(b){var c=g.K("ad-blocker-msg-data");c&&(RT.push(g.H(a,"click",apa,!0),g.H(b,"click",bpa,!0)),g.E(c,"freq-cap"),ST=g.ah(),TT("AD_BLOCKER_MESSAGING_EVENT_TYPE_DISPLAYED"))}}}},apa=function(){TT("AD_BLOCKER_MESSAGING_EVENT_TYPE_LEARN_HOW");
UT();g.wo(QT,!1)},bpa=function(){TT("AD_BLOCKER_MESSAGING_EVENT_TYPE_DISMISSED");
UT();g.wo(QT,!1)},TT=function(a){var b=g.Th();
b&&(a={displayPeriodMs:Math.round(g.ah()-ST),adBlockerMessagingEventType:a,clientScreenNonce:b},g.zh("adBlockerMessagingShown",a))},UT=function(){g.Ig(RT);
RT.length=0},epa=function(){(0,g.z)(g.J("promoted-button-container"),function(a){a:{var b=g.E(a,"promo-id");
var c=g.Cp(a,"promo-impression-cap")||0;var d=g.Cp(a,"promo-impression-delay")||0;if(b&&0<c&&0<d){b="yt-hint-"+b;var e=g.vw(b)||{},f=e.lastSeen;e=e.impressions||0;if(f&&(0,g.A)()-new Date(f)<1E3*d||e>=c){c=!1;break a}e={lastSeen:(0,g.A)(),impressions:e+1};g.uw(b,e,2592E3)}c=!0}c?("true"===g.E(a,"promo-visible")&&(c=g.Zz.getInstance(),c.pn(a),"hidden"!=window.getComputedStyle(a).visibility&&(c.show(a),g.B(a,"hide-hint-on-scroll")&&(c=g.x(g.E(a,"scroll-parent"))||window,VT.push(g.Jg(c,"scroll",(0,g.t)(dpa,
this,a)))))),g.MF(a)):(a=g.K("generic-promo-impression-logging",a))&&g.O(a,"generic-promo-impression-logging")})},dpa=function(a){g.Zz.getInstance().hide(a)},XT=function(a){g.sd.call(this);
this.C=a;this.G=[];this.J=[];this.W=this.Yl=!1;this.F=this.R=this.D=this.H=this.K=null;a=window;var b=g.Da(a);this.la=WT[b]=WT[b]||new mT(a);this.N=g.KJ.getInstance().C.then((0,g.t)(this.JF,this))},ZT=function(a){return 820<g.to(a.C).width&&!a.V?"expanded":"compact"},fpa=function(a,b){var c=g.x("stats-optout-form");
c&&(g.S("stats-optout-success"),g.S("stats-optout-error"),a.R=g.Jp(c,{format:"XML",za:{opt_out:b},onSuccess:function(){this.Yl=b;g.Q("stats-optout-success")},
onError:function(){g.x("stats-opt-out-chbox").checked=!this.Yl;g.Q("stats-optout-error")}}))},$T=function(a,b){var c=g.E(a,b);
if(c){var d=g.M(a,"watch-actions-stats-rats"),e=g.E(d,"current-"+b)||"";e!=c&&(g.fp(d,e,c),g.Dp(d,"current-"+b,c))}},aU=function(a,b,c){a=g.K("watch-actions-stats-rats",a.C);
if(!a)return null;b=g.E(a,"current-"+b);return c&&b&&g.Oa(b,c)?b.substr(c.length):b},bU=function(a){if(a.K&&a.W&&a.H){var b=aU(a,"metric-css","stats-metric-"),c=aU(a,"mode-css","stats-mode-");
if(b&&c){a.D||(a.D=new window.google.visualization.LineChart(a.H));var d=a.K.day||{};b=b in a.K?a.K[b][c]||{}:{};null===a.F&&(a.F=ZT(a));c=new gpa(a.F,a.H,b.opt);var e=c.D;a.C&&e&&g.Ec(a.C,e);(e=g.x("watch-action-panels"))&&g.Ec(e,c.N);hpa(a,a.D,a.H,d,b)}}},hpa=function(a,b,c,d,e){var f=new window.google.visualization.DataTable;
f.addColumn("date","Date");f.addColumn("number","value");"cmp_data"in e?(f.addColumn("number","cmp_data"),d=HR(d.data||[],e.data||[],e.cmp_data||[])):d=HR(d.data||[],e.data||[]);(0,g.z)(d,function(a){a[0]=new Date(a[0]);f.addRow(a)});
e=e.opt||{};"hAxis"in e&&"viewWindow"in e.hAxis&&(d=e.hAxis.viewWindow,"min"in d&&!(d.min instanceof Date)&&(d.min=new Date(d.min)),"max"in d&&!(d.max instanceof Date)&&(d.max=new Date(d.max)));d=g.xn(c);g.tc(c);c.style.left="-5000px";g.mn(a.C,c);try{b.draw(f,e)}catch(k){throw k;}finally{c.style.left="",g.tc(c),d&&g.mn(d,c)}},gpa=function(a,b,c){this.C=a;
this.J=c;this.V="compact"==this.C?590:"auto";this.F="compact"==this.C?160:160*g.to(b).width/590;this.H="compact"==this.C?"86%":"90%";this.G=this.F-50;this.K="compact"==this.C?10:12;this.W="compact"==this.C?1:2;this.R="compact"==this.C?4:6;this.D=cU("compact"==this.C?293:293+(this.F-160));this.N="compact"==this.C?cU(323):this.D+50;ipa(this)},cU=function(a){g.x("stats-opt-out-chbox")&&g.ua(a)&&(a+=30);
return a},ipa=function(a){function b(a,d){g.ab(d,function(c,d){g.qa(a)&&(g.Ba(c)?b(a[d],c):a[d]=c)})}
b(a.J,{width:a.V,height:a.F||"auto",chartArea:{width:a.H,height:a.G||"auto"},fontSize:a.K,vAxis:{gridlines:{count:a.R}},lineWidth:a.W})},dU=function(a,b,c){g.U.call(this,b);
this.ab=a;this.Sa=c;this.G=null;this.D=250;this.aa=this.V=this.N=this.Y=this.H=this.J=null;this.na=0},eU=function(a,b,c){for(var d=0;d<a.length;d++)if(g.sc(a[d]),b){var e=g.sK(b,c);
g.pn(a[d],e,0)}},lpa=function(){var a=g.K("youthere-data");
fU=!1;if(gU=g.K("mealbar-promo-renderer"))if(hU=g.K("yt-dialog-title",gU))if(iU=g.K("yt-ytb",gU))if(jU=g.K("youthere-conf"))if(kU=g.K("youthere-pause-msg"))lU=(0,window.parseInt)(g.E(a,"pause-del"),10),mU=(0,window.parseInt)(g.E(a,"lact-th"),10),nU=(0,window.parseInt)(g.E(a,"prompt-del-sec"),10),oU.push(g.H(iU,"click",pU,!0)),qU.push(g.Jf("player-ad-end",jpa)),qU.push(g.Jf("yt-ui-dialog-show-complete",kpa)),fU=rU=!0},jpa=function(){fU&&g.lh()<mU&&sU("YOU_THERE_EVENT_TYPE_BELOW_LACT_THRESHOLD")},kpa=
function(a){rU=!1;
var b=gU;b&&a&&a.F==b&&((a=g.Ku())&&Mna(a),g.Bf(function(){oU.push(g.H(window.document,"scroll",pU,!0));oU.push(g.H(window.document,"click",pU,!0))},500),tU=g.Bf(mpa,lU),sU("YOU_THERE_EVENT_TYPE_PROMPT_SHOWN"))},pU=function(){rU=!0;
uU();if(vU){var a=window.document.getElementById("movie_player");a&&a.playVideo()}g.wo(iU,!1);a=jU;g.qn(a,hU);a.className=hU.className;hU=a;g.Bf(npa,400);sU("YOU_THERE_EVENT_TYPE_USER_RESPONDED")},uU=function(){g.Df(tU);
g.Kf(qU);g.Ig(oU);qU.length=oU.length=0},mpa=function(){if(!rU){var a=kU;
g.qn(a,hU);a.className=hU.className;hU=a;if(a=window.document.getElementById("movie_player"))a.pauseVideo(),vU=!0,sU("YOU_THERE_EVENT_TYPE_PLAYBACK_PAUSED")}},npa=function(){var a=new g.gF(hU,1E3);
a.play();a.O("finish",function(){g.wo(gU,!1)})},sU=function(a){var b=g.Th();
b&&(a={clientScreenNonce:b,lactMs:String(g.lh()),lactThresholdMs:String(mU),mediaPosSec:nU,youThereEventType:a},g.zh("youThere",a))},opa=function(){-1!=g.ag("service_worker_push_logged_out_prompt_watches")&&g.sj("WatchCount").then(function(a){100<=a||g.rj("WatchCount",a+1)})},wpa=function(){wU=g.K("toggle-loop",xU);
xU=g.x("watch-appbar-playlist");yU=g.K("playlist-videos-list",xU);zU=g.K("shuffle-playlist",xU);AU=g.K("next-playlist-list-item",xU);BU=g.K("prev-playlist-list-item",xU);CU=g.K("playlist-header-content",xU);DU="currently-playing";if(xU&&yU){var a=g.CG();a&&(EU=a,a.addEventListener("onReady",FU));CU&&(GU="true"===g.E(CU,"initial-loop-state"));HU.push(g.H(wU,"click",ppa));HU.push(g.H(zU,"click",qpa));HU.push(g.H(AU,"click",function(a){IU(a,"bf_next")}));
HU.push(g.H(BU,"click",function(a){IU(a,"bf_prev")}));
HU.push(g.lq(yU,rpa));HU.push(g.P(yU,"click",spa,"yt-uix-button-playlist-remove-item"));JU.push(g.Jf("navigate",tpa));JU.push(g.Jf("player-state-change",upa));JU.push(g.Jf("player-error",vpa));JU.push(g.Jf("watch-queue-show",function(a){g.Ej()&&(0==a?g.N(xU,"watch-queue-nav"):g.S(xU))}));
JU.push(g.Jf("watch-queue-hide",function(){g.Q(xU);g.O(xU,"watch-queue-nav")}));
g.Ej()&&vS()&&(0==wS()?g.N(xU,"watch-queue-nav"):g.S(xU));g.D("SKIP_TO_NEXT_VIDEO")&&KU(5);LU();MU();NU()}},TU=function(a,b){var c=AU;
if(b){if(!OU().loop||PU)return;var d=CU;if(d){var e=QU(d,"auto");var f=g.E(d,"autoplay-clicktracking")||""}}else RU(),e=QU(c,"next"),f=g.E(c,"clicktracking")||"";f=SU(a||"bf_next",f,b,e);g.ii(c.href,f)},UU=function(a){var b=a||"bf_prev";
a=BU;var c=QU(a,"prev"),d=g.E(a,"clicktracking")||"";b=SU(b,d,!1,c);g.ii(a.href,b)},OU=function(){var a=[],b=-1,c=yU;
if(!c)return null;(0,g.z)(c.getElementsByTagName("li"),function(c,d){g.B(c,DU)&&(b=d);var e={encrypted_id:g.E(c,"video-id"),author:g.E(c,"video-username"),title:g.E(c,"video-title"),start:g.E(c,"video-clip-start"),end:g.E(c,"video-clip-end"),iurl:g.E(c,"thumbnail-url")};a.push(e)});
c=CU;var d=b+1<a.length||GU;return{author:g.E(c,"list-author"),loop:d,index:b,list:g.E(c,"full-list-id"),title:g.E(c,"list-title"),description:g.E(c,"list-description"),video:a}},MU=function(){g.F("yt-dom-content-change",yU)},QU=function(a,b){var c=g.D("SHUFFLE_VALUE"),d=GU,e="normal";
c&&d?e="loop_shuffle":c?e="shuffle":d&&(e="loop");return g.E(a,e+"-"+b+"-clicktracking")},FU=function(a){EU&&EU.removeEventListener("onReady",FU);
EU=a;a.addEventListener("onCueRangeEnter",VU);var b=a.getDuration(),c=g.D("PREFETCH_AUTOPLAY"),d=g.D("PREFETCH_AUTOPLAY_TIME",10);c&&a.addCueRange("AUTOPLAY_PREFETCH",b-d,b);g.D("EXP_DEBUG_PREFETCH")&&g.Dj(g.Tc({a:"registerNearEndEventsWithPlayer",endTime:b,prefetchEnabled:c,prefetchTime:d}));g.$f("player_external_control_on_classic_desktop")&&(a.addEventListener("onPlaylistNext",TU),a.addEventListener("onPlaylistPrevious",UU),a.addEventListener("onPlaylistIndex",WU))},VU=function(a){if("AUTOPLAY_PREFETCH"==
a&&(a=g.D("PREFETCH_AUTOPLAY_TIME",10),OU().loop&&!PU&&!XU)){XU=!0;
var b=CU;if(b){var c=QU(b,"auto");var d=g.E(b,"autoplay-clicktracking")||""}b=AU.href;d=SU("autoplay",d,!0,c,a);g.YC(b,!!g.D("PREBUFFER_AUTOPLAY"),d,xpa)}},xpa=function(a){XU=!1;
YU=a.response.cacheKey||null},RU=function(){YU&&(window.spf.cache.remove(YU),YU=null)},NU=function(){g.Xf()?(g.Uf(ZU),ZU=g.Tf(g.u(g.Lf,"watch-list-change"))):g.F("watch-list-change")},KU=function(a){0==a?TU("mr_meh",!0):$U=g.Bf(function(){KU(a-1)},1E3)},aV=function(){var a=CU;
return!(!a||"False"==g.E(a,"shareable"))},ppa=function(){var a=wU;
a&&(GU=!g.Ny.getInstance().isToggled(a))},qpa=function(){var a=yU,b=g.Ma(a.getElementsByTagName("li")),c=zU;
c&&g.Ny.getInstance().isToggled(c)?(b=ypa(b),g.uf("SHUFFLE_VALUE",0)):(c=zpa(b),b=Apa(b,c));g.sc(a);(0,g.z)(b,function(b){a.appendChild(b)});
c=g.D("SHUFFLE_VALUE");bV(b,c);LU();MU();cV();NU()},cV=function(){var a=0;
(0,g.z)(g.en("li",null,yU),function(b){(b=g.K("index",b))&&!(0,window.isNaN)(b.innerText)&&g.L(b,a+1);a+=1})},rpa=function(a){var b=g.Mn(a.currentTarget,"li"),c=g.E(b,"clicktracking")||"";
b=g.E(b,"innertube-clicktracking")||"";dV(a,void 0,c,b)},IU=function(a,b){var c=g.E(a.currentTarget,"clicktracking")||"";
dV(a,b,c)},dV=function(a,b,c,d){b=SU(b||"BFa",c,!1,d);
c=a.currentTarget.href;d={};var e=g.D("SHUFFLE_VALUE");e?d.shuffle=e:-1!=c.indexOf("shuffle=")&&(d.shuffle=0);d&&(c=g.jg(c,d));g.cc(a.currentTarget,c);g.gi(c,b);RU()},spa=function(a){var b=CU,c=g.Mn(a.currentTarget,"li");
if(b&&c){var d=yU;g.N(d,"playlist-editing-locked");a=g.E(b,"full-list-id");var e=g.E(c,"video-id"),f=g.Cp(c,"index");g.Iz("delete_from_playlist",{videoIds:e,fullListId:a,onSuccess:function(){g.tc(c);var a=g.en("li",null,d),e=g.K("currently-playing",d);(0,g.z)(a,function(a){var b=g.Cp(a,"index");b>f&&g.Dp(a,"index",b-1)});
"RD"!=g.E(b,"full-list-id").substring(0,2)&&cV();e=e&&g.Cp(e,"index")+1||0;var m=g.x("playlist-current-index");m&&g.L(m,e);(e=g.x("playlist-length"))&&g.L(e,a.length);bV(a,g.D("SHUFFLE_VALUE"))},
Ya:function(){g.O(d,"playlist-editing-locked");NU()}})}},upa=function(a){0!=a||g.Ku()&&!g.$f("player_unified_fullscreen_transitions")||TU("autoplay",!0)},vpa=function(){},tpa=function(){PU=!0},Apa=function(a,b){function c(a){var c=0,d=[];
for(a=a.split("");a.length;){c=(b+c)%a.length;var e=a[c];g.Ka(a,c);d.push(e)}return d.join("")}
g.Tl(a,function(a,b){var d=g.E(a,"video-id"),e=g.E(b,"video-id");return c(d).localeCompare(c(e))});
var d=b>>8,e=g.Fa(a,function(a){a=g.E(a,"index");return d==a})||0;
0<e&&(a=g.Pl(a,e).concat(g.Pl(a,0,e)));return a},ypa=function(a){g.Tl(a,function(a,c){var b=g.Cp(a,"index"),e=g.Cp(c,"index");
return b-e});
return a},zpa=function(a){var b=g.D("SHUFFLE_VALUE");
if(!b){var c=0;(0,g.z)(a,function(a){g.B(a,DU)&&(c=g.E(a,"index"))});
b=(c<<8)+Math.floor(256*Math.random());g.uf("SHUFFLE_VALUE",b)}return b},bV=function(a,b){var c=null;
(0,g.z)(a,function(a){g.B(a,DU)&&(c=a)});
if(c){var d=g.un(c);d||(d=a[0]);var e=g.vn(c);e||(e=a[a.length-1]);var f=AU,k=BU;f&&d&&(d={v:g.E(d,"video-id")},b?d.shuffle=b:-1!=f.href.indexOf("shuffle=")&&(d.shuffle=0),g.cc(f,g.jg(f.href,d)));k&&e&&(d={v:g.E(e,"video-id")},b?d.shuffle=b:-1!=k.href.indexOf("shuffle=")&&(d.shuffle=0),g.cc(k,g.jg(k.href,d)))}},SU=function(a,b,c,d,e){var f={},k=g.D("EVENT_ID");
k&&(f.ei=k,a&&(f.feature=a),d?f.itct=d:b&&(f.ved=b),(a=g.D("SHUFFLE_VALUE"))&&(f.shuffle=a),GU&&(f.loop_on=!0),c&&(f.playnext=g.D("LIST_AUTO_PLAY_VALUE"),f.autonav=1,c=g.lh(),0<c&&(f.lact=c),e&&(f.prefetch=e),(e=EU)&&e.isReady()&&(e=e.getVisibilityState(),0!=e&&(f.vis=e))));return f},LU=function(){var a=g.K("playlist-videos-list",xU),b=g.K(DU,a);
if(b){var c=g.SA.getInstance();if(a&&b&&(b=(0,g.Ha)(g.J(g.W(c,"scroll-unit"),a),b),0<=b&&!(!a||(0,window.isNaN)(b)||0>b)&&(c=g.J(g.W(c,"scroll-unit"),a),!(0>=c.length)))){b>=c.length&&(b=c.length-1);if(c.length){var d=c[0];var e=d.offsetHeight;1<c.length&&(e=c[1].offsetTop-d.offsetTop);d=e}else d=0;e=a.offsetHeight;b>Math.max(Math.floor(a.scrollTop/d),0)-1&&(d=Math.floor(e/d),e=c.length,b+d>e&&(b=e-d+1));0>b&&(b=0);b=c[b].offsetTop;a&&!(0,window.isNaN)(b)&&(0>b&&(b=0),a.scrollTop=b,g.Dp(a,"scroller-offset",
b+""),g.F("yt-dom-content-change",a))}}},WU=function(a){a=g.rn(yU)[a];
g.Cp(a,"index");a&&(a=g.K("playlist-video",a))&&a.click()},Bpa=function(a){var b=0,c=g.CG();
c&&c.isReady()&&(b=c.getCurrentTime());b=Math.floor(b);var d=Math.floor(b/60);b={action_get_report_video_component:1,video_id:g.D("VIDEO_ID"),t_mins:d,t_secs:b-60*d};"METADATA_LANGUAGE"in g.tf&&(b.metadata_language=g.D("METADATA_LANGUAGE"));c&&c.isReady()&&(c=c.getOption("cc","track")||c.getOption("captions","track"))&&(b.cc_vss_id=c.vss_id);return g.G("/watch_ajax",{method:"GET",za:b,onSuccess:function(b,c){a(c.report_html,!0)},
onError:function(){a(null,!1)},
nb:!0})},Cpa=function(a){return g.G("/insight_ajax",{format:"XML",
method:"POST",za:{action_get_statistics_and_data:1,v:g.D("VIDEO_ID")},onSuccess:function(b,c){a(c.html_content,c.graph_data,!0)},
onError:function(){a(null,null,!1)},
nb:!0})},fV=function(a,b){g.sd.call(this);
this.J=a;this.F=b;this.W=g.x("watch8-secondary-actions");this.D="action-panel-none";this.C=[];this.G=[];this.K=this.H=null;this.R=0;this.G.push(g.Jf("player-share",this.vs,this));this.G.push(g.Jf("livestreaming-likes-updated",this.rM,this));this.C.push(g.P(this.J,"click",(0,g.t)(this.rs,this),"action-panel-trigger"));this.C.push(g.P(this.F,"click",(0,g.t)(this.rB,this),"yt-uix-close"));var c=g.x("action-panel-overflow-menu");c&&this.C.push(g.P(c,"click",(0,g.t)(this.rs,this),"action-panel-trigger"));
c=g.Hp(window.location.hash).action;"share"==c?this.vs():"flag"==c?eV(this,"action-panel-report"):"stats"==c&&eV(this,"action-panel-stats")},Dpa=function(){var a=g.K("yt-uix-button-toggled",g.x("action-panel-share")),b;
aV()&&a?b=g.E(a,"video-id"):b=g.D("VIDEO_ID",void 0);return b},Epa=function(){var a=null;
if(aV()){var b=g.x("share-with-playlist");if(!b||b&&b.checked)a=(a=CU)?g.E(a,"full-list-id"):""}return a},eV=function(a,b,c,d){var e=g.K("watch-secondary-actions");
FR(g.Ny.getInstance(),e);e=g.x(b);var f=Fpa(a,e);e&&f&&(g.N(f,"yt-uix-button-toggled"),gV(a,b,c,d))},gV=function(a,b,c,d){if("action-panel-none"!=b){var e=g.x(b);
if(e){var f=!!g.E(e,"auth-required");e=!!g.E(e,"panel-loaded");if(f&&!g.D("LOGGED_IN"))hV(a,"action-panel-login");else if(e)hV(a,b);else switch(b){case "action-panel-share":Gpa(a,c,d);break;case "action-panel-transcript":Hpa(a);break;case "action-panel-add-transcript":b=g.x("action-panel-add-transcript");g.Q(g.x("watch-actions-add-transcript"));g.Dp(b,"panel-loaded","true");hV(a,"action-panel-add-transcript");break;case "action-panel-stats":Ipa(a);break;case "action-panel-report":Jpa(a)}}}},Gpa=function(a,
b,c){var d=Dpa(),e=Epa(),f=g.x("action-panel-share"),k=g.x("watch-actions-share-panel"),l=g.D("SHARE_CAPTION",void 0),m=g.D("SHARE_REFERER",void 0),q=g.D("PLAYLIST_INDEX",void 0),w=g.D("EVENT_ID",void 0),y=!!g.D("LIVESTREAMING_NO_SHARE_TIME");
if(g.D("LIVESTREAMING_DEFAULT_BROADCAST")&&-1==window.document.location.href.indexOf(d))var I=window.document.location.pathname;var R=new g.dH(k,d,e,(0,g.t)(a.MH,a),null,b,y,m,l,null,null,null,null,null,q,null,"watch",w,I,c);g.vd(a,R);g.Ef(a.R);var V=g.Cf(function(){var a=g.CG(),b=g.tu(f);if(a&&a.isReady()&&b){a=a.getCurrentTime();b=Math.floor(a/3600);var c=Math.floor(a%3600%60);a=(0<b?b+":":"")+g.bm(Math.floor(a%3600/60),0<b?2:1)+":"+g.bm(c,2);GR(R,a)}else g.Ef(V)},1E3);
a.R=V;g.Dp(f,"panel-loaded","true");hV(a,"action-panel-share")},Ipa=function(a){var b=g.x("action-panel-stats");
if(b){var c=new XT(b);g.vd(a,c);a.K=Cpa((0,g.t)(function(a,e,f){f?(g.Vm(b,a),c.load(e)):hV(this,"action-panel-error")},a));
g.Dp(b,"panel-loaded","true");hV(a,"action-panel-stats")}},Jpa=function(a){var b,c=!1,d=!1,e=g.x("action-panel-report"),f=(0,g.t)(function(){hV(this,"action-panel-error")},a);
g.fi(g.D("REPORTVIDEO_CSS",void 0));g.Nf(g.D("REPORTVIDEO_JS",void 0),(0,g.t)(function(){this.ob()||(c=!0,d&&c&&iV(e,b))},a));
a.H=Bpa((0,g.t)(function(a,l){l?(d=!0,b=a,d&&c&&(iV(e,b),e.focus())):f()},a));
g.Dp(e,"panel-loaded","true");hV(a,"action-panel-report")},iV=function(a,b){g.Vm(a,b);
g.r("yt.www.report.reportvideo.init")(!0)},Hpa=function(a){var b=g.x("action-panel-transcript");
g.r("yt.www.watch.transcript.open")(function(){g.S("watch-actions-transcript-loading");g.Q(g.x("watch-actions-transcript"))});
g.Dp(b,"panel-loaded","true");hV(a,"action-panel-transcript")},hV=function(a,b){var c=g.x(a.D),d=g.x(b),e=a.F;
b==a.D?g.Q(c):(g.Q(e),a.D=b,g.S(c),g.Q(d))},Fpa=function(a,b){return g.Ga(g.J("action-panel-trigger",a.J),function(a){a=g.E(a,"trigger-for");
return b.id==a})},Ppa=function(){if(jV=g.x("watch7-preview"))g.oE(),kV.push(g.P(jV,"click",Kpa,"watch-queue-preview-playlist-checkbox")),kV.push(g.P(jV,"click",Lpa,"preview-play-now-button")),kV.push(g.P(jV,"click",Mpa,"preview-play-all-now-button")),kV.push(g.P(jV,"click",lV,"preview-addto-queue-button")),kV.push(g.P(jV,"click",Npa,"preview-addto-queue-button-success")),kV.push(g.P(jV,"click",lV,"preview-addto-queue-button-error")),kV.push(g.P(null,"click",Opa,"watch-queue-preview-menu-choice")),
mV.push(g.Jf("watch-queue-show",function(){nV()?oV():g.S(jV)})),mV.push(g.Jf("watch-queue-hide",function(){g.ry()||g.S(jV)})),mV.push(g.Jf("watch-queue-update",pV)),mV.push(g.Jf("watch-queue-empty",function(){nV()?oV():g.S(jV)})),g.tn(jV)&&qV(),(nV()||rV())&&oV(),sV=!0},qV=function(){g.D("LIST_ID")&&g.cp(jV,"preview-playlist-mode",!0);
tV=g.K("preview-play-loading",jV);uV=g.K("preview-play-now-button",jV);vV=g.K("preview-play-all-now-button",jV);wV=g.K("preview-addto-queue-button",jV);xV=g.K("preview-addto-queue-button-success",jV);yV=g.K("preview-addto-queue-button-error",jV);g.S(tV)},rV=function(){if(!uS())return!1;
var a=!g.tu("player-unavailable"),b=g.Aw()?g.vw("yt-remote-session-video-id"):"";return a&&!(b==g.D("VIDEO_ID")&&!g.D("LIST_ID"))},oV=function(){if(!g.tu(jV)){var a=g.D("VIDEO_ID",void 0),b=g.D("LIST_ID",void 0);
g.tn(jV)?(zV(),pV(),g.S(tV),AV()?(g.S(uV),g.Q(vV)):(g.S(vV),g.Q(uV)),g.Q(jV)):(a={action_get_watch_queue_preview:1,v:a},b&&(a.list=b),g.G("/watch_queue_ajax",{method:"GET",za:a,onSuccess:Qpa}))}},AV=function(){return g.B(jV,"preview-playlist-mode")},pV=function(){if(g.tn(jV)&&!AV()){var a=g.AE();
a=g.Ia(a,g.D("VIDEO_ID",void 0));g.su(xV,a);g.su(wV,!a);g.S(yV)}},Kpa=function(a){g.cp(jV,"preview-playlist-mode",a.currentTarget.checked);
AV()?(g.Q(vV),g.Q(wV),g.S(xV),g.S(yV),g.S(uV)):(g.Q(uV),g.S(vV),pV())},Lpa=function(){g.Q(tV);
g.S(uV);g.F("watch-queue-addto-video-play-now",g.D("VIDEO_ID",void 0))},Mpa=function(){g.Q(tV);
g.S(vV);g.F("watch-queue-addto-playlist-play-now",g.D("LIST_ID",void 0),g.D("VIDEO_ID",void 0),BV())},lV=function(){var a=g.D("VIDEO_ID",void 0),b=g.D("LIST_ID",void 0),c=BV();
if(AV()){a=function(){g.Q(xV);g.S(wV);g.S(yV);g.F("watch-queue-addto-playlist-added")};
var d=function(){g.Q(yV);g.S(xV);g.S(wV)};
c?g.tE(c,a,d):g.xE(b,a,d)}else g.tE(a,function(){g.Q(xV);g.S(wV);g.S(yV);g.F("watch-queue-addto-video-added")},function(){g.Q(yV);
g.S(xV);g.S(wV)})},Npa=function(){var a=g.D("VIDEO_ID",void 0);
AV()?g.yE(function(){g.Q(wV);g.S(xV);g.S(yV);g.F("watch-queue-addto-playlist-removed")},function(){g.Q(yV);
g.S(xV);g.S(wV)}):g.wE(a,function(){g.Q(wV);
g.S(xV);g.S(yV);g.F("watch-queue-addto-video-removed")},function(){g.Q(yV);
g.S(xV);g.S(wV)})},Opa=function(a){var b=g.E(a.currentTarget,"action");
Rpa[b](a.currentTarget)},zV=function(){var a=uS();
if(a){var b=g.K("video-receiver",jV);b&&g.L(b,a.name)}},Qpa=function(a,b){if(jV&&!g.tn(jV)&&a.responseText&&b.html){var c=g.$p(b.html);
g.sc(jV);jV.appendChild(c);qV();nV()?(zV(),pV(),g.Q(jV)):g.S(jV)}},nV=function(){var a=!g.tu("player-unavailable"),b=wS();
b=vS()&&0==b;return a&&g.Ej()&&(b||rV())},BV=function(){var a;
(a=g.D("LIST_ID"))?(a=a.substr(0,2),a="PL"!=a&&"RD"!=a):a=!1;if(!a)return null;a=OU();if(!a)return null;a=a.video;for(var b=[],c=0;c<a.length;c++)b.push(a[c].encrypted_id);return b},DV=function(a){if(!(a.metaKey||a.ctrlKey||CV(a.target)||CV(window.document.activeElement)||a.event&&!1===a.event.returnValue))switch(a.keyCode){case 191:break;
default:g.Lf("player-unhandled-keydown",a)}},CV=function(a){return a&&("INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"EMBED"==a.tagName||a.isContentEditable)?!0:!1},Ypa=function(){if(!EV){var a=g.r("ytplayer.config");
if(a&&(EV=g.pj("player-api")||g.nj("player-api",a))){a=EV;a.addEventListener("onReady",FV);a.addEventListener("onStateChange",GV);a.addEventListener("onVideoProgress",HV);a.addEventListener("SHARE_CLICKED",IV);a.addEventListener("SIZE_CLICKED",JV);a.addEventListener("onError",KV);a.addEventListener("onFullscreenChange",LV);a.addEventListener("onAdStart",MV);a.addEventListener("onAdComplete",Spa);a.addEventListener("onAdSkip",Tpa);a.addEventListener("onAdEnd",Upa);a.addEventListener("onAutonavChangeRequest",
NV);a.addEventListener("onAutonavPauseRequest",OV);a.addEventListener("onFeedbackStartRequest",PV);a.addEventListener("onFeedbackArticleRequest",QV);a.addEventListener("onScreenChanged",RV);a.addEventListener("onLogClientVeCreated",SV);a.addEventListener("onLogServerVeCreated",TV);a.addEventListener("onLogToGel",UV);a.addEventListener("onLogVeClicked",VV);a.addEventListener("onLogVesShown",WV);a.addEventListener("onYpcContentRequest",XV);a.addEventListener("onReady",YV);g.$f("player_external_control_on_classic_desktop")&&
a.addEventListener("onPlayVideo",ZV);EV.isReady()&&YV();a=window.document.activeElement;var b=g.x("movie_player");a&&a!=window.document.body||!b||b.focus();$V();aW=g.Cf($V,1E3);bW.push(g.Jf("navigate",Vpa));bW.push(g.Jf("player-unhandled-keydown",Wpa));bW.push(g.Jf("watch-list-change",Xpa));cW(Jna);cW(Gna)}}},Xpa=function(){var a=EV;
if(a&&a.isReady()){var b;g.$f("player_external_control_on_classic_desktop")&&(b=OU());a.updatePlaylist(b)}},Zpa=function(a,b){var c=dW();
if(c){var d=g.qh.get(""+c,"").split(",");d=(0,g.Wi)(d,function(b){return 0!=b.indexOf(a)&&!!b.length});
4<=d.length&&d.shift();d.push(a+":"+b);g.rh(c,d.join(","),1814400)}},$pa=function(a){var b=dW();
if(b){var c=g.qh.get(""+b,"").split(",");c=(0,g.Wi)(c,function(b){return 0!=b.indexOf(a)});
0==c.length?g.sh(b):g.rh(b,c.join(","),1814400)}},eW=function(a){var b=g.CG();
if(b&&b.isReady()){a&&g.uf("RESUME_COOKIE_NAME",a);a=g.D("VIDEO_ID",void 0);var c=b.getDuration();b=Math.floor(b.getCurrentTime());0==c||120>=b||b+120>=c?$pa(a):Zpa(a,Math.floor(b))}},FV=function(a){fW(a);
gW(a.getPlayerState());var b=g.D("RELATED_PLAYER_ARGS",void 0);a&&a.updateVideoData&&b&&a.updateVideoData(b)},GV=function(a){1==a&&fW(EV);
gW(a);g.F("player-state-change",a)},HV=function(a){g.F("player-video-progress",a)},fW=function(a){g.F("player-quality-data-update",a.getAvailableQualityLevels())},KV=function(a){g.F("player-error",a)},LV=function(a){if(!(a.fullscreen||g.$f("player_unified_fullscreen_transitions")&&"html5"==EV.getPlayerType())){var b=g.D("VIDEO_ID"),c=b==a.videoId;
b&&!c&&(b=g.jg(window.location.href,{v:a.videoId,list:a.listId}),a.time&&(b=sS(b,{t:a.time})),g.Jj=a,g.ji(b))}},JV=function(a){g.Kq();
g.rh("wide",a?"1":"0",-1);g.F("player-resize",a)},IV=function(){g.F("player-share")},XV=function(a){var b=EV;
b&&b.isReady()&&b.pauseVideo();(b=g.x("watch-checkout-offers"))&&g.ni(g.EL,new g.yD(b,a))},MV=function(a){g.F("player-ad-start",a)},UV=function(a){var b=a.payload_name;
a=a.payload;b&&a&&g.zh(b,a)},SV=function(a){var b=a.id,c=g.Th(),d=g.Sh();
a=a.ve_type;var e=aqa++;a=new g.Bh({veType:a,veCounter:e,elementIndex:void 0,dataElement:void 0,youtubeData:void 0});hW[b]=a;c&&d&&g.qq(c,d,a)},RV=function(a){var b=a.csn;
a=a.root_ve_type;if(b&&a&&(Kna(b,a),a=g.Sh()))for(var c in hW){var d=hW[c];d&&g.qq(b,a,d)}},TV=function(a){hW[a.id]=g.oq(a.tracking_params)},VV=function(a){var b=g.Th();
a=hW[a.id];b&&a&&g.sq(b,a,void 0,void 0)},WV=function(a){a=a.ids;
for(var b=g.Th(),c=0;c<a.length;c++){var d=hW[a[c]];b&&d&&g.rq(b,d)}},YV=function(){var a=EV;
a&&a.startInteractionLogging&&a.startInteractionLogging()},Spa=function(){g.F("player-ad-complete")},Tpa=function(){g.F("player-ad-skip")},Upa=function(){g.F("player-ad-end")},NV=function(a){g.F("player-autonav-change-request",a)},OV=function(a){g.F("player-autonav-pause-request",a)},cW=function(a){iW?a():(a=g.Jf("player-playback-start",a),bW.push(a))},Wpa=function(a){var b=EV;
b&&b.handleGlobalKeyDown(a.keyCode,a.shiftKey)},jW=function(a,b){var c=EV;
if(c&&(sV?!g.tu(jV):!rV())){var d=null!=b?b:!0;c.seekTo(a,!0);d&&window.scroll(0,0);2==c.getPlayerState()&&c.playVideo()}},$V=function(){if(EV&&EV.isReady()){var a=window.location.hash;
if(a!=kW){kW=a;a=g.Hp(a);if("t"in a&&a.t!=lW.t){var b=a.t,c=0;-1!=b.indexOf("h")&&(b=b.split("h"),c=3600*b[0],b=b[1]);-1!=b.indexOf("m")&&(b=b.split("m"),c=60*b[0]+c,b=b[1]);-1!=b.indexOf("s")?(b=b.split("s"),c=1*b[0]+c):c=1*b+c;jW(c,!1)}lW=a}}},Vpa=function(){g.Ef(aW)},gW=function(a){iW||1!=a&&2!=a&&0!=a||(iW=!0,g.F("player-playback-start"))},dW=function(){return g.D("RESUME_COOKIE_NAME",void 0)},PV=function(a){g.hC(void 0,a)},QV=function(a){g.jC(a.articleId,a.helpContext,a.productData)},ZV=function(a){var b=
g.ig("/watch",{v:a.videoId,
list:a.listId},!1);g.ji(b,a.sessionData)},bqa=function(a,b){var c=g.Uc("/related_ajax",{continuation:a,
action_more_related_videos:1});window.spf.load(c,{onDone:b})},cqa=function(a){var b=a.currentTarget.href,c=g.CG();
if(c){var d=g.Gp(b).v;g.D("VIDEO_ID")==d&&(d=g.E(a.currentTarget,"secondary-video-url"),0==c.getPlayerState()&&d?g.cc(a.currentTarget,d):g.cc(a.currentTarget,sS(b,{t:Math.floor(c.getCurrentTime())})))}},dqa=function(a){var b=a.currentTarget;
a=g.E(b,"action");if(b&&"replace-enclosing-action"==a){mW(b);a=g.K("service-endpoint-replace-enclosing-action-notification",g.vn(b));var c=g.vz(b)||b,d=g.M(c,"related-list-item");(b=g.K("related-item-dismissable",d))&&c&&((c=g.K("related-item-dismissed-container",d))&&a&&(g.sc(c),g.mn(c,a)),g.S(b),g.Q(c),g.Q(a),g.Gn(d,!0),d.focus())}},eqa=function(a){a=a.currentTarget;
mW(a);a=g.M(a,"related-list-item");g.Q(g.K("related-item-dismissable",a));g.S(g.K("related-item-dismissed-container",a))},mW=function(a){var b=g.E(a,"dismissal-token"),c=g.E(a,"feedback-token");
a={itct:g.E(a,"innertube-clicktracking")};var d="";b?(d="action_dismiss_item",a.dismissal_token=b,g.D("DISMISS_THROUGH_IT")&&(a.it=1)):c&&(d="action_give_feedback",a.feedback_tokens=[c],a.wait_for_response=1);d&&g.G("/feed_change_ajax?"+d+"=1",{method:"POST",onSuccess:function(){},
ha:a,nb:!0})},oW=function(a){return-1!=(nW.get("dismissedEvents",!0)||[]).indexOf(a)},fqa=function(){var a=pW;
if(!oW(a)){var b=nW.get("dismissedEvents",!0)||[];b.push(a);nW.set("dismissedEvents",b,void 0,!0)}g.S(qW);g.O(window.document.body,"gaming-event-promo-visible")},gqa=function(){var a=g.x("live-chat-iframe");
if(a){var b=new g.RK;b.La(a);rW=b}},kqa=function(){var a=g.x("player-messages"),b=hqa=g.K("mealbar-promo-renderer",a);
if(b){var c=g.tc(b),d=g.x("watch-header")||g.x("watch-metadata-header");d&&d.appendChild(c);g.DF(b);g.MF(b);sW=new g.aA(b,!1,!1,!0,!0,!0);tW.push(g.H(g.K("dismiss-menu-choice",b),"click",iqa,!0))}uW=g.K("mealbar-visibility",a);jqa()},jqa=function(){var a=uW,b=g.E(a,"trigger-condition");
"TRIGGER_CONDITION_POST_AD"==b?((a=g.E(a,"lact-th"))&&(vW=(0,window.parseInt)(a,10)),wW.push(g.Jf("player-ad-end",function(){xW(!0)}))):"TRIGGER_CONDITION_DEFAULT"==b?xW(!1):"TRIGGER_CONDITION_DELAYED"==b&&(a=g.E(a,"prompt-del-sec"))&&(a=(0,window.parseInt)(a,0),0<a&&(yW=g.Jf("player-video-progress",lqa),zW=a))},iqa=function(){sW&&sW.dismiss("cancel")},xW=function(a){if(a&&(a=vW,-1<a&&g.lh()<a))return;
sW&&sW.show();g.N(uW,"vve-check");g.uv()},lqa=function(a){0<zW&&a>zW&&(xW(!1),g.Kf(yW),zW=-1)},AW=function(){this.F=[];
this.C=0;this.F.push(g.Jf("page-resize",this.xG,this));this.F.push(g.Jf("player-resize",this.En,this));this.F.push(g.Jf("player-quality-data-update",this.XG,this));this.F.push(g.Jf("watch-queue-remote-connection",this.ys,this));g.Ej()&&this.ys(!0);this.Jg()},nqa=function(){var a=g.CG();
a&&a.getPlayerState&&1==a.getPlayerState()?g.ZC():BW.push(g.Jf("player-state-change",mqa))},mqa=function(a){1==a&&g.ZC()},rqa=function(){Ypa();
g.Xf()?CW.push(g.Sf(g.Jq)):cW(g.Jq);var a=g.K("watch-action-buttons"),b=g.K("watch-action-panels");DW=null;a&&b&&(DW=new fV(a,b));if(a=g.K("video-metadata-renderer"))EW=new OT,EW.La(a);if(a=g.K("like-button-renderer"))FW=new g.tK,FW.La(a);if(a=g.K("donate-button-renderer"))GW=new NT,GW.La(a);epa();if(a=g.K("metadata-updateable-viewership"))b=g.Dr(window.location.href).C.get("ut",""),HW=new dU(g.D("VIDEO_ID"),null,b),HW.La(a);IW=new AW;g.jh();g.xl("ytglobal.ytUtilActivityCallback_",function(){g.F("USER_ACTIVE")});
g.H(window.document,"keydown",DV);oqa();cpa();g.D("SKIP_RELATED_ADS")||(g.Xf()?CW.push(g.Tf(wT)):wT());g.K("youthere-data")&&lpa();kqa();wpa();g.D("FACEBOOK_TOKEN_REFRESH_ENABLED")&&Zoa();JW.push(g.P(g.x("watch7-sidebar"),"click",cqa,"resumable-list"));JW.push(g.P(window.document.documentElement,"click",dqa,"dismiss-menu-choice"));JW.push(g.P(window.document.documentElement,"click",eqa,"undo-replace-action"));nqa();Ppa();g.pl&&(!window.document.documentMode||8>window.document.documentMode)&&KW.push(g.P(window.document.body,
"click",pqa,"video-thumb"));g.aG();gqa();if(qW=g.x("gaming-event-promo-overlay"))if(pW=qW.getAttribute("data-event-id"))oW(pW)?g.S(qW):(g.Q(qW),g.N(window.document.body,"gaming-event-promo-visible")),LW.push(g.H(g.x("gaming-event-promo-cancel-button"),"click",fqa));qqa();g.iK.init();-1!=g.ag("service_worker_push_logged_out_prompt_watches")&&cW(opa)},pqa=function(a){g.Mn(a.target,"BUTTON")||a.currentTarget.click()},oqa=function(){var a=g.K("whitelist-alert");
a&&(MW=new g.LJ,MW.La(a))},qqa=function(){var a=g.Gp(window.location.href);
if(window.history.replaceState&&"time_continue"in a||"disable_polymer"in a)a=g.jg(window.location.href,{time_continue:null,disable_polymer:null}),window.history.replaceState(window.history.state,"",a)},sqa=function(){var a=["guide"];
NW.guide=g.Bf(function(){g.K("guide-module-loading")&&(g.Ig(OW.jz),PW(a,"time",!1))},3E3)},tqa=function(a){if(!g.x("watch-sidebar-discussion")){var b=g.x("watch-discussion");
if(g.wn(b)){g.N(b,"scrolldetect");g.Dp(b,"scrolldetect-callback","comments-delay-load");var c=(0,g.A)()+1E3;g.PC({"comments-delay-load":function(){var b=c-(0,g.A)();NW.comments=g.Bf(g.u(PW,a,0<b?"time":"scroll"),b)}})}}},PW=function(a,b,c){var d=g.D("VIDEO_ID",void 0);
d||g.La(a,"comments");if(a&&a.length){var e=g.Gp(window.location.href);e.v=d;e.tr=b;g.Ia(a,"comments")&&g.D("IS_DISTILLER")&&(e.distiller="1",g.D("COMMENTS_TOKEN")?e.ctoken=g.D("COMMENTS_TOKEN"):g.La(a,"comments"));g.tC(a,c,e,g.u(uqa,a))}},uqa=function(a){g.Ia(a,"comments")&&(g.iK.init(),(a=g.D("JS_COMMENTS_MODULE_NAMES"))&&window.spf.script.require(a),g.F("yt-www-comments-page-updated"))},Ioa={"AMP-CAROUSEL":"ac",
"AMP-FX-FLYING-CARPET":"fc","AMP-LIGHTBOX":"lb","AMP-STICKY-AD":"sa"},una=[/^https?:\/\/(secure)?pubads\.g\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(googleads|adx)\.g\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(?!adx)ad.*\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(tpc|pagead2)\.googlesyndication\.com(:\d+)?($|\/)/i,/^https?:\/\/www\.googletagservices\.com(:\d+)?($|\/)/i,/^https?:\/\/adservice\.google\.(com?\.)?[a-z]{2,3}(:\d+)?($|\/)/i],dS=null;g.ea(fS,YR);
var gS=null,Ana={QR:5,hR:7,jS:17,EQ:19,VP:41,fR:48,aW:62,TU:67,TV:69,LY:74,oX:79,mW:82,nW:83,ZU:87,xW:88,qQ:89,eV:90,FQ:103,bP:104,RR:106,NY:107,tR:108,UU:114,VU:116,HV:118,tP:119,RU:121,SU:122,QU:123,MO:124,cX:125,KY:126,aP:127},kS=null,lS=null,Joa={sQ:"21060548",ENABLED:"21060549"},mS={},Fna=[],oS=!1,rS=!1,pS=0,qS="",aqa=1;var QW={},zS=(QW.google_ad_channel="channel",QW.google_ad_type="ad_type",QW.google_ad_format="format",QW.google_color_bg="color_bg",QW.google_color_border="color_border",QW.google_color_link="color_link",QW.google_color_text="color_text",QW.google_color_url="color_url",QW.google_page_url="url",QW.google_allow_expandable_ads="ea",QW.google_ad_section="region",QW.google_cpm="cpm",QW.google_encoding="oe",QW.google_safe="adsafe",QW.google_flash_version="flash",QW.google_font_face="f",QW.google_font_size=
"fs",QW.google_hints="hints",QW.google_ad_host="host",QW.google_ad_host_channel="h_ch",QW.google_ad_host_tier_id="ht_id",QW.google_kw_type="kw_type",QW.google_kw="kw",QW.google_contents="contents",QW.google_targeting="targeting",QW.google_adtest="adtest",QW.google_alternate_color="alt_color",QW.google_alternate_ad_url="alternate_ad_url",QW.google_cust_age="cust_age",QW.google_cust_ch="cust_ch",QW.google_cust_gender="cust_gender",QW.google_cust_interests="cust_interests",QW.google_cust_job="cust_job",
QW.google_cust_l="cust_l",QW.google_cust_lh="cust_lh",QW.google_cust_u_url="cust_u_url",QW.google_cust_id="cust_id",QW.google_language="hl",QW.google_city="gcs",QW.google_country="gl",QW.google_region="gr",QW.google_available_width="avail_w",QW.google_content_recommendation_ad_positions="ad_pos",QW.google_content_recommendation_columns_num="cr_col",QW.google_content_recommendation_rows_num="cr_row",QW.google_content_recommendation_ui_type="crui",QW.google_color_line="color_line",QW.google_disable_video_autoplay=
"disable_video_autoplay",QW.google_full_width_responsive_allowed="fwr",QW.google_full_width_responsive="fwrattr",QW.efwr="efwr",QW.fwifhbc="fwifhbc",QW.google_pgb_reactive="pra",QW.google_resizing_allowed="rs",QW.google_resizing_height="rh",QW.google_resizing_width="rw",QW.google_responsive_formats="resp_fmts",QW.google_safe_for_responsive_override="sfro",QW.google_video_doc_id="video_doc_id",QW.google_video_product_type="video_product_type",QW.google_webgl_support="wgl",QW),RW={},AS=(RW.google_ad_block=
"ad_block",RW.google_ad_client="client",RW.google_ad_output="output",RW.google_ad_callback="callback",RW.google_ad_height="h",RW.google_ad_resize="twa",RW.google_ad_slot="slotname",RW.google_ad_unit_key="adk",RW.google_ad_dom_fingerprint="adf",RW.google_ad_width="w",RW.google_analytics_url_parameters="aup",RW.google_captcha_token="captok",RW.google_content_recommendation_ui_type="crui",RW.google_content_recommendation_columns_num="cr_col",RW.google_content_recommendation_rows_num="cr_row",RW.google_ctr_threshold=
"ctr_t",RW.google_cust_criteria="cust_params",RW.google_full_width_responsive="fwr_io",RW.gfwrnwer="fwrn",RW.gfwrnher="fwrnh",RW.google_image_size="image_size",RW.google_last_modified_time="lmt",RW.google_loeid="loeid",RW.google_max_num_ads="num_ads",RW.google_max_radlink_len="max_radlink_len",RW.google_mtl="mtl",RW.google_native_settings_key="nsk",RW.google_enable_content_recommendations="ecr",RW.google_infinite_scroll_slot_type="ifsl",RW.google_num_radlinks="num_radlinks",RW.google_num_radlinks_per_unit=
"num_radlinks_per_unit",RW.google_pucrd="pucrd",RW.google_reactive_plaf="plaf",RW.google_reactive_plat="plat",RW.google_reactive_fba="fba",RW.google_reactive_sra_channels="plach",RW.google_responsive_auto_format="rafmt",RW.google_rl_dest_url="rl_dest_url",RW.google_rl_filtering="rl_filtering",RW.google_rl_mode="rl_mode",RW.google_rt="rt",RW.google_source_type="src_type",RW.google_sui="sui",RW.google_tag_for_child_directed_treatment="tfcd",RW.google_tag_for_under_age_of_consent="tfua",RW.google_tag_origin=
"to",RW.google_tfs="tfs",RW.google_package="pwprc",RW.google_tag_partner="tp",RW.fra="fpla",RW),SW={},BS=(SW.google_core_dbp="dbp",SW.google_lact="lact",SW.google_only_pyv_ads="pyv",SW.google_scs="scs",SW.google_video_url_to_fetch="durl",SW.google_yt_pt="yt_pt",SW.google_yt_up="yt_up",SW);var IS={Bv:1,Cv:2,xR:8,AW:9,vW:16,EP:26,xP:27,Fv:30,VR:32},vqa={eP:{name:"adFormat",Od:g.ua},dP:{name:"adClient",Od:/^[a-z0-9-]+$/i},gP:{name:"adTest",Od:/^on$/i},oW:{name:"reqSrc",Od:g.ua},XV:{name:"pubVars",Od:null},fP:{name:"adKey",Od:g.ua},eR:{name:"enabledInAsfe",Od:g.ta}},TW=[{name:"google_ad_channel",Od:{predicate:/^[a-z0-9_-]+$/i,nullOnInvalid:!0}},{name:"google_reactive_sra_index",Od:{predicate:g.ua,nullOnInvalid:!0}},{name:"google_ad_unit_key",Od:{predicate:g.ua,nullOnInvalid:!0}}];var ES={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1},Tna=/(corp|borg)\.google\.com:\d+$/;GS.prototype.getVerifier=function(a){return this.F?this.F[a]:null};
GS.prototype.getSchema=function(a){return this.C?this.C(a):null};
GS.prototype.doesReturnAnotherSchema=function(){return this.C?!0:!1};var XS=728*1.35;g.h=NS.prototype;g.h.add=function(a){this.C[a]=!0;this.F[a]=a};
g.h.remove=function(a){this.C[a]=!1;this.F[a]=void 0};
g.h.removeAll=function(){this.C={};this.F={}};
g.h.contains=function(a){return!!this.C[a]};
g.h.Eb=function(){var a=[],b;for(b in this.C)this.C[b]&&this.C.hasOwnProperty(b)&&a.push(this.F[b]);return a};new NS;var OS=window.navigator,Koa=/^\s*_ga=\s*1\.(\d+)[^.]*\.(.*?)\s*$/,Loa=/^[^=]+=\s*GA1\.(\d+)[^.]*\.(.*?)\s*$/,Moa=/^\s*_ga=\s*()(amp-[\w.-]{22,64})$/;var roa=g.Lk||g.yd||g.C&&g.wb(11)||g.Jk,qoa=g.yd&&"srcdoc"in g.jn("IFRAME");var doa={Cv:"google_anchor_debug",Bv:"google_bottom_anchor_debug",UR:"google_ifsl_debug",WR:"google_inflate_debug",bS:"google_ia_debug",SR:"google_scr_debug",cS:"google_ia_debug_allow_onclick",nS:"google_lat_debug",oS:"google_lat_debug_all",GU:"google_native_debug",aV:"googleads",Fv:"google_pedestal_debug",qW:"google_resize_debug",KW:"google_shoppable_images_debug",LW:"google_shoppable_images_cookie",MW:"google_shoppable_images_forced",iX:"google_supersize_debug",OY:"google_visible_intentful_click",
IW:"google_server_side_slot_resize",HW:"google_server_side_expand_anchor",HU:"google_native_instant_preview",tW:"google_responsive_slot_debug",uW:"google_responsive_slot_preview"},UW={},eoa=(UW.google_bottom_anchor_debug=1,UW.google_anchor_debug=2,UW.google_ia_debug=8,UW.google_resize_debug=16,UW.google_ifsl_debug=32,UW.google_scr_debug=9,UW.googleads=2,UW.google_server_side_expand_anchor=1,UW.google_pedestal_debug=30,UW),VW={},RS=(VW.google_server_side_slot_resize=1,VW.google_server_side_expand_anchor=
4,VW);var hT=null;var US={},VS=null;US.le=0;US.nt=2;US.Fr=3;US.Po=5;US.me=1;US.om=4;(function(a){function b(a){a.Od&&(c[a.name]=a.Od)}
var c={msg_type:/^[a-zA-Z0-9_-]+$/};MR(vqa,b);for(var d=0;d<TW.length;d++)b(TW[d]);for(d=0;d<a.length;d++)b(a[d]);return new GS(c)})([]);var $na={1:"<<<DISABLE_IFRAME_ON_COPY_FRACTION>>>",9:"<<<RESPONSIVE_LINK_UNIT_HEIGHT_LIMIT_LOWER>>>",10:"<<<RESPONSIVE_LINK_UNIT_HEIGHT_LIMIT_WIDTH>>>",11:"<<<TOO_WIDE_AD_RESIZE_HOLDBACK_FRACTION>>>",12:"<<<SHOW_ADS_SINGLE_LOAD_FRACTION>>>",13:"<<<LATENCY_REPORTING_FRACTION>>>",14:"<<<RELAX_MOBILE_ATF_RESPONSIVE_HEIGHT_LOWER>>>",15:"<<<RELAX_MOBILE_ATF_RESPONSIVE_HEIGHT_WIDTH>>>",19:"<<<ALWAYS_USE_HTTPS_CHINA_EXP_FRACTION>>>",22:"<<<JS_RNG_EXP_FRACTION>>>",23:"<<<PRERENDERING_DELAYED_IMPRESSION_EXP_FRACTION>>>",
24:"<<<ENABLE_CMS_DETECTION_EXP_FRACTION>>>",27:"<<<REACTIVE_MESSAGE_VERIFICATION_FRACTION>>>",28:"<<<OSD_ACTIVEVIEW_MEASURABLE_FRACTION>>>",29:"<<<PAGE_LATENCY_REPORTING_FRACTION>>>",34:"<<<SANDBOX_IFRAME_FRACTION>>>",37:"<<<PREDICTIVE_REACTIVE_SRA_FRACTION>>>",40:"<<<ENABLE_SRA_EXP_FRACTION>>>",43:"<<<VIGNETTE_ON_TABLETS_FRACTION>>>",47:"<<<PAGE_VISIBILITY_UNKNOWN_FRACTION>>>",56:"<<<LEAN_ERROR_REPORTING_FRACTION>>>",60:"<<<REAL_USER_MONITORING_FRACTION>>>",66:"<<<REAL_USER_MONITORING_WITH_FLAGS_FRACTION>>>",
67:"<<<DEPRECATE_IE89_FOR_AV_FRACTION>>>",74:"<<<ADSENSE_GET_LIMIT_FRACTION>>>",76:"<<<IDENTITY_TOKEN_FRACTION>>>",77:"<<<MUTSU_ALLOW_EXTERNAL_ENABLED>>>",78:"<<<SANDBOX_IFRAME_CHROME_58_NON_DESKTOP_FRACTION>>>",79:"<<<CONTENT_RECOMMENDATION_PEDESTAL_MAX_WIDTH>>>",82:"<<<VIEW_OPTIMIZED_MOBILE_SCALING_FACTOR>>>",83:"<<<SAFARI_11_IDENTITY_TOKEN_FRACTION>>>",92:"<<<PRECONNECT_AD_DOMAIN_FRACTION>>>",96:"<<<FIXED_SIZE_TO_AUTO_RESPONSIVE_SLOT_MOD_LOWER>>>",97:"<<<FIXED_SIZE_TO_AUTO_RESPONSIVE_SLOT_MOD_WIDTH>>>",
98:"<<<FULL_WIDTH_RESPONSIVE_ELIGIBILITY_FRACTION>>>",99:"<<<FULL_WIDTH_RESPONSIVE_CORE_MOD_LOWER>>>",100:"<<<FULL_WIDTH_RESPONSIVE_CORE_MOD_WIDTH>>>",103:"<<<OSD_START_ON_ELEMENT_LOADED_FRACTION>>>",105:"<<<FULL_WIDTH_RESPONSIVE_FOR_FULL_WIDTH_AND_IGNORING_FORMAT_HINTS_MOD_LOWER>>>",106:"<<<FULL_WIDTH_RESPONSIVE_FOR_FULL_WIDTH_AND_IGNORING_FORMAT_HINTS_MOD_WIDTH>>>",107:"<<<OSD_UNSUPPORT_JS_ADS_FRACTION>>>",108:"<<<RESPONSIVE_LINK_UNIT_FULL_WIDTH_MOD_LOWER>>>",109:"<<<RESPONSIVE_LINK_UNIT_FULL_WIDTH_MOD_WIDTH>>>",
111:"<<<SANDBOX_IFRAME_TOP_NAVIGATION_USER_GESTURE_FRACTION>>>",112:"<<<SANDBOX_IFRAME_POPUPS_ESCAPE_SANDBOX_FRACTION>>>",114:"<<<PLA_SRA_DELAY_FRACTION>>>",115:"<<<SHOW_ADS_SINGLE_LOAD_MOD_LOWER>>>",116:"<<<SHOW_ADS_SINGLE_LOAD_MOD_WIDTH>>>",117:"<<<AMP_CANONICAL_URL_FRACTION>>>",118:"<<<DISABLE_LAZY_LOAD>>>",120:"<<<FIXED_SIZE_TO_AUTO_RESPONSIVE_SLOT_HOLDBACK_MOD_LOWER>>>",121:"<<<FIXED_SIZE_TO_AUTO_RESPONSIVE_SLOT_HOLDBACK_MOD_WIDTH>>>",122:"<<<RELAX_MOBILE_ATF_RESPONSIVE_HEIGHT_FULL_LAUNCH>>>",
123:"<<<OSD_INITIALIZE_ON_ADBLOCK_REGISTER_FRACTION>>>",124:"<<<OSD_INITIALIZE_STRATEGY_TO_UNKNOWN_FRACTION>>>",125:"<<<OSD_AD_LOADED_DEFAULT_FALSE_FRACTION>>>",126:"<<<ACTIVE_VIEW_MEASUREMENT_STRATEGY_VERIFICATION_FRACTION>>>",127:"<<<SRA_PEDESTAL_FRACTION>>>",128:"<<<SHOULD_USE_IAB_CMPS>>>",129:"<<<USE_IAB_CMPS_EXP_FRACTION>>>",130:"<<<STANDALONE_SLOT_VARS_FRACTION>>>",131:"<<<IN_IAB_CMP_GRACEPERIOD>>>",133:"<<<ADSENSE_GDPR_PAUSE_FRACTION>>>",134:"<<<FULL_WIDTH_RESPONSIVE_ATTRIBUTE_FRACTION>>>",
135:"<<<RUM_ENABLE_PPRUE_COLLECTION_FRACTION>>>",136:"<<<FULL_WIDTH_MANUAL_RESPONSIVE_DISABLED_FRACTION>>>"};var YS=null;var WW={},goa=(WW[16]=4,WW[27]=512,WW[26]=128,WW[32]=16,WW);var lT={"image-top":0,"image-middle":1,"image-side":2,"text-only":3,"in-article":4};var jT;g.h=ZS.prototype;g.h.Zw=function(a,b){0!=this.C||0!=this.G.length||b&&b!=window?this.To(a,b):(this.C=2,this.Ft(new bT(a,window)))};
g.h.To=function(a,b){this.G.push(new bT(a,b||this.F));$S(this)};
g.h.cJ=function(a){this.C=1;if(a){var b=bS(188,(0,g.t)(this.Dt,this,!0));this.D=this.F.setTimeout(b,a)}};
g.h.Dt=function(a){a&&++this.H;1==this.C&&(null!=this.D&&(this.F.clearTimeout(this.D),this.D=null),this.C=0);$S(this)};
g.h.YL=function(){return!(!window||!Array)};
g.h.Qy=function(){return this.H};
g.h.mM=function(){if(0==this.C&&this.G.length){var a=this.G.shift();this.C=2;var b=bS(190,(0,g.t)(this.Ft,this,a));a.Mg.setTimeout(b,0);$S(this)}};
g.h.Ft=function(a){this.C=0;a.lc()};
ZS.prototype.nq=ZS.prototype.Zw;ZS.prototype.nqa=ZS.prototype.To;ZS.prototype.al=ZS.prototype.cJ;ZS.prototype.rl=ZS.prototype.Dt;ZS.prototype.sz=ZS.prototype.YL;ZS.prototype.tc=ZS.prototype.Qy;var moa="adsafe channel client description_url durl google_ad_channel h h_ch iu kfa page_slots prev_ius prev_slotnames slotname tfcd video_url_to_fetch w".split(" ");g.Ta("var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}");g.sb("script");var voa=/^blogger$/,woa=/^wordpress(.|\s|$)/i,xoa=/^joomla!/i,yoa=/^drupal/i,zoa=/\/wp-content\//,toa=/\/wp-content\/plugins\/advanced-ads/,uoa=/\/wp-content\/themes\/genesis/,iT=/\/wp-content\/plugins\/genesis/;for(var XW="margin-left margin-right padding-left padding-right border-left-width border-right-width".split(" "),YW=0;YW<XW.length;YW++);XW="margin-top margin-bottom padding-top padding-bottom border-top-width border-bottom-width".split(" ");for(var ZW=0;ZW<XW.length;ZW++);var kT=/[+, ]/,Coa=/YtLoPri/;g.v(mT,g.Zd);var WT={};mT.prototype.X=function(){mT.M.X.call(this);this.F&&(g.Td(this.F),this.F=null);this.D=this.C=null};
mT.prototype.G=function(){var a=g.nc(this.C);g.an(a,this.D)||(this.D=a,this.dispatchEvent("resize"))};var DW,EW,FW,GW,HW,IW,MW,oT,qT;g.h=nT.prototype;g.h.start=function(a){var b={start:0};b.end=a.scrollHeight-a.clientHeight;b.duration=b.end/3;b.Nh="linear";this.D=new g.Xu(a,b);this.C=!0;this.F.O(a,"click",this.gN);this.F.O(a,"mouseover",this.iN);this.F.O(a,"mouseout",this.fN);this.F.O(a,"scroll",this.hN)};
g.h.hN=function(){this.G||this.C||(this.D.pause(),this.G=!0)};
g.h.gN=function(){this.D.pause();this.C=!1;this.G=!0};
g.h.iN=function(){this.D.pause();this.C=!1};
g.h.fN=function(){this.C||this.G||(this.D.play(),this.C=!0)};
g.h.dispose=function(){this.F.removeAll();this.G=this.C=!1;this.D=null;this.H=!0};
g.h.ob=function(){return this.H};var GT="",HT="",KT=[],LT=!1,yT=[],rT=null,uT=!1,MT=0,zT=null,AT=null,BT=null,xT=!1;g.p("yt.www.watch.ads.setAdId",function(a){window.ad_debug=a},void 0);
g.p("yt.www.watch.ads.setCompanion",CT,void 0);g.p("yt.www.watch.ads.showForcedMpu",function(a){var b=DT(a);a=ET(a);CT(b,a)},void 0);
g.p("yt.www.watch.ads.setGutSlotSizes",function(a,b){if(zT){var c=zT.getSizes();g.Ll(c);b&&AT&&c.push(AT);a&&BT&&c.push(BT)}},void 0);
g.p("yt.www.watch.ads.handleSetCompanion",function(a){a=a.replace(";dc_seed=",";kmyd=watch-channel-brand-div;dc_seed=");var b=DT(a);a=ET(a);CT(b,a)},void 0);
g.p("yt.www.watch.ads.handleSetCompanionForFreewheel",FT,void 0);g.p("yt.www.watch.ads.handleSetAfvCompanionVars",sT,void 0);g.p("yt.www.watch.ads.companionSetupComplete",IT,void 0);g.p("yt.www.watch.ads.pauseVideo",JT,void 0);g.p("yt.www.watch.ads.loadAfc",vT,void 0);g.p("yt.www.watch.ads.isAfcAdVisible",function(){var a=g.x("google_companion_ad_div");return a?(a=g.tn(a))&&"IFRAME"==a.tagName?-1!=a.src.indexOf("youtube.com%2Fad_frame"):!1:!1},void 0);
g.p("yt.www.watch.ads.checkInit",tT,void 0);g.p("yt.www.watch.ads.initVideoWallCompanionListeners",function(a,b){GT=a;HT=b;window.addEventListener("message",function(a){"companion-setup-complete"==a.data?IT():"pause-video"==a.data&&JT()},!1)},void 0);
g.p("yt.www.watch.ads.getGlobals",function(){return yT},void 0);
g.p("window.google_ad_request_done",window.IZ,void 0);g.p("yt.www.ads.pyv.pyvWatchAfcCallback",g.zJ,void 0);g.p("yt.www.ads.pyv.loadPyvAjax",xS,void 0);g.p("yt.www.watch.ads.restrictioncookie.spr",function(a){g.di(a+"mac_204?action_fcts=1");return!0},void 0);
g.p("yt.www.watch.ads.isPromotionShelfSlotExist",function(){return null!=g.x("promotion-shelf")},void 0);
g.p("yt.www.watch.ads.promotionShelfClear",function(){var a=g.x("promotion-shelf");a&&(g.N(a,"hid"),g.sc(a))},void 0);
g.p("yt.www.watch.ads.promotionShelfShow",function(a){var b=g.x("promotion-shelf");b&&(b.appendChild(a),g.O(b,"hid"))},void 0);
g.p("yt.www.watch.ads.addInstreamCompanionWtaUi",function(a){var b=g.x("google_companion_ad_div");if(b){if(g.K("iv-cards-companion",b)){if(!g.$f("desktop_shopping_companion_wta_support"))return}else if(g.K("iv-website-companion",b)){if(!g.$f("desktop_action_companion_wta_support"))return}else if(g.dn("iframe",null,b)){var c=g.dn("iframe",null,b);if(c.src&&-1!=c.src.indexOf("ad_companion")){if(!g.$f("desktop_videowall_companion_wta_support"))return}else if(!g.$f("desktop_image_companion_wta_support"))return}c=
g.K("iv-cards-companion",b)||g.K("iv-website-companion",b)||b;g.N(b,"companion-with-wta");c.appendChild(a)}else g.wf(Error("Cannot find google_companion_ad_div"))},void 0);
g.p("setFreewheelCompanion",FT,void 0);g.p("setAfvCompanionVars",sT,void 0);g.v(NT,g.U);NT.prototype.Z=function(){NT.M.Z.call(this);this.D=g.K("donate-button",this.L());g.Cy(this,"click","donate-button",this.G)};
NT.prototype.G=function(){var a=g.E(this.D,"tip-params"),b=g.r("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams");b&&(g.Hj().pauseVideo(),b("T",a))};g.v(OT,g.U);g.h=OT.prototype;g.h.Z=function(){OT.M.Z.call(this);this.D=this.T("video-metadata-renderer-panel");this.J=g.E(this.Ud(),"video-id");var a=g.K("playlist-header-content",g.x("watch-appbar-playlist"));this.Y=a?g.E(a,"full-list-id"):"";g.Cy(this,"click","video-metadata-renderer-button",this.yz)};
g.h.X=function(){OT.M.X.call(this);PT(this);this.Y=this.J="";this.D=null};
g.h.yz=function(a){a=g.E(a.currentTarget,"action");a in this.N&&(this.V!=a?(this.N[a](),g.Q(this.D),this.V=a):(g.S(this.D),this.D&&g.sc(this.D),PT(this),this.V=null))};
g.h.GL=function(){this.Gc||($oa(this),g.zy("share"))};
g.h.iL=function(){this.H||(g.fi(g.D("REPORTVIDEO_CSS",void 0)),g.Nf(g.D("REPORTVIDEO_JS",void 0),(0,g.t)(this.XB,this)))};
g.h.XB=function(){var a=0,b=g.CG();b&&b.pauseVideo()&&(b.pauseVideo(),a=b.getCurrentTime());a={action_get_report_video_component:1,video_id:this.J,t_mins:Math.floor(a)/60,t_secs:Math.floor(a)%60};"METADATA_LANGUAGE"in g.tf&&(a.metadata_language=g.D("METADATA_LANGUAGE"));g.G("/watch_ajax",{method:"GET",za:a,onSuccess:(0,g.t)(function(a,b){this.H=b.report_html;g.Vm(this.D,this.H);g.r("yt.www.report.reportvideo.init")(!0)},this),
nb:!0})};var QT=null,ST=0,RT=[];var VT=[];g.v(XT,g.sd);g.h=XT.prototype;g.h.bv=function(){if("compact"==ZT(this)){if("compact"==this.F)return;this.F="compact"}else this.F="expanded";bU(this)};
g.h.aO=function(a){this.V=a;this.bv()};
g.h.X=function(){this.N&&this.N.cancel();g.Ig(this.G);this.G.length=0;g.Kf(this.J);this.J.length=0;this.R&&this.R.abort();this.D&&(this.D.clearChart(),this.D=null);XT.M.X.call(this)};
g.h.load=function(a){this.G.push(g.H(this.la,"resize",(0,g.t)(this.bv,this)));this.J.push(g.Jf("player-resize",(0,g.t)(this.aO,this)));var b=g.x("stats-opt-out-chbox");b&&(this.Yl=!b.checked,this.G.push(g.H(b,"change",(0,g.t)(function(){fpa(this,!b.checked)},this))));
this.G.push(g.P(this.C,"click",(0,g.t)(function(a){$T(a.currentTarget,"mode-css");bU(this)},this),"stats-mode-button"));
this.G.push(g.P(this.C,"click",(0,g.t)(function(a){$T(a.currentTarget,"top-site-css");$T(a.currentTarget,"metric-css");bU(this)},this),"stats-bragbar"));
g.nB(g.cB);a&&(this.K=JSON.parse(a));this.H=g.K("stats-chart-gviz",this.C);bU(this)};
g.h.JF=function(){this.W=!0;bU(this)};g.v(dU,g.U);g.h=dU.prototype;g.h.bb=function(a){dU.M.bb.call(this,a);this.ia=a};
g.h.Z=function(){dU.M.Z.call(this);this.G||(this.G=new g.Je(this.dJ,this.D,this),g.vd(this,this.G));this.G.start()};
g.h.Wa=function(){this.G.stop();dU.M.Wa.call(this)};
g.h.dJ=function(){this.J||(this.J=new g.mh(void 0));var a={context:g.bh(this.J.C)};this.H?a.continuation=this.H:(a.videoId=this.ab,this.Sa&&(a.ut=this.Sa));var b={timeout:3E4};b.onSuccess=(0,g.t)(this.gB,this);b.onError=(0,g.t)(this.Fl,this);b.Oc=(0,g.t)(this.Fl,this);g.ch(this.J,"updated_metadata",a,b)};
g.h.gB=function(a){if(this.tb)if(!a||a.error)this.Fl();else{var b=a.continuation;if(b&&b.timedContinuationData){b=b.timedContinuationData;var c=(0,window.parseInt)(b.timeoutMs,10);this.D=!c||0>c?0:c;this.H=b.continuation||null}else this.H=null,this.D=0;0<this.D&&this.G.start(this.D);if(a=a.actions)for(b=0;b<a.length;b++)if(a[b].updateViewershipAction)a:{c=a[b].updateViewershipAction||null;try{var d=c.viewership.videoViewCountRenderer.viewCount;if(!d&&!c.isEmpty)break a}catch(f){break a}null===this.aa&&
(this.aa=g.J("metadata-updateable-viewership"));eU(this.aa,d||null,!1)}else if(a[b].updateDateTextAction)(c=a[b].updateDateTextAction||null)&&c.dateText&&(c=c.dateText,null===this.N&&(this.N=g.J("metadata-updateable-date-text")),eU(this.N,c,!1));else if(a[b].updateDescriptionAction){if((c=a[b].updateDescriptionAction||null)&&c.description){var e=c.description;if(e||c.isEmpty)null===this.V&&(this.V=g.J("metadata-updateable-description")),eU(this.V,e,!0)}}else a[b].updateTitleAction?(c=a[b].updateTitleAction||
null)&&c.title&&(c=c.title,null===this.Y&&(this.Y=g.J("metadata-updateable-title")),eU(this.Y,c,!1)):a[b].updateSentimentAction&&g.F("new-like-renderer-notification",a[b].updateSentimentAction.sentimentRenderer.likeButtonRenderer)}};
g.h.Fl=function(){this.tb&&(this.na++,3<=this.na?this.D=0:(this.D=Math.max(6E4,2*this.D),this.G.start(this.D)))};var gU,hU,iU,jU,kU,lU,mU,nU,fU,rU,tU,vU=!1,qU=[],oU=[];var HU=[],JU=[],ZU=0,EU=null,PU=!1,XU=!1,YU=null,xU=null,yU=null,wU=null,zU=null,AU=null,BU=null,CU=null,DU="",$U=null,GU=!1;g.v(fV,g.sd);g.h=fV.prototype;g.h.X=function(){g.Ig(this.C);this.C.length=0;g.Kf(this.G);this.G.length=0;g.Ef(this.R);this.H&&this.H.abort();this.K&&this.K.abort();fV.M.X.call(this)};
g.h.vs=function(){eV(this,"action-panel-share",!1,!0);g.Fo(this.F,window.document.body,!0)};
g.h.rB=function(){FR(g.Ny.getInstance(),this.W);g.S(this.F)};
g.h.rs=function(a){a=g.E(a.currentTarget,"trigger-for");a==this.D?g.vu(this.F):gV(this,a,!1,!0);"action-panel-report"==a&&(a=g.CG())&&a.isReady()&&a.pauseVideo()};
g.h.MH=function(){g.S("watch-actions-share-loading")};
g.h.rM=function(a,b,c,d){var e=g.x("watch7-views-info"),f=g.K("likes-count",e);f&&g.L(f,a);(a=g.K("dislikes-count",e))&&g.L(a,b);if(b=g.K("video-extras-sparkbar-likes",e))b.style.width=c+"%";if(c=g.K("video-extras-sparkbar-dislikes",e))c.style.width=d+"%"};var jV,sV,tV,uV,vV,wV,xV,yV,Rpa={"play-next":function(){var a=g.D("VIDEO_ID",void 0),b=g.D("LIST_ID",void 0);AV()?g.F("watch-queue-addto-playlist-play-next",b,a):g.F("watch-queue-addto-video-play-next",a)}},kV=[],mV=[];var EV,bW=[],iW=!1,kW="",lW={},aW=0,hW={};var JW=[];g.p("yt.www.watch.related.loadMore",function(a){g.S("watch-more-related-button");g.Q("watch-more-related");a=g.E(a,"continuation");bqa(a,function(){var a=g.x("watch-more-related");g.F("yt-uix-load-more-success");g.F("yt-dom-content-change",a)})},void 0);
g.p("yt.www.watch.player.getClientPlaybackNonce",function(){var a=EV;return a&&a.isReady()?a.getVideoData().cpn||"":""},void 0);
g.p("yt.www.watch.player.seekTo",jW,void 0);g.p("yt.www.watch.player.pause",function(){var a=EV;a&&a.pauseVideo()},void 0);
g.p("yt.www.watch.player.saveResumeOffset",eW,void 0);g.p("yt.sharing.facebooktokenrefresh.finish",function(a){var b={service:"facebook"},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);g.G("/social_connector_ajax",{method:"POST",format:"JSON",za:{action_connect_service:1},ha:b})},void 0);
g.p("yt.www.watch.lists.loadThumbnails",MU,void 0);g.p("yt.www.watch.lists.getState",OU,void 0);g.p("yt.www.watch.lists.next",TU,void 0);g.p("yt.www.watch.lists.prev",UU,void 0);var LW=[],qW=null,pW=null,nW=new g.th("ytg-eventpromo");var rW=null;var wW=[],tW=[],sW=null,hqa=null,uW=null,vW=-1,yW=-1,zW=-1;g.h=AW.prototype;g.h.dispose=function(){g.Df(this.C);g.Kf(this.F);this.F.length=0};
g.h.xG=function(){this.Jg()};
g.h.ys=function(a){var b=g.x("page");b&&(b=g.B(b,"watch-wide"),a?b&&this.En(!1):"1"!==g.qh.get("wide",void 0)||b||this.En(!0))};
g.h.En=function(a){a=!!a;var b=g.x("watch7-sidebar"),c=g.x("page");if(g.x("player")&&b&&c){var d=Yoa(b);a?(g.N(c,"watch-wide"),g.F("yt-dom-content-change",b),g.Df(this.C),this.C=g.Bf((0,g.t)(function(){this.Jg();g.F("yt-dom-content-change")},this),d)):(g.O(c,"watch-wide"),g.N(c,"watch-non-stage-mode"),g.O(c,"watch-stage-mode"),this.Jg(),g.F("yt-dom-content-change"),g.Df(this.C),this.C=g.Bf(function(){g.F("yt-dom-content-change",b)},d))}};
g.h.XG=function(a){g.B(window.document.body,"flexwatch-noupscale")&&((0,g.Ck)(["large","hd720","hd1080"],function(b){return g.Ia(a,b)}),this.Jg())};
g.h.Jg=function(){g.Df(this.C);var a=g.x("player"),b=g.x("page");if(g.x("watch7-container")&&a){a=g.B(b,"watch-wide");var c=window.matchMedia&&window.matchMedia("screen and (max-width: 656px)").matches;c?b&&(g.O(b,"watch-stage-mode"),g.N(b,"watch-non-stage-mode")):a&&b&&(g.O(b,"watch-non-stage-mode"),g.N(b,"watch-stage-mode"));(b=g.CG())&&(b.isReady()?b.setSizeStyle(!c,a):b.addEventListener("onReady",(0,g.t)(this.Jg,this)))}};var BW=[];var CW=[],KW=[],$W=[];var OW={},NW={};g.Zh(g.uq({name:"www/watch",deps:["www/common"],page:"watch",init:function(){rqa();g.K("guide-module-loading")&&sqa();var a=[];g.D("WATCH_COMMENTS_FORCE_DISABLED")||a.push("comments");g.D("DELAY_LOAD_FOOTER")&&a.push("footer");tqa(a);g.vF();g.AF()},
dispose:function(){DW&&(g.ud(DW),DW=null);IW&&(g.ud(IW),IW=null);EW&&(g.ud(EW),EW=null);FW&&(g.ud(FW),FW=null);GW&&(g.ud(GW),GW=null);HW&&(g.ud(HW),HW=null);g.nq(window.document,"keydown",DV);UT();g.Vf(KT);KT.length=0;var a=qT;a&&(a.use_gut&&g.Of("//www.googletagservices.com/tag/js/gpt.js"),a.show_afv&&g.Of("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"));null!=window.adModuleLoaded&&g.zp("adModuleLoaded");g.Df(MT);rT&&(rT=null);oT&&(oT.dispose(),oT=null);pT();qT=BT=AT=zT=null;xT=uT=
LT=!1;if(yT.length){for(a=yT.length-1;0<=a;a--)g.zp(yT[a]);yT.length=0}g.tJ();uU();g.Kf(wW);g.Kf(yW);g.Ig(tW);wW.length=0;tW.length=0;g.EF();g.NF();g.Ig(HU);HU.length=0;a=EU;EU=null;a&&(a.removeEventListener("onCueRangeEnter",VU),a.removeEventListener("onReady",FU),a.isReady()&&(a.removeCueRange("AUTOPLAY_PREFETCH"),g.$f("player_external_control_on_classic_desktop")&&(a.removeEventListener("onPlaylistNext",TU),a.removeEventListener("onPlaylistPrevious",UU),a.removeEventListener("onPlaylistIndex",
WU))));g.Kf(JU);JU.length=0;xU&&g.O(xU,"scrolled");XU=PU=!1;CU=BU=AU=zU=yU=wU=xU=YU=null;DU="";$U&&(g.Df($U),$U=null);g.Uf(ZU);(a=g.x("guide-container"))&&g.O(a,"branded");if(a=g.x("player"))a.style.background="";JW&&(g.Ig(JW),JW=[]);g.Kf(BW);BW.length=0;g.Kf(mV);mV.length=0;g.Ig(kV);kV.length=0;jV&&(sV=!1,yV=xV=wV=vV=uV=tV=jV=null,g.qE());MW&&MW.dispose();g.Ig(KW);KW.length=0;g.Kf($W);$W.length=0;g.Vf(CW);CW.length=0;(a=EV)&&a.sendAbandonmentPing&&a.sendAbandonmentPing();if(dW()&&(eW(),g.D("IS_RESUMABLE_PLAYBACK")&&
g.$f("restore_save_resume_204")&&(a=EV)&&a.isReady())){var b=Math.floor(a.getCurrentTime());0==a.getDuration()||20>=b||g.di("/save_resume_204?"+g.Tc({v:a.getVideoData().video_id,t:b.toString()}))}g.Ef(aW);EV&&(a=EV,a.removeEventListener("onReady",FV),a.removeEventListener("onStateChange",GV),a.removeEventListener("onVideoProgress",HV),a.removeEventListener("SHARE_CLICKED",IV),a.removeEventListener("SIZE_CLICKED",JV),a.removeEventListener("onError",KV),a.removeEventListener("onFullscreenChange",LV),
a.removeEventListener("onAdStart",MV),a.removeEventListener("onAutonavChangeRequest",NV),a.removeEventListener("onAutonavPauseRequest",OV),a.removeEventListener("onFeedbackStartRequest",PV),a.removeEventListener("onFeedbackArticleRequest",QV),a.removeEventListener("onScreenChanged",RV),a.removeEventListener("onLogClientVeCreated",SV),a.removeEventListener("onLogServerVeCreated",TV),a.removeEventListener("onLogToGel",UV),a.removeEventListener("onLogVeClicked",VV),a.removeEventListener("onLogVesShown",
WV),a.removeEventListener("onYpcContentRequest",XV),a.removeEventListener("onReady",YV),g.$f("player_external_control_on_classic_desktop")&&a.removeEventListener("onPlayVideo",ZV));EV=null;iW=!1;kW="";lW={};g.Kf(bW);bW.length=0;hW={};g.fG();g.ud(rW);rW=null;g.NF();g.Ig(VT);for(a=VT.length=0;a<LW.length;a++)g.Ig(LW[a]);window.document.body&&g.O(window.document.body,"gaming-event-promo-visible");g.iK.dispose();for(var c in NW)g.Df(NW[c]);NW={};g.Ig(OW.jz);g.iK.dispose();g.oB(g.xF)}}));})(_yt_www);
