(function(g){var window=this;var l9=function(a){this.languageCode=a.languageCode;this.languageName=a.languageName||null;this.C=a.languageOriginal||null;this.id=a.id||null;this.isDefault=a.is_default||!1},m9=function(a){a=void 0===a?{}:a;
this.K=a.formats||"";this.F=a.format||1;if(1==this.F)for(var b=this.K.split(","),c=0;c<b.length;c++){var d=(0,window.parseInt)(b[c],10);(0,window.isNaN)(d)||(this.F=Math.max(d,this.F))}this.C=a.languageCode||"";this.H=a.languageName;this.D=a.kind||"";this.G=a.name;this.hb=a.id;this.R=a.url||null;this.J=a.vss_id||"";this.isDefault=a.is_default;this.translationLanguage=null;if(a=a.translationLanguage)this.translationLanguage=new l9(a)},n9=function(a){var b=a.H||"",c=[b];
"asr"==a.D&&-1==b.indexOf("(")&&c.push(" ("+g.wq("YTP_ASR_SETTINGS_LABEL")+")");a.G&&c.push(" - "+a.G);a.translationLanguage&&c.push(" >> "+a.translationLanguage.languageName);return c.join("")},Ywa=function(){if(!g.C)return!1;
try{return new window.ActiveXObject("MSXML2.DOMDocument"),!0}catch(a){return!1}},o9=function(a){if("undefined"!=typeof window.DOMParser)return(new window.DOMParser).parseFromString(a,"application/xml");
if(Zwa){var b=new window.ActiveXObject("MSXML2.DOMDocument");b.resolveExternals=!1;b.validateOnParse=!1;try{b.setProperty("ProhibitDTD",!0),b.setProperty("MaxXMLSize",2048),b.setProperty("MaxElementDepth",256)}catch(c){}b.loadXML(a);return b}throw Error("Your browser does not support loading xml documents");},$wa=function(a,b,c,d){this.data=a;
this.offset=b;this.size=c;this.type=d;this.C=8;this.dataOffset=this.offset+this.C},axa=function(a,b){if(8>a.byteLength-b)return!1;
var c=a.getUint32(b);if(8>c||a.byteLength-b<c)return!1;c=a.getUint32(b+4);if(1635148593==c||1635148611==c||1937126244==c||1936995172==c)return!0;for(c=4;8>c;c++){var d=a.getInt8(b+c);if(97>d||122<d)return!1}return!0},p9=function(a,b,c){g.sd.call(this);
this.start=a;this.end=b;bxa++;a=c||{};this.hb=a.id||"";this.active=!0;this.visible=a.visible||!1;this.style=a.style||"ytp-ad-progress";this.namespace=a.namespace||"";this.color="";if(b=a.color)b=b.toString(16),this.color="#"+Array(7-b.length).join("0")+b;this.tooltip=a.tooltip;this.icons=a.icons?a.icons.filter(function(a){var b=void 0===b?!1:b;return g.ty(cxa.test(a),a,b,"Trusted Image URL")}):null;
this.visible=this.visible;this.style=this.style;this.start=this.start},dxa=function(a){return-0x8000000000000==a?"BEFORE_MEDIA_START":0==a?"MEDIA_START":0x7ffffffffffff==a?"MEDIA_END":0x8000000000000==a?"AFTER_MEDIA_END":a.toString()},exa=function(){},r9=function(){this.G=this.F=this.mode=this.D=0;
this.H=new q9(this);this.K=new q9(this);this.C=[];this.clear()},gxa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{gi:a,
ji:b,result:0};a=fxa[a];b=fxa[b];if(a&128){if(!(b&128)&&0!=c.C&&c.F==b)return{gi:a,ji:b,result:1}}else if(b&128&&1<=a&&31>=a)return{gi:a,ji:b,result:2};return{gi:a,ji:b,result:3}},ixa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.G&&a.reset(),a.H.C.clear(),a.K.C.clear()):(a.G=0,hxa(a.H,b,c,d))},jxa=function(a,b){a.C.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.C.length;c++){var d=a.C[c];a.F=d.time;0==d.type?ixa(a,d.lo,d.oo,b):1==d.type&&a.D&496&&hxa(a.K,d.lo,d.oo,b)}a.C.length=0},s9=function(){this.C=0},t9=function(){this.F=this.D=this.C=0},u9=function(){this.timestamp=this.ed=0},v9=function(a){this.D=[];
for(var b=0;15>=b;b++){this.D[b]=[];for(var c=0;32>=c;c++)this.D[b][c]=new u9}this.C=this.F=this.row=0;this.style=new s9;this.H=a;this.G=0},w9=function(a,b){if(3==a.style.C){for(var c=0,d=0,e=a.H.F+0,f="",k="",l=e,m=1;15>=m;++m){for(var q=!1,w=d?d:1;32>=w;++w){var y=a.D[m][w];
if(0!=y.ed){0==c&&(c=m,d=w);q=String.fromCharCode(y.ed);var I=y.timestamp;I<e&&(e=I);y.timestamp=l;k&&(f+=k,k="");f+=q;q=!0}if((0==y.ed||32==w)&&q){k="\n";break}else if(d&&!q)break}if(c&&!q)break}f&&b.H(c,d,e,l,f)}else for(d=c=0,f=e=a.H.F+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(w=a.D[k][m],y=w.ed,0!=y&&(0==c&&(c=k,d=m),q=String.fromCharCode(y),I=w.timestamp,I<=e&&(e=I),l+=q,w.reset()),32==m||0==y)l&&b.H(c,d,e,f,l),e=f,l="",d=c=0},oxa=function(a,b){switch(a){case 0:return kxa[(b&127)-32];
case 1:return lxa[b&15];case 2:return mxa[b&31];case 3:return nxa[b&31]}return 0},x9=function(a){return a.D[a.row][a.F]},y9=function(a,b,c){2<=b&&1<a.F&&(--a.F,x9(a).ed=0);
var d=x9(a);d.timestamp=a.H.F+0;d.ed=oxa(b,c);32>a.F&&a.F++},pxa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.D[b+e][f].copy(a.D[c+e][f])},z9=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.D[b+d][e].reset()},A9=function(a){a.row=0<a.C?a.C:1;
a.F=1;z9(a,0,15)},B9=function(a){this.G=a;
this.H=0;this.style=new s9;this.K=new v9(a);this.R=new v9(a);this.J=new v9(a);this.F=this.K;this.D=this.R;this.C=this.F},C9=function(a,b,c){var d=a.F,e=!1;
switch(a.style.get()){case 4:if(0<d.C)break;case 1:case 2:w9(d,c),A9(a.F),A9(a.D),d.row=15,d.C=b,e=!0}a.style.set(3);a.C=d;a.C.style=a.style;a.G.mode=1<<d.G;e?d.F=1:d.C!=b&&(d.C>b?(w9(d,c),z9(d,d.row-d.C,b)):d.row<b&&(b=d.C),d.C=b)},qxa=function(a){a.style.set(1);
a.C=a.D;a.C.C=0;a.C.style=a.style;a.G.mode=1<<a.C.G},rxa=function(a){a.style.set(4);
a.C=a.J;a.C.style=a.style;a.G.mode=1<<a.C.G},q9=function(a){this.F=a;
this.C=new t9;this.H=0;this.D=new B9(a);this.K=new B9(a);this.G=this.D},hxa=function(a,b,c,d){a.C.update();
b=gxa(b,c,a.C);switch(b.result){case 0:return;case 1:case 2:return}var e=b.gi;c=b.ji;if(32<=e||!e)a.F.mode&a.F.D&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.G.C,b&96&&y9(a,0,b),c&96&&y9(a,0,c),0!=b&&0!=c&&3==a.style.C&&w9(a,d));else if(e&16)a:if(b=a.C,0==b.C||e!=b.D||c!=b.F)if(b=a.C,b.D=e,b.F=c,b.C=2,b=e&8?a.K:a.D,a.G=b,a.F.mode=1<<(a.H<<2)+(b.H<<1)+(4==b.style.C?1:0),(a.F.mode|1<<(a.H<<2)+(b.H<<1)+(4!=b.style.C?1:0))&a.F.D)if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*
((c&14)>>1):0;c=b.C;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.C&&(d=c.C,d==c.row))break;var f=1+c.row-c.C,k=1+d-c.C;pxa(c,k,f,c.C);b=f;e=c.C;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));z9(c,b,e)}}c.row=d;c.F=a+1}else switch(e&7){case 1:switch(c&112){case 32:y9(b.C,0,32);break a;case 48:57==c?(d=b.C,x9(d).ed=0,32>d.F&&d.F++):y9(b.C,1,c&15)}break;case 2:c&32&&y9(b.C,2,c&31);break;case 3:c&32&&y9(b.C,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:qxa(b);
break;case 33:d=b.C;1<d.F&&(--d.F,x9(d).ed=0);break;case 36:d=b.C;b=x9(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.D[a][c]==b){for(;32>=c;c++)d.D[a][c].reset();break}break;case 37:C9(b,2,d);break;case 38:C9(b,3,d);break;case 39:C9(b,4,d);break;case 40:y9(b.C,0,32);break;case 41:b.style.set(2);b.C=b.F;b.C.C=0;b.C.style=b.style;b.G.mode=1<<b.C.G;break;case 42:d=b.J;d.C=15;d.style.set(4);A9(d);rxa(b);break;case 43:rxa(b);break;case 44:a=b.F;switch(b.style.get()){case 1:case 2:case 3:w9(a,d)}z9(a,0,15);
break;case 45:b:{a=b.C;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.F=1;break b}case 3:}2>a.C&&(a.C=2,a.row<a.C&&(a.row=a.C));b=a.row-a.C+1;w9(a,d);pxa(a,b,b+1,a.C-1);z9(a,a.row,1)}break;case 46:z9(b.D,0,15);break;case 47:w9(b.F,d);d=b.D;a=b.G.F+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.D[c][e].timestamp=a;d=b.D;b.D=b.F;b.F=d;qxa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.C,32<(d.F+=c&3)&&(d.F=32)}}},D9=function(){},E9=function(a,b,c,d,e,f){f=void 0===
f?!1:f;
p9.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f},F9=function(a,b,c,d,e){p9.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.C=[]},H9=function(a){a=void 0===a?{}:a;
var b="_"+G9++;return new F9(0,0x8000000000000,0,b,a)},I9=function(a){this.F=a;
this.C=null},txa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=o9("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");sxa(d,e,k,b,f,a.firstChild,{},c)},sxa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Hq=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");uxa.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var q=f.childNodes[m];if(3==q.nodeType)l.push(new E9(a,b,c,d,q.nodeValue,e||0<m,g.eb(k)?void 0:k));else{var w={};g.Hl(w,k);sxa(a,b,c,d,e||0<m,q,w,l)}}},J9=function(){this.F={};
this.C=null},K9=function(a){this.G={};
this.W={};this.N={};this.H="_"+G9++;this.K=a;this.J={};this.F=this.C=null;this.R=!0},L9=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},M9=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},N9=function(a,b){var c=L9(a,b);
if(void 0!=c)return c},O9=function(a,b){var c=a.getAttribute(b);
if(null!=c)return uxa.test(c),c},vxa=function(a,b){var c={},d=b.getAttribute("ws");
g.Hl(c,d?a.N[d]:a.K);d=N9(b,"mh");null!=d&&(c.qC=d);d=N9(b,"ju");null!=d&&(c.textAlign=d);d=N9(b,"pd");null!=d&&(c.hn=d);d=O9(b,"wfc");null!=d&&(c.windowColor=d);d=L9(b,"wfo");void 0!=d&&(c.ZZ=d/255);return c},wxa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Hl(c,a.W[d]);d=N9(b,"ap");null!=d&&(c.anchorPoint=d);d=L9(b,"cc");null!=d&&(c.zo=d);d=L9(b,"ah");null!=d&&(c.Bg=d);d=L9(b,"rc");null!=d&&(c.pL=d);d=L9(b,"av");null!=d&&(c.ck=d);return c},xxa=function(a,b,c,d){var e={};
g.Hl(e,wxa(a,b));g.Hl(e,vxa(a,b));d?g.hb(e,a.K)?(d=a.H,e=a.K):d="_"+G9++:d=b.getAttribute("id")||"_"+G9++;a=L9(b,"t")+c;b=L9(b,"d")||0x8000000000000;return new F9(a,b,0,d,e)},P9=function(a,b,c){this.R=c;
this.version=this.K=this.G=this.C=0;this.F=new window.DataView(a);this.D=[]},Q9=function(a){var b=a.C;
a.C+=1;return a.F.getUint8(b)},R9=function(a){var b=a.C;
a.C+=4;return a.F.getUint32(b)},S9=function(a,b){this.F=a;
this.track="CC3"==b.H?4:0;this.C=new r9;this.C.D=1<<this.track},zxa=function(a){if(g.sa(a))return!1;
a=new P9(a,8,0);return yxa(a)},yxa=function(a){if(!(a.C<a.F.byteLength)||1380139777!=R9(a))return!1;
a.version=Q9(a);if(1<a.version)return!1;Q9(a);Q9(a);Q9(a);return!0},Axa=function(){this.F=[];
this.C=[]},T9=function(a,b){return b?a.C.concat(a.F):a.C},U9=function(a,b){switch(b.D){case "asr":return Bxa(b,a.F);
default:return Bxa(b,a.C)}},Bxa=function(a,b){return g.Ga(b,(0,g.t)(a.equals,a))?!1:(b.push(a),!0)},V9=function(){},Cxa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Hq=!0;break;case "u":l.underline=!0}for(var q=0;q<k.childNodes.length;q++){var w=k.childNodes[q];if(3==w.nodeType)w=new E9(b,c,d,e.id,w.nodeValue,f||0<q,g.eb(l)?void 0:l),m.push(w),e.C.push(w);else{var y={};g.Hl(y,l);Cxa(a,b,c,d,e,!0,w,y,m)}}},W9=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},Dxa=function(a,b,c,d){d=Object.assign({qC:0},d);
return new F9(a,b,c,"_"+G9++,d)},X9=function(a){g.sd.call(this);
this.J=!!a;this.F=new Axa;this.W=[];this.C=null},Fxa=function(a){var b={};
if(a=a.translationLanguage?a.translationLanguage.languageCode:a.C)b.lang=a,Exa.test(a)&&(b.hn=1);return b},Gxa=function(a,b,c,d){d=d||0;
var e=e||0;if(!g.sa(b)){var f=new window.DataView(b);if(1718909296==f.getUint32(4)){a:{for(var k=0;axa(f,k);){var l=k,m=f.getUint32(l),q=f.getUint32(l+4);l=new $wa(f,l,m,q);if(1835295092==l.type){f=l;break a}m=l.type;k=1836019558==m||1836019574==m||1835297121==m||1835626086==m||1937007212==m||1953653094==m||1953653099==m?k+8:k+l.size}f=null}b=b.slice(f.dataOffset,f.dataOffset+f.size);if(!zxa(b)){b=new window.Uint8Array(b);if(8192>=b.length)b=String.fromCharCode.apply(null,b);else{f="";for(k=0;k<b.length;k+=
8192)f+=String.fromCharCode.apply(null,g.Pl(b,k,k+8192));b=f}if(!b)return[]}}}if(g.sa(b)){if("WEBVTT"==b.substring(0,6))return a.C||(a.C=new V9),a.C.D(b,d);e=o9(b);if(!e||!e.firstChild)return[];if(!a.C)if("timedtext"==e.firstChild.tagName)3==(0,window.parseInt)(e.firstChild.getAttribute("format"),10)?a.C=new K9(Fxa(c)):a.C=new J9;else try{return a.C=new I9(Fxa(c)),a.C.D(e,d)}catch(w){return g.wf(w),a.C=null,[]}return a.C.D(e,d)}try{if(zxa(b))return a.C||(a.C=new S9(e,c)),a.C.D(b,d)}catch(w){g.wf(w),
a.C=null}return[]},Hxa=function(a,b){return g.Ga(T9(a.F,!0),function(a){return a.toString()==b})},Y9=function(a,b,c,d){X9.call(this,d);
c=c||g.Gp(a).hl||"";c=c.split("_").join("-");this.R=g.jg(a,{hl:c});this.K=b;this.H={};this.D=null},Z9=function(a,b,c){var d=Ixa(a,b),e=(0,g.t)(function(a){this.D=null;
c(a.responseText,b)},a);
a.G();a.D=g.G(d,{format:"RAW",onSuccess:e,withCredentials:!0})},Jxa=function(a,b){var c=a.R,d={type:"list",
tlangs:1,v:a.K,fmts:Number(!1),vssids:1};a.J&&(d.asrs=1);c=g.jg(c,d);d=(0,g.t)(function(a){this.D=null;if((a=a.responseXML)&&a.firstChild){for(var c=this.F,d=g.ma(a.getElementsByTagName("track")),e=d.next();!e.done;e=d.next()){var m=e.value;e=m.getAttribute("formats");var q=m.getAttribute("lang_code"),w=m.getAttribute("lang_translated"),y=m.getAttribute("name"),I=m.getAttribute("kind"),R=m.getAttribute("id"),V="true"==m.getAttribute("lang_default"),T="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");
U9(c,new m9({formats:e,format:void 0,languageCode:q,languageName:w,name:y,kind:I,id:R,is_servable:!0,is_translateable:T,vss_id:m,is_default:V}))}a=a.getElementsByTagName("target");c=a.length;for(d=0;d<c;d++)e=a[d].getAttribute("lang_code"),q=a[d].getAttribute("lang_translated"),w=a[d].getAttribute("lang_original"),y=a[d].getAttribute("id"),I="true"==a[d].getAttribute("lang_default"),e={languageCode:e,languageName:q,languageOriginal:w,id:y,is_default:I},this.H[e.languageCode]=e.languageName,this.W.push(new l9(e))}b()},
a);
a.G();a.D=g.G(c,{format:"RAW",onSuccess:d,withCredentials:!0})},Ixa=function(a,b){var c=a.R,d={v:a.K,
type:"track",lang:b.C,name:b.G,kind:b.D,fmt:b.F};b.translationLanguage&&(d.tlang=b.translationLanguage?b.translationLanguage.languageCode:b.C);return c=g.jg(c,d)},Lxa=function(){if(g.D("TTS_URL")&&!$9){var a=g.CG();
a&&($9=new Kxa(a))}},Kxa=function(a){this.Qb=a;
this.R=null;this.la=!1;this.G=[];this.K=[];this.D=new Y9(g.D("TTS_URL",void 0),g.D("VIDEO_ID",void 0),null,!0);this.Y=null;this.aa=[];this.N=-1;this.V=!1;this.J=this.W=0;this.C=this.F=null;this.Qb.addEventListener("captionschanged",(0,g.t)(this.pD,this))},Mxa=function(a,b){if(b.translationLanguage){var c=b.translationLanguage.languageCode;
b.translationLanguage.languageName=a.D.H[c]||c}c=new m9(b);return!c.C||c.translationLanguage&&!c.translationLanguage.languageCode?null:c},a$=function(a,b,c){var d=g.qc("BUTTON",{className:["yt-ui-menu-item yt-uix-menu-close-on-select yt-uix-button-menu-item"],
value:c});c=g.qc("SPAN",{className:"yt-uix-button-content transcript-lang",value:c});b=window.document.createTextNode(String(b));a.H.appendChild(d);d.appendChild(c);c.appendChild(b)},Nxa=function(a,b){g.Ef(a.J);
var c=Math.min(b.offsetTop-a.C.offsetTop,a.C.scrollHeight-a.C.offsetHeight),d=0;a.J=g.Cf((0,g.t)(function(){var a=c-this.C.scrollTop,b=Math.round(100*a/(1E3-50*d));Math.abs(a)<=Math.abs(b)||20<d?(this.C.scrollTop=c,g.Ef(this.J)):(this.C.scrollTop+=b,d++)},a),50)},Exa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;
l9.prototype.toString=function(){return this.languageCode+"_"+this.languageName+"_"+this.C+"_"+this.id+"_"+this.isDefault};
m9.prototype.getUrl=function(){return this.R};
m9.prototype.toString=function(){return this.C+": "+n9(this)+" - "+this.J};
m9.prototype.equals=function(a){return a?this.toString()==a.toString():!1};
var cxa=/^((http(s)?):)?\/\/((((lh[3-6](-tt|-d[a-g,z])?\.((ggpht)|(googleusercontent)|(google)))|(([1-4]\.bp\.blogspot)|(bp[0-3]\.blogger))|((((cp|ci|gp)[3-6])|(ap[1-2]))\.(ggpht|googleusercontent))|(gm[1-4]\.ggpht)|(((yt[3-4])|(sp[1-3]))\.(ggpht|googleusercontent)))\.com)|(dp[3-6]\.googleusercontent\.cn)|(dp4\.googleusercontent\.com)|(photos\-image\-(dev|qa)(-auth)?\.corp\.google\.com)|((dev|dev2|dev3|qa|qa2|qa3|qa-red|qa-blue|canary)[-.]lighthouse\.sandbox\.google\.com\/image)|(image\-(dev|qa)\-lighthouse(-auth)?\.sandbox\.google\.com(\/image)?))\/|^https?:\/\/(([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|c\.googlers\.com|borg\.google\.com|docs\.google\.com|drive\.google\.com|googleplex\.com|play\.google\.com|prod\.google\.com|plus\.google\.com|video\.google\.com|youtube\.com|ytimg\.com|chat\.google\.com)(:[0-9]+)?\/|([A-Za-z0-9-]{1,63}\.)*(sandbox\.google\.com)(:[0-9]+)?\/(?!url\b)|s2\.googleusercontent\.com\/s2\/favicons\?|yt[3-4]\.ggpht\.com\/)/,
Zwa=g.C&&Ywa();$wa.prototype.skip=function(a){this.C+=a};g.ea(p9,g.sd);p9.prototype.F=function(){return this.hb};
p9.prototype.toString=function(){return"CueRange{"+this.namespace+":"+this.hb+"}["+dxa(this.start)+", "+dxa(this.end)+"]"};
p9.prototype.contains=function(a,b){return a>=this.start&&(a<this.end||a==this.end&&this.start==this.end)&&(null==b||a<b&&b<=this.end)};
var bxa=1;p9.prototype.getId=p9.prototype.F;exa.prototype.H=function(){};r9.prototype.clear=function(){this.G=this.F=this.mode=0;this.C=[];this.reset()};
r9.prototype.reset=function(){this.mode=0;this.H.reset(0);this.K.reset(1)};
var fxa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];s9.prototype.set=function(a){this.C=a};
s9.prototype.get=function(){return this.C};
t9.prototype.clear=function(){this.C=0};
t9.prototype.update=function(){this.C=2==this.C?1:0};
u9.prototype.copy=function(a){this.ed=a.ed;this.timestamp=a.timestamp};
u9.prototype.reset=function(){this.timestamp=this.ed=0};
v9.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.D[b][c];a=0==d.ed?a+"_":a+String.fromCharCode(d.ed)}a+="\n"}return a};
v9.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.D[b][c].reset();this.G=a;this.C=0;this.F=this.row=1};
var kxa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],lxa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],mxa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],nxa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];B9.prototype.reset=function(a,b){this.H=b;this.style.set(2);this.F=this.K;this.D=this.R;this.C=this.F;var c=(a<<2)+(b<<1);this.K.reset(c);this.R.reset(c);this.J.reset((a<<2)+(b<<1)+1)};
q9.prototype.reset=function(a){this.H=a;this.C.clear();this.G=this.D;this.D.reset(a,0);this.K.reset(a,1)};var uxa=/^#(?:[0-9a-f]{3}){1,2}$/i,Oxa={"default":0,monoSerif:1,propSerif:2,monoSans:3,propSans:4,casual:5,cursive:6,smallCaps:7};Object.keys(Oxa).reduce(function(a,b){a[Oxa[b]]=b;return a},{});
var Pxa={none:0,raised:1,depressed:2,uniform:3,dropShadow:4};Object.keys(Pxa).reduce(function(a,b){a[Pxa[b]]=b;return a},{});
var Qxa={normal:0,bold:1,italic:2,bold_italic:3};Object.keys(Qxa).reduce(function(a,b){a[Qxa[b]]=b;return a},{});D9.prototype.reset=function(){};g.ea(E9,p9);g.ea(F9,p9);var G9=0;g.ea(I9,D9);I9.prototype.D=function(a){var b=[];this.C||(this.C=H9(this.F),b.push(this.C));a=Array.from(a.firstChild.childNodes);a=g.ma(a);for(var c=a.next();!c.done;c=a.next())txa(c.value,this.C.id,b);return b};g.ea(J9,D9);
J9.prototype.D=function(a){var b=[];this.C||(this.C=H9(),this.F[this.C.id]=this.C,b.push(this.C));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.F[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=H9());
var k={};f&&(g.Hl(k,f.params),f=f.params.zd)&&(k.zd={},g.Hl(k.zd,f));e.getAttribute("rc")&&(k.pL=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.zo=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.anchorPoint=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Bg=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.ck=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.hn=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.hn=0));e.getAttribute("bc")&&(k.zd||(k.zd={}),k.zd.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.zd||(k.zd={}),k.zd.hw=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.zd||(k.zd={}),k.zd.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.YZ=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+G9++;c=new F9(c,f,0,e,k)}else c=null}this.F[d]=c;b.push(c);break;case "text":for(d=[],txa(a,this.C.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.F[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.ea(K9,D9);K9.prototype.reset=function(){this.J={};this.F=this.C=null;this.R=!0};
K9.prototype.D=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);var c=Array.from(a.firstChild.childNodes);c=g.ma(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.ma(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.G,l={},m=c.getAttribute("p");m&&g.Hl(l,this.G[m]);m=M9(c,"b");null!=
m&&(l.bold=m);m=M9(c,"i");null!=m&&(l.Hq=m);m=M9(c,"u");null!=m&&(l.underline=m);m=N9(c,"et");null!=m&&(l.BZ=m);m=N9(c,"of");null!=m&&(l.offset=m);m=O9(c,"bc");null!=m&&(l.background=m);m=O9(c,"ec");null!=m&&(l.AZ=m);m=O9(c,"fc");null!=m&&(l.color=m);m=N9(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=L9(c,"sz");void 0!=m&&(l.EZ=m/100-1);m=L9(c,"bo");void 0!=m&&(l.hw=m/255);c=L9(c,"fo");void 0!=c&&(l.XZ=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");this.N[d]=vxa(this,c);break;case "wp":d=c.getAttribute("id"),
this.W[d]=wxa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.ma(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.C=xxa(this,d,e,!1);(d=this.J[this.C.id])&&d.end>this.C.start&&(d.end=this.C.start);this.J[this.C.id]=this.C;c.push(this.C);break;case "p":var q=e;k=[];l=d.getAttribute("w")||this.H;m=!!M9(d,"a");q=(L9(d,"t")||0)+q;var w=L9(d,"d")||5E3;m||(!this.R&&this.F&&this.F.windowId==l&&this.F.end>q&&(this.F.end=q),this.F&&"\n"==this.F.text&&(this.F.text=
""));var y=m?6:5,I=this.G[d.getAttribute("p")],R=d.childNodes;R.length&&(this.R=null!=d.getAttribute("d"));for(var V=0;V<R.length;V++){var T=R[V];0<V&&(m=!0);var ra=void 0;1==T.nodeType&&(ra=T);if(ra&&"s"==ra.tagName){var Wa=ra;T=q;ra=w;var kb=l,Ud=m,Ue=y,Yb=Wa.textContent?Wa.textContent:"",Fm=this.G[Wa.getAttribute("p")];Wa=L9(Wa,"t")||0;T=new E9(T+Wa,ra-Wa,Ue,kb,Yb,Ud,Fm)}else T=new E9(q,w,y,l,T.textContent||"",m,I);k.push(T);this.F=T}if(0<k.length)for(k[0].windowId==this.H&&(this.C=xxa(this,d,
e,!0),c.push(this.C)),d=g.ma(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.C.id,this.C.C.push(k),c.push(k)}e=c}else e=[];return e};g.ea(P9,exa);P9.prototype.H=function(a,b,c,d,e){if(c<d){var f="_"+G9++;c=c/1E3-this.R;d=d/1E3-this.R;a=new F9(c,d-c,5,f,{textAlign:0,anchorPoint:0,Bg:2.5*b,ck:5.33*a});e=new E9(c,d-c,5,f,e);this.D.push(a);this.D.push(e)}};
g.ea(S9,D9);S9.prototype.D=function(a){a=new P9(a,a.byteLength,this.F);if(yxa(a)){for(;a.C<a.F.byteLength;)for(0==a.version?a.G=R9(a)*(1E3/45):1==a.version&&(a.G=4294967296*R9(a)+R9(a)),a.K=Q9(a);0<a.K;a.K--){var b=Q9(a),c=Q9(a),d=Q9(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.C,b.C.push({time:a.G,type:this.track,lo:c,oo:d,order:b.C.length}))}jxa(this.C,a);return a.D}return[]};
S9.prototype.reset=function(){this.C.clear()};g.ea(V9,D9);
V9.prototype.D=function(a,b){for(var c=[],d=a.split(Rxa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Sxa.test(f)){var l=b$.exec(f);if(l&&4<=l.length){var m=W9(l[1]),q=W9(l[2])-m;m+=k;var w,y=w=void 0,I=void 0,R=void 0,V=l[3];l={textAlign:2};V=g.ma(V?V.split(" "):[]);for(var T=V.next();!T.done;T=V.next())if(T=T.value.split(":"),2==T.length){var ra=T[1];switch(T[0]){case "line":T=ra.split(",");T[0].endsWith("%")&&(R=T[0],l.ck=Number.parseInt(R,10),2==T.length&&(I=T[1].trim()));break;case "position":T=ra.split(",");
y=T[0];l.Bg=Number.parseInt(y,10);2==T.length&&(w=T[1].trim());break;case "align":switch(ra){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}R||(l.ck=100,I||(I="end"));if(!y)switch(l.textAlign){case 0:l.Bg=0;break;case 1:l.Bg=100;break;default:l.Bg=50}y=0;switch(I){case "center":y+=3;break;case "end":y+=6;break;default:y+=0}switch(w){case "line-left":y+=0;break;case "center":y+=1;break;case "line-right":y+=2;break;default:switch(l.textAlign){case 0:y+=
0;break;case 2:y+=1;break;case 1:y+=2}}l.anchorPoint=0>y||8<y?7:y;w=l;f=f.substring(b$.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");y=w;w=f;f={};if(0>w.indexOf("<")&&0>w.indexOf("&"))k=Dxa(m,q,5,y),q=new E9(m,q,5,k.id,w,!1,g.eb(f)?void 0:f),c.push(k),c.push(q),k.C.push(q);else for(I=w.split(Txa),1==I.length?(w=5,y=Dxa(m,q,w,y)):(R=w=6,y=Object.assign({zo:32},y),y=new F9(m,q,R,"_"+G9++,y)),c.push(y),R=m,l=0;l<I.length;l++)V=I[l],0==l%2?(T=o9("<html>"+V+"</html>"),T.getElementsByTagName("parsererror").length?
(ra=T.createElement("span"),ra.appendChild(T.createTextNode(V))):ra=T.firstChild,Cxa(this,R,q-(R-m),w,y,0<l,ra,f,c)):R=W9(V)+k}b$.lastIndex=0}}return c};
var Sxa=/^NOTE/,Rxa=/(?:\r\n|\r|\n){2,}/,b$=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Txa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.ea(X9,g.sd);X9.prototype.trackCount=function(){return T9(this.F,!0).length};
X9.prototype.G=function(){this.C=null};
X9.prototype.X=function(){g.sd.prototype.X.call(this);this.G()};g.ea(Y9,X9);Y9.prototype.G=function(){X9.prototype.G.call(this);this.D&&this.D.abort()};
Y9.prototype.X=function(){this.G();X9.prototype.X.call(this)};var $9=null;g.h=Kxa.prototype;g.h.dispose=function(){g.Ig(this.G);this.G.length=0;this.K.length=0;g.Ef(this.W);g.Ef(this.J)};
g.h.pD=function(a){a.format=1;var b=Mxa(this,a);b&&(this.la?(U9(this.D.F,b)&&a$(this,n9(b),b.toString()),Z9(this.D,b,(0,g.t)(this.Pm,this))):this.K.push(a))};
g.h.open=function(a){if(this.la)a();else if(this.R=g.x("watch-transcript-container"),"true"==g.E(this.R,"disabled"))a();else{var b=g.qc("DIV",{className:"yt-uix-menu"}),c=g.qc("DIV",{className:"yt-uix-menu-trigger"});this.F=g.qc("BUTTON",{className:["yt-uix-button yt-uix-button-default hidden"],"button-menu-id":"watch-transcript-track-selector"});this.H=g.qc("DIV",{className:["yt-uix-menu-content yt-ui-menu-content yt-uix-menu-content-hidden"]});this.R.appendChild(b);b.appendChild(c);c.appendChild(this.F);
b.appendChild(this.H);this.C=window.document.createElement("div");this.C.id="transcript-scrollbox";g.N(this.C,"yt-uix-scroller");this.G.push(g.H(this.C,"mouseover",(0,g.t)(function(){this.V=!0},this)));
this.G.push(g.H(this.C,"mouseout",(0,g.t)(function(){this.V=!1},this)));
this.R.appendChild(this.C);this.G.push(g.P(this.C,"click",(0,g.t)(this.oD,this),"caption-line"));Jxa(this.D,(0,g.t)(function(){a:{for(var b=this.D,c=null,f=0;f<this.K.length;f++)(c=Mxa(this,this.K[f]))&&U9(b.F,c);var k=T9(b.F,!0);if(0>=k.length)g.Q("watch-transcript-not-found");else{f=g.qc("SPAN",{className:"yt-uix-button-content transcript-lang"});var l=window.document.createTextNode(String(n9(k[0])));this.F.appendChild(f);f.appendChild(l);f=g.qc("IMG",{"class":"yt-uix-button-arrow",src:g.D("DROPDOWN_ARROW_URL",
void 0)});this.F.appendChild(f);g.Q(this.F);f=0;for(l=k.length;f<l;f++)a$(this,n9(k[f]),k[f].toString());if(k=g.wq("CC_ADD_TRANSCRIPT_TITLE"))a$(this,k,"add-cc"),g.cv(6035988,"cc_transcriptions"),g.bv();this.G.push(g.P(this.H,"click",(0,g.t)(this.bB,this),"yt-uix-button-menu-item"));if(!c&&(c=T9(b.F,void 0)[0],!c))break a;Z9(b,c,(0,g.t)(this.Pm,this))}}a()},this));
this.la=!0}};
g.h.bB=function(a){if("add-cc"==a.target.value)(a=g.D("CC_ADD_TRANSCRIPT_URL",void 0))&&g.hi(a);else{var b=this.D,c=(0,g.t)(this.Pm,this),d=Hxa(b,a.target.value);d&&Z9(b,d,c);this.H&&(this.F.firstChild.innerHTML=a.target.innerHTML)}};
g.h.oD=function(a){var b=g.E(a.currentTarget,"time");b&&(this.Qb.seekTo((0,window.parseInt)(b,10),!0),a.preventDefault())};
g.h.Pm=function(a,b,c){this.N=-1;a=Gxa(this.D,a,b,c);this.Y=b;b=[];g.Ef(this.W);g.sc(this.C);c=window.document.createDocumentFragment();for(var d=-1,e=0,f=a.length;e<f;e++){var k=a[e];if(k instanceof E9)if(k.C){var l=c.getElementById("cp-"+d),m=l.getElementsByClassName("caption-line-text")[0];l=g.Kn(m);g.sa(k.text)&&g.L(m,l.concat(k.text))}else{d++;l=window.document.createElement("div");m=k.start/1E3;b.push(k.start);l.id="cp-"+d;l.className="caption-line";g.Dp(l,"time",m+"");c.appendChild(l);var q=
window.document.createElement("div");q.className="caption-line-time";q.innerHTML=Math.floor(m/60)+":"+(10>m%60?"0":"")+Math.floor(m%60);l.appendChild(q);m=window.document.createElement("div");m.className="caption-line-text";g.sa(k.text)&&g.L(m,k.text);l.appendChild(m)}}this.F&&g.L(g.K("transcript-lang",this.F),n9(this.Y));this.aa=b;this.C.appendChild(c);this.W=g.Cf((0,g.t)(this.pM,this),500)};
g.h.pM=function(){for(var a=this.Qb.getCurrentTime(),b=this.aa,c=this.N,d=c;;){var e=0<=d?b[d]/1E3:-1;if(a+.5<e)--d;else if(e=d+1<b.length?b[d+1]/1E3:1E6,a+.5>e)d+=1;else break}d!=c&&(0<=c&&(a=g.x("cp-"+c),g.O(a,"caption-line-highlight")),0<=d&&(a=g.x("cp-"+d),g.N(a,"caption-line-highlight")),this.N=d,this.V||Nxa(this,g.x("cp-"+(3<=d?d-3:0))))};g.p("yt.www.watch.transcript.open",function(a){Lxa();$9.open(a)},void 0);
g.Zh(g.uq({name:"www/watch_transcript",deps:["www/watch"],page:"watch",init:function(){Lxa()},
dispose:function(){$9&&($9.dispose(),$9=null)}}));})(_yt_www);
