(function(g){var window=this;var aX=function(a){var b=a.itemData.itemId,c=a.config.flowType,d=a.offerData?a.offerData.offerId:null,e=a.innertubeRequestParams,f=a.transactionAction,k={};k.ypc_it=a.itemData.itemType;k.ypc_ii=b;k.ypc_ft=c;e&&(k.ypc_irp=e);d&&(k.ypc_oi=d);f&&(k.ypc_ta=f);return k},dX=function(){var a=bX,b=g.x("legacy-history-iframe");
this.G=this.D=this.C=null;this.F=a;this.K=cX?b:null;this.J=window;this.H=this.J.location;this.W=this.H.href.split("#")[0];this.R=(0,g.t)(this.N,this)},eX=function(a){a=a.H.href;
var b=a.indexOf("#");return 0>b?"":a.substring(b+1)},fX=function(a,b){var c=a.W+"#"+b,d=a.H.href;
d!=c&&d+"#"!=c&&g.dc(a.H,c)},gX=function(a,b){var c=a.K.contentWindow.document,d=c.body?c.body.innerHTML:"",e="#"+g.Ra(b);
d!=e&&(d=g.Sm(g.Um("title",{},window.document.title||""),g.Um("body")),c.open("text/html"),c.write(g.$b(d)),g.L(c.body,e),c.close())},hX=function(){var a=bX;
this.H=this.K=this.C=null;this.D=a;this.G=window;this.F=this.G.location;this.R=(0,g.t)(this.J,this)},wqa=function(){var a=iX("state");
a.setEnabled.call(a,!0,!0)},xqa=function(a){var b=null,c=iX();
b=b||window.history&&window.history.state;c.replace.call(c,a,b,!0)},iX=function(a){var b=g.r("ytglobal.HistoryHistoryInstance");
b||("state"==(void 0===a?"hash":a)?(b=new hX,hX.prototype.setEnabled=hX.prototype.qb,hX.prototype.add=hX.prototype.add,hX.prototype.replace=hX.prototype.replace):(b=new dX,dX.prototype.setEnabled=dX.prototype.qb,dX.prototype.add=dX.prototype.add,dX.prototype.replace=dX.prototype.add),g.p("ytglobal.HistoryHistoryInstance",b,void 0));return b},bX=function(a,b){g.F("navigate",a,b)},lX=function(a){var b=g.D("YPC_LOADER_CSS",void 0),c=g.D("YPC_LOADER_JS",void 0);
jX&&(c="www/ypc_core");kX.length||(kX.push(new g.qe(function(a){g.fi(b,a)})),kX.push(new g.qe(function(a){g.Nf(c,a)})));
g.we(kX).then(function(){a&&a()})},nX=function(a,b,c,d,e){if(g.HC())lX(function(){g.r("yt.www.ypc.checkout.showYpcOverlay")(a,b,c,d,e)});
else{var f={ypc_it:a,ypc_ii:b,ypc_ft:c};d&&(f.ypc_irp=d);e&&(f.ypc_cc=e);f=mX(f);g.hi(f)}},yqa=function(a){if(g.HC())lX(function(){g.r("yt.www.ypc.checkout.showPrepurchaseOverlay")(a)});
else{var b=mX({});g.hi(b)}},oX=function(a,b){if(g.HC())lX(function(){g.r("yt.www.ypc.checkout.showYpcOverlayForInnertubeRequestParams")(a,b)});
else{var c=mX({ypc_ft:a,ypc_irp:b});g.hi(c)}},pX=function(a,b,c){g.HC()?lX(function(){g.r("yt.www.ypc.checkout.offerpurchaser.purchaseOffer")(a,c)}):(b=mX(b),g.hi(b))},qX=function(a,b){if(g.HC())lX(function(){g.r("yt.www.ypc.subscription.openUnsubscribeOverlay")(a,b)});
else throw Error("Unsubscribe triggered when user not signed in.");},mX=function(a){a=g.jg(window.location.href,a);
var b=g.D("YPC_SIGNIN_URL",void 0),c=g.Gp(b)["continue"];c=g.jg(c,{next:a});return g.jg(b,{"continue":c})},zqa=function(a){if(a=a.currentTarget)rX(a),(a=g.E(a,"ytr-prepurchase-html"))&&yqa(g.$l(a))},Aqa=function(a){var b=a.currentTarget;
if(b)if(a=g.E(b,"ypc-transaction-action"),b=g.CK(b,"D")){if(b.gtmData){var c=JSON.parse(b.gtmData);c&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push(c))}(a="start_payment"==a)&&sX("inline-offer-button-click",b.itemData);pX(b,aX(b),a);window.setTimeout(g.Vg,0)}else g.wf(Error("ypc-offer-button does not contain purchaseFlowData."))},Bqa=function(a){(a=a.currentTarget)&&tX(a)},Cqa=function(a){lX(a.ne)},Dqa=function(a){sX("container-button-click-attempt");
var b=g.K("ypc-checkout-button",a.container);(a=g.K("ytr-purchase-button",a.container))?(b=g.B(a,"ypc-offer-button"),(a.href||b)&&a.click()):b&&tX(b)},Eqa=function(a){var b=a.C;
a=b.itemId;var c=b.itemType;b=b.flowType;sX("paid-subscribe-button-click",{itemType:c,itemId:a});nX(c,a,b)},tX=function(a){var b=g.E(a,"ypc-item-type"),c=g.E(a,"ypc-item-id"),d=g.E(a,"ypc-flow-type");
a=g.E(a,"ypc-irp")||void 0;g.HC()?sX("purchase-button-click",{itemId:c,itemType:b}):sX("signin-button-click");nX(b,c,d,a)},uX=function(a){var b=a.currentTarget;
a=g.E(b,"ypc-item-type");b=g.E(b,"ypc-item-id");a&&b&&(sX("unsubscribe-button-click",{itemId:b,itemType:a}),qX(a,b))},Fqa=function(a){var b=a.C;
a=b.itemType;b=b.itemId;sX("paid-unsubscribe-button-click",{itemType:a,itemId:b});qX(a,b)},sX=function(a,b){var c={};
g.lb(c,{label:a,pageName:g.D("PAGE_NAME")});b&&g.lb(c,b);g.Eq("ypc-checkout",g.Tc(c))},rX=function(a){var b;
g.B(a,"yt-unlimited-more-offer-button")?b="YTO_GTM_2_BUTTON_CLICK_DATA":g.B(a,"ypc-offer-button")&&(b="YTO_GTM_1_BUTTON_CLICK_DATA");b&&(a=g.D(b,""))&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push(a))},Gqa=function(a){a=a.currentTarget;
var b=g.E(a,"tab-id");if(b){for(var c=g.J("offer-module-tab-content"),d=0;d<c.length;d++)c[d].classList.remove("active-tab");c=g.J("offer-module-tab");for(d=0;d<c.length;d++)c[d].classList.remove("active-tab");g.x(b).classList.add("active-tab");a.classList.add("active-tab")}},Hqa=function(a){if(a=a.currentTarget){rX(a);
var b=g.CK(a,"U");b?(lX(function(){g.r("yt.www.ypc.checkout.offerpurchaser.completeTransaction")(b)}),window.setTimeout(g.Vg,0)):g.wf(Error("ypc-complete-transaction-button does not contain purchaseFlowData"))}},Jqa=function(){var a=g.Gp(window.location.href);
if(vX){g.ab(Iqa,function(b){g.fb(a,b)});
var b=g.Uc(window.location.href.split("?",2)[0],a);wqa();xqa(b)}},wX=g.C&&8<=window.document.documentMode||g.Lk&&g.wb("1.9.2")||g.yd&&g.wb("532.1"),cX=g.C&&!wX;
dX.prototype.qb=function(a,b){this.D&&(g.Ig(this.D),delete this.D);this.G&&(g.Ef(this.G),delete this.G);if(a){this.C=eX(this);if(cX){var c=this.K.contentWindow.document.body;c&&c.innerHTML||gX(this,this.C)}b||this.F(this.C);wX?this.D=g.H(this.J,"hashchange",this.R):this.G=g.Cf(this.R,200)}};
dX.prototype.N=function(){if(cX){var a=(a=this.K.contentWindow.document.body)?g.Sa(g.Kn(a).substring(1)):"";a!=this.C?(this.C=a,fX(this,a),this.F(a)):(a=eX(this),a!=this.C&&(this.C=a,gX(this,a),this.F(a)))}else a=eX(this),a!=this.C&&(this.C=a,this.F(a))};
dX.prototype.add=function(a,b,c){this.C=""+a;cX&&gX(this,a);fX(this,a);c||this.F(this.C)};hX.prototype.qb=function(a,b){this.H&&(g.Ig(this.H),delete this.H);this.K&&(g.Ef(this.K),delete this.K);a&&vX&&(this.C=this.F.href,b||this.D(this.C),this.H=g.H(this.G,"popstate",this.R))};
hX.prototype.J=function(a){var b=this.F.href;if((a=a.state)||b!=this.C)this.C=b,this.D(b,a)};
hX.prototype.add=function(a,b,c){if(a||b)a=a||this.F.href,this.G.history.pushState(b,"",a),this.C=a,c||this.D(a,b)};
hX.prototype.replace=function(a,b,c){if(a||b)a=a||this.F.href,this.G.history.replaceState(b,"",a),this.C=a,c||this.D(a,b)};
var vX=!!window.history.pushState&&(!g.yd||g.yd&&g.wb("534.11"));var kX=[],jX=!1;var xX=[],yX=[];var Iqa={vQ:"ypc_cc",pR:"ypc_ft",XR:"ypc_irp",dS:"ypc_ii",eS:"ypc_it"};g.Zh(g.uq({name:"www/ypc_bootstrap",deps:["www/common"],page:"feed index results watch channel playlist subscription_manager unlimited live_chat live_dashboard".split(" "),init:function(){jX=!0;g.K("ypc-delayedloader-target")&&lX();var a=g.Gp(window.location.href),b=a.ypc_it,c=a.ypc_ii,d=a.ypc_ft||"D",e=a.ypc_oi,f=a.ypc_irp,k=a.ypc_cc,l=a.ypc_ta;"channel"==g.D("PAGE_NAME")&&"fan_fund"in a&&(d="T",b="U",c=g.D("CHANNEL_ID",void 0));"channel"==g.D("PAGE_NAME")&&"ypc_cc"in a&&(b="U",c=g.D("CHANNEL_ID",
void 0));if(f||c&&b)Jqa(),"start_payment"==l?(a=g.BK(e,b,c,d,k,null,"","",f,l),pX(a,aX(a),!0)):c&&b?nX(b,c,d,f,k):oX(d,f);xX.push(g.P(window.document.body,"click",Bqa,"ypc-checkout-button"),g.P(window.document.body,"click",Aqa,"ypc-offer-button"),g.P(window.document.body,"click",Hqa,"ypc-complete-transaction-button"),g.P(window.document.body,"click",zqa,"ytr-pre-purchase-button"),g.P(window.document.documentElement,"click",uX,"ypc-unsubscribe-link"),g.P(window.document.documentElement,"click",uX,
"ypc-unsubscribe-button"),g.P(window.document.documentElement,"click",Gqa,"offer-module-tab"));yX.push(g.Aq(g.GD,Cqa),g.Aq(g.EL,Dqa),g.Aq(g.HD,Eqa),g.Aq(g.KD,Fqa))},
dispose:function(){kX.length=0;g.Ig(xX);xX.length=0;g.Bq(yX);yX.length=0}}));
g.p("yt.www.ypc.bootstrap.api.loadOffers",nX,void 0);g.p("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams",oX,void 0);})(_yt_www);
