(function(g){var window=this;var Kqa=function(a,b){return g.Ol.apply([],(0,g.Zi)(a,b,void 0))},Lqa=function(a,b){if(-1!=a.indexOf("<"))throw Error("Selector does not allow '<', got: "+a);
var c=a.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(c))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+a);a:{for(var d={"(":")","[":"]"},e=[],f=0;f<c.length;f++){var k=c[f];if(d[k])e.push(d[k]);else if(g.km(d,k)&&e.pop()!=k){c=!1;break a}}c=0==e.length}if(!c)throw Error("() and [] in selector must be balanced, got: "+a);b instanceof g.Sb||(b=g.Pm(b));c=a+"{"+g.Nm(b)+"}";return g.Wb(c)},Mqa=function(a){function b(a){g.ya(a)?
(0,g.z)(a,b):c+=g.Qm(a)}
var c="";(0,g.z)(arguments,b);return g.Wb(c)},zX=function(a){g.ki.call(this,1,arguments);
this.C=a},Nqa=function(a){a&&g.vK("transactionFlowSucceeded",a)},CX=function(a){g.sd.call(this);
this.D=a.flowName;this.F=AX(this);this.C=a.trackingData||{};BX(this,{flowid:this.F,pageName:g.D("PAGE_NAME",null)});this.track("starting-tracking-for-ypc-flow")},BX=function(a,b){g.lb(a.C,b)},Oqa=function(a,b){var c={};
g.ab(b,function(a,b){"object"!=typeof a&&"function"!=typeof a&&(c["purchaseInsertFailure-"+b]=a)});
BX(a,c)},AX=function(a){if(a.F)return a.F;
var b=(0,g.A)();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=(b+16*Math.random())%16|0;b=Math.floor(b/16);return("x"==a?c:c&3|8).toString(16)})},DX=function(){return new CX({flowName:"ypc-checkout"})},EX=function(a){return{itemType:a.itemData.itemType,
itemId:a.itemData.itemId,offerId:a.offerData.offerId}},FX=function(a,b,c,d){a={tipParams:a,
currencyCode:b};c&&(a.customTipAmount=c);d&&(a.tipComment=d);return a},JX=function(a){if(g.C&&!g.wb(9))return[0,
0,0,0];var b=GX.hasOwnProperty(a)?GX[a]:null;if(b)return b;65536<Object.keys(GX).length&&(GX={});var c=[0,0,0,0],d=RegExp("\\\\[0-9A-Fa-f]{1,5}\\s","g");b=HX(a,RegExp("\\\\[0-9A-Fa-f]{6}\\s?","g"));b=HX(b,d);b=HX(b,/\\./g);b=b.replace(RegExp(":not\\(([^\\)]*)\\)","g"),"     $1 ");b=b.replace(RegExp("{[^]*","gm"),"");b=IX(b,c,RegExp("(\\[[^\\]]+\\])","g"),2);b=IX(b,c,RegExp("(#[^\\#\\s\\+>~\\.\\[:]+)","g"),1);b=IX(b,c,RegExp("(\\.[^\\s\\+>~\\.\\[:]+)","g"),2);b=IX(b,c,/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,
3);b=IX(b,c,/(:[\w-]+\([^\)]*\))/gi,2);b=IX(b,c,/(:[^\s\+>~\.\[:]+)/g,2);b=b.replace(/[\*\s\+>~]/g," ");b=b.replace(/[#\.]/g," ");IX(b,c,/([^\s\+>~\.\[:]+)/g,3);b=c;return GX[a]=b},IX=function(a,b,c,d){return a.replace(c,function(a){b[d]+=1;
return Array(a.length+1).join(" ")})},HX=function(a,b){return a.replace(b,function(a){return Array(a.length+1).join("A")})},KX=function(a,b){var c=g.n[a];
return c&&c.prototype?(c=Object.getOwnPropertyDescriptor(c.prototype,b))&&c.get||null:null},LX=function(a,b){var c=g.n[a];
return c&&c.prototype&&c.prototype[b]||null},MX=function(a,b,c,d){if(a)return a.apply(b);
a=b[c];if(!d(a))throw Error("Clobbering detected");return a},NX=function(a,b,c,d){if(a)return a.apply(b,d);
if(g.C&&10>window.document.documentMode){if(!b[c].call)throw Error("IE Clobbering detected");}else if("function"!=typeof b[c])throw Error("Clobbering detected");return b[c].apply(b,d)},OX=function(a){return MX(Pqa,a,"attributes",function(a){return a instanceof window.NamedNodeMap})},PX=function(a,b,c){try{NX(Qqa,a,"setAttribute",[b,
c])}catch(d){if(-1==d.message.indexOf("A security problem occurred"))throw d;}},Sqa=function(a){return MX(Rqa,a,"style",function(a){return a instanceof window.CSSStyleDeclaration})},Uqa=function(a){return MX(Tqa,a,"sheet",function(a){return a instanceof window.CSSStyleSheet})},QX=function(a){return MX(Vqa,a,"nodeName",function(a){return"string"==typeof a})},RX=function(a){return MX(Wqa,a,"nodeType",function(a){return"number"==typeof a})},SX=function(a){return MX(Xqa,a,"parentNode",function(a){return!(a&&
"string"==typeof a.name&&a.name&&"parentnode"==a.name.toLowerCase())})},TX=function(a,b){return NX(Yqa,a,a.getPropertyValue?"getPropertyValue":"getAttribute",[b])||""},UX=function(a,b,c){NX(Zqa,a,a.setProperty?"setProperty":"setAttribute",[b,
c])},ara=function(a){return $qa[a]||null},cra=function(a,b,c){var d=[];
a=VX(g.Ma(a.cssRules));(0,g.z)(a,function(a){if(b&&!/[a-zA-Z][\w-:\.]*/.test(b))throw Error("Invalid container id");if(!(b&&g.C&&10==window.document.documentMode&&/\\['"]/.test(a.selectorText))){var e=b?a.selectorText.replace(bra,"#"+b+" $1"):a.selectorText;d.push(Lqa(e,WX(a.style,c)))}});
return Mqa(d)},VX=function(a){return(0,g.Wi)(a,function(a){return a instanceof window.CSSStyleRule||a.type==window.CSSRule.STYLE_RULE})},dra=function(a,b,c){a=XX("<style>"+a+"</style>");
return null==a?g.el:cra(a.sheet,void 0!=b?b:null,c)},XX=function(a){return g.C&&!g.wb(10)||"function"!=typeof g.n.DOMParser?null:(new window.DOMParser).parseFromString("<html><head></head><body>"+a+"</body></html>","text/html").body.children[0]},WX=function(a,b){if(!a)return g.cl;
for(var c=window.document.createElement("div").style,d=YX(a),e=0;e<d.length;e++){var f=d[e].replace(/^-(?:apple|css|epub|khtml|moz|mso?|o|rim|wap|webkit|xv)-(?=[a-z])/i,"");if(!g.Oa(f,"--")&&!g.Oa(f,"var")){var k=TX(a,f);k=(0,g.Ua)(k);if(""==k)k=null;else if(g.Xl(k,"url("))if(b){a:{k=k.substring(4,k.length-1);for(var l=0;2>l;l++){var m="\"'".charAt(l);if(k.charAt(0)==m&&k.charAt(k.length-1)==m){k=k.substring(1,k.length-1);break a}}}k=b?(k=b(k,f))&&"about:invalid#zClosurez"!=g.Mb(k)?'url("'+g.Mb(k).replace(era,
ara)+'")':null:null}else k=null;else k=0<k.indexOf("(")?1<(k?k.split("(").length-1:0)||!g.Ia(fra,k.substring(0,k.indexOf("(")).toLowerCase())||!g.Pa(k,")")?null:k:k;null!=k&&UX(c,f,k)}}g.Jb("Output of CSS sanitizer");return g.Tb(c.cssText||"")},pra=function(a){var b=Array.from(NX(gra,a,"getElementsByTagName",["STYLE"])),c=Kqa(b,function(a){return g.Ma(Uqa(a).cssRules)});
c=VX(c);c.sort(function(a,b){var c=JX(a.selectorText);a:{for(var d=JX(b.selectorText),e=Math.min(c.length,d.length),f=0;f<e;f++){var w=g.Sl(c[f],d[f]);if(0!=w){c=w;break a}}c=g.Sl(c.length,d.length)}return-c});
a=window.document.createTreeWalker(a,window.NodeFilter.SHOW_ELEMENT,null,!1);for(var d;d=a.nextNode();)(0,g.z)(c,function(a){NX(hra,d,d.matches?"matches":"msMatchesSelector",[a.selectorText])&&a.style&&ora(d,a.style)});
g.z(b,g.tc)},ora=function(a,b){var c=YX(a.style),d=YX(b);
(0,g.z)(d,function(d){if(!(0<=c.indexOf(d))){var e=TX(b,d);UX(a.style,d,e)}})},YX=function(a){g.za(a)?a=g.Ma(a):(a=g.mm(a),g.La(a,"cssText"));
return a},ZX=function(){this.D=[];
this.F=[];this.C="data-elementweakmap-index-"+qra++},rra=function(){},bY=function(a){a=a||new $X;
sra(a);this.C=g.ib(a.C);this.G=g.ib(a.V);this.H=g.ib(a.la);this.J=a.K;(0,g.z)(a.H,function(a){this.C["* "+a.toUpperCase()]=aY},this);
this.R=a.D;this.D=a.N;this.F=null;this.K=a.W},cY=function(a){return function(b,c){var d=a((0,g.Ua)(b),c);
return d&&"about:invalid#zClosurez"!=g.Mb(d)?g.Mb(d):null}},$X=function(){this.C={};
(0,g.z)([tra,ura],function(a){(0,g.z)(g.mm(a),function(a){this.C[a]=aY},this)},this);
this.F={};this.H=[];this.V=g.ib(vra);this.la=g.ib(wra);this.K=!1;this.aa=xra;this.J=this.G=this.Y=this.D=g.$k;this.N=null;this.R=this.W=!1},zra=function(){var a=dY();
g.Na(a.H,yra);return a},dY=function(){var a=new $X;
a.K=!0;a.J=Ara;return a},eY=function(a){a.D=g.Pb;
return a},fY=function(a,b){a.G=b;
return a},Bra=function(a,b){return function(c,d,e,f){c=a(c,d,e,f);
return null==c?null:b(c,d,e,f)}},gY=function(a,b,c,d){a[c]&&!b[c]&&(a[c]=Bra(a[c],d))},sra=function(a){if(a.R)throw Error("HtmlSanitizer.Builder.build() can only be used once.");
gY(a.C,a.F,"* USEMAP",Cra);var b=cY(a.aa);(0,g.z)(["* ACTION","* CITE","* HREF"],function(a){gY(this.C,this.F,a,b)},a);
var c=cY(a.D);(0,g.z)(["* LONGDESC","* SRC","LINK HREF"],function(a){gY(this.C,this.F,a,c)},a);
(0,g.z)(["* FOR","* HEADERS","* NAME"],function(a){gY(this.C,this.F,a,g.u(Dra,this.Y))},a);
gY(a.C,a.F,"A TARGET",g.u(Era,["_blank","_self"]));gY(a.C,a.F,"* CLASS",g.u(Fra,a.G));gY(a.C,a.F,"* ID",g.u(Gra,a.G));gY(a.C,a.F,"* STYLE",g.u(a.J,c));a.R=!0},hY=function(a,b){a||(a="*");
return(a+" "+b).toUpperCase()},Ara=function(a,b,c,d){if(!d.Sk)return null;
b=g.Nm(WX(d.Sk,function(b,d){c.Fw=d;var e=a(b,c);null==e?e=null:(g.Jb("HtmlSanitizerPolicy created with networkRequestUrlPolicy_ when installing '* STYLE' handler."),e=g.Ob(e));return e}));
return""==b?null:b},aY=function(a){return(0,g.Ua)(a)},Era=function(a,b){var c=(0,g.Ua)(b);
return g.Ia(a,c.toLowerCase())?c:null},Cra=function(a){return(a=(0,g.Ua)(a))&&"#"==a.charAt(0)?a:null},Dra=function(a,b,c){return a((0,g.Ua)(b),c)},Fra=function(a,b,c){b=b.split(/(?:\s+)/);
for(var d=[],e=0;e<b.length;e++){var f=a(b[e],c);f&&d.push(f)}return 0==d.length?null:d.join(" ")},Gra=function(a,b,c){return a((0,g.Ua)(b),c)},jY=function(a,b){var c=!("STYLE"in a.G)&&"STYLE"in a.H;
c="*"==a.D&&c?"sanitizer-"+g.dm():a.D;a.F=c;if(iY){var d=b;if(iY){c=g.jn("SPAN");a.F&&"*"==a.D&&(c.id=a.F);a.K&&(d=XX("<div>"+d+"</div>"),pra(d),d=d.innerHTML);var e=window.document.createElement("template");if("content"in e)e.innerHTML=d,e=e.content;else{var f=window.document.implementation.createHTMLDocument("x");e=f.body;f.body.innerHTML=d}d=window.document.createTreeWalker(e,window.NodeFilter.SHOW_ELEMENT|window.NodeFilter.SHOW_TEXT,null,!1);for(e=Hra?new window.WeakMap:new ZX;f=d.nextNode();){c:{var k=
a;var l=f;switch(RX(l)){case 3:k=Ira(k,l);break c;case 1:if("TEMPLATE"==QX(l).toUpperCase())k=null;else{var m=QX(l).toUpperCase();if(m in k.G)var q=null;else k.H[m]?q=window.document.createElement(m):(q=g.jn("SPAN"),k.J&&PX(q,"data-sanitizer-original-tag",m.toLowerCase()));if(q){var w=q,y=OX(l);if(null!=y)for(var I=0;m=y[I];I++)if(m.specified){var R=k;var V=l,T=m,ra=T.name;if(g.Oa(ra,"data-sanitizer-"))R=null;else{var Wa=QX(V);T=T.value;var kb={tagName:(0,g.Ua)(Wa).toLowerCase(),attributeName:(0,g.Ua)(ra).toLowerCase()},
Ud={Sk:void 0};"style"==kb.attributeName&&(Ud.Sk=Sqa(V));V=hY(Wa,ra);V in R.C?(R=R.C[V],R=R(T,kb,Ud)):(ra=hY(null,ra),ra in R.C?(R=R.C[ra],R=R(T,kb,Ud)):R=null)}null===R||PX(w,m.name,R)}k=q}else k=null}break c;default:k=null}}if(k){if(1==RX(k)&&e.set(f,k),f=SX(f),l=!1,f)m=RX(f),q=QX(f).toLowerCase(),w=SX(f),11!=m||w?"body"==q&&w&&(m=SX(w))&&!SX(m)&&(l=!0):l=!0,m=null,l||!f?m=c:1==RX(f)&&(m=e.get(f)),m.content&&(m=m.content),m.appendChild(k)}else g.sc(f)}e.clear&&e.clear()}else c=g.jn("SPAN");0<OX(c).length&&
(d=g.jn("SPAN"),d.appendChild(c),c=d);c=(new window.XMLSerializer).serializeToString(c);c=c.slice(c.indexOf(">")+1,c.lastIndexOf("</"))}else c="";return g.ec(g.Jb("Output of HTML sanitizer"),c)},Ira=function(a,b){var c=b.data,d=SX(b);
d&&"style"==QX(d).toLowerCase()&&!("STYLE"in a.G)&&"STYLE"in a.H&&(c=g.Qm(dra(c,a.F,(0,g.t)(function(a,b){return this.R(a,{Fw:b})},a))));
return window.document.createTextNode(c)},kY=function(){g.Jy.call(this,"promo")},Kra=function(a,b){var c=g.xK.getInstance(),d=a.onSuccess,e=a.onError,f=a.Ya;
c.set(b,Jra([function(b,c){d&&d.call(a.context,b,c);f&&f.call(a.context,b,c)}],[function(b,c){e&&e.call(a.context,b,c);
f&&f.call(a.context,b,c)}]));
a.onSuccess=function(a,d){for(var e=c.get(b),f;f=e.du.shift();)f(a,d);d&&!d.error?(e.xhr=a,e.Dm=d,e.Zg=2,c.set(b,e)):c.C[b]&&delete c.C[b]};
a.onError=function(a,d){for(var e=c.get(b),f;f=e.Uo.shift();)f(a,d);c.C[b]&&delete c.C[b]};
a.Ya=void 0},Lra=function(a,b){2==b.Zg?g.Bf(function(){a.onSuccess&&a.onSuccess.call(a.context,b.xhr,b.Dm);
a.Ya&&a.Ya.call(a.context,b.xhr,b.Dm)},0):1==b.Zg&&(b.du.push(function(b,d){a.onSuccess&&a.onSuccess.call(a.context,b,d);
a.Ya&&a.Ya.call(a.context,b,d)}),b.Uo.push(function(b,d){a.onError&&a.onError.call(a.context,b,d);
a.Ya&&a.Ya.call(a.context,b,d)}))},Jra=function(a,b){return{xhr:new window.XMLHttpRequest,
Dm:{},Zg:1,du:a,Uo:b}},lY=function(a,b){var c=a.itemData;
c=["/offer_details_ajax",a.flowType,c&&c.itemId,c&&c.itemType,a.offerIdsToMatch,a.innertubeRequestParams,a.couponCode];g.Tl(c);c=c.join("-");b.method="POST";b.ha=b.ha||{};b.za={ei:g.D("EVENT_ID",void 0)};var d=b.ha,e=a.itemData,f=a.flowType,k=a.offerIdsToMatch,l=a.innertubeRequestParams,m=a.couponCode;e&&(d.ii=e.itemId,d.it=e.itemType);l&&(d.irp=l);k&&(d.offer_ids=k);m&&(d.cc=m);"T"==f&&(d.action_tip_flow=1);a:{b.context=b.context||g.n;d=g.xK.getInstance();if(c&&d){if((e=d.get(c))&&(2==e.Zg||1==e.Zg)){Lra(b,
e);break a}Kra(b,c)}(e=g.G("/offer_details_ajax",b))&&c&&d&&(d.get(c).xhr=e)}},mY=function(a,b,c,d){c={supressError:!!c};
a&&(c.overlayHtml=a);b&&(c.errorHtml=b);d&&(c.screenOverlayHtml=d);return c},Mra=function(a){var b={offersHtml:a.offers_html,
channelsToSubscriptionidMap:a.channels_to_subscription_id_map,channelInfoMap:a.channel_info_map,componentChannels:a.component_channels,isPurchaseNotAvailable:a.not_available,messageHtml:a.message_html,isPlusPageDirectLogin:a.is_plus_page_direct_login,shouldSkipOverlay:a.should_skip_overlay};b.shouldSkipOverlay&&(b.skipOverlayConfig={offerId:a.offer_id||"",tipConfig:FX(a.serialized_default_tip_params,a.currency_code)});return b},nY=function(a,b,c,d,e){g.ow.call(this);
this.D=a.config;this.C=a.itemData;this.J=a.offerData;this.yb=b;this.F=c;this.G=d;this.K=a.innertubeRequestParams;this.H=e},Nra=function(a){var b=g.D("YPC_TRANSACTION_URL",void 0),c={oid:a.J.offerId,
ps:"C"};a.F&&(c.oc=a.F);a.G&&(c.pp=a.G);var d=g.D("EVENT_ID",void 0);d={flow_uuid:AX(a.yb),ei:d};var e=a.D.flowType;if("T"==e)c.action_tip=1,BX(a.yb,{registerTransactionAction:"action_tip"}),c.ii=a.C.itemId,c.it=a.C.itemType,e=a.D.tipConfig,c.irp=e.tipParams,e.tipComment&&(c.comment=e.tipComment);else if("U"==e)if(d={action_register_upgrade:1},a.H)c.tp=a.H;else{a.oa("ypc-process-order-failure");return}else c.action_register=1,BX(a.yb,{registerTransactionAction:"action_register"}),c.eiid=a.C.itemId,
c.it=a.C.itemType,c.cc=a.D.couponCode,a.K&&(c.irp=a.K);a.yb.track("begin-register-transaction");g.G(b,{method:"POST",context:a,ha:c,za:d,onSuccess:function(a,b){switch(b.status){case 0:var c=b.subscription_id,d=null;c&&(d=b.channel_info);c={subscriptionId:c||null,channelInfo:d};b.post_purchase_redirect_url&&g.uf("YPC_POST_PURCHASE_REDIRECT_URL",b.post_purchase_redirect_url);b.red_theme&&g.uf("YPC_RED_THEME",b.red_theme);var e;b.post_purchase_screen_overlay_html?e=mY(null,null,!1,b.post_purchase_screen_overlay_html):
b.post_purchase_overlay_html&&(e=mY(b.post_purchase_overlay_html));this.yb.track("purchase-insert-success");this.oa("ypc-process-order-success",c,e);break;case 4:this.yb.track("purchase-insert-sync-required");this.oa("ypc-process-order-failure");break;case 2:this.yb.track("purchase-insert-rejected");this.oa("ypc-process-order-failure");break;default:this.yb.track("purchase-insert-failure"),this.oa("ypc-process-order-failure")}},
onError:function(a,b){Oqa(this.yb,{http_status:a.status,servlet_status:b&&b.status});this.yb.track("purchase-insert-failure");this.oa("ypc-process-order-failure")}})},oY=function(a,b,c){g.ow.call(this);
this.F=a.config;this.D=a.itemData;this.K=a.offerData;this.yb=b;this.Lj=a;this.C=null;this.G=a.innertubeRequestParams;this.H=a.transactionLoggingParams;this.J=c},Ora=function(a){var b=g.D("YPC_TRANSACTION_URL",void 0),c={oid:a.K.offerId},d=g.D("EVENT_ID",void 0);
d={flow_uuid:AX(a.yb),ei:d};var e=a.F.flowType;if("T"==e){c.ii=a.D.itemId;c.it=a.D.itemType;var f=a.F.tipConfig;c.action_request_tip=1;BX(a.yb,{requestTransactionAction:"action_request_tip"});c.tp=f.tipParams;c.cur=f.currencyCode;f.customTipAmount&&(c.ca=f.customTipAmount)}else c.action_request=1,a.G&&(c.irp=a.G),BX(a.yb,{requestTransactionAction:"action_request"});a.F.couponCode&&(c.cc=a.F.couponCode);g.G(b,{method:"POST",za:d,ha:c,context:a,onSuccess:function(b,c){a.yb.track("dynamic-success");
if(c.error_confirm_dialog_html){var d=c.error_confirm_dialog_html,e=new bY(fY(eY(dY()),g.Bl));a.oa("ypc-close-offer-overlay");var f=window.document.createElement("div");window.document.body.appendChild(f);g.Vm(f,jY(e,d));(d=g.tn(f))&&(new g.aA(d)).show()}else g.zh("buyFlowStarted",{offerParams:a.G}),pY(a,c.encrypted_purchase_params)},
onError:function(a,b){var c=b.innertube_error_code,d=b.error||null;this.yb.track("dynamic-error",{dynamicErrorStatus:b.status});var f="D"==e&&"start_payment"==this.Lj.transactionAction;"T"==e&&"INVALID_VALUE"==c?this.oa("ypc-tip-validation-error",{errorMessage:d}):f&&"FORBIDDEN"==c?this.oa("ypc-direct-purchase-error",{errorMessage:d}):qY(this,d)}})},pY=function(a,b){var c=g.yK.getInstance();
a.yb.track("mb-start");a.oa("ypc-purchase-wallet-start");var d=(0,g.t)(a.J.F,a.J,a.D,a.K);g.zK(c,b,(0,g.t)(a.jG,a),(0,g.t)(a.lG,a),(0,g.t)(a.kG,a),(0,g.t)(a.kD,a),d,void 0,a.H)},rY=function(a,b,c,d){a.C=new nY(a.Lj,a.yb,b,c,d);
a.C&&(a.C.subscribe("ypc-process-order-success",a.UG,a),a.C.subscribe("ypc-process-order-failure",a.TG,a));Nra(a.C)},qY=function(a,b,c){a.oa("ypc-post-purchase-init",mY(null,b,c))},sY=function(a){a.C&&(a.C.dispose(),a.C=null)},tY=function(){this.D=g.D("YPC_TRANSACTION_URL",void 0);
this.C=void 0},uY=function(a){g.sd.call(this);
this.F=new g.iH(this);this.C=g.K("ypc-offer-overlay-container");this.rb=a;this.H=[];this.K=[];this.af();this.wh()},vY=function(a,b){this.G=g.K(a);
this.D=b;this.C=this.F=null},wY=function(a){var b=window.document.createElement("div");
b.innerHTML=a;window.document.body.appendChild(b);this.id="ypc-offer-overlay"},yY=function(a,b){b&&g.lb(xY,b);
var c=a.L("ypc-offer-overlay-container");g.bp(c,g.lm(xY))},zY=function(a){uY.call(this,a);
g.jH(this.F,this.C,"click",this.G,"unlimited-family-message-action-button");g.jH(this.F,this.C,"click",this.R,"unlimited-family-message-not-now-button")},AY=function(){wY.call(this,g.wq("YPC_OFFER_OVERLAY"));
this.F=Pra();this.C=null},Pra=function(){return new bY(fY(eY(zra()),function(a){return a}))},CY=function(a){var b=g.K("ypc-offer-overlay-container"),c=g.K("yt-dialog-show-content"),d=g.M(c,"yt-dialog-base");
b&&BY(b,a);c&&BY(c,a);d&&BY(d,a)},BY=function(a,b){a&&(b&&!g.B(a,"ytr-style-unicorn-iframe-container")?g.N(a,"ytr-style-unicorn-iframe-container"):!b&&g.B(a,"ytr-style-unicorn-iframe-container")&&g.O(a,"ytr-style-unicorn-iframe-container"))},DY=function(a,b,c){uY.call(this,a);
this.G=b;this.rb=a;this.flowType=c;this.D=null},GY=function(a,b){EY(a.rb);
FY(a,b);a.D=new oY(b,a.G,new tY);a.ij(a.D);var c=a.D,d=c.Lj.walletPrefetchdata;d&&d.encryptedPurchaseParams?(g.zh("buyFlowStarted",{offerParams:c.G}),pY(c,d.encryptedPurchaseParams)):Ora(c)},FY=function(a,b){var c=b.itemData;
c={itemType:c.itemType,itemId:c.itemId,offerId:b.offerData.offerId,flowType:a.flowType};var d=b.config.couponCode;d&&(c.couponCode=d);BX(a.G,c)},HY=function(a){a.D&&(a.D.dispose(),a.D=null)},IY=function(a,b){DY.call(this,a,b,"D")},Qra=function(a,b){var c=b.updated_offers,d=b.coupon_code,e=!1;
typeof("number"==b.status&&c)&&(0,g.z)(g.J("ypc-coupon-updatable",a.C),function(a){var b=g.E(a,"ypc-offer-id");b=c[b];if(b.is_coupon_applied){var f;g.B(a,"ypc-coupon-updatable-offer-price-text")?f=b.updated_display_price:g.B(a,"ypc-coupon-updatable-free-trial-text")&&(f=b.updated_free_trial_text);f&&(g.L(a,f),g.Dp(a,"coupon-code",d),e=!0)}},a);
return e},JY=function(a,b){var c=g.K("ypc-offer-overlay-coupon-section",a.C),d=g.K("ypc-offer-overlay-show-coupon-input",a.C),e=g.K("ypc-offer-overlay-apply-coupon",a.C);
g.bp(c,["ypc-valid-coupon","ypc-invalid-coupon"]);b?(g.N(c,"ypc-valid-coupon"),d.disabled=!0,e.disabled=!0):(g.N(c,"ypc-invalid-coupon"),d.value="",d.focus())},KY=function(a,b){b.error&&g.L(g.K("ypc-offer-overlay-show-coupon-error",a.C),b.error)},LY=function(a,b){DY.call(this,a,b,"T")},Rra=function(a){var b=null,c=null;
(0,g.z)(g.J("ypc-tip-choice",a.C),function(a){a.checked&&(b=a.value)});
if(g.K("ypc-tip-choice-custom",a.C).checked&&(c=g.K("ypc-tip-custom-amount-input",a.C).value,!(c&&(0,window.isFinite)(c)&&0<(0,window.parseFloat)(c))))return MY(a,""),null;var d=g.K("ypc-tip-comment-input",a.C);return FX(b,g.K("ypc-tip-currency-input",a.C).value,c,d?d.value:null)},MY=function(a,b){g.gz(g.K("ypc-tip-custom-amount-input-container",a.C),b);
NY(a.rb)},OY=function(a){g.hz(g.K("ypc-tip-custom-amount-input-container",a.C))},PY=function(){wY.call(this,g.wq("YPC_OFFER_OVERLAY"))},QY=function(a,b){var c=b.flowTracker,d=b.itemData,e=b.flowType;
c.track("flow-start",{itemType:d&&d.itemType,itemId:d&&d.itemId,flowType:e,innertubeRequestParams:b.innertubeRequestParams,couponCode:b.couponCode});g.ni("ypc-purchase-flow-start",new zX(e));a.ud();Sra(a,e);lY(b,{context:a,onSuccess:function(a,d){c.track("flow-offers-load-success");var e=Mra(d),f=e.offersHtml,k=e.channelsToSubscriptionidMap,w=e.componentChannels,y=e.isPurchaseNotAvailable;f?(g.yK.getInstance().load(),this.Be(f)):k&&!g.eb(k)?(g.ni(g.FL,new g.AD(k,e.channelInfoMap)),(0,g.z)(w,function(a){g.ni(g.CL,
new g.hD(a))}),c.track("flow-offers-already-purchased-error"),this.cd(e.messageHtml)):y?(c.track("flow-offers-not-available-error"),Tra(this,d.message_html,b.flowType,e.isPlusPageDirectLogin)):(c.track("flow-offers-load-error"),this.cd(e.messageHtml))},
onError:function(){c.track("flow-offers-load-error");this.cd()},
Ya:function(){this.Je(c,e)}})},EY=function(a){a=RY(a);
(0,g.z)(a,function(a){a.disabled=!0})},NY=function(a){a=RY(a);
(0,g.z)(a,function(a){a.disabled=!1})},RY=function(a){var b=[];
a=a.L("ypc-offer-overlay-container");if(!a)return b;(0,g.z)(g.en("button",null,a),function(a){b.push(a)});
(0,g.z)(g.en("input",null,a),function(a){b.push(a)});
return b},Sra=function(a,b){var c=a.L("ypc-offer-overlay-container");
g.bp(c,g.lm(Ura));"T"==b?g.N(c,"ypc-offer-overlay-flow-tip"):g.N(c,"ypc-offer-overlay-flow-default")},Tra=function(a,b,c,d){b&&(d?(a.bd("ypc-offer-overlay-show-plus-page-not-available-error"),a=a.L("ypc-offer-plus-page-not-available-content")):"T"==c?(a.bd("ypc-offer-overlay-show-tip-not-available-error"),a=a.L("ypc-offer-overlay-tip-not-available-content")):(a.bd("ypc-offer-overlay-show-not-available-error"),a=a.L("ypc-offer-overlay-not-available-content")),a.innerHTML=b)},SY=function(a,b){DY.call(this,
a,b,"D");
g.jH(this.F,this.C,"click",this.ls,"ypc-offer-button");g.jH(this.F,this.C,"click",this.R,"unlimited-family-message-continue-button")},TY=function(){PY.call(this)},UY=function(a){if(a){var b=TY.getInstance();
b.ud();b.Be(a);b.Je(DX(),"")}},VY=function(){g.sd.call(this);
this.C=g.D("PAGE_NAME",null);this.D=g.D("CHANNEL_TAB",null);this.F=[];g.nB(kY);this.F.push(g.Aq(g.OD,this.G,this),g.Aq(g.PD,this.H,this))},WY=function(a,b){if(g.D("CHANNEL_ID")==a){var c=g.J("yt-badge-ypc");
c=(0,g.Wi)(c,function(a){var b=g.B(a,"yt-badge-ypc-purchased");a=g.B(a,"yt-badge-ypc-free");return!b&&!a});
b?g.Q.apply(null,c):g.S.apply(null,c)}},XY=function(a){var b=g.K("ypc-channel-offer-card-container",g.K("primary-header-actions"));
b&&g.cp(b,"purchased",!a)},YY=function(){g.sd.call(this);
this.G=g.D("PAGE_NAME",null);this.C=!1;this.F=null;this.D=[];this.D.push(g.Aq(g.GL,this.K,this),g.Aq("ypc-purchase-flow-end",this.H,this))},Wra=function(){var a=[];
(0,g.z)(Vra,function(b){g.Na(a,g.J(b))});
(0,g.z)(a,function(a){var b=g.E(a,"ypc-item-type"),d=g.E(a,"ypc-item-id"),e=g.E(a,"ypc-flow-type");a=g.E(a,"ypc-irp");e=e||"D";b={itemId:d,itemType:b};var f=DX();f.track("triggering-prefetch");e={itemData:b,flowType:e,flowTracker:f};a&&(e.innertubeRequestParams=a);lY(e,{onSuccess:function(){f.track("prefetch-triggered")},
onError:function(){f.track("prefetch-trigger-failed")},
Ya:function(){f.dispose()}})})},ZY=function(){var a=g.wq("YPC_UNSUBSCRIBE_OVERLAY"),b=window.document.createElement("div");
b.innerHTML=a;window.document.body.appendChild(b)},Xra=function(a){var b=a.currentTarget;
a=g.E(b,"ypc-item-type");b=g.E(b,"ypc-item-id");a&&b&&$Y(a,b)},Yra=function(a,b){var c=ZY.getInstance();
g.G(g.D("YPC_SUBSCRIPTION_URL",void 0),{method:"GET",za:{action_pre_cancel_confirm:1,it:a,ii:b},onSuccess:function(a,b){var d=b.header,e=b.html,l=b.confirm_button_text,m=b.keep_button_text,q=b.help_url,w=b.is_plus_page_error;b.is_xauth_subscription?c.ze("ypc-unsubscribe-overlay-xauth"):w?c.ze("ypc-unsubscribe-overlay-plus-page-error"):(d&&(g.K("ypc-unsubscribe-overlay-title",c.Ta()).innerHTML=d),e&&(d=g.K("ypc-unsubscribe-overlay-confirm-content",c.Ta()),d.innerHTML=e),q&&(d=g.K("ypc-unsubscribe-help",
c.Ta()),g.cc(d,q)),l&&(d=g.K("ypc-unsubscribe-confirm",c.Ta()),d.innerHTML=l),m&&(d=g.K("ypc-unsubscribe-keep",c.Ta()),d.innerHTML=m),c.ze("ypc-unsubscribe-overlay-confirm"))},
onError:function(){c.cd()}})},$Y=function(a,b){ZY.getInstance().show();
g.G(g.D("YPC_TRANSACTION_URL",void 0),{method:"POST",ha:{action_cancel:1,it:a,ii:b},onSuccess:function(c,d){var e=d.status,f=d.component_channels,k=d.title,l=d.html;0===e?(e=ZY.getInstance(),k&&(g.K("ypc-unsubscribe-overlay-title-success",e.Ta()).innerHTML=k),l&&(g.K("ypc-unsubscribe-overlay-content-success",e.Ta()).innerHTML=l),e.ze("ypc-unsubscribe-overlay-success"),aZ(a,b,f)):3==e?(ZY.getInstance().ze("ypc-unsubscribe-overlay-delayed"),aZ(a,b,f)):ZY.getInstance().cd()},
onError:function(){ZY.getInstance().cd()}})},aZ=function(a,b,c){var d={itemType:a,
itemId:b},e=[];g.Na(e,g.J("ypc-unsubscribe-link"),g.J("ypc-unsubscribe-label"));e=bZ(e,a,b);g.S.apply(null,e);a=bZ(g.J("ypc-unsubscribe-complete"),a,b);g.Q.apply(null,a);g.ni(g.HL,new g.CD(d,c))},bZ=function(a,b,c){return(0,g.Wi)(a,function(a){var d=g.E(a,"ypc-item-type");
a=g.E(a,"ypc-item-id");return d==b&&a==c})},$ra=function(){cZ||(cZ=!0,dZ.push(g.P(window.document.documentElement,"click",Xra,"ypc-unsubscribe-confirm")));
eZ.push(g.Aq("ypc-purchase-flow-start",Zra),g.Aq(g.KD,function(){new VY}));
g.xK.getInstance().init();g.D("PREFETCH_YPC_OFFERS")&&Wra()},Zra=function(a){new YY;
new VY;"watch"==g.D("PAGE_NAME",null)&&"T"!=a.C&&(a=g.r("yt.www.watch.player.pause"),"function"==typeof a&&a())};
g.v(zX,g.ki);g.v(CX,g.sd);CX.prototype.X=function(){this.track("end-of-tracking-for-ypc-flow");CX.M.X.call(this);g.om(this)};
CX.prototype.track=function(a,b){b=b||{};var c=g.D("PAGE_NAME",null),d=this.C.jstimestamp||null,e=(0,g.A)();d=d?e-d:null;g.lb(b,{label:a,pageName:c,jstimestamp:e,previousTimeLoggedAt:this.C.label||null,timeFromLastTrack:d,netFlowTime:(this.C.netFlowTime||null)+d});BX(this,b);g.Eq(this.D,g.Tc(this.C))};
var GX={};var tra={"* ARIA-CHECKED":!0,"* ARIA-COLCOUNT":!0,"* ARIA-COLINDEX":!0,"* ARIA-DESCRIBEDBY":!0,"* ARIA-DISABLED":!0,"* ARIA-LABEL":!0,"* ARIA-LABELLEDBY":!0,"* ARIA-READONLY":!0,"* ARIA-REQUIRED":!0,"* ARIA-ROWCOUNT":!0,"* ARIA-ROWINDEX":!0,"* ARIA-SELECTED":!0,"* ABBR":!0,"* ACCEPT":!0,"* ACCESSKEY":!0,"* ALIGN":!0,"* ALT":!0,"* AUTOCOMPLETE":!0,"* AXIS":!0,"* BGCOLOR":!0,"* BORDER":!0,"* CELLPADDING":!0,"* CELLSPACING":!0,"* CHAROFF":!0,"* CHAR":!0,"* CHECKED":!0,"* CLEAR":!0,"* COLOR":!0,"* COLSPAN":!0,
"* COLS":!0,"* COMPACT":!0,"* COORDS":!0,"* DATETIME":!0,"* DIR":!0,"* DISABLED":!0,"* ENCTYPE":!0,"* FACE":!0,"* FRAME":!0,"* HEIGHT":!0,"* HREFLANG":!0,"* HSPACE":!0,"* ISMAP":!0,"* LABEL":!0,"* LANG":!0,"* MAXLENGTH":!0,"* METHOD":!0,"* MULTIPLE":!0,"* NOHREF":!0,"* NOSHADE":!0,"* NOWRAP":!0,"* READONLY":!0,"* REL":!0,"* REV":!0,"* ROLE":!0,"* ROWSPAN":!0,"* ROWS":!0,"* RULES":!0,"* SCOPE":!0,"* SELECTED":!0,"* SHAPE":!0,"* SIZE":!0,"* SPAN":!0,"* START":!0,"* SUMMARY":!0,"* TABINDEX":!0,"* TITLE":!0,
"* TYPE":!0,"* VALIGN":!0,"* VALUE":!0,"* VSPACE":!0,"* WIDTH":!0},ura={"* USEMAP":!0,"* ACTION":!0,"* CITE":!0,"* HREF":!0,"* LONGDESC":!0,"* SRC":!0,"LINK HREF":!0,"* FOR":!0,"* HEADERS":!0,"* NAME":!0,"A TARGET":!0,"* CLASS":!0,"* ID":!0,"* STYLE":!0};var Pqa=KX("Element","attributes")||KX("Node","attributes"),fZ=LX("Element","hasAttribute"),gZ=LX("Element","getAttribute"),Qqa=LX("Element","setAttribute"),asa=LX("Element","removeAttribute"),gra=LX("Element","getElementsByTagName"),hra=LX("Element","matches")||LX("Element","msMatchesSelector"),Vqa=KX("Node","nodeName"),Wqa=KX("Node","nodeType"),Xqa=KX("Node","parentNode"),Rqa=KX("HTMLElement","style")||KX("Element","style"),Tqa=KX("HTMLStyleElement","sheet"),Yqa=LX("CSSStyleDeclaration","getPropertyValue"),
Zqa=LX("CSSStyleDeclaration","setProperty");var era=/[\n\f\r"'()*<>]/g,$qa={"\n":"%0a","\f":"%0c","\r":"%0d",'"':"%22","'":"%27","(":"%28",")":"%29","*":"%2a","<":"%3c",">":"%3e"},bra=g.C&&10>window.document.documentMode?null:RegExp("\\s*([^\\s'\",]+[^'\",]*(('([^'\\r\\n\\f\\\\]|\\\\[^])*')|(\"([^\"\\r\\n\\f\\\\]|\\\\[^])*\")|[^'\",])*)","g"),fra="rgb rgba alpha rect image linear-gradient radial-gradient repeating-linear-gradient repeating-radial-gradient cubic-bezier matrix perspective rotate rotate3d rotatex rotatey steps rotatez scale scale3d scalex scaley scalez skew skewx skewy translate translate3d translatex translatey translatez".split(" ");var Hra="undefined"!=typeof window.WeakMap&&-1!=window.WeakMap.toString().indexOf("[native code]"),qra=0;ZX.prototype.set=function(a,b){if(NX(fZ,a,"hasAttribute",[this.C])){var c=(0,window.parseInt)(NX(gZ,a,"getAttribute",[this.C])||null,10);this.F[c]=b}else c=this.F.push(b)-1,PX(a,this.C,c.toString()),this.D.push(a);return this};
ZX.prototype.get=function(a){if(NX(fZ,a,"hasAttribute",[this.C]))return a=(0,window.parseInt)(NX(gZ,a,"getAttribute",[this.C])||null,10),this.F[a]};
ZX.prototype.clear=function(){this.D.forEach(function(a){NX(asa,a,"removeAttribute",[this.C])},this);
this.D=[];this.F=[]};var iY=!g.C||g.yb(10);var vra={APPLET:!0,AUDIO:!0,BASE:!0,BGSOUND:!0,EMBED:!0,FORM:!0,IFRAME:!0,ISINDEX:!0,KEYGEN:!0,LAYER:!0,LINK:!0,META:!0,OBJECT:!0,SCRIPT:!0,SVG:!0,STYLE:!0,TEMPLATE:!0,VIDEO:!0};var wra={A:!0,ABBR:!0,ACRONYM:!0,ADDRESS:!0,AREA:!0,ARTICLE:!0,ASIDE:!0,B:!0,BDI:!0,BDO:!0,BIG:!0,BLOCKQUOTE:!0,BR:!0,BUTTON:!0,CAPTION:!0,CENTER:!0,CITE:!0,CODE:!0,COL:!0,COLGROUP:!0,DATA:!0,DATALIST:!0,DD:!0,DEL:!0,DETAILS:!0,DFN:!0,DIALOG:!0,DIR:!0,DIV:!0,DL:!0,DT:!0,EM:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FONT:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,I:!0,IMG:!0,INPUT:!0,INS:!0,KBD:!0,LABEL:!0,LEGEND:!0,LI:!0,MAIN:!0,MAP:!0,MARK:!0,MENU:!0,METER:!0,
NAV:!0,NOSCRIPT:!0,OL:!0,OPTGROUP:!0,OPTION:!0,OUTPUT:!0,P:!0,PRE:!0,PROGRESS:!0,Q:!0,S:!0,SAMP:!0,SECTION:!0,SELECT:!0,SMALL:!0,SOURCE:!0,SPAN:!0,STRIKE:!0,STRONG:!0,STYLE:!0,SUB:!0,SUMMARY:!0,SUP:!0,TABLE:!0,TBODY:!0,TD:!0,TEXTAREA:!0,TFOOT:!0,TH:!0,THEAD:!0,TIME:!0,TR:!0,TT:!0,U:!0,UL:!0,VAR:!0,WBR:!0};g.v(bY,rra);var xra=g.Pb;g.v(kY,g.Jy);g.wa(kY);kY.prototype.register=function(){g.X(this,"click",this.C)};
kY.prototype.unregister=function(){g.Y(this,"click",this.C)};
kY.prototype.C=function(a){a=this.Ta(a);a=this.ka(a,"promo-id");(new g.OE(a)).write("write_dismiss")};g.v(nY,g.ow);nY.prototype.X=function(){this.yb.track("dispose-orderprocessor");this.F=null;nY.M.X.call(this)};g.v(oY,g.ow);g.h=oY.prototype;g.h.X=function(){this.yb.track("dispose-offerpurchase");sY(this);oY.M.X.call(this)};
g.h.jG=function(a){this.oa("ypc-purchase-wallet-end");a&&a.checkoutOrderId?(a=a.checkoutOrderId,this.yb.track("mb-complete",{orderId:a}),rY(this,a,null,null)):a&&a.integratorData?rY(this,null,a.integratorData,null):(a=a.error,this.yb.track("mb-complete-error",{mbCompleteErrorCode:a}),qY(this,null,"-1"==String(a)))};
g.h.lG=function(){this.yb.track("mb-ready")};
g.h.kG=function(a){this.oa("ypc-purchase-wallet-end");this.yb.track("mb-error");this.yb.track("mb-error",{mbFailureErrorName:a.name,mbFailureErrorMessage:a.message?a.message.substring(0,1400):""});qY(this,null,!0)};
g.h.kD=function(a){this.yb.track("mb-"+a)};
g.h.UG=function(a,b){sY(this);g.AK(g.D("DBLCLK_YPC_ACTIVITY_GROUP",void 0),"brrim580");var c=this.F.flowType,d=this.D.itemId,e=this.D.itemType,f={it:e,ii:d};b?this.oa("ypc-post-purchase-init",b):("T"==c?(f.action_tip_flow=1,BX(this.yb,{postPurchaseAction:"action_tip_flow"})):f.oid=this.K.offerId,this.yb.track("post-purchase-request"),c=g.D("YPC_POST_PURCHASE_URL",void 0),"YPC_RED_THEME"in g.tf&&(f.red_theme=g.D("YPC_RED_THEME",void 0)),g.G(c,{method:"GET",context:this,za:f,Ya:function(a,b){this.oa("ypc-post-purchase-init",
mY(b.html,b.error))}}));
g.ni(g.GL,new g.BD({itemType:e,itemId:d},a,e,d));Nqa(this.H)};
g.h.TG=function(){sY(this);this.oa("ypc-post-purchase-init",mY());g.wK("TRANSACTION_ERROR_TYPE_YPC_COMPLETE_TRANSACTION_RPC_FAILURE",this.H)};tY.prototype.F=function(a,b,c){a={action_log_payment_server_analytics:1,backend_analytics_event:c,it:a.itemType,ii:a.itemId,oid:b.offerId};this.C&&(a.session_token=this.C);g.G(this.D,{method:"POST",ha:a,context:this})};g.v(uY,g.sd);uY.prototype.X=function(){this.F.removeAll();g.Kf(this.H);this.H.length=0;g.Bq(this.K);this.K.length=0;uY.M.X.call(this)};
uY.prototype.af=function(){g.jH(this.F,this.C,"click",this.yd,"ypc-offer-overlay-close")};
uY.prototype.wh=function(){this.H.push(g.Jf("dispose",this.yd,this))};
uY.prototype.yd=function(a){a instanceof g.Ag&&a.preventDefault();this.rb&&this.rb.hide();this.dispose()};g.v(vY,g.sd);g.h=vY.prototype;g.h.start=function(a,b,c,d,e,f){this.C=g.Bf((0,g.t)(this.abort,this,a),3E5);g.av("family_creation",(0,g.t)(this.IO,this,a,b,c,d,e,f))};
g.h.abort=function(a){this.C&&(this.C&&(g.Df(this.C),this.C=null),a.rb.cd(),g.tc(this.F))};
g.h.IO=function(a,b,c,d,e,f){var k=g.D("YTR_FAMILY_CREATION_URL");g.jm(f)&&(k=g.ig(k,f||{},!1));f=g.r("gapi.config.update");g.Aa(f)&&f("iframes/family_creation/url",k);a={clientId:3,initialflow:[4,5,6,7],authUser:g.D("SESSION_INDEX")||0,onFlowComplete:(0,g.t)(this.xF,this,a,d),OnError:(0,g.t)(this.pF,this,a,e),onReady:(0,g.t)(this.ZG,this,a,c)};b&&(a.hl=b);b=g.r("gapi.family_creation.render");g.Aa(b)&&(this.F||(this.F=g.K(this.D),this.F||(this.F=g.qc("div",this.D),this.G.appendChild(this.F))),b(this.F,
a))};
g.h.xF=function(a,b){a.yd(null,!1,b)};
g.h.pF=function(a,b){a.yd(null,!1,b)};
g.h.ZG=function(a,b){if(this.C){this.C&&(g.Df(this.C),this.C=null);if(b){var c=g.r("gapi.family_creation.setConfig");g.Aa(c)&&c(0,b)}a.rb.bd("ypc-offer-overlay-show-unicorn-iframe-in-content")}};var xY={OW:"ypc-offer-overlay-show-loading",Jv:"ypc-offer-overlay-show-error",Iv:"ypc-offer-overlay-show-offers-content",PW:"ypc-offer-overlay-show-not-available-error"};g.h=wY.prototype;g.h.hide=function(){g.nA.getInstance().hide()};
g.h.show=function(a){a=g.jc(a);g.nA.getInstance().show(a)};
g.h.L=function(a){var b=g.rA();return b?g.K(a,b):null};
g.h.bd=function(a){var b=this.L("ypc-offer-overlay-container");g.N(b,a)};
g.h.ud=function(){this.show(this.id);this.bd("ypc-offer-overlay-show-loading")};g.v(zY,uY);zY.prototype.R=function(a){(a=g.ys(a.currentTarget,"come_back_html"))?this.rb.Be(g.$l(a),!0):(a=this.rb,a.C?(a.Be(a.C),a=!0):a=!1,a||this.yd(null,!1,null))};
zY.prototype.G=function(a){var b=g.ys(a.currentTarget,"is_unicorn_debug_enabled"),c=g.ys(a.currentTarget,"hl"),d=g.ys(a.currentTarget,"rpcid_params"),e=g.ys(a.currentTarget,"success_redirect_url");a=g.ys(a.currentTarget,"error_redirect_url");this.rb.ud();this.D||(this.D=new vY("ypc-offer-overlay-content-wrapper","unlimited-family-message-overlay-container"));a:{if(b&&"true"==b&&(b=g.Gp(window.location.href).unicorn)){b=g.hg((0,window.decodeURIComponent)(b));break a}b={}}this.D.start(this,c,d,e,a,
b)};
zY.prototype.yd=function(a,b,c){a instanceof g.Ag&&a.preventDefault();this.rb&&this.rb.hide();c?g.ii(c):b&&window.location.reload(!0);this.dispose()};g.v(AY,wY);g.wa(AY);var yra="data-come_back_html data-error_redirect_url data-hl data-is_unicorn_debug_enabled data-rpcid_params data-sessionlink data-success_redirect_url data-url data-visibility-tracking data-ytimg".split(" "),bsa={Kv:"ypc-offer-overlay-show-unicorn-iframe-in-content"};g.h=AY.prototype;g.h.Be=function(a,b){var c=this.L("ypc-offer-overlay-content-wrapper");a&&c&&(g.Vm(c,jY(this.F,a)),this.bd("ypc-offer-overlay-show-offers-content"),b||(this.C=a))};
g.h.cd=function(a){var b=this.L("ypc-offer-overlay-error");g.O(b,"ypc-offer-overlay-show-custom-error");var c=this.L("ypc-offer-overlay-error-custom-content");a&&c&&(g.N(b,"ypc-offer-overlay-show-custom-error"),g.Vm(c,jY(this.F,a)));this.bd("ypc-offer-overlay-show-error")};
g.h.hide=function(){var a=this.L("ypc-offer-overlay-content-wrapper");a&&g.sc(a);AY.M.hide.call(this)};
g.h.bd=function(a){yY(this,bsa);AY.M.bd.call(this,a);"ypc-offer-overlay-show-unicorn-iframe-in-content"==a?CY(!0):CY(!1)};
g.h.Je=function(){return new zY(this)};g.v(DY,uY);g.h=DY.prototype;g.h.X=function(){this.G.track("dispose-OfferOverlay-EventsManager");HY(this);this.G.dispose();this.F.removeAll();g.Kf(this.H);this.H.length=0;g.Bq(this.K);this.K.length=0;DY.M.X.call(this)};
g.h.af=function(){DY.M.af.call(this);g.jH(this.F,this.C,"click",this.ls,"ypc-offer-overlay-offer-button");g.jH(this.F,this.C,"click",this.NG,"ypc-post-purchase-overlay-done-button");g.jH(this.F,this.C,"click",this.YH,"ypc-offer-overlay-switch-accounts-button")};
g.h.ij=function(a){a&&(a.subscribe("ypc-purchase-wallet-start",this.OI,this),a.subscribe("ypc-purchase-wallet-end",this.NI,this),a.subscribe("ypc-post-purchase-init",this.lJ,this),a.subscribe("ypc-direct-purchase-error",this.Mw,this),a.subscribe("ypc-close-offer-overlay",this.DE,this))};
g.h.yd=function(a){a instanceof g.Ag&&a.preventDefault();this.rb&&this.rb.hide();g.ni("ypc-purchase-flow-end");this.dispose()};
g.h.ls=function(a){if(a=a.currentTarget)if(a=g.CK(a,this.flowType)){try{this.rn(a)}catch(b){return}this.G.track("initiate-purchase-from-offeroverlay");GY(this,a)}else g.wf(Error("ypc-offer-overlay-offer-button does not contain purchaseFlowData."))};
g.h.rn=function(){};
g.h.OI=function(){this.rb&&this.rb.hide();g.eq()};
g.h.NI=function(){g.fq();this.rb.ud()};
g.h.lJ=function(a){HY(this);var b=a.overlayHtml||null,c=a.screenOverlayHtml||null,d=a.errorHtml||null;a=!!a.supressError;c?(b=AY.getInstance(),b.ud(),b.Be(c),b.Je()):b?this.rb.Be(b):a?this.yd(null):d?this.rb.cd(d):this.rb.cd()};
g.h.NG=function(){var a=[];(0,g.z)(g.J("subscription-list-item",this.C),function(b){g.B(b,"selected")&&a.push(g.E(b,"channel-id"))});
a.length?(this.rb.ud(),g.ni(g.yL,new g.gD(a))):this.yd(null)};
g.h.YH=function(a){a.preventDefault();g.ii(g.jg(g.D("YPC_SWITCH_URL",void 0),{next:window.location.href}))};
g.h.Mw=function(a){HY(this);a=a.errorMessage||"";this.rb&&a&&this.rb.ah(a)};
g.h.DE=function(){this.rb&&this.rb.hide()};g.v(IY,DY);g.h=IY.prototype;g.h.af=function(){IY.M.af.call(this);g.jH(this.F,this.C,"click",g.u(this.ju,!0),"ypc-offer-overlay-show-subscription-offers");g.jH(this.F,this.C,"click",g.u(this.ju,!1),"ypc-offer-overlay-show-non-subscription-offers");g.jH(this.F,this.C,"click",this.ML,"ypc-google-help");g.jH(this.F,this.C,"click",this.Vn,"ypc-offer-overlay-apply-coupon");g.jH(this.F,this.C,"keydown",this.Vn,"ypc-offer-overlay-show-coupon-input")};
g.h.wh=function(){IY.M.wh.call(this);this.K.push(g.Aq("subscription-batch-subscribe-finished",this.yd,this),g.Aq("subscription-batch-subscribe-failure",this.rb.cd,this.rb))};
g.h.ju=function(a){g.cp(g.K("ypc-offer-overlay-offers-section",this.C),"show-subscription-offers",!!a)};
g.h.Vn=function(a){if("keydown"!=a.type||13==a.keyCode){var b=(0,g.Ua)(g.K("ypc-offer-overlay-show-coupon-input",this.C).value),c=[];b&&((0,g.z)(g.J("ypc-offer-overlay-offer-button",this.C),function(a){(a=g.E(a,"ypc-offer-id"))&&c.push(a)}),0!=c.length&&(EY(this.rb),a=g.D("YPC_TRANSACTION_URL",void 0),b={action_apply_coupon:1,
cc:b,oids:c.join(",")},g.G(a,{method:"POST",ha:b,context:this,onSuccess:function(a,b){var c=Qra(this,b);NY(this.rb);JY(this,c);c||KY(this,b)},
onError:function(a,b){NY(this.rb);JY(this,!1);KY(this,b)}})))}};
g.h.ML=function(){var a=g.K("ypc-google-help",this.C),b=g.K("ypc-offer-overlay-offer-button",this.C);if(b)var c=g.E(b,"ghelp-product-id"),d=g.E(b,"ghelp-product-data");c&&d&&(b=JSON.parse(d),g.dC(a,c,"moo",b,!0,!0))};g.v(LY,DY);g.h=LY.prototype;g.h.af=function(){LY.M.af.call(this);g.jH(this.F,this.C,"click",this.yd,"ypc-tip-overlay-close");g.jH(this.F,this.C,"click",this.mI,"ypc-tip-custom-amount-input");g.jH(this.F,this.C,"keydown",this.nI,"ypc-tip-custom-amount-input");g.jH(this.F,this.C,"change",this.oI,"ypc-tip-choice")};
g.h.wh=function(){LY.M.wh.call(this);this.H.push(g.Jf("yt-uix-expander-toggle",this.lI,this))};
g.h.rn=function(a){LY.M.rn.call(this,a);var b=Rra(this);if(b&&a.config)a.config.tipConfig=b;else throw Error("Invalid Config");};
g.h.ij=function(a){a&&(LY.M.ij.call(this,a),a.subscribe("ypc-tip-validation-error",this.pI,this))};
g.h.mI=function(){g.K("ypc-tip-choice-custom",this.C).checked=!0};
g.h.nI=function(a){3==a.keyCode||13==a.keyCode?(a.preventDefault(),g.mq(g.K("ypc-tip-overlay-next-button"),"click")):OY(this)};
g.h.oI=function(){OY(this);g.K("ypc-tip-custom-amount-input",this.C).value=""};
g.h.lI=function(a,b){var c=g.K("ypc-tip-comment-input",a);c&&(b?c.focus():c.value="")};
g.h.pI=function(a){HY(this);MY(this,a.errorMessage||"")};g.v(PY,wY);g.wa(PY);var csa={SW:"ypc-offer-overlay-show-tip-not-available-error",QW:"ypc-offer-overlay-show-plus-page-not-available-error",Kv:"ypc-offer-overlay-show-unicorn-iframe-in-content"},Ura={NW:"ypc-offer-overlay-flow-default",RW:"ypc-offer-overlay-flow-tip"};g.h=PY.prototype;g.h.Be=function(a){a&&(this.L("ypc-offer-overlay-content-wrapper").innerHTML=a,this.bd("ypc-offer-overlay-show-offers-content"))};
g.h.cd=function(a){var b=this.L("ypc-offer-overlay-error");b&&(g.O(b,"ypc-offer-overlay-show-custom-error"),a&&(g.N(b,"ypc-offer-overlay-show-custom-error"),this.L("ypc-offer-overlay-error-custom-content").innerHTML=a),this.bd("ypc-offer-overlay-show-error"))};
g.h.ah=function(a){this.show(this.id);this.cd(a)};
g.h.hide=function(){var a=this.L("ypc-offer-overlay-content-wrapper");a&&g.sc(a);PY.M.hide.call(this)};
g.h.bd=function(a){yY(this,csa);PY.M.bd.call(this,a)};
g.h.Je=function(a,b){switch(b){case "T":return new LY(this,a);default:return new IY(this,a)}};g.v(SY,DY);SY.prototype.R=function(a){a=g.ys(a.currentTarget,"continue_html");this.rb&&a?this.rb.Be(g.$l(a),!0):this.rb&&this.rb.hide()};g.v(TY,PY);g.wa(TY);TY.prototype.Je=function(a){return new SY(this,a)};g.v(VY,g.sd);VY.prototype.X=function(){VY.M.X.call(this);g.oB(kY);g.Bq(this.F);this.F.length=0};
VY.prototype.G=function(a){"channel"==this.C&&(g.D("CHANNEL_ID")==a.C&&XY(!1),WY(a.C,!1),a=g.x("paid-channel-promo")||g.x("paid-package-promo"))&&(g.S(a),a=g.E(g.K("ypc-promo-close",a),"promo-id"),(new g.OE(a)).write("write_dismiss"));this.dispose()};
VY.prototype.H=function(a){"channel"==this.C&&"transaction"==this.D?window.location.reload(!0):"channel"==this.C&&(g.D("CHANNEL_ID")==a.C&&XY(!0),WY(a.C,!0));this.dispose()};g.v(YY,g.sd);YY.prototype.X=function(){g.Bq(this.D);this.D.length=0;this.G=null;this.C=!1;this.F=null;YY.M.X.call(this)};
YY.prototype.K=function(a){this.C=!0;var b=g.D("YTO_GTM_DATA");window.dataLayer=window.dataLayer||[];window.dataLayer.push(b);a.C.subscriptionId&&(this.F=!0)};
YY.prototype.H=function(){if(this.C){switch(this.G){case "musickey":case "channel":case "unlimited":var a=g.D("YPC_POST_PURCHASE_REDIRECT_URL");a&&g.ii(a);break;case "playlist":window.location.reload(!0);break;case "watch":this.F&&window.location.reload(!0)}this.dispose()}};var Vra=["ypc-checkout-button","ypc-enabled"];g.wa(ZY);var hZ={mQ:"ypc-unsubscribe-overlay-confirm",wZ:"ypc-unsubscribe-overlay-xauth",IV:"ypc-unsubscribe-overlay-plus-page-error",LOADING:"ypc-unsubscribe-overlay-loading",SUCCESS:"ypc-unsubscribe-overlay-success",DQ:"ypc-unsubscribe-overlay-delayed",ERROR:"ypc-unsubscribe-overlay-error"};g.h=ZY.prototype;g.h.show=function(){var a=g.jc("ypc-unsubscribe-overlay");g.nA.getInstance().show(a);this.ud()};
g.h.ud=function(){this.ze("ypc-unsubscribe-overlay-loading")};
g.h.cd=function(){this.ze("ypc-unsubscribe-overlay-error")};
g.h.Ta=function(){var a=g.rA();return a?g.K("ypc-unsubscribe-overlay",a):null};
g.h.ze=function(a){var b=this.Ta();if(b){for(var c in hZ)g.O(b,hZ[c]);g.N(b,a)}};var dZ=[],cZ=!1;var eZ=[];g.Zh(g.uq({name:"www/ypc_core",deps:["www/common"],page:"feed index results watch channel playlist subscription_manager unlimited".split(" "),init:function(){$ra()},
dispose:function(){cZ=!1;g.Ig(dZ);dZ.length=0;g.Bq(eZ);eZ.length=0;g.xK.getInstance().dispose()}}));
g.p("yt.www.ypc.checkout.showYpcOverlay",function(a,b,c,d,e){c=c||"D";a={itemId:b,itemType:a};b=DX();c={itemData:a,flowType:c,flowTracker:b,innertubeRequestParams:d,couponCode:e};QY(PY.getInstance(),c)},void 0);
g.p("yt.www.ypc.checkout.showScreenOverlay",function(a){if(a){var b=AY.getInstance();b.ud();b.Be(a);b.Je()}},void 0);
g.p("yt.www.ypc.checkout.showPrepurchaseOverlay",UY,void 0);g.p("yt.www.ypc.checkout.showPrepurchaseOverlay",UY,void 0);g.p("yt.www.ypc.checkout.showYpcOverlayForInnertubeRequestParams",function(a,b){a=a||"D";var c=DX();c={flowType:a,flowTracker:c,innertubeRequestParams:b};QY(PY.getInstance(),c)},void 0);
g.p("yt.www.ypc.subscription.openUnsubscribeOverlay",function(a,b){var c=ZY.getInstance();c.show();Yra(a,b);c=c.Ta();c=g.K("ypc-unsubscribe-confirm",c);g.Dp(c,"ypc-item-type",a);g.Dp(c,"ypc-item-id",b)},void 0);
g.p("yt.www.ypc.subscription.requestUnsubscribe",$Y,void 0);g.p("yt.www.ypc.checkout.offerpurchaser.purchaseOffer",function(a,b){var c=DX();BX(c,EX(a));g.ni("ypc-purchase-flow-start",new zX(a.config.flowType));var d=PY.getInstance();b||d.ud();GY(d.Je(c,a.config.flowType),a)},void 0);
g.p("yt.www.ypc.checkout.offerpurchaser.completeTransaction",function(a){var b=DX();BX(b,EX(a));g.ni("ypc-purchase-flow-start",new zX(a.config.flowType));var c=PY.getInstance();c.ud();b=c.Je(b,a.config.flowType);FY(b,a);b.D=new oY(a,b.G,new tY);b.ij(b.D);a=b.D;rY(a,null,null,a.Lj.transactionParams)},void 0);})(_yt_www);
